import type { GrammaireTheoryDoc } from '../types'

/** Théorie FALC — thème gram-activite. Français seul (pas de traductions). */
export const activiteDocs: GrammaireTheoryDoc[] = [
  {
    id: 'd1',
    typeId: 'gram-d1-theorie',
    index: 1,
    title: 'Faire une activité',
    topic: 'gram-activite',
    public: 'A1',
    objectif: 'Parler d’un loisir avec faire du / de la / de l’.',
    blocks: [
    { kind: 'heading', text: 'Faire une activité' },
    { kind: 'paragraph', text: 'Je parle d’une activité avec faire + du / de la / de l’.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Tu fais du piano.' }, { correct: 'Nous faisons de la natation.' }, { correct: 'Ils font de l’équitation.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Faire au présent + du (masculin), de la (féminin), de l’ (voyelle).' },
    { kind: 'note', text: 'Je retiens : activité = faire + du / de la / de l’.' },
    { kind: 'table', headers: ['Genre', 'Forme', 'Exemple'], rows: [['masculin', 'du', 'Il fait du jogging.'], ['féminin', 'de la', 'Vous faites de la musique.'], ['voyelle', 'de l’', 'Elles font de l’équitation.']] },
    { kind: 'note', text: 'Attention ! Sport / instrument : souvent du / de la, pas le.' },
    ],
  },
  {
    id: 'd2',
    typeId: 'gram-d2-theorie',
    index: 2,
    title: 'Les verbes pronominaux',
    topic: 'gram-activite',
    public: 'A1',
    objectif: 'Conjuguer un verbe avec me, te, se…',
    blocks: [
    { kind: 'heading', text: 'Les verbes pronominaux' },
    { kind: 'paragraph', text: 'J’utilise un pronom réfléchi avec le verbe.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je me douche.' }, { correct: 'Tu t’appelles Sam.' }, { correct: 'Ils se baignent.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Un verbe pronominal a deux pronoms : sujet + me/te/se/nous/vous/se.' },
    { kind: 'paragraph', text: 'Devant une voyelle : me → m’, te → t’, se → s’.' },
    { kind: 'note', text: 'Je retiens : je me / tu t’ / il se / nous nous / vous vous / ils se.' },
    { kind: 'table', headers: ['Personne', 'Pronom', 'Exemple'], rows: [['je', 'me / m’', 'Je me lave.'], ['tu', 'te / t’', 'Tu t’appelles.'], ['il / elle / on', 'se / s’', 'Elle se couche.'], ['nous', 'nous', 'Nous nous regardons.'], ['vous', 'vous', 'Vous vous levez.'], ['ils / elles', 'se / s’', 'Ils se baignent.']] },
    { kind: 'note', text: 'Attention ! Négation : Je ne me souviens pas.' },
    ],
  },
  {
    id: 'd3',
    typeId: 'gram-d3-theorie',
    index: 3,
    title: 'Les pronoms toniques',
    topic: 'gram-activite',
    public: 'A1',
    objectif: 'Utiliser moi, toi, lui, elle…',
    blocks: [
    { kind: 'heading', text: 'Les pronoms toniques' },
    { kind: 'paragraph', text: 'J’utilise moi, toi, lui… après une préposition ou pour insister.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Tu viens avec moi ?' }, { correct: 'Moi, je joue au tennis.' }, { correct: 'Qui veut jouer ? — Moi !' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Pronoms toniques : moi, toi, lui, elle, soi, nous, vous, eux, elles.' },
    { kind: 'paragraph', text: 'Après une préposition : avec moi, chez eux.' },
    { kind: 'paragraph', text: 'Pour renforcer : Moi, je…' },
    { kind: 'paragraph', text: 'Sans verbe : — Moi !' },
    { kind: 'note', text: 'Je retiens : après préposition → pronom tonique.' },
    { kind: 'table', headers: ['Sujet', 'Tonique'], rows: [['je', 'moi'], ['tu', 'toi'], ['il', 'lui'], ['elle', 'elle'], ['on', 'soi'], ['nous', 'nous'], ['vous', 'vous'], ['ils', 'eux'], ['elles', 'elles']] },
    { kind: 'note', text: 'Attention ! Phrase positive → moi aussi. Phrase négative → moi non plus.' },
    ],
  },
]
