import type { GrammaireTheoryDoc } from '../types'

/** Théorie FALC — thème gram-aide. Français seul (pas de traductions). */
export const aideDocs: GrammaireTheoryDoc[] = [
  {
    id: 'l1',
    typeId: 'gram-l1-theorie',
    index: 1,
    title: 'L’apostrophe',
    topic: 'gram-aide',
    public: 'A1',
    objectif: 'Utiliser l’apostrophe.',
    blocks: [
    { kind: 'heading', text: 'L’apostrophe' },
    { kind: 'paragraph', text: 'Je remplace une voyelle par ’ devant une autre voyelle.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'l’école' }, { correct: 'j’aime' }, { correct: 's’appeler' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Le/la → l’. Je → j’. Me/te/se → m’/t’/s’. De → d’. Que → qu’.' },
    { kind: 'note', text: 'Je retiens : voyelle + voyelle → apostrophe souvent.' },
    { kind: 'table', headers: ['Avant', 'Après'], rows: [['le ami', 'l’ami'], ['je ai', 'j’ai'], ['se appelle', 's’appelle']] },
    { kind: 'note', text: 'Attention ! Pas d’apostrophe au hasard : seulement ces petits mots.' },
    ],
  },
  {
    id: 'l2',
    typeId: 'gram-l2-theorie',
    index: 2,
    title: 'Le genre des noms',
    topic: 'gram-aide',
    public: 'A1',
    objectif: 'Former le féminin des noms.',
    blocks: [
    { kind: 'heading', text: 'Le genre des noms' },
    { kind: 'paragraph', text: 'Je forme le féminin d’un nom.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'un boulanger → une boulangère' }, { correct: 'un chanteur → une chanteuse' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Souvent + e. Autres : -eur → -euse, -teur → -trice, -er → -ère…' },
    { kind: 'note', text: 'Je retiens : regarde la terminaison pour former le féminin.' },
    { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['-ien', '-ienne'], ['-eur', '-euse'], ['-teur', '-trice'], ['-er', '-ère']] },
    { kind: 'note', text: 'Attention ! Quelques exceptions : un chef → une cheffe.' },
    ],
  },
  {
    id: 'l3',
    typeId: 'gram-l3-theorie',
    index: 3,
    title: 'Le nombre des noms',
    topic: 'gram-aide',
    public: 'A1',
    objectif: 'Former le pluriel des noms.',
    blocks: [
    { kind: 'heading', text: 'Le nombre des noms' },
    { kind: 'paragraph', text: 'Je mets un nom au pluriel.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'un livre → des livres' }, { correct: 'un cheval → des chevaux' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Souvent + s. -eau / -au / -eu → + x. -al → -aux (souvent).' },
    { kind: 'note', text: 'Je retiens : pluriel souvent + s.' },
    { kind: 'table', headers: ['Singulier', 'Pluriel'], rows: [['livre', 'livres'], ['bateau', 'bateaux'], ['journal', 'journaux']] },
    { kind: 'note', text: 'Attention ! Un œil → des yeux.' },
    ],
  },
  {
    id: 'l4',
    typeId: 'gram-l4-theorie',
    index: 4,
    title: 'Le genre des adjectifs',
    topic: 'gram-aide',
    public: 'A1',
    objectif: 'Accorder l’adjectif au féminin.',
    blocks: [
    { kind: 'heading', text: 'Le genre des adjectifs' },
    { kind: 'paragraph', text: 'J’accorde l’adjectif au féminin.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'petit → petite' }, { correct: 'heureux → heureuse' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Souvent + e. -eux → -euse. -f → -ve. -er → -ère.' },
    { kind: 'note', text: 'Je retiens : adjectif féminin = accord avec le nom.' },
    { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['grand', 'grande'], ['actif', 'active'], ['premier', 'première']] },
    { kind: 'note', text: 'Attention ! Beau → belle. Nouveau → nouvelle. Vieux → vieille.' },
    ],
  },
  {
    id: 'l5',
    typeId: 'gram-l5-theorie',
    index: 5,
    title: 'Le nombre des adjectifs',
    topic: 'gram-aide',
    public: 'A1',
    objectif: 'Mettre l’adjectif au pluriel.',
    blocks: [
    { kind: 'heading', text: 'Le nombre des adjectifs' },
    { kind: 'paragraph', text: 'J’accorde l’adjectif au pluriel.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'un livre intéressant → des livres intéressants' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Souvent + s. Adjectifs en -eau → + x.' },
    { kind: 'note', text: 'Je retiens : pluriel de l’adjectif = accord avec le nom.' },
    { kind: 'table', headers: ['Singulier', 'Pluriel'], rows: [['petit', 'petits'], ['beau', 'beaux']] },
    { kind: 'note', text: 'Attention ! Accord en genre et en nombre ensemble.' },
    ],
  },
  {
    id: 'l6',
    typeId: 'gram-l6-theorie',
    index: 6,
    title: 'Les lettres G et C',
    topic: 'gram-aide',
    public: 'A1',
    objectif: 'Comprendre les sons de g et c.',
    blocks: [
    { kind: 'heading', text: 'Les lettres G et C' },
    { kind: 'paragraph', text: 'Je sais quand g et c sont durs ou doux.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'garçon (c doux)' }, { correct: 'gateau → gâteau (g dur)' }, { correct: 'girafe (g doux)' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'C/G devant e, i, y → son doux. Devant a, o, u → son dur.' },
    { kind: 'paragraph', text: 'Ç garde le son s devant a, o, u.' },
    { kind: 'note', text: 'Je retiens : e/i/y → doux. a/o/u → dur.' },
    { kind: 'table', headers: ['Lettre', 'Doux', 'Dur'], rows: [['c', 'cerise', 'carotte'], ['g', 'girafe', 'gateau / gâteau']] },
    { kind: 'note', text: 'Attention ! On ajoute e pour garder le son : nous mangeons.' },
    ],
  },
  {
    id: 'l7',
    typeId: 'gram-l7-theorie',
    index: 7,
    title: 'Les lettres S et M',
    topic: 'gram-aide',
    public: 'A1',
    objectif: 'Repères sur s et m.',
    blocks: [
    { kind: 'heading', text: 'Les lettres S et M' },
    { kind: 'paragraph', text: 'Je fais attention aux lettres s et m dans les mots.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'poisson (ss = son s)' }, { correct: 'maison (s entre voyelles = son z)' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'S entre deux voyelles → souvent son z.' },
    { kind: 'paragraph', text: 'Ss → son s. M devant b/p souvent.' },
    { kind: 'note', text: 'Je retiens : s entre voyelles → souvent z.' },
    { kind: 'table', headers: ['Cas', 'Exemple'], rows: [['s = z', 'maison'], ['ss = s', 'classe']] },
    { kind: 'note', text: 'Attention ! Un mot = une règle à la fois en FALC.' },
    ],
  },
  {
    id: 'l8',
    typeId: 'gram-l8-theorie',
    index: 8,
    title: 'Les accents',
    topic: 'gram-aide',
    public: 'A1',
    objectif: 'Reconnaître les accents courants.',
    blocks: [
    { kind: 'heading', text: 'Les accents' },
    { kind: 'paragraph', text: 'Je reconnais é, è, ê, à, ù, ç.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'école' }, { correct: 'père' }, { correct: 'forêt' }, { correct: 'à' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'É = accent aigu. È / Ê = grave / circonflexe.' },
    { kind: 'paragraph', text: 'À et ù : surtout mots courts (à, où).' },
    { kind: 'note', text: 'Je retiens : l’accent change parfois le son et le sens.' },
    { kind: 'table', headers: ['Accent', 'Exemple'], rows: [['aigu é', 'été'], ['grave è', 'très'], ['circonflexe ê', 'être']] },
    { kind: 'note', text: 'Attention ! a (verbe avoir) ≠ à (préposition).' },
    ],
  },
  {
    id: 'l9',
    typeId: 'gram-l9-theorie',
    index: 9,
    title: 'Les classes grammaticales',
    topic: 'gram-aide',
    public: 'A1 / A2',
    objectif: 'Nommer les classes de mots.',
    blocks: [
    { kind: 'heading', text: 'Les classes grammaticales' },
    { kind: 'paragraph', text: 'Je reconnais la classe d’un mot.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'maison = nom' }, { correct: 'grande = adjectif' }, { correct: 'manger = verbe' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Noms, adjectifs, déterminants, pronoms, verbes, adverbes, prépositions, conjonctions…' },
    { kind: 'note', text: 'Je retiens : chaque mot a une classe.' },
    { kind: 'list', title: 'Classes', items: ['nom', 'adjectif', 'déterminant', 'pronom', 'verbe', 'adverbe', 'préposition', 'conjonction'] },
    { kind: 'note', text: 'Attention ! Le même mot peut changer de rôle selon la phrase.' },
    ],
  },
  {
    id: 'l10',
    typeId: 'gram-l10-theorie',
    index: 10,
    title: 'La ponctuation',
    topic: 'gram-aide',
    public: 'A1',
    objectif: 'Utiliser la ponctuation de base.',
    blocks: [
    { kind: 'heading', text: 'La ponctuation' },
    { kind: 'paragraph', text: 'J’utilise les signes pour clarifier.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Bonjour.' }, { correct: 'Tu viens ?' }, { correct: 'Attention !' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: '. = fin. ? = question. ! = exclamation. , = pause courte.' },
    { kind: 'note', text: 'Je retiens : une phrase = une ponctuation claire.' },
    { kind: 'table', headers: ['Signe', 'Usage'], rows: [['.', 'fin de phrase'], ['?', 'question'], ['!', 'exclamation'], [',', 'pause']] },
    { kind: 'note', text: 'Attention ! Espace avant ? ! ; : en français typographique (selon usage scolaire).' },
    ],
  },
  {
    id: 'l11',
    typeId: 'gram-l11-theorie',
    index: 11,
    title: 'Les homophones (sélection)',
    topic: 'gram-aide',
    public: 'A1 / A2',
    objectif: 'Distinguer les homophones courants.',
    blocks: [
    { kind: 'heading', text: 'Les homophones' },
    { kind: 'paragraph', text: 'Je distingue les mots qui se prononcent pareil.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'a (verbe avoir) / à (préposition)' }, { correct: 'ou (choix) / où (lieu)' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Astuce : remplace pour tester (a → avait ; ou → ou bien ; on → il).' },
    { kind: 'note', text: 'Je retiens : remplace pour choisir le bon mot.' },
    { kind: 'table', headers: ['Mot', 'Nature', 'Test'], rows: [['a', 'verbe avoir', 'avait'], ['à', 'préposition', 'vers / dans'], ['ou', 'choix', 'ou bien'], ['où', 'lieu', 'là où'], ['son', 'possessif', 'mon'], ['sont', 'verbe être', 'étaient'], ['on', 'pronom', 'il'], ['ont', 'verbe avoir', 'avaient']] },
    { kind: 'note', text: 'Attention ! Un homophone à la fois dans la fiche.' },
    ],
  },
]
