import type { GrammaireTheoryDoc } from '../types'

/** Théorie FALC — thème gram-aliments. Français seul (pas de traductions). */
export const alimentsDocs: GrammaireTheoryDoc[] = [
  {
    id: 'g1',
    typeId: 'gram-g1-theorie',
    index: 1,
    title: 'Les articles indéfinis',
    topic: 'gram-aliments',
    public: 'A1',
    objectif: 'Utiliser un, une, des.',
    blocks: [
    { kind: 'heading', text: 'Les articles indéfinis' },
    { kind: 'paragraph', text: 'Je présente une chose non précise.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Un pain.' }, { correct: 'Une pomme.' }, { correct: 'Des œufs.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Un (masculin), une (féminin), des (pluriel).' },
    { kind: 'paragraph', text: 'Négation : un/une/des → de / d’ : Je n’ai pas de pain.' },
    { kind: 'note', text: 'Je retiens : un / une / des. Négation → de.' },
    { kind: 'table', headers: ['', 'Masculin', 'Féminin'], rows: [['singulier', 'un', 'une'], ['pluriel', 'des', 'des']] },
    { kind: 'note', text: 'Attention ! Après négation : pas de, pas d’.' },
    ],
  },
  {
    id: 'g2',
    typeId: 'gram-g2-theorie',
    index: 2,
    title: 'Les articles définis',
    topic: 'gram-aliments',
    public: 'A1',
    objectif: 'Utiliser le, la, l’, les.',
    blocks: [
    { kind: 'heading', text: 'Les articles définis' },
    { kind: 'paragraph', text: 'Je parle d’une chose connue ou générale.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Le pain.' }, { correct: 'La soupe.' }, { correct: 'L’eau.' }, { correct: 'Les fruits.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Le / la / l’ / les.' },
    { kind: 'paragraph', text: 'L’ devant voyelle ou h.' },
    { kind: 'note', text: 'Je retiens : le / la / l’ / les = défini.' },
    { kind: 'table', headers: ['', 'Masculin', 'Féminin'], rows: [['singulier', 'le / l’', 'la / l’'], ['pluriel', 'les', 'les']] },
    { kind: 'note', text: 'Attention ! J’aime le chocolat = en général.' },
    ],
  },
  {
    id: 'g3',
    typeId: 'gram-g3-theorie',
    index: 3,
    title: 'Les articles partitifs',
    topic: 'gram-aliments',
    public: 'A1',
    objectif: 'Parler d’une quantité non comptée.',
    blocks: [
    { kind: 'heading', text: 'Les articles partitifs' },
    { kind: 'paragraph', text: 'Je parle d’une partie d’un aliment.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je mange du pain.' }, { correct: 'Je bois de l’eau.' }, { correct: 'Elle prend de la confiture.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Du / de la / de l’ = une quantité non précise.' },
    { kind: 'paragraph', text: 'Négation : du/de la/de l’ → de / d’.' },
    { kind: 'note', text: 'Je retiens : partitif = du / de la / de l’.' },
    { kind: 'table', headers: ['Forme', 'Exemple'], rows: [['du', 'du fromage'], ['de la', 'de la salade'], ['de l’', 'de l’huile']] },
    { kind: 'note', text: 'Attention ! Je ne mange pas de fromage.' },
    ],
  },
  {
    id: 'g4',
    typeId: 'gram-g4-theorie',
    index: 4,
    title: 'Les quantités',
    topic: 'gram-aliments',
    public: 'A1',
    objectif: 'Exprimer une quantité.',
    blocks: [
    { kind: 'heading', text: 'Les quantités' },
    { kind: 'paragraph', text: 'Je dis une quantité avec un nombre ou une expression.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Un kilo de pommes.' }, { correct: 'Beaucoup de riz.' }, { correct: 'Un peu de sel.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Nombre + nom. Expression + de + nom : beaucoup de, un peu de, assez de, trop de.' },
    { kind: 'paragraph', text: 'Après une quantité, souvent de (sans article).' },
    { kind: 'note', text: 'Je retiens : quantité + de + nom.' },
    { kind: 'list', title: 'Expressions', items: ['un kilo de', 'une bouteille de', 'beaucoup de', 'un peu de', 'assez de', 'trop de'] },
    { kind: 'note', text: 'Attention ! Beaucoup de lait (pas du).' },
    ],
  },
  {
    id: 'g5',
    typeId: 'gram-g5-theorie',
    index: 5,
    title: 'Les déterminants indéfinis',
    topic: 'gram-aliments',
    public: 'A1 / A2',
    objectif: 'Utiliser tout, chaque, plusieurs…',
    blocks: [
    { kind: 'heading', text: 'Les déterminants indéfinis' },
    { kind: 'paragraph', text: 'Je parle d’une quantité vague.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Chaque élève.' }, { correct: 'Plusieurs livres.' }, { correct: 'Tout le monde.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Mots utiles : chaque, plusieurs, quelques, tout / toute / tous / toutes, aucun / aucune.' },
    { kind: 'note', text: 'Je retiens : indéfini = quantité non exacte.' },
    { kind: 'table', headers: ['Mot', 'Exemple'], rows: [['chaque', 'chaque jour'], ['plusieurs', 'plusieurs amis'], ['quelques', 'quelques minutes'], ['tout le', 'tout le monde']] },
    { kind: 'note', text: 'Attention ! Aucun va avec ne : je n’ai aucun ticket.' },
    ],
  },
]
