import type { GrammaireTheoryDoc } from '../types'

/** Théorie FALC — thème gram-decrire. Français seul (pas de traductions). */
export const decrireDocs: GrammaireTheoryDoc[] = [
  {
    id: 'f4',
    typeId: 'gram-f4-theorie',
    index: 1,
    title: 'La météo',
    topic: 'gram-decrire',
    public: 'A1',
    objectif: 'Décrire le temps qu’il fait.',
    blocks: [
    { kind: 'heading', text: 'La météo' },
    { kind: 'paragraph', text: 'Je dis le temps qu’il fait.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Il fait beau.' }, { correct: 'Il pleut.' }, { correct: 'Il y a du vent.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Il fait + adjectif : beau, mauvais, chaud, froid.' },
    { kind: 'paragraph', text: 'Il pleut. Il neige.' },
    { kind: 'paragraph', text: 'Il y a + du / de la : du soleil, du vent, de la pluie.' },
    { kind: 'note', text: 'Je retiens : il fait / il pleut / il y a…' },
    { kind: 'table', headers: ['Forme', 'Exemple'], rows: [['Il fait…', 'Il fait froid.'], ['Il + verbe météo', 'Il pleut.'], ['Il y a…', 'Il y a du brouillard.']] },
    { kind: 'note', text: 'Attention ! On dit il fait beau, pas il est beau (pour la météo).' },
    ],
  },
  {
    id: 'f5',
    typeId: 'gram-f5-theorie',
    index: 2,
    title: 'C’est, il est, il y a',
    topic: 'gram-decrire',
    public: 'A1',
    objectif: 'Choisir c’est, il est ou il y a.',
    blocks: [
    { kind: 'heading', text: 'C’est, il est, il y a' },
    { kind: 'paragraph', text: 'Je choisis la bonne formule pour présenter ou situer.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'C’est un livre.' }, { correct: 'Il est professeur.' }, { correct: 'Il y a une école.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'C’est + nom (présentation).' },
    { kind: 'paragraph', text: 'Il / elle est + adjectif ou profession sans article.' },
    { kind: 'paragraph', text: 'Il y a + nom (existence / présence).' },
    { kind: 'note', text: 'Je retiens : c’est (présenter) / il est (qualifier) / il y a (il existe).' },
    { kind: 'table', headers: ['Forme', 'Usage', 'Exemple'], rows: [['c’est', 'présenter', 'C’est mon ami.'], ['il est', 'qualité / métier', 'Il est gentil.'], ['il y a', 'présence', 'Il y a un bus.']] },
    { kind: 'note', text: 'Attention ! Métier : il est médecin (sans un).' },
    ],
  },
  {
    id: 'f6',
    typeId: 'gram-f6-theorie',
    index: 3,
    title: 'Les déterminants possessifs',
    topic: 'gram-decrire',
    public: 'A1',
    objectif: 'Utiliser mon, ton, son…',
    blocks: [
    { kind: 'heading', text: 'Les déterminants possessifs' },
    { kind: 'paragraph', text: 'Je dis à qui appartient une chose.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Mon livre.' }, { correct: 'Ta sœur.' }, { correct: 'Ses amis.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Le possessif s’accorde avec le nom possédé, pas avec le possesseur.' },
    { kind: 'paragraph', text: 'Devant voyelle : mon / ton / son même au féminin : mon amie.' },
    { kind: 'note', text: 'Je retiens : accord avec le nom. mon amie (voyelle).' },
    { kind: 'table', headers: ['', 'masc.', 'fém.', 'pluriel'], rows: [['je', 'mon', 'ma', 'mes'], ['tu', 'ton', 'ta', 'tes'], ['il / elle', 'son', 'sa', 'ses'], ['nous', 'notre', 'notre', 'nos'], ['vous', 'votre', 'votre', 'vos'], ['ils / elles', 'leur', 'leur', 'leurs']] },
    { kind: 'note', text: 'Attention ! ma → mon devant voyelle : mon école.' },
    ],
  },
  {
    id: 'f7',
    typeId: 'gram-f7-theorie',
    index: 4,
    title: 'Les adjectifs qualificatifs',
    topic: 'gram-decrire',
    public: 'A1',
    objectif: 'Placer et accorder un adjectif.',
    blocks: [
    { kind: 'heading', text: 'Les adjectifs qualificatifs' },
    { kind: 'paragraph', text: 'Je décris avec un adjectif accordé.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Une grande maison.' }, { correct: 'Des enfants heureux.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'L’adjectif s’accorde en genre et en nombre avec le nom.' },
    { kind: 'paragraph', text: 'Souvent après le nom. Quelques-uns avant : grand, petit, beau, bon, nouveau…' },
    { kind: 'note', text: 'Je retiens : adjectif = accord avec le nom.' },
    { kind: 'table', headers: ['Nom', 'Adjectif'], rows: [['un garçon', 'petit'], ['une fille', 'petite'], ['des livres', 'intéressants']] },
    { kind: 'note', text: 'Attention ! Beau → bel devant voyelle : un bel homme.' },
    ],
  },
  {
    id: 'f8',
    typeId: 'gram-f8-theorie',
    index: 5,
    title: 'Les professions',
    topic: 'gram-decrire',
    public: 'A1',
    objectif: 'Dire mon métier.',
    blocks: [
    { kind: 'heading', text: 'Les professions' },
    { kind: 'paragraph', text: 'Je dis mon métier avec être.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je suis boulanger.' }, { correct: 'Elle est infirmière.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Être + profession (sans article).' },
    { kind: 'paragraph', text: 'Avec un adjectif ou un complément : c’est un bon médecin.' },
    { kind: 'note', text: 'Je retiens : je suis + métier (pas un).' },
    { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['boulanger', 'boulangère'], ['infirmier', 'infirmière'], ['vendeur', 'vendeuse']] },
    { kind: 'note', text: 'Attention ! Pas d’article : Je suis professeur.' },
    ],
  },
  {
    id: 'f9',
    typeId: 'gram-f9-theorie',
    index: 6,
    title: 'La comparaison',
    topic: 'gram-decrire',
    public: 'A1 / A2',
    objectif: 'Comparer avec plus, moins, aussi.',
    blocks: [
    { kind: 'heading', text: 'La comparaison' },
    { kind: 'paragraph', text: 'Je compare deux personnes ou deux choses.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Marie est plus grande que Paul.' }, { correct: 'Ce livre est moins cher que l’autre.' }, { correct: 'Il est aussi rapide que toi.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Plus … que = supérieur. Moins … que = inférieur. Aussi … que = égal.' },
    { kind: 'paragraph', text: 'Avec un nom : plus de / moins de + nom.' },
    { kind: 'note', text: 'Je retiens : plus / moins / aussi + adjectif + que.' },
    { kind: 'table', headers: ['Forme', 'Exemple'], rows: [['plus … que', 'plus grand que'], ['moins … que', 'moins facile que'], ['aussi … que', 'aussi fort que']] },
    { kind: 'note', text: 'Attention ! Bon → meilleur. Mauvais → pire (formes spéciales).' },
    ],
  },
]
