import type { GrammaireTheoryDoc } from '../types'

/** Théorie FALC — thème gram-demander. Français seul (pas de traductions). */
export const demanderDocs: GrammaireTheoryDoc[] = [
  {
    id: 'f1',
    typeId: 'gram-f1-theorie',
    index: 1,
    title: 'Les déterminants démonstratifs',
    topic: 'gram-demander',
    public: 'A1',
    objectif: 'Utiliser ce, cet, cette, ces.',
    blocks: [
    { kind: 'heading', text: 'Les déterminants démonstratifs' },
    { kind: 'paragraph', text: 'Je montre une chose proche avec ce / cet / cette / ces.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Ce livre.' }, { correct: 'Cet homme.' }, { correct: 'Cette table.' }, { correct: 'Ces stylos.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Masculin + consonne → ce. Masculin + voyelle ou h → cet.' },
    { kind: 'paragraph', text: 'Féminin → cette. Pluriel → ces.' },
    { kind: 'note', text: 'Je retiens : ce / cet / cette / ces.' },
    { kind: 'table', headers: ['', 'Masculin', 'Féminin'], rows: [['singulier', 'ce / cet', 'cette'], ['pluriel', 'ces', 'ces']] },
    { kind: 'note', text: 'Attention ! Cet devant voyelle : cet ami, cet hôtel.' },
    ],
  },
  {
    id: 'f2',
    typeId: 'gram-f2-theorie',
    index: 2,
    title: 'Pouvoir, devoir, vouloir',
    topic: 'gram-demander',
    public: 'A1',
    objectif: 'Exprimer capacité, obligation, volonté.',
    blocks: [
    { kind: 'heading', text: 'Pouvoir, devoir, vouloir' },
    { kind: 'paragraph', text: 'Je dis ce que je peux, dois ou veux.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je peux t’aider.' }, { correct: 'Tu dois partir.' }, { correct: 'Nous voulons un café.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Pouvoir = capacité ou permission.' },
    { kind: 'paragraph', text: 'Devoir = obligation.' },
    { kind: 'paragraph', text: 'Vouloir = volonté / souhait.' },
    { kind: 'paragraph', text: 'Ces verbes + infinitif.' },
    { kind: 'note', text: 'Je retiens : pouvoir / devoir / vouloir + infinitif.' },
    { kind: 'table', headers: ['Verbe', 'Sens', 'Exemple'], rows: [['pouvoir', 'capacité / permission', 'Je peux venir.'], ['devoir', 'obligation', 'Tu dois étudier.'], ['vouloir', 'volonté', 'Elle veut manger.']] },
    { kind: 'note', text: 'Attention ! Après ces verbes, le 2e verbe reste à l’infinitif.' },
    ],
  },
  {
    id: 'f3',
    typeId: 'gram-f3-theorie',
    index: 3,
    title: 'Accepter et refuser',
    topic: 'gram-demander',
    public: 'A1',
    objectif: 'Accepter ou refuser une proposition.',
    blocks: [
    { kind: 'heading', text: 'Accepter et refuser' },
    { kind: 'paragraph', text: 'Je réponds oui ou non à une proposition.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Oui, avec plaisir.' }, { correct: 'Non, merci.' }, { correct: 'Désolé, je ne peux pas.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Accepter : oui, d’accord, avec plaisir, volontiers.' },
    { kind: 'paragraph', text: 'Refuser poliment : non merci, désolé, je ne peux pas.' },
    { kind: 'note', text: 'Je retiens : refuse avec politesse.' },
    { kind: 'list', title: 'Formules', items: ['Oui, d’accord.', 'Avec plaisir.', 'Non, merci.', 'Désolé, je ne peux pas.'] },
    { kind: 'note', text: 'Attention ! Un refus clair reste poli.' },
    ],
  },
]
