import type { GrammaireTheoryDoc } from '../types'

/** Théorie FALC — thème gram-exprimer. Français seul (pas de traductions). */
export const exprimerDocs: GrammaireTheoryDoc[] = [
  {
    id: 'k3',
    typeId: 'gram-k3-theorie',
    index: 1,
    title: 'Exprimer la cause',
    topic: 'gram-exprimer',
    public: 'A2',
    objectif: 'Dire pourquoi.',
    blocks: [
    { kind: 'heading', text: 'Exprimer la cause' },
    { kind: 'paragraph', text: 'Je dis la raison d’une action.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je suis resté à la maison parce que j’étais malade.' }, { correct: 'J’ai réussi grâce à ce professeur.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Parce que / car / puisque / comme…' },
    { kind: 'paragraph', text: 'À cause de (négatif), grâce à (positif), en raison de (neutre).' },
    { kind: 'paragraph', text: 'Gérondif : en + -ant.' },
    { kind: 'note', text: 'Je retiens : parce que répond à pourquoi.' },
    { kind: 'table', headers: ['Forme', 'Exemple'], rows: [['parce que', 'parce que j’étais fatigué'], ['à cause de', 'à cause de la neige'], ['grâce à', 'grâce à mon ami']] },
    { kind: 'note', text: 'Attention ! À cause de ≠ grâce à.' },
    ],
  },
  {
    id: 'k4',
    typeId: 'gram-k4-theorie',
    index: 2,
    title: 'Exprimer la conséquence',
    topic: 'gram-exprimer',
    public: 'A2',
    objectif: 'Dire le résultat.',
    blocks: [
    { kind: 'heading', text: 'Exprimer la conséquence' },
    { kind: 'paragraph', text: 'Je dis le résultat d’une action.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Il pleut, donc je prends un parapluie.' }, { correct: 'Il est malade, alors il reste chez lui.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Donc, alors, c’est pourquoi, si bien que, alors…' },
    { kind: 'note', text: 'Je retiens : cause → donc → conséquence.' },
    { kind: 'list', title: 'Connecteurs', items: ['donc', 'alors', 'c’est pourquoi', 'si bien que'] },
    { kind: 'note', text: 'Attention ! Une phrase courte pour la conséquence en FALC.' },
    ],
  },
  {
    id: 'k5',
    typeId: 'gram-k5-theorie',
    index: 3,
    title: 'Exprimer le but',
    topic: 'gram-exprimer',
    public: 'A2',
    objectif: 'Dire dans quel but.',
    blocks: [
    { kind: 'heading', text: 'Exprimer le but' },
    { kind: 'paragraph', text: 'Je dis le but d’une action.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je travaille pour réussir.' }, { correct: 'Il parle lentement afin que tout le monde comprenne.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Pour + infinitif (même sujet).' },
    { kind: 'paragraph', text: 'Afin de + infinitif. Afin que + subjonctif (sujets différents).' },
    { kind: 'note', text: 'Je retiens : pour + infinitif (cas le plus simple).' },
    { kind: 'table', headers: ['Forme', 'Exemple'], rows: [['pour + infinitif', 'pour apprendre'], ['afin de + infinitif', 'afin de partir tôt']] },
    { kind: 'note', text: 'Attention ! Même sujet → pour + infinitif.' },
    ],
  },
  {
    id: 'k6',
    typeId: 'gram-k6-theorie',
    index: 4,
    title: 'Exprimer l’opposition',
    topic: 'gram-exprimer',
    public: 'A2',
    objectif: 'Opposer deux idées.',
    blocks: [
    { kind: 'heading', text: 'Exprimer l’opposition' },
    { kind: 'paragraph', text: 'Je montre deux idées différentes.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Il est fatigué, mais il continue.' }, { correct: 'Alors que tu dors, je travaille.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Mais, pourtant, cependant, alors que, tandis que…' },
    { kind: 'note', text: 'Je retiens : mais = opposition simple.' },
    { kind: 'list', title: 'Mots d’opposition', items: ['mais', 'pourtant', 'cependant', 'alors que'] },
    { kind: 'note', text: 'Attention ! Une opposition claire, une phrase courte.' },
    ],
  },
  {
    id: 'k7',
    typeId: 'gram-k7-theorie',
    index: 5,
    title: 'Exprimer la concession',
    topic: 'gram-exprimer',
    public: 'A2',
    objectif: 'Concéder un fait puis opposer.',
    blocks: [
    { kind: 'heading', text: 'Exprimer la concession' },
    { kind: 'paragraph', text: 'J’admets un fait, puis je montre un contraste.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Bien qu’il soit fatigué, il vient.' }, { correct: 'Malgré la pluie, nous sortons.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Bien que / quoique + subjonctif.' },
    { kind: 'paragraph', text: 'Malgré + nom. Même si + indicatif.' },
    { kind: 'note', text: 'Je retiens : malgré + nom. Bien que + subjonctif.' },
    { kind: 'table', headers: ['Forme', 'Exemple'], rows: [['malgré + nom', 'malgré le froid'], ['même si', 'même s’il pleut'], ['bien que + subjonctif', 'bien qu’il soit tard']] },
    { kind: 'note', text: 'Attention ! Malgré sans que : malgré la pluie.' },
    ],
  },
  {
    id: 'k8',
    typeId: 'gram-k8-theorie',
    index: 6,
    title: 'Pronoms relatifs neutres',
    topic: 'gram-exprimer',
    public: 'A2',
    objectif: 'Utiliser ce qui, ce que, ce dont.',
    blocks: [
    { kind: 'heading', text: 'Pronoms relatifs neutres' },
    { kind: 'paragraph', text: 'Je parle d’une idée (pas d’un nom précis).' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Ce qui est important, c’est la santé.' }, { correct: 'Je fais ce que tu dis.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Ce qui = sujet. Ce que = complément. Ce dont = de + idée.' },
    { kind: 'note', text: 'Je retiens : ce qui / ce que / ce dont.' },
    { kind: 'table', headers: ['Forme', 'Exemple'], rows: [['ce qui', 'Ce qui me plaît…'], ['ce que', 'Ce que je veux…'], ['ce dont', 'Ce dont j’ai besoin…']] },
    { kind: 'note', text: 'Attention ! Ce que → ce qu’ devant voyelle.' },
    ],
  },
  {
    id: 'k9',
    typeId: 'gram-k9-theorie',
    index: 7,
    title: 'Les doubles pronoms',
    topic: 'gram-exprimer',
    public: 'A2',
    objectif: 'Placer deux pronoms devant le verbe.',
    blocks: [
    { kind: 'heading', text: 'Les doubles pronoms' },
    { kind: 'paragraph', text: 'Je mets deux pronoms avant le verbe.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je te le donne.' }, { correct: 'Il me les montre.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Ordre courant : me/te/nous/vous + le/la/les + lui/leur + y + en…' },
    { kind: 'paragraph', text: 'À l’impératif affirmif, ordre différent : donne-le-moi.' },
    { kind: 'note', text: 'Je retiens : je te le / je le lui…' },
    { kind: 'table', headers: ['Exemple', 'Sens'], rows: [['Je te le donne.', 'à toi + le livre'], ['Je le lui donne.', 'le livre + à elle/lui']] },
    { kind: 'note', text: 'Attention ! me/te change en moi/toi à l’impératif : donne-le-moi.' },
    ],
  },
  {
    id: 'k10',
    typeId: 'gram-k10-theorie',
    index: 8,
    title: 'Le subjonctif (emplois principaux)',
    topic: 'gram-exprimer',
    public: 'A2 / B1',
    objectif: 'Reconnaître quand utiliser le subjonctif.',
    blocks: [
    { kind: 'heading', text: 'Le subjonctif' },
    { kind: 'paragraph', text: 'J’utilise le subjonctif après certains verbes et expressions.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Il faut que tu viennes.' }, { correct: 'Je veux qu’il parte.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Après volonté, obligation, sentiment, doute… + que.' },
    { kind: 'paragraph', text: 'Il faut que, je veux que, j’ai peur que, je doute que…' },
    { kind: 'paragraph', text: 'Après espérer → indicatif (présent ou futur).' },
    { kind: 'note', text: 'Je retiens : émotion / volonté / doute + que → souvent subjonctif.' },
    { kind: 'list', title: 'Contextes', items: ['volonté', 'obligation', 'sentiment', 'doute', 'possibilité'] },
    { kind: 'note', text: 'Attention ! J’espère que tu vas bien (pas subjonctif).' },
    ],
  },
  {
    id: 'k11',
    typeId: 'gram-k11-theorie',
    index: 9,
    title: 'Verbes avec préposition',
    topic: 'gram-exprimer',
    public: 'A2',
    objectif: 'Choisir à ou de après un verbe.',
    blocks: [
    { kind: 'heading', text: 'Verbes avec préposition' },
    { kind: 'paragraph', text: 'Certains verbes demandent à ou de.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je commence à lire.' }, { correct: 'J’essaie de comprendre.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Verbe + à + infinitif : commencer à, aider à, apprendre à…' },
    { kind: 'paragraph', text: 'Verbe + de + infinitif : essayer de, décider de, finir de…' },
    { kind: 'note', text: 'Je retiens : mémorise à ou de avec le verbe.' },
    { kind: 'table', headers: ['+ à', '+ de'], rows: [['commencer à', 'essayer de'], ['aider à', 'décider de'], ['apprendre à', 'finir de']] },
    { kind: 'note', text: 'Attention ! Le verbe suivant reste à l’infinitif.' },
    ],
  },
]
