import type { GrammaireTheoryDoc } from '../types'

/** Théorie FALC — thème gram-faits. Français seul (pas de traductions). */
export const faitsDocs: GrammaireTheoryDoc[] = [
  {
    id: 'j6',
    typeId: 'gram-j6-theorie',
    index: 1,
    title: 'La forme passive',
    topic: 'gram-faits',
    public: 'A2',
    objectif: 'Transformer une phrase active en passive.',
    blocks: [
    { kind: 'heading', text: 'La forme passive' },
    { kind: 'paragraph', text: 'Je mets l’objet au début de la phrase.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Active : Le chat mange la souris.' }, { correct: 'Passive : La souris est mangée par le chat.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Passive = être + participe passé (+ par).' },
    { kind: 'paragraph', text: 'Le participe s’accorde avec le nouveau sujet.' },
    { kind: 'note', text: 'Je retiens : être + participe (+ par).' },
    { kind: 'table', headers: ['Active', 'Passive'], rows: [['Le chat mange la souris.', 'La souris est mangée par le chat.']] },
    { kind: 'note', text: 'Attention ! Accorde le participe : mangée (féminin).' },
    ],
  },
  {
    id: 'j7',
    typeId: 'gram-j7-theorie',
    index: 2,
    title: 'Discours direct et indirect',
    topic: 'gram-faits',
    public: 'A2',
    objectif: 'Rapporter des paroles.',
    blocks: [
    { kind: 'heading', text: 'Discours direct et indirect' },
    { kind: 'paragraph', text: 'Je rapporte des paroles avec ou sans guillemets.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Il dit : « Il y a un incendie. »' }, { correct: 'Il dit qu’il y a un incendie.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Direct = guillemets. Indirect = que / si / mot interrogatif.' },
    { kind: 'paragraph', text: 'Ordre → de + infinitif.' },
    { kind: 'paragraph', text: 'Question oui/non → si.' },
    { kind: 'note', text: 'Je retiens : indirect = que / si / mot interrogatif.' },
    { kind: 'table', headers: ['Direct', 'Indirect'], rows: [['Il dit : « Sortez ! »', 'Il demande de sortir.'], ['Il demande : « Est-ce qu’il y a… ? »', 'Il demande s’il y a…']] },
    { kind: 'note', text: 'Attention ! Qu’est-ce que → ce que à l’indirect.' },
    ],
  },
  {
    id: 'j8',
    typeId: 'gram-j8-theorie',
    index: 3,
    title: 'Le conditionnel (emploi)',
    topic: 'gram-faits',
    public: 'A2',
    objectif: 'Exprimer un souhait ou une hypothèse.',
    blocks: [
    { kind: 'heading', text: 'Le conditionnel' },
    { kind: 'paragraph', text: 'J’exprime un souhait, un conseil ou une hypothèse.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'J’aimerais un café.' }, { correct: 'Ce serait bien.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Souvent poli : j’aimerais, je voudrais.' },
    { kind: 'paragraph', text: 'Même terminaisons que l’imparfait, radical du futur.' },
    { kind: 'note', text: 'Je retiens : radical du futur + ais/ais/ait…' },
    { kind: 'table', headers: ['Personne', 'aimer'], rows: [['j’aimerais', 'tu aimerais', 'il aimerait']] },
    { kind: 'note', text: 'Attention ! Souvent avec si + imparfait (fiche hypothèse).' },
    ],
  },
  {
    id: 'j9',
    typeId: 'gram-j9-theorie',
    index: 4,
    title: 'L’hypothèse avec si',
    topic: 'gram-faits',
    public: 'A2',
    objectif: 'Construire une hypothèse avec si.',
    blocks: [
    { kind: 'heading', text: 'L’hypothèse avec si' },
    { kind: 'paragraph', text: 'Je parle d’une situation imaginée.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Si j’avais le temps, je viendrais.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Si + présent → futur / présent (possible).' },
    { kind: 'paragraph', text: 'Si + imparfait → conditionnel (imaginé).' },
    { kind: 'note', text: 'Je retiens : si + imparfait → conditionnel.' },
    { kind: 'table', headers: ['Si…', 'Alors…'], rows: [['Si tu viens', 'nous mangerons ensemble.'], ['Si j’étais riche', 'j’achèterais une maison.']] },
    { kind: 'note', text: 'Attention ! Pas de conditionnel juste après si.' },
    ],
  },
]
