import type { GrammaireTheoryDoc } from '../types'

/** Théorie FALC — thème gram-passe. Français seul (pas de traductions). */
export const passeDocs: GrammaireTheoryDoc[] = [
  {
    id: 'h1',
    typeId: 'gram-h1-theorie',
    index: 1,
    title: 'Le passé composé (idée)',
    topic: 'gram-passe',
    public: 'A1',
    objectif: 'Comprendre le passé composé.',
    blocks: [
    { kind: 'heading', text: 'Le passé composé' },
    { kind: 'paragraph', text: 'Je parle d’une action finie dans le passé.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'J’ai mangé.' }, { correct: 'Elle est partie.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Passé composé = auxiliaire au présent + participe passé.' },
    { kind: 'paragraph', text: 'Auxiliaire avoir (souvent) ou être (certains verbes).' },
    { kind: 'note', text: 'Je retiens : auxiliaire + participe passé.' },
    { kind: 'table', headers: ['Auxiliaire', 'Participe', 'Exemple'], rows: [['j’ai', 'mangé', 'J’ai mangé.'], ['elle est', 'partie', 'Elle est partie.']] },
    { kind: 'note', text: 'Attention ! Choisis le bon auxiliaire (fiches suivantes).' },
    ],
  },
  {
    id: 'h2',
    typeId: 'gram-h2-theorie',
    index: 2,
    title: 'Passé composé avec avoir',
    topic: 'gram-passe',
    public: 'A1',
    objectif: 'Conjuguer le passé composé avec avoir.',
    blocks: [
    { kind: 'heading', text: 'Passé composé avec avoir' },
    { kind: 'paragraph', text: 'Je forme le passé composé avec avoir.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Tu as fini.' }, { correct: 'Nous avons vu un film.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Avoir au présent + participe passé.' },
    { kind: 'paragraph', text: 'Participe : -er → é ; -ir → i ; -re → u (souvent).' },
    { kind: 'note', text: 'Je retiens : j’ai / tu as / il a… + participe.' },
    { kind: 'table', headers: ['Personne', 'Exemple'], rows: [['j’ai', 'J’ai parlé.'], ['tu as', 'Tu as mangé.'], ['il / elle a', 'Elle a fini.'], ['nous avons', 'Nous avons lu.'], ['vous avez', 'Vous avez pris.'], ['ils / elles ont', 'Ils ont vu.']] },
    { kind: 'note', text: 'Attention ! Avec avoir, le participe s’accorde surtout avec le COD placé avant.' },
    ],
  },
  {
    id: 'h3',
    typeId: 'gram-h3-theorie',
    index: 3,
    title: 'Passé composé avec être',
    topic: 'gram-passe',
    public: 'A1',
    objectif: 'Conjuguer le passé composé avec être.',
    blocks: [
    { kind: 'heading', text: 'Passé composé avec être' },
    { kind: 'paragraph', text: 'Certains verbes utilisent être.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je suis allé(e).' }, { correct: 'Ils sont arrivés.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Verbes de mouvement / état courants : aller, venir, arriver, partir, entrer, sortir, monter, descendre, naître, mourir, rester, tomber, retourner, passer…' },
    { kind: 'paragraph', text: 'Verbes pronominaux : être aussi.' },
    { kind: 'paragraph', text: 'Le participe s’accorde avec le sujet.' },
    { kind: 'note', text: 'Je retiens : être + participe accordé.' },
    { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['allé', 'allée'], ['arrivé', 'arrivée'], ['partis', 'parties']] },
    { kind: 'note', text: 'Attention ! Accorde toujours avec le sujet : elle est partie.' },
    ],
  },
  {
    id: 'h4',
    typeId: 'gram-h4-theorie',
    index: 4,
    title: 'L’imparfait',
    topic: 'gram-passe',
    public: 'A1 / A2',
    objectif: 'Décrire le passé avec l’imparfait.',
    blocks: [
    { kind: 'heading', text: 'L’imparfait' },
    { kind: 'paragraph', text: 'Je décris une habitude ou un décor dans le passé.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Quand j’étais enfant, j’aimais le foot.' }, { correct: 'Il faisait beau.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Imparfait = description, habitude, action longue dans le passé.' },
    { kind: 'paragraph', text: 'Base : nous du présent sans -ons + ais, ais, ait, ions, iez, aient.' },
    { kind: 'note', text: 'Je retiens : imparfait = décor / habitude. Passé composé = action finie.' },
    { kind: 'table', headers: ['Personne', 'parler'], rows: [['je', 'parlais'], ['tu', 'parlais'], ['il / elle', 'parlait'], ['nous', 'parlions'], ['vous', 'parliez'], ['ils / elles', 'parlaient']] },
    { kind: 'note', text: 'Attention ! Être est irrégulier : j’étais, tu étais…' },
    ],
  },
  {
    id: 'h5',
    typeId: 'gram-h5-theorie',
    index: 5,
    title: 'Le plus-que-parfait',
    topic: 'gram-passe',
    public: 'A2',
    objectif: 'Dire qu’une action est avant une autre dans le passé.',
    blocks: [
    { kind: 'heading', text: 'Le plus-que-parfait' },
    { kind: 'paragraph', text: 'Je parle d’une action passée avant une autre action passée.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'J’avais fini quand tu es arrivé.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Plus-que-parfait = avoir / être à l’imparfait + participe passé.' },
    { kind: 'note', text: 'Je retiens : avant une autre action passée → plus-que-parfait.' },
    { kind: 'table', headers: ['Forme', 'Exemple'], rows: [['j’avais + participe', 'J’avais mangé.'], ['elle était + participe', 'Elle était partie.']] },
    { kind: 'note', text: 'Attention ! Choisis le même auxiliaire qu’au passé composé.' },
    ],
  },
]
