import type { GrammaireTheoryDoc } from '../types'

/** Théorie FALC — thème gram-pronoms. Français seul (pas de traductions). */
export const pronomsDocs: GrammaireTheoryDoc[] = [
  {
    id: 'i1',
    typeId: 'gram-i1-theorie',
    index: 1,
    title: 'Les pronoms relatifs',
    topic: 'gram-pronoms',
    public: 'A2',
    objectif: 'Relier deux idées avec qui, que, où…',
    blocks: [
    { kind: 'heading', text: 'Les pronoms relatifs' },
    { kind: 'paragraph', text: 'Je relie deux informations dans une phrase.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'L’homme qui parle est mon père.' }, { correct: 'Le livre que je lis est bien.' }, { correct: 'La ville où j’habite est calme.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Qui = sujet. Que = complément. Où = lieu ou temps.' },
    { kind: 'paragraph', text: 'Dont = de + nom (le livre dont je parle).' },
    { kind: 'note', text: 'Je retiens : qui / que / où / dont.' },
    { kind: 'table', headers: ['Pronom', 'Rôle', 'Exemple'], rows: [['qui', 'sujet', 'la femme qui chante'], ['que', 'COD', 'le film que je regarde'], ['où', 'lieu / temps', 'le jour où je suis né'], ['dont', 'de + nom', 'l’ami dont je parle']] },
    { kind: 'note', text: 'Attention ! Que → qu’ devant voyelle : l’homme qu’elle connaît.' },
    ],
  },
  {
    id: 'i2',
    typeId: 'gram-i2-theorie',
    index: 2,
    title: 'Les pronoms possessifs',
    topic: 'gram-pronoms',
    public: 'A2',
    objectif: 'Remplacer mon / ton / son par le mien…',
    blocks: [
    { kind: 'heading', text: 'Les pronoms possessifs' },
    { kind: 'paragraph', text: 'Je remplace un nom déjà connu.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Ce livre est le mien.' }, { correct: 'Cette voiture est la tienne.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Le mien, le tien, le sien, le nôtre, le vôtre, le leur (+ formes fém./plur.).' },
    { kind: 'note', text: 'Je retiens : pronom possessif = article + mien / tien…' },
    { kind: 'table', headers: ['', 'masc. sing.', 'fém. sing.'], rows: [['je', 'le mien', 'la mienne'], ['tu', 'le tien', 'la tienne'], ['il / elle', 'le sien', 'la sienne']] },
    { kind: 'note', text: 'Attention ! Garde l’article : le mien (pas mien seul).' },
    ],
  },
  {
    id: 'i3',
    typeId: 'gram-i3-theorie',
    index: 3,
    title: 'Les pronoms démonstratifs',
    topic: 'gram-pronoms',
    public: 'A2',
    objectif: 'Utiliser celui, celle, ceux, celles.',
    blocks: [
    { kind: 'heading', text: 'Les pronoms démonstratifs' },
    { kind: 'paragraph', text: 'Je désigne une chose sans répéter le nom.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Celui-ci est rouge.' }, { correct: 'Je préfère celle de Marie.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Celui / celle / ceux / celles.' },
    { kind: 'paragraph', text: 'Souvent + -ci / -là ou + de / qui / que.' },
    { kind: 'note', text: 'Je retiens : celui-ci / celle-là…' },
    { kind: 'table', headers: ['', 'singulier', 'pluriel'], rows: [['masculin', 'celui', 'ceux'], ['féminin', 'celle', 'celles']] },
    { kind: 'note', text: 'Attention ! Accorde avec le nom remplacé.' },
    ],
  },
  {
    id: 'i4',
    typeId: 'gram-i4-theorie',
    index: 4,
    title: 'Les pronoms COD',
    topic: 'gram-pronoms',
    public: 'A1 / A2',
    objectif: 'Remplacer le complément d’objet direct.',
    blocks: [
    { kind: 'heading', text: 'Les pronoms COD' },
    { kind: 'paragraph', text: 'Je remplace un nom complément direct.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je regarde le film. → Je le regarde.' }, { correct: 'Tu aimes les pommes. → Tu les aimes.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'me, te, le, la, nous, vous, les.' },
    { kind: 'paragraph', text: 'Le pronom se place avant le verbe.' },
    { kind: 'note', text: 'Je retiens : COD avant le verbe.' },
    { kind: 'table', headers: ['Pronom', 'Exemple'], rows: [['le / la / l’', 'Je le vois.'], ['les', 'Je les mange.'], ['me / te', 'Il me connaît.']] },
    { kind: 'note', text: 'Attention ! Devant voyelle : le/la → l’.' },
    ],
  },
  {
    id: 'i5',
    typeId: 'gram-i5-theorie',
    index: 5,
    title: 'Les pronoms COI',
    topic: 'gram-pronoms',
    public: 'A2',
    objectif: 'Remplacer le complément d’objet indirect.',
    blocks: [
    { kind: 'heading', text: 'Les pronoms COI' },
    { kind: 'paragraph', text: 'Je remplace à + personne.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je parle à Marie. → Je lui parle.' }, { correct: 'Il donne un livre à ses amis. → Il leur donne un livre.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'me, te, lui, nous, vous, leur.' },
    { kind: 'paragraph', text: 'Lui = à lui / à elle. Leur = à eux / à elles.' },
    { kind: 'note', text: 'Je retiens : COI avant le verbe. lui / leur sans à.' },
    { kind: 'table', headers: ['Pronom', 'Remplace'], rows: [['lui', 'à lui / à elle'], ['leur', 'à eux / à elles']] },
    { kind: 'note', text: 'Attention ! Pas de s à leur pronom : je leur parle.' },
    ],
  },
  {
    id: 'i6',
    typeId: 'gram-i6-theorie',
    index: 6,
    title: 'Les pronoms indéfinis',
    topic: 'gram-pronoms',
    public: 'A2',
    objectif: 'Utiliser quelqu’un, quelque chose, rien…',
    blocks: [
    { kind: 'heading', text: 'Les pronoms indéfinis' },
    { kind: 'paragraph', text: 'Je parle d’une personne ou d’une chose non précise.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Quelqu’un frappe.' }, { correct: 'Je ne vois rien.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Quelqu’un / quelque chose / tout le monde / rien / personne…' },
    { kind: 'paragraph', text: 'Rien et personne vont avec ne.' },
    { kind: 'note', text: 'Je retiens : personne / rien + ne.' },
    { kind: 'table', headers: ['Pronom', 'Exemple'], rows: [['quelqu’un', 'Quelqu’un appelle.'], ['quelque chose', 'Je veux quelque chose.'], ['personne', 'Je ne vois personne.'], ['rien', 'Je n’ai rien.']] },
    { kind: 'note', text: 'Attention ! Personne n’est là (personne au début + n’).' },
    ],
  },
  {
    id: 'i7',
    typeId: 'gram-i7-theorie',
    index: 7,
    title: 'En et y',
    topic: 'gram-pronoms',
    public: 'A2',
    objectif: 'Utiliser les pronoms en et y.',
    blocks: [
    { kind: 'heading', text: 'En et y' },
    { kind: 'paragraph', text: 'Je remplace de + chose (en) ou à / dans + lieu (y).' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Tu veux du pain ? — Oui, j’en veux.' }, { correct: 'Tu vas à l’école ? — Oui, j’y vais.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'En remplace de + nom (quantité, partitif).' },
    { kind: 'paragraph', text: 'Y remplace à / en / dans + lieu (ou idée).' },
    { kind: 'note', text: 'Je retiens : en = de. y = à / lieu.' },
    { kind: 'table', headers: ['Pronom', 'Remplace', 'Exemple'], rows: [['en', 'de + chose', 'J’en mange.'], ['y', 'à / lieu', 'J’y vais.']] },
    { kind: 'note', text: 'Attention ! Place en / y avant le verbe : j’y vais.' },
    ],
  },
]
