import type { GrammaireTheoryDoc } from '../types'

/** Théorie FALC — thème gram-questions. Français seul (pas de traductions). */
export const questionsDocs: GrammaireTheoryDoc[] = [
  {
    id: 'c1',
    typeId: 'gram-c1-theorie',
    index: 1,
    title: 'Trois façons de poser une question',
    topic: 'gram-questions',
    public: 'A1',
    objectif: 'Former une question de trois façons.',
    blocks: [
    { kind: 'heading', text: 'Trois façons de poser une question' },
    { kind: 'paragraph', text: 'Je pose une question à l’oral, avec est-ce que, ou avec l’inversion.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Vous êtes italien ? (intonation)' }, { correct: 'Est-ce que vous êtes italien ?' }, { correct: 'Êtes-vous italien ?' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: '1. Intonation (parlé) : même ordre, voix qui monte.' },
    { kind: 'paragraph', text: '2. Est-ce que + phrase (standard).' },
    { kind: 'paragraph', text: '3. Inversion verbe-sujet (soutenu).' },
    { kind: 'note', text: 'Je retiens : est-ce que = forme claire pour débuter.' },
    { kind: 'table', headers: ['Façon', 'Exemple'], rows: [['intonation', 'Vous êtes italien ?'], ['est-ce que', 'Est-ce que vous êtes italien ?'], ['inversion', 'Êtes-vous italien ?']] },
    { kind: 'note', text: 'Attention ! À l’écrit scolaire, préfère est-ce que ou l’inversion.' },
    ],
  },
  {
    id: 'c2',
    typeId: 'gram-c2-theorie',
    index: 2,
    title: 'Questions fermées et ouvertes',
    topic: 'gram-questions',
    public: 'A1',
    objectif: 'Distinguer oui/non et mots interrogatifs.',
    blocks: [
    { kind: 'heading', text: 'Questions fermées et ouvertes' },
    { kind: 'paragraph', text: 'Je sais si la réponse est oui/non ou une information.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Aimes-tu les glaces ? → Oui.' }, { correct: 'Où dors-tu ? → À l’hôtel.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Question fermée → oui ou non.' },
    { kind: 'paragraph', text: 'Question ouverte → qui, que, quand, où, combien, comment, pourquoi.' },
    { kind: 'note', text: 'Je retiens : mot interrogatif = question ouverte.' },
    { kind: 'table', headers: ['Mot', 'Sens', 'Exemple'], rows: [['Qui ?', 'personne', 'Qui vient demain ?'], ['Que ?', 'chose', 'Que prenez-vous ?'], ['Quand ?', 'temps', 'Quand pars-tu ?'], ['Où ?', 'lieu', 'Où dormons-nous ?'], ['Combien ?', 'quantité', 'Combien coûte la chambre ?'], ['Comment ?', 'manière', 'Comment voyage-t-il ?'], ['Pourquoi ?', 'cause', 'Pourquoi est-elle absente ?']] },
    { kind: 'note', text: 'Attention ! Qui = personne. Que = chose.' },
    ],
  },
  {
    id: 'c3',
    typeId: 'gram-c3-theorie',
    index: 3,
    title: 'Les questions avec quel',
    topic: 'gram-questions',
    public: 'A1',
    objectif: 'Accorder quel / quelle / quels / quelles.',
    blocks: [
    { kind: 'heading', text: 'Les questions avec quel' },
    { kind: 'paragraph', text: 'J’utilise quel pour demander une précision sur un nom.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Quel est ton nom ?' }, { correct: 'Quelle est ton adresse ?' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Quel s’accorde avec le nom.' },
    { kind: 'paragraph', text: 'Masculin : quel / quels. Féminin : quelle / quelles.' },
    { kind: 'note', text: 'Je retiens : quel = accord avec le nom.' },
    { kind: 'table', headers: ['', 'Masculin', 'Féminin'], rows: [['singulier', 'quel', 'quelle'], ['pluriel', 'quels', 'quelles']] },
    { kind: 'note', text: 'Attention ! Regarde le genre du nom : activité → quelles activités.' },
    ],
  },
]
