import type { GrammaireTheoryDoc } from '../types'

/** Théorie FALC — thème gram-se-presenter. Français seul (pas de traductions). */
export const sePresenterDocs: GrammaireTheoryDoc[] = [
  {
    id: 'a1',
    typeId: 'gram-a1-theorie',
    index: 1,
    title: 'Qui suis-je ?',
    topic: 'gram-se-presenter',
    public: 'pré-A1 / A1',
    objectif: 'Me présenter avec être, habiter, parler, s’appeler.',
    blocks: [
    { kind: 'heading', text: 'Qui suis-je ?' },
    { kind: 'paragraph', text: 'Je dis mon nom, ma nationalité, ma ville et ma langue.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je m’appelle Adeline.' }, { correct: 'Je suis française.' }, { correct: 'J’habite à Lyon.' }, { correct: 'Je parle français.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Pour me présenter, je donne des informations simples.' },
    { kind: 'paragraph', text: 'J’utilise les verbes : être, habiter, parler, s’appeler.' },
    { kind: 'paragraph', text: 'Un verbe, c’est un mot d’action ou d’état.' },
    { kind: 'paragraph', text: 'Devant une voyelle ou un h, j’écris : j’, m’, t’, s’.' },
    { kind: 'note', text: 'Je retiens : être + nationalité. Habiter à + ville. Parler + langue. S’appeler + prénom.' },
    { kind: 'table', headers: ['Personne', 'être', 'habiter', 'parler', 's’appeler'], rows: [['je', 'suis', 'habite', 'parle', 'm’appelle'], ['tu', 'es', 'habites', 'parles', 't’appelles'], ['il / elle / on', 'est', 'habite', 'parle', 's’appelle'], ['nous', 'sommes', 'habitons', 'parlons', 'nous appelons'], ['vous', 'êtes', 'habitez', 'parlez', 'vous appelez'], ['ils / elles', 'sont', 'habitent', 'parlent', 's’appellent']] },
    { kind: 'note', text: 'Attention ! Avec nous et vous, s’appeler garde nous / vous deux fois : nous nous appelons.' },
    ],
  },
  {
    id: 'a2',
    typeId: 'gram-a2-theorie',
    index: 2,
    title: 'Les adjectifs de nationalité',
    topic: 'gram-se-presenter',
    public: 'A1',
    objectif: 'Accorder l’adjectif de nationalité.',
    blocks: [
    { kind: 'heading', text: 'Les adjectifs de nationalité' },
    { kind: 'paragraph', text: 'Je dis ma nationalité au masculin ou au féminin.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Paul est allemand.' }, { correct: 'Susanne est allemande.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Un adjectif de nationalité dit le pays d’une personne.' },
    { kind: 'paragraph', text: 'Souvent, j’ajoute un e au féminin.' },
    { kind: 'paragraph', text: 'Si le masculin finit déjà par e, le féminin ne change pas.' },
    { kind: 'paragraph', text: 'Exemple : belge, suisse, russe.' },
    { kind: 'note', text: 'Je retiens : féminin souvent + e. Masculin en -e → même forme.' },
    { kind: 'table', headers: ['Masculin', 'Féminin', 'Exemples'], rows: [['-ais', '-aise', 'français / française'], ['-ois', '-oise', 'chinois / chinoise'], ['-ain', '-aine', 'américain / américaine'], ['-en', '-enne', 'italien / italienne']] },
    { kind: 'note', text: 'Attention ! turc → turque ; grec → grecque. Pays en -e souvent féminins, sauf Mexique, Cambodge, Mozambique, Zimbabwe.' },
    ],
  },
  {
    id: 'a3',
    typeId: 'gram-a3-theorie',
    index: 3,
    title: 'Aller : destination (pays et villes)',
    topic: 'gram-se-presenter',
    public: 'A1',
    objectif: 'Dire où je vais (pays, continent, ville).',
    blocks: [
    { kind: 'heading', text: 'Aller : destination (pays et villes)' },
    { kind: 'paragraph', text: 'Je dis ma destination avec le verbe aller.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je vais au Sénégal.' }, { correct: 'Elle va en Chine.' }, { correct: 'Ils vont à Sion.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Le verbe aller indique la destination.' },
    { kind: 'paragraph', text: 'Pays masculin + consonne → au.' },
    { kind: 'paragraph', text: 'Pays masculin + voyelle → en.' },
    { kind: 'paragraph', text: 'Pays féminin → en. Pays pluriel → aux.' },
    { kind: 'paragraph', text: 'Continent → en. Ville → à.' },
    { kind: 'note', text: 'Je retiens : aller = destination. au / en / aux / à selon le lieu.' },
    { kind: 'table', headers: ['Lieu', 'Forme', 'Exemple'], rows: [['pays masc. + consonne', 'au', 'Je vais au Sénégal.'], ['pays masc. + voyelle', 'en', 'Tu vas en Irak.'], ['pays féminin', 'en', 'Elle va en Chine.'], ['pays pluriel', 'aux', 'Nous allons aux Pays-Bas.'], ['continent', 'en', 'Vous allez en Europe.'], ['ville', 'à', 'Ils vont à Sion.']] },
    { kind: 'note', text: 'Attention ! Ne confonds pas au et en.' },
    ],
  },
  {
    id: 'a4',
    typeId: 'gram-a4-theorie',
    index: 4,
    title: 'Aller : destination (lieux et chez)',
    topic: 'gram-se-presenter',
    public: 'A1',
    objectif: 'Dire où je vais (lieux, chez quelqu’un).',
    blocks: [
    { kind: 'heading', text: 'Aller : lieux et chez' },
    { kind: 'paragraph', text: 'Je vais à un lieu. Je vais chez une personne.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je vais chez Sarah.' }, { correct: 'Elle va à la poste.' }, { correct: 'Ils vont au magasin.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Chez + personne.' },
    { kind: 'paragraph', text: 'Lieu féminin → à la. Voyelle ou h → à l’.' },
    { kind: 'paragraph', text: 'Lieu masculin + consonne → au. Pluriel → aux.' },
    { kind: 'note', text: 'Je retiens : chez = personne. à la / à l’ / au / aux = lieu.' },
    { kind: 'table', headers: ['Cas', 'Forme', 'Exemple'], rows: [['personne', 'chez', 'Je vais chez Sarah.'], ['lieu féminin', 'à la', 'Elle va à la poste.'], ['voyelle / h', 'à l’', 'Nous allons à l’école.'], ['lieu masculin', 'au', 'Ils vont au magasin.'], ['pluriel', 'aux', 'Je vais aux Îles.']] },
    { kind: 'note', text: 'Attention ! École est féminin → à l’école.' },
    ],
  },
  {
    id: 'a5',
    typeId: 'gram-a5-theorie',
    index: 5,
    title: 'Venir de : provenance',
    topic: 'gram-se-presenter',
    public: 'A1',
    objectif: 'Dire d’où je viens.',
    blocks: [
    { kind: 'heading', text: 'Venir de : provenance' },
    { kind: 'paragraph', text: 'Je dis ma provenance avec venir de.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je viens du Sénégal.' }, { correct: 'On vient de Chine.' }, { correct: 'Je viens de chez Sarah.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Venir de indique la provenance.' },
    { kind: 'paragraph', text: 'J’utilise du, de, d’, des, de la, de l’, de chez.' },
    { kind: 'note', text: 'Je retiens : aller = où je vais. Venir de = d’où je viens.' },
    { kind: 'table', headers: ['Lieu', 'Forme', 'Exemple'], rows: [['pays masc. + consonne', 'du', 'Je viens du Sénégal.'], ['voyelle', 'd’', 'Tu viens d’Irak.'], ['pays féminin', 'de', 'On vient de Chine.'], ['pluriel', 'des', 'Nous venons des Pays-Bas.'], ['personne', 'de chez', 'Je viens de chez le médecin.']] },
    { kind: 'note', text: 'Attention ! Ne mélange pas aller et venir de.' },
    ],
  },
  {
    id: 'a6',
    typeId: 'gram-a6-theorie',
    index: 6,
    title: 'Dire son âge',
    topic: 'gram-se-presenter',
    public: 'pré-A1 / A1',
    objectif: 'Dire mon âge avec avoir + ans.',
    blocks: [
    { kind: 'heading', text: 'Dire son âge' },
    { kind: 'paragraph', text: 'Je dis mon âge avec le verbe avoir.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Quel âge as-tu ?' }, { correct: 'J’ai 25 ans.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'En français, j’utilise avoir + nombre + an(s).' },
    { kind: 'paragraph', text: 'Je ne dis pas « je suis 25 ans ».' },
    { kind: 'note', text: 'Je retiens : âge = avoir + nombre + an(s).' },
    { kind: 'table', headers: ['Personne', 'Forme', 'Exemple'], rows: [['je', 'j’ai', 'J’ai 15 ans.'], ['tu', 'tu as', 'Tu as 12 ans.'], ['il / elle / on', 'a', 'Elle a 45 ans.'], ['nous', 'avons', 'Nous avons 27 ans.'], ['vous', 'avez', 'Vous avez 50 ans.'], ['ils / elles', 'ont', 'Ils ont 20 ans.']] },
    { kind: 'note', text: 'Attention ! Un an → an. Plusieurs années → ans.' },
    ],
  },
  {
    id: 'a7',
    typeId: 'gram-a7-theorie',
    index: 7,
    title: 'La négation ne … pas',
    topic: 'gram-se-presenter',
    public: 'A1',
    objectif: 'Former une phrase négative avec ne … pas.',
    blocks: [
    { kind: 'heading', text: 'La négation ne … pas' },
    { kind: 'paragraph', text: 'Je mets ne et pas autour du verbe.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je ne suis pas italien.', wrong: 'Je suis pas italien (à l’écrit)' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Ne et pas forment la négation.' },
    { kind: 'paragraph', text: 'Ils se placent autour du verbe.' },
    { kind: 'paragraph', text: 'Temps composé : ne + auxiliaire + pas + participe.' },
    { kind: 'note', text: 'Je retiens : négation de base = ne … pas autour du verbe.' },
    { kind: 'table', headers: ['Cas', 'Forme', 'Exemple'], rows: [['présent', 'ne + verbe + pas', 'Je ne suis pas italien.'], ['composé', 'ne + auxiliaire + pas + participe', 'Je n’ai pas compris.'], ['infinitif', 'ne pas + verbe', 'Ne pas fumer.'], ['impératif', 'ne + verbe + pas', 'Ne fumez pas !']] },
    { kind: 'note', text: 'Attention ! Devant une voyelle : ne → n’.' },
    ],
  },
  {
    id: 'a8',
    typeId: 'gram-a8-theorie',
    index: 8,
    title: 'Autres négations',
    topic: 'gram-se-presenter',
    public: 'A1 / A2',
    objectif: 'Utiliser jamais, plus, rien, personne…',
    blocks: [
    { kind: 'heading', text: 'Autres négations' },
    { kind: 'paragraph', text: 'Je choisis la bonne négation selon le sens.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je n’ai jamais gagné.' }, { correct: 'Je n’ai plus d’argent.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Certaines négations remplacent pas.' },
    { kind: 'paragraph', text: 'Ne … jamais = aucune fois.' },
    { kind: 'paragraph', text: 'Ne … plus = avant oui, maintenant non.' },
    { kind: 'paragraph', text: 'Après sans, le déterminant disparaît.' },
    { kind: 'note', text: 'Je retiens : une idée négative = une négation adaptée.' },
    { kind: 'table', headers: ['Affirmatif', 'Négatif'], rows: [['déjà / toujours', 'ne … jamais / ne … pas encore'], ['encore', 'ne … plus'], ['tout', 'ne … rien'], ['quelqu’un', 'ne … personne'], ['quelques', 'ne … aucun(e)'], ['avec', 'sans']] },
    { kind: 'note', text: 'Attention ! Réponse à une négation : Si = oui malgré le non.' },
    ],
  },
]
