import type { GrammaireTheoryDoc } from '../types'

/** Théorie FALC — thème gram-temps. Français seul (pas de traductions). */
export const tempsDocs: GrammaireTheoryDoc[] = [
  {
    id: 'e2',
    typeId: 'gram-e2-theorie',
    index: 1,
    title: 'Le moment',
    topic: 'gram-temps',
    public: 'A1',
    objectif: 'Dire l’heure, la date, le moment.',
    blocks: [
    { kind: 'heading', text: 'Le moment' },
    { kind: 'paragraph', text: 'Je situe un moment dans le temps.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Il est 8 heures 10.' }, { correct: 'Nous sommes le 24 juin.' }, { correct: 'Nous sommes en décembre.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Heure : Il est … J’ai rendez-vous à 8 h. Vers 8 h = à peu près.' },
    { kind: 'paragraph', text: 'Date : jour, mois, année.' },
    { kind: 'paragraph', text: 'Mois : en décembre / au mois de décembre.' },
    { kind: 'paragraph', text: 'Saisons : au printemps ; en été, en automne, en hiver.' },
    { kind: 'paragraph', text: 'Année : en 2024. Siècle : au XXIe siècle.' },
    { kind: 'note', text: 'Je retiens : à + heure. en + mois / année. au printemps.' },
    { kind: 'table', headers: ['Cas', 'Forme'], rows: [['heure précise', 'à 8 h'], ['environ', 'vers 8 h'], ['mois', 'en décembre'], ['printemps', 'au printemps'], ['été / automne / hiver', 'en …']] },
    { kind: 'note', text: 'Attention ! Printemps → au. Autres saisons → en.' },
    ],
  },
  {
    id: 'e3',
    typeId: 'gram-e3-theorie',
    index: 2,
    title: 'La durée',
    topic: 'gram-temps',
    public: 'A1 / A2',
    objectif: 'Dire combien de temps.',
    blocks: [
    { kind: 'heading', text: 'La durée' },
    { kind: 'paragraph', text: 'Je dis combien de temps dure une action.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je travaille depuis deux heures.' }, { correct: 'Le cours dure une heure.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Depuis = action commencée, encore vraie.' },
    { kind: 'paragraph', text: 'Pendant = durée terminée ou totale.' },
    { kind: 'paragraph', text: 'Pour = durée prévue (souvent futur).' },
    { kind: 'paragraph', text: 'Il y a = moment passé (il y a deux jours).' },
    { kind: 'note', text: 'Je retiens : depuis / pendant / pour / il y a — sens différents.' },
    { kind: 'table', headers: ['Mot', 'Sens', 'Exemple'], rows: [['depuis', 'commencé, continue', 'J’habite ici depuis 2019.'], ['pendant', 'durée', 'J’ai dormi pendant 8 heures.'], ['pour', 'durée prévue', 'Je pars pour une semaine.'], ['il y a', 'dans le passé', 'Il est parti il y a 10 minutes.']] },
    { kind: 'note', text: 'Attention ! Ne confonds pas depuis et pendant.' },
    ],
  },
  {
    id: 'e4',
    typeId: 'gram-e4-theorie',
    index: 3,
    title: 'La fréquence',
    topic: 'gram-temps',
    public: 'A1',
    objectif: 'Dire à quelle fréquence.',
    blocks: [
    { kind: 'heading', text: 'La fréquence' },
    { kind: 'paragraph', text: 'Je dis si une action est rare ou fréquente.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'Je vais toujours à pied.' }, { correct: 'Parfois, je prends le bus.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Mots de fréquence : toujours, souvent, parfois, rarement, jamais.' },
    { kind: 'paragraph', text: 'Autres : tous les jours, une fois par semaine, le lundi…' },
    { kind: 'note', text: 'Je retiens : place souvent devant le verbe (présent).' },
    { kind: 'table', headers: ['Fréquence', 'Exemple'], rows: [['toujours', 'Je suis toujours à l’heure.'], ['souvent', 'Tu viens souvent ici.'], ['parfois', 'Parfois, il pleut.'], ['rarement', 'Nous sortons rarement.'], ['jamais', 'Je ne mange jamais de viande.']] },
    { kind: 'note', text: 'Attention ! Jamais va avec ne : je ne … jamais.' },
    ],
  },
  {
    id: 'e5',
    typeId: 'gram-e5-theorie',
    index: 4,
    title: 'La succession',
    topic: 'gram-temps',
    public: 'A1 / A2',
    objectif: 'Ordonner des actions dans le temps.',
    blocks: [
    { kind: 'heading', text: 'La succession' },
    { kind: 'paragraph', text: 'Je dis l’ordre des actions.' },
    { kind: 'heading', text: 'Je regarde', sub: true },
    { kind: 'rule', text: 'Exemple', examples: [{ correct: 'D’abord je me lève. Ensuite je prends le bus.' }, { correct: 'Puis j’arrive au travail.' }] },
    { kind: 'heading', text: 'J’explique', sub: true },
    { kind: 'paragraph', text: 'Mots utiles : d’abord, puis, ensuite, après, enfin, finalement.' },
    { kind: 'paragraph', text: 'Avant / après + nom ou infinitif.' },
    { kind: 'note', text: 'Je retiens : d’abord → puis / ensuite → enfin.' },
    { kind: 'list', title: 'Mots de succession', items: ['d’abord', 'puis', 'ensuite', 'après', 'enfin', 'finalement', 'avant', 'après'] },
    { kind: 'note', text: 'Attention ! Une idée par phrase, surtout en FALC.' },
    ],
  },
]
