/** Généré par scripts/build-grammar-theory-banks.mjs — théories FR (soutien scolaire). */
import type { GrammarTheoryDoc } from './grammar-theory'

export const GRAMMAR_THEORY_BY_TOPIC: Record<string, GrammarTheoryDoc[]> = {
  'fr-presenter': [
    {
      id: 'fr-presenter-theorie-1',
      index: 1,
      title: 'Le verbe être',
      sourceSlug: 'a1-gr-etre',
      blocks: [
        { kind: 'paragraph', text: 'Le verbe ÊTRE sert à donner des informations sur une personne, comme son identité ou décrire quelqu\'un.' },
        { kind: 'table', headers: ['', 'Exemple'], rows: [['Identité', 'Je suis Ali.'], ['Nationalité', 'Elle est française.'], ['Profession', 'Nous sommes étudiants.'], ['Description', 'Il est grand.'], ['Situation', 'Tu es à Genève.']] },
        { kind: 'heading', text: 'Conjugaison' },
        { kind: 'table', headers: ['Pronom sujet', 'Verbe'], rows: [['Je', 'suis'], ['Tu', 'es'], ['Il / Elle / On', 'est'], ['Nous', 'sommes'], ['Vous', 'êtes'], ['Ils / Elles', 'sont']] },
        { kind: 'heading', text: 'Prononciation' },
        { kind: 'paragraph', text: '1. On ne prononce pas le e final de elle.' },
        { kind: 'paragraph', text: '2. On fait la liaison.' },
        { kind: 'list', items: ['O{li}n|e{/li}st, vou{li}s|ê{/li}tes.'] },
      ],
    },
    {
      id: 'fr-presenter-theorie-2',
      index: 2,
      title: 'Le verbe avoir',
      sourceSlug: 'a1-gr-avoir',
      blocks: [
        { kind: 'paragraph', text: 'Le verbe AVOIR sert à dire l\'âge, de parler de la famille et des amis, de dire ce qu\'on possède ou d\'exprimer une sensation.' },
        { kind: 'table', headers: ['', 'Exemple'], rows: [['Possession', 'J\'ai un téléphone.'], ['Âge', 'Elle a 25 ans.'], ['Sensations', 'Nous avons faim.'], ['Expressions', 'Il a de la chance.']] },
        { kind: 'heading', text: 'Conjugaison' },
        { kind: 'table', headers: ['Pronom sujet', 'Verbe'], rows: [['J\'', 'ai'], ['Tu', 'as'], ['Il / Elle / On', 'a'], ['Nous', 'avons'], ['Vous', 'avez'], ['Ils / Elles', 'ont']] },
        { kind: 'heading', text: 'Expressions avec AVOIR' },
        { kind: 'table', headers: ['Expression', 'Signification'], rows: [['Avoir faim', 'vouloir manger'], ['Avoir soif', 'vouloir boire'], ['Avoir froid', 'ressentir le froid'], ['Avoir chaud', 'ressentir la chaleur'], ['Avoir peur', 'être effrayé(e)'], ['Avoir mal', 'ressentir une douleur'], ['Avoir raison', 'être correct(e)'], ['Avoir tort', 'se tromper']] },
        { kind: 'heading', text: 'Prononciation et orthographe' },
        { kind: 'paragraph', text: '1. On ne prononce pas le e final de elle.' },
        { kind: 'paragraph', text: '2. On fait la liaison.' },
        { kind: 'list', items: ['O{li}n|a{/li},nou{li}s|a{/li}vons,vou{li}s|a{/li}vez,il{li}s|o{/li}nt,elle{li}s|o{/li}nt.'] },
        { kind: 'paragraph', text: '3. Le pronom je devient j\' devant une voyelle.' },
        { kind: 'list', items: ['{s}Je ai{/s}→J\'ai 20 ans.'] },
      ],
    },
    {
      id: 'fr-presenter-theorie-3',
      index: 3,
      title: 'Il y a… C\'est… Il est…',
      sourceSlug: 'a1-gr-cest-il-est',
      blocks: [
        { kind: 'paragraph', text: 'Il y a permet d\'indiquer la présence d\'une personne ou d\'une chose dans un lieu.' },
        { kind: 'list', items: ['Il y a beaucoup de photos.', 'Il y a le professeur dans la salle.'] },
        { kind: 'paragraph', text: 'C\'est permet d\'identifier une personne ou une chose.' },
        { kind: 'list', items: ['C\'est mon cousin.', 'C\'est un stylo.'] },
      ],
    },
  ],
  'fr-famille': [
    {
      id: 'fr-famille-theorie-1',
      index: 1,
      title: 'Les adjectifs possessifs',
      sourceSlug: 'a1-gr-l19',
      blocks: [
        { kind: 'heading', text: 'Utilisation' },
        { kind: 'paragraph', text: 'Pour indiquer une possession.' },
        { kind: 'list', items: ['C\'est ma veste.'] },
        { kind: 'paragraph', text: 'Pour indiquer une relation entre personnes.' },
        { kind: 'list', items: ['Je te présente mon frère.'] },
        { kind: 'paragraph', text: 'Pour indiquer une relation entre des choses ou des lieux.' },
        { kind: 'list', items: ['Mon appartement est à Lyon.'] },
        { kind: 'heading', text: 'Formes' },
        { kind: 'paragraph', text: 'L\'adjectif possessif se place devant le nom et s\'accorde avec lui. La forme dépend de la personne et du genre / nombre de l\'objet possédé.' },
        { kind: 'table', headers: ['Personne', 'Masculin', 'Féminin', 'Pluriel'], rows: [['Je', 'mon manteau', 'ma veste', 'mes vêtements'], ['Tu', 'ton manteau', 'ta veste', 'tes vêtements'], ['Il / Elle', 'son manteau', 'sa veste', 'ses vêtements'], ['Nous', 'notre manteau', 'notre veste', 'nos vêtements'], ['Vous', 'votre manteau', 'votre veste', 'vos vêtements'], ['Ils / Elles', 'leur manteau', 'leur veste', 'leurs vêtements']] },
        { kind: 'heading', text: 'Attention', sub: true },
        { kind: 'paragraph', text: 'Quand l\'article est devant un nom féminin qui commence par une voyelle ou un h muet, on utilise mon, ton, son à la place de ma, ta, sa. On ne peut alors pas savoir le genre d\'après l\'adjectif seul.' },
        { kind: 'list', items: ['{s}Ma{/s} écharpe est rouge. → Mon écharpe est rouge.', '{s}Ta{/s} école est loin ? → Ton école est loin ?', '{s}Sa{/s} histoire est triste → {s}Son histoire est triste.'] },
        { kind: 'paragraph', text: 'Quand on utilise le pronom on à la place de nous dans la phrase, on utilise les adjectifs possessifs notre et nos.' },
        { kind: 'list', items: ['On invite souvent notre voisin et nos amis à dîner.'] },
      ],
    },
  ],
  'fr-description': [
    {
      id: 'fr-description-theorie-1',
      index: 1,
      title: 'Le genre des adjectifs',
      sourceSlug: 'a1-gr-genre-adjectifs',
      blocks: [
        { kind: 'heading', text: 'Les adjectifs' },
        { kind: 'paragraph', text: 'L\'adjectif donne une information sur le nom. Les adjectifs changent aussi selon le genre.' },
        { kind: 'paragraph', text: 'On ajoute souvent -e au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Le sac est petit.', 'La voiture est petite.'], ['Un homme français parle.', 'Une femme française parle.']] },
        { kind: 'paragraph', text: 'Si l\'adjectif masculin se termine déjà par e, le féminin ne change pas.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Ce lit est moderne.', 'Cette chaise est moderne.'], ['Ce garçon est calme.', 'Cette fille est calme.']] },
        { kind: 'heading', text: 'Cas particuliers' },
        { kind: 'paragraph', text: 'Certains adjectifs ont des terminaisons différentes au masculin et au féminin.' },
        { kind: 'heading', text: '-en', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -en au masculin changent en -enne au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Le meuble est ancien.', 'La table est ancienne.'], ['Le train est européen.', 'La voiture est européenne.'], ['Le prix est moyen.', 'La taille est moyenne.']] },
        { kind: 'heading', text: '-on', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -on au masculin changent en -onne au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Le café est bon.', 'La tarte est bonne.'], ['Le chat est mignon.', 'La robe est mignonne.'], ['Il est breton.', 'Elle est bretonne.']] },
        { kind: 'heading', text: '-el', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -el au masculin changent en -elle au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Le parfum est naturel.', 'La fleur est naturelle.'], ['Le choix est personnel.', 'La lettre est personnelle.'], ['Le ton est formel.', 'La tenue est formelle.']] },
        { kind: 'heading', text: '-er', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -er au masculin changent en -ère au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Il est étranger.', 'Elle est étrangère.'], ['Le sac est cher.', 'La robe est chère.'], ['C\'est le premier jour.', 'C\'est la première fois.']] },
        { kind: 'heading', text: '-et', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -et au masculin changent en -ète ou -ette au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['L\'hôtel est complet.', 'La salle est complète.'], ['Le pull est violet.', 'La robe est violette.'], ['Le plan est secret.', 'La porte est secrète.']] },
        { kind: 'heading', text: '-eux', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -eux au masculin changent en -euse au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Il est heureux.', 'Elle est heureuse.'], ['Il est sérieux.', 'Elle est sérieuse.'], ['Il est joyeux.', 'Elle est joyeuse.']] },
        { kind: 'heading', text: '-eur', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -eur au masculin changent en -euse au féminin.' },
      ],
    },
    {
      id: 'fr-description-theorie-2',
      index: 2,
      title: 'Le pluriel des adjectifs',
      sourceSlug: 'a1-gr-pluriel-adjectifs',
      blocks: [
        { kind: 'heading', text: 'Formation du pluriel' },
        { kind: 'paragraph', text: 'Les adjectifs changent aussi selon le nombre. On ajoute souvent -s au pluriel.' },
        { kind: 'table', headers: ['Singulier', 'Pluriel'], rows: [['Le sac est petit.', 'Les sacs sont petits.'], ['La voiture est petite.', 'Les voitures sont petites.']] },
        { kind: 'paragraph', text: 'Si l\'adjectif singulier se termine par s ou x, le pluriel ne change pas.' },
        { kind: 'table', headers: ['Singulier', 'Pluriel'], rows: [['Cet homme est mauvais.', 'Ces hommes sont mauvais.'], ['Le professeur est ennuyeux.', 'Les professeurs sont ennuyeux.']] },
        { kind: 'heading', text: 'Les adjectifs invariables' },
        { kind: 'paragraph', text: 'Les adjectifs de couleur dérivés d\'un nom sont invariables.' },
        { kind: 'table', headers: ['Singulier', 'Pluriel'], rows: [['une robe orange', 'des robes orange'], ['une chaussure marron', 'des chaussures marron'], ['un œil noisette', 'des yeux noisette']] },
        { kind: 'heading', text: 'Exceptions', sub: true },
        { kind: 'list', items: ['Les adjectifs de couleur rose, mauve, écarlate et pourpre s\'accordent en nombre comme les adjectifs réguliers.'] },
        { kind: 'table', headers: ['Singulier', 'Pluriel'], rows: [['une robe rose', 'des robes roses'], ['une fleur mauve', 'des fleurs mauves'], ['une écharpe écarlate', 'des écharpes écarlates'], ['une robe pourpre', 'des robes pourpres']] },
        { kind: 'heading', text: 'Cas particuliers' },
        { kind: 'paragraph', text: 'Le féminin pluriel reste régulier (+ s).' },
        { kind: 'heading', text: '-al', sub: true },
        { kind: 'paragraph', text: 'Les mots masculins terminant par -al au singulier changent en -aux au pluriel.' },
        { kind: 'table', headers: ['Singulier', 'Pluriel'], rows: [['Ce pantalon est original.', 'Ces pantalons sont originaux.'], ['Ce livre est national.', 'Ces livres sont nationaux.'], ['Ce problème est principal.', 'Ces problèmes sont principaux.']] },
        { kind: 'heading', text: 'Exceptions', sub: true },
        { kind: 'list', items: ['fatal → fatals', 'banal → banals'] },
        { kind: 'heading', text: '-eau', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -eau au singulier changent en -eaux au pluriel.' },
        { kind: 'table', headers: ['Singulier', 'Pluriel'], rows: [['Ce pantalon est beau.', 'Ces pantalons sont beaux.'], ['Ce lit est nouveau.', 'Ces lits sont nouveaux.'], ['Ce frère est jumeau.', 'Ces frères sont jumeaux.']] },
      ],
    },
  ],
  'fr-logement': [
    {
      id: 'fr-logement-theorie-1',
      index: 1,
      title: 'Les articles définis et indéfinis',
      sourceSlug: 'a1-gr-l04',
      blocks: [
        { kind: 'heading', text: 'Utilisation' },
        { kind: 'paragraph', text: 'Les articles accompagnent un nom. Ils indiquent son genre (masculin ou féminin) et son nombre (singulier ou pluriel).' },
        { kind: 'heading', text: 'Articles définis' },
        { kind: 'paragraph', text: 'Les articles définis sont le, la, l\' et les. On utilise ces articles pour parler de :' },
        { kind: 'heading', text: 'Notion générale', sub: true },
        { kind: 'list', items: ['La monnaie est importante.', 'Les animaux ont besoin d\'eau.'] },
        { kind: 'heading', text: 'Personne, objet ou lieu déjà connu', sub: true },
        { kind: 'list', items: ['La carte bancaire de Marie.', 'Le directeur est dans son bureau.', 'J\'ouvre la fenêtre.'] },
        { kind: 'heading', text: 'Articles indéfinis' },
        { kind: 'paragraph', text: 'Les articles indéfinis sont un, une et des. On utilise ces articles pour parler de :' },
        { kind: 'heading', text: 'Personne ou chose non précise', sub: true },
        { kind: 'list', items: ['Un client entre dans le magasin.', 'Ce sont des billets de banque.'] },
        { kind: 'heading', text: 'Quantité', sub: true },
        { kind: 'list', items: ['Vous avez des pièces de 5 francs ?', 'J\'ai un billet de 10 francs.'] },
        { kind: 'paragraph', text: 'Verbes de préférence (aimer, adorer, préférer ou détester' },
        { kind: 'list', items: ['J\'aime les fruits.', 'Elle préfère le thé.'] },
        { kind: 'heading', text: 'Formes' },
        { kind: 'paragraph', text: 'L\'article se place devant un nom ou un groupe nominal et s\'accorde en genre et en nombre.' },
        { kind: 'table', headers: ['', 'Articles définis', 'Articles indéfinis'], rows: [['Masculin singulier', 'le chèque', 'un chèque'], ['Féminin singulier', 'la carte bancaire', 'une carte bancaire'], ['Masculin pluriel', 'les billets', 'des billets'], ['Féminin pluriel', 'les pièces', 'des pièces']] },
        { kind: 'heading', text: 'Attention', sub: true },
        { kind: 'paragraph', text: 'Les le, la deviennent l\' devant une voyelle ou un h muet.' },
        { kind: 'list', items: ['{s}Le{/s} argent → l\'argent', '{s}La{/s} histoire → l\'histoire'] },
      ],
    },
  ],
  'fr-achats': [
    {
      id: 'fr-achats-theorie-1',
      index: 1,
      title: 'La place de l\'adjectif',
      sourceSlug: 'a1-gr-place-adjectif',
      blocks: [
        { kind: 'heading', text: 'Utilisation' },
        { kind: 'paragraph', text: 'En général, l\'adjectif qualificatif se place après le nom.' },
        { kind: 'list', items: ['J\'habite dans une maison moderne.', 'six milliards d\'habitants'] },
        { kind: 'paragraph', text: 'Les adjectifs se placent toujours après le nom lorsqu\'ils indiquent :' },
        { kind: 'table', headers: ['Type', 'Exemples'], rows: [['la nationalité', 'une amie japonaise'], ['la couleur', 'une voiture rouge'], ['la forme', 'une table ronde'], ['la religion', 'une école catholique'], ['la matière', 'une bague métallique'], ['les adjectifs longs', 'un exercice intéressant'], ['les adjectifs participiaux', 'une personne fatiguée']] },
        { kind: 'heading', text: 'Les adjectifs placés avant le nom' },
        { kind: 'paragraph', text: 'Certains adjectifs courts et très fréquents se placent généralement avant le nom. Ils appartiennent souvent à la catégorie BAGS.' },
        { kind: 'table', headers: ['Catégorie', 'Adjectifs fréquents'], rows: [['Beauté', 'C’est un beau jardin. Elle porte une jolie robe.'], ['Âge', 'Un jeune homme arrive. Un vieux bâtiment est près d’ici. J’ai un nouveau téléphone. Un ancien professeur travaille ici.'], ['Grandeur', 'Une grande maison est à vendre. J’ai un petit sac. Un gros chien court dans le parc. Elle porte un long manteau. Il achète un court pantalon.'], ['Sentiment', 'Un bon repas est préparé. Un mauvais résultat arrive. Un gentil garçon aide sa mère. Un méchant homme crie dans la rue.']] },
        { kind: 'heading', text: 'Les adjectifs qui peuvent être avant ou après' },
        { kind: 'paragraph', text: 'Certains adjectifs changent de place selon le sens recherché.' },
        { kind: 'table', headers: ['Adjectif', 'Après le nom', 'Avant le nom'], rows: [['ancien ancienne', 'un bâtiment ancien (= vieux)', 'mon ancienne maison (= précédente)'], ['cher chère', 'une voiture chère (= coûteuse)', 'mon cher ami (= bien-aimé)'], ['curieux curieuse', 'des voisins curieux (= indiscrets)', 'une curieuse histoire (= étrange)'], ['dernier dernière', 'le mois dernier (= précédent)', 'la dernière page (= finale)'], ['différent différente', 'des exercices différents (= variés)', 'différentes personnes (= plusieurs)'], ['grand grande', 'un homme grand (= de grande taille)', 'un grand homme (= célèbre)'], ['pauvre', 'un homme pauvre (= sans argent)', 'ce pauvre homme (= malheureux)'], ['prochain prochaine', 'la semaine prochaine (= à venir)', 'le prochain train (= le suivant)'], ['petit petite', 'une fille petite (= de petite taille)', 'un petit cadeau (= modeste)'], ['propre', 'une cuisine propre (= nette)', 'ma propre chambre (= à moi)'], ['seul seule', 'une personne seule (= isolée)', 'une seule personne (= une seule)'], ['simple', 'une idée simple (= facile)', 'une simple erreur (= seulement)'], ['vrai vraie', 'une histoire vraie (= réelle)', 'un vrai ami (= authentique)'], ['brave', 'un homme brave (= courageux)', 'un brave homme (= gentil)']] },
        { kind: 'heading', text: 'Ordre des adjectifs' },
        { kind: 'paragraph', text: 'Lorsqu\'un nom est accompagné de plusieurs adjectifs, ils suivent généralement cet ordre :' },
        { kind: 'paragraph', text: '1. adjectif numéral 2. adjectif BAGS 3. nom 4. adjectifs descriptifs' },
        { kind: 'heading', text: 'Exemples', sub: true },
        { kind: 'list', items: ['les trois petits chiens noirs', 'les quatre nouveaux élèves français', 'une grande maison blanche'] },
        { kind: 'paragraph', text: 'L\'adjectif placé le plus près du nom précise généralement sa caractéristique principale.' },
        { kind: 'list', items: ['une élection présidentielle espagnole', 'une voiture électrique allemande'] },
      ],
    },
    {
      id: 'fr-achats-theorie-2',
      index: 2,
      title: 'L\'expression de la quantité',
      sourceSlug: 'a1-gr-expression-quantite',
      blocks: [
        { kind: 'heading', text: 'Utilisation' },
        { kind: 'paragraph', text: 'On utilise différentes expressions pour indiquer une quantité. La quantité peut être indéterminée, précise ou relative.' },
        { kind: 'heading', text: 'Quantités indéterminées' },
        { kind: 'paragraph', text: 'On utilise les articles partitifs du, de la, de l\' ou l\'article indéfini des lorsque l\'on parle d\'une quantité non précisée.' },
        { kind: 'list', items: ['Je veux du beurre et de la confiture.'] },
        { kind: 'heading', text: 'Quantités précises' },
        { kind: 'paragraph', text: 'Pour donner une quantité exacte ou mesurable, on utilise une expression de mesure suivie de de ou d\'.' },
        { kind: 'table', headers: ['Expression', 'Signification'], rows: [['un kilo de pommes', 'mesure de poids'], ['une bouteille de lait', 'quantité contenue dans une bouteille'], ['un morceau de fromage', 'petite partie d\'un aliment'], ['un litre de jus', 'mesure de volume'], ['une tasse de café', 'quantité contenue dans une tasse'], ['une tranche de pain', 'partie fine et plate coupée dans un aliment']] },
        { kind: 'heading', text: 'Attention', sub: true },
        { kind: 'paragraph', text: 'Le nom qui suit une mesure ne prend pas d\'article.' },
        { kind: 'list', items: ['un kilo {s}de la{/s} farine → un kilo de farine.', 'une bouteille {s}du{/s} jus → une bouteille de jus.'] },
        { kind: 'heading', text: 'Quantités relatives' },
        { kind: 'table', headers: ['Expression', 'Signification'], rows: [['Il mange trop de chocolat.', 'quantité excessive, plus que nécessaire'], ['Nous avons beaucoup de travail.', 'grande quantité'], ['Je voudrais un peu de sucre.', 'petite quantité'], ['Il boit peu de café.', 'très faible quantité'], ['J\'ai assez de temps.', 'quantité suffisante, qui répond au besoin'], ['Il n\'y a pas assez de places.', 'quantité insuffisante, moins que nécessaire']] },
      ],
    },
  ],
  'fr-vetements': [
    {
      id: 'fr-vetements-theorie-1',
      index: 1,
      title: 'Le conditionnel présent',
      sourceSlug: 'a1-gr-conditionnel-present',
      blocks: [
        { kind: 'heading', text: 'Utilisation' },
        { kind: 'heading', text: 'Demander un service poliment', sub: true },
        { kind: 'list', items: ['Je voudrais deux baguettes… ; Vous pourriez m\'apporter de l\'eau…', 'Auriez-vous l\'heure ? ; Sauriez-vous comment on va à Giverny ?'] },
        { kind: 'heading', text: 'Exprimer un souhait, un désir', sub: true },
        { kind: 'list', items: ['On voudrait déménager. ; Tu aimerais aller où ?', 'Je préférerais une bouteille… ; Vous souhaiteriez vivre au bord de la mer ?'] },
        { kind: 'heading', text: 'Suggestion / conseil', sub: true },
        { kind: 'list', items: ['Ce soir, si tu veux, on pourrait aller au cinéma.', 'Tu devrais te renseigner… ; Si j\'étais toi / À ta place, je me renseignerais.'] },
        { kind: 'heading', text: 'Conjugaison' },
        { kind: 'list', items: ['Radical du futur simple + terminaisons de l\'imparfait (-ais, -ais, -ait, -ions, -iez, -aient).'] },
        { kind: 'table', headers: ['', 'aimer', 'préférer', 'souhaiter'], rows: [['je / j\'', 'aimerais', 'préférerais', 'souhaiterais'], ['tu', 'aimerais', 'préférerais', 'souhaiterais'], ['il / elle / on', 'aimerait', 'préférerait', 'souhaiterait'], ['nous', 'aimerions', 'préférerions', 'souhaiterions'], ['vous', 'aimeriez', 'préféreriez', 'souhaiteriez'], ['ils / elles', 'aimeraient', 'préféreraient', 'souhaiteraient']] },
        { kind: 'note', text: 'Les verbes irréguliers au futur le sont aussi au conditionnel. → À ta place, j\'irais chez le médecin. ; À ma place, vous feriez quoi ?' },
        { kind: 'heading', text: 'Le conditionnel présent' },
        { kind: 'paragraph', text: 'Formation : infinitif (ou base du futur) + terminaisons de l\'imparfait' },
        { kind: 'list', items: ['Terminaisons : -ais / -ais / -ait / -ions / -iez / -aient'] },
        { kind: 'heading', text: 'parler (conditionnel présent)', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'parlerais'], ['tu', 'parlerais'], ['il / elle / on', 'parlerait'], ['nous', 'parlerions'], ['vous', 'parleriez'], ['ils / elles', 'parleraient']] },
        { kind: 'heading', text: 'Bases irrégulières', sub: true },
        { kind: 'table', headers: ['Infinitif', 'Base', 'Exemple'], rows: [['être', 'ser-', 'je serais'], ['avoir', 'aur-', 'j\'aurais'], ['aller', 'ir-', 'j\'irais'], ['faire', 'fer-', 'je ferais'], ['pouvoir', 'pourr-', 'je pourrais'], ['vouloir', 'voudr-', 'je voudrais'], ['venir', 'viendr-', 'je viendrais'], ['devoir', 'devr-', 'je devrais'], ['savoir', 'saur-', 'je saurais']] },
        { kind: 'heading', text: 'Le conditionnel passé' },
        { kind: 'paragraph', text: 'Formation : avoir ou être au conditionnel présent + participe passé' },
        { kind: 'list', items: ['Même choix d\'auxiliaire qu\'au passé composé.'] },
        { kind: 'table', headers: ['Verbe', 'Conditionnel passé', 'Sens'], rows: [['parler', 'j\'aurais parlé', 'I would have spoken'], ['partir', 'je serais parti(e)', 'I would have left'], ['se lever', 'je me serais levé(e)', 'I would have got up']] },
        { kind: 'heading', text: 'Les phrases hypothétiques avec si' },
        { kind: 'table', headers: ['Type', 'Si + …', 'Résultat', 'Exemple'], rows: [['Probable', 'présent', 'futur simple', 'Si tu viens, nous irons au cinéma.'], ['Improbable', 'imparfait', 'conditionnel présent', 'Si j\'avais le temps, je voyagerais.'], ['Impossible (passé)', 'plus-que-parfait', 'conditionnel passé', 'Si j\'avais étudié, j\'aurais réussi.']] },
        { kind: 'heading', text: 'Règle clé', sub: true },
        { kind: 'list', items: ['Jamais de conditionnel dans la proposition avec si.', 'Si + présent → futur ; Si + imparfait → conditionnel présent ; Si + plus-que-parfait → conditionnel passé.'] },
        { kind: 'heading', text: 'Entraînement conjugaison' },
        { kind: 'heading', text: 'Le conditionnel présent' },
      ],
    },
  ],
  'fr-nourriture': [
    {
      id: 'fr-nourriture-theorie-1',
      index: 1,
      title: 'L\'article partitif',
      sourceSlug: 'a1-gr-article-partitif',
      blocks: [
        { kind: 'paragraph', text: 'L\'article partitif est utilisé pour parler d\'une quantité indéterminée — une partie de quelque chose que l\'on ne peut pas compter.' },
        { kind: 'heading', text: 'Choses concrètes', sub: true },
        { kind: 'list', items: ['du poulet', 'de la pizza', 'de l\'eau.'] },
        { kind: 'heading', text: 'Choses abstraites', sub: true },
        { kind: 'list', items: ['du courage', 'de la chance', 'de l\'amour.'] },
        { kind: 'heading', text: 'Formes' },
        { kind: 'table', headers: ['Genre', 'Article', 'Exemple'], rows: [['Masculin', 'du (de + le)', 'Je mange du pain.'], ['Féminin', 'de la', 'Je bois de la limonade.'], ['Devant voyelle', 'de l\'', 'Je bois de l\'eau.'], ['Devant h', 'de l\'', 'Je rajoute de l\'huile.'], ['Pluriel', 'des', 'Je mange des légumes.']] },
        { kind: 'heading', text: 'Négation' },
        { kind: 'paragraph', text: 'À la forme négative, le partitif est remplacé par de ou d\'. La distinction masculin et féminin disparaît.' },
        { kind: 'table', headers: ['Affirmatif', 'Négatif'], rows: [['Je mange du pain.', 'Je ne mange pas de pain.'], ['Tu bois de la soupe.', 'Tu ne bois pas de soupe.'], ['Elle prend de l\'huile.', 'Elle ne prend pas d\'huile.'], ['Ils ont des enfants.', 'Ils n\'ont pas d\'enfants.']] },
        { kind: 'heading', text: 'Attention', sub: true },
        { kind: 'paragraph', text: 'Avec le verbe être, le partitif ne change pas.' },
        { kind: 'list', items: ['C\'est du sucre. → Ce n\'est pas du sucre.'] },
      ],
    },
  ],
  'fr-sante': [
    {
      id: 'fr-sante-theorie-1',
      index: 1,
      title: 'Les verbes modaux',
      sourceSlug: 'a1-gr-modaux',
      blocks: [
        { kind: 'heading', text: 'Utilisation' },
        { kind: 'paragraph', text: 'Ces verbes expriment un état,une capacité ou une obligation. Ils sont toujours suivis d\'un infinitif.' },
        { kind: 'heading', text: 'Vouloir', sub: true },
        { kind: 'paragraph', text: 'Vouloir sert à exprimer un désir ou une volonté.' },
        { kind: 'table', headers: ['Emploi', 'Exemple'], rows: [['Désir', 'Je veux manger une pizza.'], ['Volonté', 'Je veux apprendre le français.']] },
        { kind: 'heading', text: 'Pouvoir', sub: true },
        { kind: 'paragraph', text: 'Pouvoir sert à exprimer une capacité,une possibilité,une autorisation ou une interdiction à la forme négative.' },
        { kind: 'table', headers: ['Emploi', 'Exemple'], rows: [['Capacité', 'Je peux nager.'], ['Possibilité', 'Nous pouvons partir maintenant.'], ['Autorisation', 'Est-ce que je peux entrer ?'], ['Interdiction', 'Vous ne pouvez pas fumer ici.']] },
        { kind: 'heading', text: 'Devoir', sub: true },
        { kind: 'paragraph', text: 'Devoir sert à exprimer une obligation,une nécessité,une interdiction à la forme négative ou une somme à payer.' },
        { kind: 'table', headers: ['Emploi', 'Exemple'], rows: [['Obligation', 'Je dois faire mes devoirs.'], ['Nécessité', 'Nous devons partir tôt.'], ['Interdiction', 'Tu ne dois pas courir.'], ['Somme à payer', 'Je vous dois 20 francs.']] },
        { kind: 'heading', text: 'Falloir', sub: true },
        { kind: 'paragraph', text: 'Il faut sert à exprimer une nécessité générale ou une interdiction à la forme négative.' },
        { kind: 'table', headers: ['Emploi', 'Exemple'], rows: [['Nécessité générale', 'Il faut un passeport pour voyager. Il faut arriver à l\'heure.'], ['Interdiction', 'Il ne faut pas parler pendant l\'examen.']] },
        { kind: 'heading', text: 'La forme affirmative' },
        { kind: 'heading', text: 'vouloir', sub: true },
        { kind: 'heading', text: 'vouloir', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'veux'], ['tu', 'veux'], ['il / elle / on', 'veut'], ['nous', 'voulons'], ['vous', 'voulez'], ['ils / elles', 'veulent']] },
        { kind: 'heading', text: 'pouvoir', sub: true },
        { kind: 'heading', text: 'pouvoir', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'peux'], ['tu', 'peux'], ['il / elle / on', 'peut'], ['nous', 'pouvons'], ['vous', 'pouvez'], ['ils / elles', 'peuvent']] },
        { kind: 'heading', text: 'devoir', sub: true },
        { kind: 'heading', text: 'devoir', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'dois'], ['tu', 'dois'], ['il / elle / on', 'doit'], ['nous', 'devons'], ['vous', 'devez'], ['ils / elles', 'doivent']] },
        { kind: 'heading', text: 'falloir', sub: true },
        { kind: 'heading', text: 'falloir', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['il', 'faut']] },
        { kind: 'heading', text: 'La forme négative' },
      ],
    },
  ],
  'fr-transports': [
    {
      id: 'fr-transports-theorie-1',
      index: 1,
      title: 'Les verbes en -er : cas général',
      sourceSlug: 'a1-gr-verbes-er',
      blocks: [
        { kind: 'paragraph', text: 'Les verbes en -er sont les verbes les plus fréquents en français. Ils font partie du 1er groupe. Le présent de l\'indicatif est utilisé pour :' },
        { kind: 'paragraph', text: '1. Parler d\'une action qui se passe au moment où l\'on parle.' },
        { kind: 'list', items: ['Vous regardez la télévision ?'] },
        { kind: 'paragraph', text: '2. Parler d\'une action habituelle.' },
        { kind: 'list', items: ['Tous les matins, je regarde mes mails.'] },
        { kind: 'paragraph', text: '3. Faire une description générale, ou exprimer des goûts et des idées.' },
        { kind: 'list', items: ['Vous habitez à Paris ?'] },
        { kind: 'heading', text: 'Comment former le verbe ?' },
        { kind: 'paragraph', text: 'En général, les verbes en -er ont une base verbale. On ajoute la terminaison e, es, e, ons, ez, ent à cette base.' },
        { kind: 'table', headers: ['Pronom', 'Verbe', 'Complément'], rows: [['Je', 'regarde', 'mes mails.'], ['Tu', 'écoutes', 'la radio.'], ['Il / Elle / On', 'habite', 'à Paris.'], ['Nous', 'parlons', 'français.'], ['Vous', 'aimez', 'le football.'], ['Ils / Elles', 'étudient', 'les relations internationales.']] },
        { kind: 'paragraph', text: 'On prend le verbe et on enlève -er.' },
        { kind: 'heading', text: 'parler', sub: true },
        { kind: 'heading', text: 'parler', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'parle'], ['tu', 'parles'], ['il / elle / on', 'parle'], ['nous', 'parlons'], ['vous', 'parlez'], ['ils / elles', 'parlent']] },
        { kind: 'heading', text: 'aimer', sub: true },
        { kind: 'heading', text: 'aimer', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'aime'], ['tu', 'aimes'], ['il / elle / on', 'aime'], ['nous', 'aimons'], ['vous', 'aimez'], ['ils / elles', 'aiment']] },
        { kind: 'heading', text: 'écouter', sub: true },
        { kind: 'heading', text: 'écouter', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'écoute'], ['tu', 'écoutes'], ['il / elle / on', 'écoute'], ['nous', 'écoutons'], ['vous', 'écoutez'], ['ils / elles', 'écoutent']] },
        { kind: 'heading', text: 'habiter', sub: true },
        { kind: 'heading', text: 'habiter', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'habite'], ['tu', 'habites'], ['il / elle / on', 'habite'], ['nous', 'habitons'], ['vous', 'habitez'], ['ils / elles', 'habitent']] },
        { kind: 'heading', text: 'regarder', sub: true },
        { kind: 'heading', text: 'regarder', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'regarde'], ['tu', 'regardes'], ['il / elle / on', 'regarde'], ['nous', 'regardons'], ['vous', 'regardez'], ['ils / elles', 'regardent']] },
        { kind: 'heading', text: 'étudier', sub: true },
        { kind: 'heading', text: 'étudier', sub: true },
      ],
    },
  ],
  'fr-inviter': [
    {
      id: 'fr-inviter-theorie-1',
      index: 1,
      title: 'Les questions fermées',
      sourceSlug: 'a1-gr-question-totale',
      blocks: [
        { kind: 'paragraph', text: 'La question fermée demande simplement de répondre par oui ou non.' },
        { kind: 'heading', text: 'Comment répondre à la question' },
        { kind: 'paragraph', text: 'Pour répondre à une question fermée, on peut dire oui, non, si pour contredire une question négative' },
        { kind: 'table', headers: ['Réponse', 'Quand l\'utiliser', 'Exemple'], rows: [['Oui', 'Réponse affirmative', 'Tu aimes le café ? — Oui, j\'aime le café.'], ['Non', 'Réponse négative', 'Tu aimes le café ? — Non, je n\'aime pas le café.']] },
        { kind: 'heading', text: 'Attention', sub: true },
        { kind: 'paragraph', text: 'Si s’utilise pour donner une réponse affirmative à une question négative, afin de contredire la négation.' },
        { kind: 'table', headers: ['Question', 'Affirmative', 'Négative'], rows: [['Tu ne viens pas ?', 'Si, je viens !', 'Non, je ne viens pas.'], ['Lisa ne parle pas francais ?', 'Si, elle parle français !', 'Non, elle ne parle pas français.']] },
        { kind: 'heading', text: 'Les réponses en écho avec « moi »' },
        { kind: 'paragraph', text: 'On utilise Moi aussi, Moi non plus, Moi si ou Moi pas pour dire rapidement si on est pareil ou différent.' },
        { kind: 'table', headers: ['Ce qu\'il dit', 'Tu es d\'accord', 'Tu n\'es pas d\'accord'], rows: [['J\'aime le café. Affirmation positive', 'Moi aussi !', 'Moi pas.'], ['Je ne fume pas. Affirmation négative', 'Moi non plus !', 'Moi si !']] },
      ],
    },
  ],
  'fr-travail': [
    {
      id: 'fr-travail-theorie-1',
      index: 1,
      title: 'Le genre des adjectifs',
      sourceSlug: 'a1-gr-genre-adjectifs',
      blocks: [
        { kind: 'heading', text: 'Les adjectifs' },
        { kind: 'paragraph', text: 'L\'adjectif donne une information sur le nom. Les adjectifs changent aussi selon le genre.' },
        { kind: 'paragraph', text: 'On ajoute souvent -e au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Le sac est petit.', 'La voiture est petite.'], ['Un homme français parle.', 'Une femme française parle.']] },
        { kind: 'paragraph', text: 'Si l\'adjectif masculin se termine déjà par e, le féminin ne change pas.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Ce lit est moderne.', 'Cette chaise est moderne.'], ['Ce garçon est calme.', 'Cette fille est calme.']] },
        { kind: 'heading', text: 'Cas particuliers' },
        { kind: 'paragraph', text: 'Certains adjectifs ont des terminaisons différentes au masculin et au féminin.' },
        { kind: 'heading', text: '-en', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -en au masculin changent en -enne au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Le meuble est ancien.', 'La table est ancienne.'], ['Le train est européen.', 'La voiture est européenne.'], ['Le prix est moyen.', 'La taille est moyenne.']] },
        { kind: 'heading', text: '-on', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -on au masculin changent en -onne au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Le café est bon.', 'La tarte est bonne.'], ['Le chat est mignon.', 'La robe est mignonne.'], ['Il est breton.', 'Elle est bretonne.']] },
        { kind: 'heading', text: '-el', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -el au masculin changent en -elle au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Le parfum est naturel.', 'La fleur est naturelle.'], ['Le choix est personnel.', 'La lettre est personnelle.'], ['Le ton est formel.', 'La tenue est formelle.']] },
        { kind: 'heading', text: '-er', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -er au masculin changent en -ère au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Il est étranger.', 'Elle est étrangère.'], ['Le sac est cher.', 'La robe est chère.'], ['C\'est le premier jour.', 'C\'est la première fois.']] },
        { kind: 'heading', text: '-et', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -et au masculin changent en -ète ou -ette au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['L\'hôtel est complet.', 'La salle est complète.'], ['Le pull est violet.', 'La robe est violette.'], ['Le plan est secret.', 'La porte est secrète.']] },
        { kind: 'heading', text: '-eux', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -eux au masculin changent en -euse au féminin.' },
        { kind: 'table', headers: ['Masculin', 'Féminin'], rows: [['Il est heureux.', 'Elle est heureuse.'], ['Il est sérieux.', 'Elle est sérieuse.'], ['Il est joyeux.', 'Elle est joyeuse.']] },
        { kind: 'heading', text: '-eur', sub: true },
        { kind: 'paragraph', text: 'Les mots terminant par -eur au masculin changent en -euse au féminin.' },
      ],
    },
  ],
  'fr-journee': [
    {
      id: 'fr-journee-theorie-1',
      index: 1,
      title: 'Les verbes pronominaux',
      sourceSlug: 'a1-gr-pronominaux',
      blocks: [
        { kind: 'paragraph', text: 'Le sujet du verbe fait l\'action sur lui-même. Un verbe pronominal est toujours accompagné d\'un pronom réfléchi.' },
        { kind: 'list', items: ['Elle se regarde dans le miroir.'] },
        { kind: 'heading', text: 'Conjugaison' },
        { kind: 'paragraph', text: 'Les verbes pronominaux se conjuguent avec deux pronoms : le pronom sujet + un pronom réfléchi de la même personne. À l\'infinitif, on utilise le pronom se : se lever, se doucher.' },
        { kind: 'table', headers: ['Sujet', 'Pronom réfléchi'], rows: [['je', 'me (m\')'], ['tu', 'te (t\')'], ['il / elle / on', 'se (s\')'], ['nous', 'nous'], ['vous', 'vous'], ['ils / elles', 'se (s\')']] },
        { kind: 'heading', text: 'Prononciation et orthographe' },
        { kind: 'paragraph', text: 'Les pronoms me, te, se deviennent m\', t\', s\' devant une voyelle ou un h muet.' },
        { kind: 'list', items: ['Je {s}me{/s} habille → Je m\'habille.', 'Tu {s}te{/s} amuses → Tu t\'amuses.', 'Elle {s}se{/s} arrête → Elle s\'arrête.', 'Ils {s}se{/s} embrassent → Ils s\'embrassent.'] },
        { kind: 'heading', text: 'Verbes pronominaux courants' },
        { kind: 'heading', text: 'se lever', sub: true },
        { kind: 'heading', text: 'se lever', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'me lève'], ['tu', 'te lèves'], ['il / elle / on', 'se lève'], ['nous', 'nous levons'], ['vous', 'vous levez'], ['ils / elles', 'se lèvent']] },
        { kind: 'heading', text: 'se coucher', sub: true },
        { kind: 'heading', text: 'se coucher', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'me couche'], ['tu', 'te couches'], ['il / elle / on', 'se couche'], ['nous', 'nous couchons'], ['vous', 'vous couchez'], ['ils / elles', 'se couchent']] },
        { kind: 'heading', text: 'se laver', sub: true },
        { kind: 'heading', text: 'se laver', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'me lave'], ['tu', 'te laves'], ['il / elle / on', 'se lave'], ['nous', 'nous lavons'], ['vous', 'vous lavez'], ['ils / elles', 'se lavent']] },
        { kind: 'heading', text: 'se doucher', sub: true },
        { kind: 'heading', text: 'se doucher', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'me douche'], ['tu', 'te douches'], ['il / elle / on', 'se douche'], ['nous', 'nous douchons'], ['vous', 'vous douchez'], ['ils / elles', 'se douchent']] },
        { kind: 'heading', text: 'se brosser', sub: true },
        { kind: 'heading', text: 'se brosser', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'me brosse'], ['tu', 'te brosses'], ['il / elle / on', 'se brosse'], ['nous', 'nous brossons'], ['vous', 'vous brossez'], ['ils / elles', 'se brossent']] },
        { kind: 'heading', text: 'se raser', sub: true },
        { kind: 'heading', text: 'se raser', sub: true },
        { kind: 'table', headers: ['Pronom', 'Forme'], rows: [['je', 'me rase'], ['tu', 'te rases'], ['il / elle / on', 'se rase'], ['nous', 'nous rasons'], ['vous', 'vous rasez'], ['ils / elles', 'se rasent']] },
        { kind: 'heading', text: 'se coiffer', sub: true },
      ],
    },
  ],
  'fr-loisirs': [
    {
      id: 'fr-loisirs-theorie-1',
      index: 1,
      title: 'Les pronoms COD et COI',
      sourceSlug: 'a1-gr-pronoms-cod-coi',
      blocks: [
        { kind: 'heading', text: 'Utilisation' },
        { kind: 'list', items: ['Les pronoms compléments évitent de répéter un nom complément (personne ou chose).', 'Le choix dépend de la construction du verbe. → Je préviens madame Dupuy → Je la préviens. ; Je téléphone à madame Dupuy → Je lui téléphone.'] },
        { kind: 'heading', text: 'Place et structure' },
        { kind: 'list', items: ['Devant le verbe ou l\'auxiliaire. → Oui, je l\'ai. ; Elle m\'a téléphoné.', 'Avec deux verbes : devant l\'infinitif. → Le directeur va nous recevoir et nous expliquer le problème.'] },
        { kind: 'note', text: 'Négation : Je ne les ai pas. ; Elle ne m\'a pas téléphoné. ; Il ne va pas nous recevoir.' },
        { kind: 'heading', text: 'Pronoms compléments directs (COD)' },
        { kind: 'paragraph', text: 'Avec un verbe sans préposition (aimer, connaître, voir…).' },
        { kind: 'table', headers: ['', 'Exemple'], rows: [['personnes', 'Il me regarde. ; Je te préviens. ; Nous le/la connaissons. ; Il nous invite. ; Je vous remercie. ; On les attend.'], ['choses', 'Le rapport, je le termine. ; L\'information, je la communique. ; Les documents, je les ai.']] },
        { kind: 'note', text: 'Avec aimer / détester + chose → ça (pas le/la/les). → Tu aimes le ski ? — Oui, j\'aime ça.' },
        { kind: 'heading', text: 'Pronoms compléments indirects (COI)' },
        { kind: 'list', items: ['Remplacent seulement des personnes ; verbes avec à (parler à, téléphoner à…). → Je lui ai téléphoné.', 'Il me parle. ; Je te parle. ; Il lui parle. ; Ils nous parlent. ; On vous parle. ; Je leur parle.', 'Lui = une personne (ms ou fs). → Je parle à mon frère / à ma sœur → Je lui parle.', 'Leur = des personnes (mp ou fp). → Je réponds à mes amis / à mes amies → Je leur réponds.'] },
        { kind: 'note', text: 'Certains verbes avec à gardent à + pronom tonique. → Il pense à ses amis → Il pense à eux. (voir unité 56)' },
        { kind: 'heading', text: 'Prononciation et orthographe' },
        { kind: 'list', items: ['Liaison / enchaînement avec les, nous, vous, leur devant voyelle ou h muet. → Je les imprime. ; Elle nous attend.', 'me, te, le, la → m\', t\', l\' devant voyelle ou h muet. → Il m\'a téléphoné. ; Je l\'imprime.'] },
        { kind: 'heading', text: 'Les pronoms COD et COI' },
        { kind: 'paragraph', text: 'Les pronoms personnels remplacent un nom déjà mentionné pour éviter les répétitions.' },
        { kind: 'list', items: ['COD = Complément d\'Objet Direct (sans préposition).', 'COI = Complément d\'Objet Indirect (avec la préposition à).'] },
        { kind: 'table', headers: ['Personne', 'COD', 'COI'], rows: [['1re sing.', 'me / m\'', 'me / m\''], ['2e sing.', 'te / t\'', 'te / t\''], ['3e sing. masc.', 'le / l\'', 'lui'], ['3e sing. fém.', 'la / l\'', 'lui'], ['1re plur.', 'nous', 'nous'], ['2e plur.', 'vous', 'vous'], ['3e plur.', 'les', 'leur']] },
        { kind: 'heading', text: 'Comment identifier COD vs COI ?', sub: true },
        { kind: 'table', headers: ['Question à poser', 'Réponse = …', 'Pronom'], rows: [['Je vois qui / quoi ?', 'COD (sans à)', 'le, la, les, me, te…'], ['Je parle à qui ?', 'COI (avec à)', 'lui, leur, me, te…']] },
        { kind: 'table', headers: ['Phrase originale', '→ Avec pronom'], rows: [['J\'appelle Marco.', 'Je le appelle. → Je l\'appelle. (COD)'], ['Je parle à Marco.', 'Je lui parle. (COI)'], ['Je regarde le film.', 'Je le regarde. (COD)'], ['J\'écris à mes amis.', 'Je leur écris. (COI)'], ['Il nous aide.', 'Il nous aide. (COD)'], ['Elle te téléphone.', 'Elle te téléphone. (COI)']] },
        { kind: 'heading', text: 'Place du pronom', sub: true },
        { kind: 'paragraph', text: 'Le pronom se place avant le verbe conjugué.' },
        { kind: 'list', items: ['Au passé composé : avant l\'auxiliaire.', 'Avec infinitif : avant l\'infinitif.'] },
        { kind: 'table', headers: ['Temps', 'Exemple'], rows: [['Présent', 'Je le vois.'], ['Passé composé', 'Je l\'ai vu.'], ['Futur proche', 'Je vais le voir.'], ['Négatif', 'Je ne le vois pas.'], ['Impératif affirmatif', 'Vois-le ! (pronom après)'], ['Impératif négatif', 'Ne le vois pas !']] },
      ],
    },
  ],
}

export function theoriesForTopic(topic: string): GrammarTheoryDoc[] {
  return GRAMMAR_THEORY_BY_TOPIC[topic] ?? []
}

export function theoryByTypeId(typeId: string): GrammarTheoryDoc | null {
  const match = /^(fr-[a-z]+)-gram-theorie-(\d+)$/.exec(typeId)
  if (!match) return null
  const topic = match[1]!
  const index = Number(match[2])
  return theoriesForTopic(topic).find((doc) => doc.index === index) ?? null
}
