import type { PhraseCategory } from '@/math/types'

/** Couleurs Gattegno — grammaire en couleur (imprimables, contrastées). */
export const PHRASE_COLORS: Record<PhraseCategory, string> = {
  pronom: '#8b5a2b',
  verbe: '#e67e22',
  nom: '#2e8b57',
  determinant: '#d4a017',
  adjectif: '#9b4dca',
  adverbe: '#3d9bc9',
  preposition: '#c0392b',
  conjonction: '#1a1a1a',
  negation: '#1a1a1a',
  interjection: '#7a7a7a',
}

export const PHRASE_CATEGORY_LABELS: Record<PhraseCategory, string> = {
  pronom: 'Pronoms',
  verbe: 'Verbes',
  nom: 'Noms',
  determinant: 'Déterminants',
  adjectif: 'Adjectifs',
  adverbe: 'Adverbes',
  preposition: 'Prépositions',
  conjonction: 'Conjonctions',
  negation: 'Négation',
  interjection: 'Interjections',
}

/** Exemples affichés dans le tableau « mots » (extraits des banques). */
export const CHART_WORD_SAMPLES: Record<PhraseCategory, string> = {
  pronom:
    'je, tu, il, elle, on, nous, vous, ils, elles, me, te, se, le, la, les, lui, leur, y, en, moi, toi, soi, qui, que, où, dont…',
  verbe: 'être, avoir, aller, faire, prendre, venir, dire, voir, lire, écrire, manger, boire…',
  nom: 'chat, chien, maison, école, livre, fille, garçon, voiture, arbre, montagne…',
  determinant:
    'le, la, l’, les, un, une, des, du, de la, ce, cet, cette, ces, mon, ma, mes, ton, ta, tes, son, sa, ses, notre, nos, votre, vos, leur, leurs, quel, quelle, quelques, plusieurs, chaque, tout, toute…',
  adjectif:
    'grand, petit, beau, belle, joli, long, court, haut, bas, jeune, vieux, nouveau, vieux, bon, mauvais, chaud, froid, rapide, lent, heureux, triste, rouge, bleu, vert, noir, blanc, intelligent, sympa…',
  adverbe:
    'très, trop, assez, peu, bien, mal, vite, lentement, souvent, toujours, jamais, parfois, ici, là, ailleurs, aujourd’hui, demain, hier, maintenant, bientôt, déjà, encore, aussi, peut-être, vraiment…',
  preposition:
    'à, de, en, dans, sur, sous, chez, avec, sans, pour, par, entre, parmi, devant, derrière, avant, après, depuis, pendant, vers, jusqu’à, contre, selon, malgré, près de, loin de…',
  conjonction: 'et, ou, mais, donc, or, ni, car…',
  negation: 'ne, n’, pas, plus, jamais, rien, personne, aucun, aucune, nulle part, guère, que…',
  interjection: 'ah, oh, hé, eh, ouf, aïe, bravo, chut, stop, allez, tiens, mince, zut, hourra…',
}

/** Conjonctions de coordination (case gauche du tableau). */
export const CHART_CONJ_COORD =
  'et, ou, mais, donc, or, ni, car, puis, cependant, pourtant…'

/** Conjonctions de subordination (case droite du tableau). */
export const CHART_CONJ_SUB =
  'quand, lorsque, si, comme, parce que, puisque, bien que, afin que, pour que, tandis que…'

/** Pronoms sujets (génération de phrases). */
export const PRONOMS = [
  'je',
  'tu',
  'il',
  'elle',
  'on',
  'nous',
  'vous',
  'ils',
  'elles',
] as const

/** Pronoms objets / toniques / relatifs (référence tableau & enrichissement). */
export const PRONOMS_COMPLETS = [
  'je',
  'tu',
  'il',
  'elle',
  'on',
  'nous',
  'vous',
  'ils',
  'elles',
  'me',
  'te',
  'se',
  'le',
  'la',
  'les',
  'lui',
  'leur',
  'y',
  'en',
  'moi',
  'toi',
  'soi',
  'eux',
  'elles',
  'qui',
  'que',
  'quoi',
  'où',
  'dont',
  'lequel',
  'laquelle',
  'lesquels',
  'lesquelles',
  'celui',
  'celle',
  'ceux',
  'celles',
  'ceci',
  'cela',
  'ça',
] as const

export const NOMS_PROPRES = [
  'Fanny',
  'Thomas',
  'Sophie',
  'Déborah',
  'Iryna',
  'Hugo',
  'Léa',
  'Noah',
  'Maya',
  'Sami',
  'Amira',
  'Lucas',
  'Nina',
  'Omar',
  'Clara',
  'Adam',
  'Inès',
  'Yanis',
  'Lina',
  'Rayan',
] as const

export const DETERMINANTS = {
  m_sing: [
    'le',
    'un',
    'mon',
    'ton',
    'son',
    'notre',
    'votre',
    'leur',
    'ce',
    'cet',
    'quel',
    'chaque',
    'tout',
    'aucun',
  ],
  f_sing: [
    'la',
    'une',
    'ma',
    'ta',
    'sa',
    'notre',
    'votre',
    'leur',
    'cette',
    'quelle',
    'chaque',
    'toute',
    'aucune',
  ],
  plur: [
    'les',
    'des',
    'mes',
    'tes',
    'ses',
    'nos',
    'vos',
    'leurs',
    'ces',
    'quels',
    'quelles',
    'quelques',
    'plusieurs',
    'tous',
    'toutes',
    'certains',
    'certaines',
    'beaucoup de',
  ],
} as const

export const DETERMINANTS_TOUS = [
  'le',
  'la',
  'l’',
  'les',
  'un',
  'une',
  'des',
  'du',
  'de la',
  'de l’',
  'ce',
  'cet',
  'cette',
  'ces',
  'mon',
  'ma',
  'mes',
  'ton',
  'ta',
  'tes',
  'son',
  'sa',
  'ses',
  'notre',
  'nos',
  'votre',
  'vos',
  'leur',
  'leurs',
  'quel',
  'quelle',
  'quels',
  'quelles',
  'chaque',
  'tout',
  'toute',
  'tous',
  'toutes',
  'quelques',
  'plusieurs',
  'certains',
  'certaines',
  'aucun',
  'aucune',
  'beaucoup de',
  'peu de',
  'assez de',
  'trop de',
] as const

export type NounEntry = { text: string; gender: 'm' | 'f'; number: 'sing' | 'plur' }

/** Noms : liste pédagogique limitée (pas exhaustive). */
export const NOMS: NounEntry[] = [
  { text: 'chat', gender: 'm', number: 'sing' },
  { text: 'chien', gender: 'm', number: 'sing' },
  { text: 'garçon', gender: 'm', number: 'sing' },
  { text: 'livre', gender: 'm', number: 'sing' },
  { text: 'crayon', gender: 'm', number: 'sing' },
  { text: 'train', gender: 'm', number: 'sing' },
  { text: 'poisson', gender: 'm', number: 'sing' },
  { text: 'chapeau', gender: 'm', number: 'sing' },
  { text: 'ballon', gender: 'm', number: 'sing' },
  { text: 'sac', gender: 'm', number: 'sing' },
  { text: 'fille', gender: 'f', number: 'sing' },
  { text: 'maison', gender: 'f', number: 'sing' },
  { text: 'école', gender: 'f', number: 'sing' },
  { text: 'voiture', gender: 'f', number: 'sing' },
  { text: 'chemise', gender: 'f', number: 'sing' },
  { text: 'pomme', gender: 'f', number: 'sing' },
  { text: 'fleur', gender: 'f', number: 'sing' },
  { text: 'table', gender: 'f', number: 'sing' },
  { text: 'fenêtre', gender: 'f', number: 'sing' },
  { text: 'télé', gender: 'f', number: 'sing' },
  { text: 'chats', gender: 'm', number: 'plur' },
  { text: 'livres', gender: 'm', number: 'plur' },
  { text: 'pommes', gender: 'f', number: 'plur' },
  { text: 'fleurs', gender: 'f', number: 'plur' },
]

export type AdjEntry = { m: string; f: string }

export const ADJECTIFS: AdjEntry[] = [
  { m: 'grand', f: 'grande' },
  { m: 'petit', f: 'petite' },
  { m: 'beau', f: 'belle' },
  { m: 'joli', f: 'jolie' },
  { m: 'long', f: 'longue' },
  { m: 'court', f: 'courte' },
  { m: 'haut', f: 'haute' },
  { m: 'bas', f: 'basse' },
  { m: 'jeune', f: 'jeune' },
  { m: 'vieux', f: 'vieille' },
  { m: 'nouveau', f: 'nouvelle' },
  { m: 'bon', f: 'bonne' },
  { m: 'mauvais', f: 'mauvaise' },
  { m: 'chaud', f: 'chaude' },
  { m: 'froid', f: 'froide' },
  { m: 'rapide', f: 'rapide' },
  { m: 'lent', f: 'lente' },
  { m: 'heureux', f: 'heureuse' },
  { m: 'triste', f: 'triste' },
  { m: 'content', f: 'contente' },
  { m: 'fatigué', f: 'fatiguée' },
  { m: 'calme', f: 'calme' },
  { m: 'bruyant', f: 'bruyante' },
  { m: 'propre', f: 'propre' },
  { m: 'sale', f: 'sale' },
  { m: 'plein', f: 'pleine' },
  { m: 'vide', f: 'vide' },
  { m: 'ouvert', f: 'ouverte' },
  { m: 'fermé', f: 'fermée' },
  { m: 'facile', f: 'facile' },
  { m: 'difficile', f: 'difficile' },
  { m: 'important', f: 'importante' },
  { m: 'intéressant', f: 'intéressante' },
  { m: 'intelligent', f: 'intelligente' },
  { m: 'sympa', f: 'sympa' },
  { m: 'gentil', f: 'gentille' },
  { m: 'méchant', f: 'méchante' },
  { m: 'fort', f: 'forte' },
  { m: 'faible', f: 'faible' },
  { m: 'lourd', f: 'lourde' },
  { m: 'léger', f: 'légère' },
  { m: 'rond', f: 'ronde' },
  { m: 'carré', f: 'carrée' },
  { m: 'rouge', f: 'rouge' },
  { m: 'bleu', f: 'bleue' },
  { m: 'vert', f: 'verte' },
  { m: 'jaune', f: 'jaune' },
  { m: 'noir', f: 'noire' },
  { m: 'blanc', f: 'blanche' },
  { m: 'gris', f: 'grise' },
  { m: 'rose', f: 'rose' },
  { m: 'orange', f: 'orange' },
  { m: 'marron', f: 'marron' },
  { m: 'violet', f: 'violette' },
  { m: 'clair', f: 'claire' },
  { m: 'sombre', f: 'sombre' },
  { m: 'doux', f: 'douce' },
  { m: 'dur', f: 'dure' },
  { m: 'sec', f: 'sèche' },
  { m: 'mouillé', f: 'mouillée' },
  { m: 'premier', f: 'première' },
  { m: 'dernier', f: 'dernière' },
  { m: 'autre', f: 'autre' },
  { m: 'même', f: 'même' },
  { m: 'seul', f: 'seule' },
  { m: 'entier', f: 'entière' },
]

/** Verbes : liste pédagogique limitée (pas exhaustive). */
export const VERBES_ER = [
  { infinitive: 'manger', forms: { je: 'mange', tu: 'manges', il: 'mange', nous: 'mangeons', vous: 'mangez', ils: 'mangent' } },
  { infinitive: 'porter', forms: { je: 'porte', tu: 'portes', il: 'porte', nous: 'portons', vous: 'portez', ils: 'portent' } },
  { infinitive: 'regarder', forms: { je: 'regarde', tu: 'regardes', il: 'regarde', nous: 'regardons', vous: 'regardez', ils: 'regardent' } },
  { infinitive: 'acheter', forms: { je: 'achète', tu: 'achètes', il: 'achète', nous: 'achetons', vous: 'achetez', ils: 'achètent' } },
  { infinitive: 'aimer', forms: { je: 'aime', tu: 'aimes', il: 'aime', nous: 'aimons', vous: 'aimez', ils: 'aiment' } },
  { infinitive: 'trouver', forms: { je: 'trouve', tu: 'trouves', il: 'trouve', nous: 'trouvons', vous: 'trouvez', ils: 'trouvent' } },
  { infinitive: 'dessiner', forms: { je: 'dessine', tu: 'dessines', il: 'dessine', nous: 'dessinons', vous: 'dessinez', ils: 'dessinent' } },
  { infinitive: 'lancer', forms: { je: 'lance', tu: 'lances', il: 'lance', nous: 'lançons', vous: 'lancez', ils: 'lancent' } },
  { infinitive: 'chercher', forms: { je: 'cherche', tu: 'cherches', il: 'cherche', nous: 'cherchons', vous: 'cherchez', ils: 'cherchent' } },
  { infinitive: 'habiter', forms: { je: 'habite', tu: 'habites', il: 'habite', nous: 'habitons', vous: 'habitez', ils: 'habitent' } },
  { infinitive: 'écouter', forms: { je: 'écoute', tu: 'écoutes', il: 'écoute', nous: 'écoutons', vous: 'écoutez', ils: 'écoutent' } },
  { infinitive: 'être', forms: { je: 'suis', tu: 'es', il: 'est', nous: 'sommes', vous: 'êtes', ils: 'sont' } },
  { infinitive: 'avoir', forms: { je: 'ai', tu: 'as', il: 'a', nous: 'avons', vous: 'avez', ils: 'ont' } },
] as const

export const VERBES_AUTRES = [
  { infinitive: 'prendre', forms: { je: 'prends', tu: 'prends', il: 'prend', nous: 'prenons', vous: 'prenez', ils: 'prennent' } },
  { infinitive: 'lire', forms: { je: 'lis', tu: 'lis', il: 'lit', nous: 'lisons', vous: 'lisez', ils: 'lisent' } },
  { infinitive: 'voir', forms: { je: 'vois', tu: 'vois', il: 'voit', nous: 'voyons', vous: 'voyez', ils: 'voient' } },
  { infinitive: 'ouvrir', forms: { je: 'ouvre', tu: 'ouvres', il: 'ouvre', nous: 'ouvrons', vous: 'ouvrez', ils: 'ouvrent' } },
  { infinitive: 'écrire', forms: { je: 'écris', tu: 'écris', il: 'écrit', nous: 'écrivons', vous: 'écrivez', ils: 'écrivent' } },
  { infinitive: 'boire', forms: { je: 'bois', tu: 'bois', il: 'boit', nous: 'buvons', vous: 'buvez', ils: 'boivent' } },
  { infinitive: 'finir', forms: { je: 'finis', tu: 'finis', il: 'finit', nous: 'finissons', vous: 'finissez', ils: 'finissent' } },
  { infinitive: 'choisir', forms: { je: 'choisis', tu: 'choisis', il: 'choisit', nous: 'choisissons', vous: 'choisissez', ils: 'choisissent' } },
  { infinitive: 'faire', forms: { je: 'fais', tu: 'fais', il: 'fait', nous: 'faisons', vous: 'faites', ils: 'font' } },
  { infinitive: 'mettre', forms: { je: 'mets', tu: 'mets', il: 'met', nous: 'mettons', vous: 'mettez', ils: 'mettent' } },
  { infinitive: 'aller', forms: { je: 'vais', tu: 'vas', il: 'va', nous: 'allons', vous: 'allez', ils: 'vont' } },
  { infinitive: 'venir', forms: { je: 'viens', tu: 'viens', il: 'vient', nous: 'venons', vous: 'venez', ils: 'viennent' } },
  { infinitive: 'apprendre', forms: { je: 'apprends', tu: 'apprends', il: 'apprend', nous: 'apprenons', vous: 'apprenez', ils: 'apprennent' } },
  { infinitive: 'comprendre', forms: { je: 'comprends', tu: 'comprends', il: 'comprend', nous: 'comprenons', vous: 'comprenez', ils: 'comprennent' } },
  { infinitive: 'descendre', forms: { je: 'descends', tu: 'descends', il: 'descend', nous: 'descendons', vous: 'descendez', ils: 'descendent' } },
  { infinitive: 'attendre', forms: { je: 'attends', tu: 'attends', il: 'attend', nous: 'attendons', vous: 'attendez', ils: 'attendent' } },
  { infinitive: 'vendre', forms: { je: 'vends', tu: 'vends', il: 'vend', nous: 'vendons', vous: 'vendez', ils: 'vendent' } },
  { infinitive: 'perdre', forms: { je: 'perds', tu: 'perds', il: 'perd', nous: 'perdons', vous: 'perdez', ils: 'perdent' } },
  { infinitive: 'dire', forms: { je: 'dis', tu: 'dis', il: 'dit', nous: 'disons', vous: 'dites', ils: 'disent' } },
  { infinitive: 'suivre', forms: { je: 'suis', tu: 'suis', il: 'suit', nous: 'suivons', vous: 'suivez', ils: 'suivent' } },
  { infinitive: 'vivre', forms: { je: 'vis', tu: 'vis', il: 'vit', nous: 'vivons', vous: 'vivez', ils: 'vivent' } },
  { infinitive: 'conduire', forms: { je: 'conduis', tu: 'conduis', il: 'conduit', nous: 'conduisons', vous: 'conduisez', ils: 'conduisent' } },
  { infinitive: 'construire', forms: { je: 'construis', tu: 'construis', il: 'construit', nous: 'construisons', vous: 'construisez', ils: 'construisent' } },
  { infinitive: 'peindre', forms: { je: 'peins', tu: 'peins', il: 'peint', nous: 'peignons', vous: 'peignez', ils: 'peignent' } },
  { infinitive: 'cueillir', forms: { je: 'cueille', tu: 'cueilles', il: 'cueille', nous: 'cueillons', vous: 'cueillez', ils: 'cueillent' } },
  { infinitive: 'offrir', forms: { je: 'offre', tu: 'offres', il: 'offre', nous: 'offrons', vous: 'offrez', ils: 'offrent' } },
  { infinitive: 'couvrir', forms: { je: 'couvre', tu: 'couvres', il: 'couvre', nous: 'couvrons', vous: 'couvrez', ils: 'couvrent' } },
  { infinitive: 'découvrir', forms: { je: 'découvre', tu: 'découvres', il: 'découvre', nous: 'découvrons', vous: 'découvrez', ils: 'découvrent' } },
  { infinitive: 'tenir', forms: { je: 'tiens', tu: 'tiens', il: 'tient', nous: 'tenons', vous: 'tenez', ils: 'tiennent' } },
  { infinitive: 'sentir', forms: { je: 'sens', tu: 'sens', il: 'sent', nous: 'sentons', vous: 'sentez', ils: 'sentent' } },
  { infinitive: 'servir', forms: { je: 'sers', tu: 'sers', il: 'sert', nous: 'servons', vous: 'servez', ils: 'servent' } },
  { infinitive: 'connaître', forms: { je: 'connais', tu: 'connais', il: 'connaît', nous: 'connaissons', vous: 'connaissez', ils: 'connaissent' } },
  { infinitive: 'savoir', forms: { je: 'sais', tu: 'sais', il: 'sait', nous: 'savons', vous: 'savez', ils: 'savent' } },
  { infinitive: 'vouloir', forms: { je: 'veux', tu: 'veux', il: 'veut', nous: 'voulons', vous: 'voulez', ils: 'veulent' } },
  { infinitive: 'recevoir', forms: { je: 'reçois', tu: 'reçois', il: 'reçoit', nous: 'recevons', vous: 'recevez', ils: 'reçoivent' } },
  { infinitive: 'battre', forms: { je: 'bats', tu: 'bats', il: 'bat', nous: 'battons', vous: 'battez', ils: 'battent' } },
  { infinitive: 'éteindre', forms: { je: 'éteins', tu: 'éteins', il: 'éteint', nous: 'éteignons', vous: 'éteignez', ils: 'éteignent' } },
  { infinitive: 'traduire', forms: { je: 'traduis', tu: 'traduis', il: 'traduit', nous: 'traduisons', vous: 'traduisez', ils: 'traduisent' } },
  { infinitive: 'coudre', forms: { je: 'couds', tu: 'couds', il: 'coud', nous: 'cousons', vous: 'cousez', ils: 'cousent' } },
  { infinitive: 'joindre', forms: { je: 'joins', tu: 'joins', il: 'joint', nous: 'joignons', vous: 'joignez', ils: 'joignent' } },
  { infinitive: 'atteindre', forms: { je: 'atteins', tu: 'atteins', il: 'atteint', nous: 'atteignons', vous: 'atteignez', ils: 'atteignent' } },
  { infinitive: 'résoudre', forms: { je: 'résous', tu: 'résous', il: 'résout', nous: 'résolvons', vous: 'résolvez', ils: 'résolvent' } },
] as const

export type VerbEntry = {
  infinitive: string
  forms: { je: string; tu: string; il: string; nous: string; vous: string; ils: string }
}

export const VERBES: readonly VerbEntry[] = [...VERBES_ER, ...VERBES_AUTRES]

export function verbesFor(group: 'er' | 'autres' = 'er'): readonly VerbEntry[] {
  return group === 'autres' ? VERBES_AUTRES : VERBES_ER
}

export const ADVERBES = [
  'très',
  'trop',
  'assez',
  'peu',
  'beaucoup',
  'bien',
  'mal',
  'mieux',
  'vite',
  'lentement',
  'doucement',
  'fort',
  'souvent',
  'toujours',
  'jamais',
  'parfois',
  'quelquefois',
  'rarement',
  'déjà',
  'encore',
  'enfin',
  'soudain',
  'maintenant',
  'aujourd’hui',
  'demain',
  'hier',
  'bientôt',
  'tard',
  'tôt',
  'ici',
  'là',
  'ailleurs',
  'partout',
  'dehors',
  'dedans',
  'loin',
  'près',
  'ensemble',
  'seul',
  'aussi',
  'également',
  'surtout',
  'seulement',
  'vraiment',
  'sûrement',
  'peut-être',
  'probablement',
  'certainement',
  'clairement',
  'facilement',
  'difficilement',
  'heureusement',
  'malheureusement',
  'simplement',
  'exactement',
  'complètement',
  'presque',
  'environ',
  'ainsi',
  'puis',
  'ensuite',
  'alors',
  'pourtant',
  'cependant',
] as const

export const PREPOSITIONS = [
  'à',
  'de',
  'en',
  'dans',
  'sur',
  'sous',
  'chez',
  'avec',
  'sans',
  'pour',
  'par',
  'entre',
  'parmi',
  'devant',
  'derrière',
  'avant',
  'après',
  'depuis',
  'pendant',
  'durant',
  'vers',
  'jusqu’à',
  'contre',
  'selon',
  'malgré',
  'sauf',
  'hormis',
  'près de',
  'loin de',
  'à côté de',
  'au-dessus de',
  'au-dessous de',
  'autour de',
  'au milieu de',
  'en face de',
  'à cause de',
  'grâce à',
  'afin de',
  'avant de',
  'jusque',
  'envers',
  'vis-à-vis de',
  'quant à',
] as const

export const CONJONCTIONS_COORD = [
  'et',
  'ou',
  'mais',
  'donc',
  'or',
  'ni',
  'car',
  'puis',
  'ensuite',
  'cependant',
  'pourtant',
  'toutefois',
  'néanmoins',
  'aussi',
  'ainsi',
] as const

export const CONJONCTIONS_SUB = [
  'quand',
  'lorsque',
  'si',
  'comme',
  'parce que',
  'puisque',
  'car',
  'bien que',
  'quoique',
  'afin que',
  'pour que',
  'de sorte que',
  'tandis que',
  'pendant que',
  'avant que',
  'après que',
  'dès que',
  'aussitôt que',
  'tant que',
  'jusqu’à ce que',
  'sans que',
  'à moins que',
  'pourvu que',
  'que',
] as const

export const NEGATIONS = [
  'ne',
  'n’',
  'pas',
  'plus',
  'jamais',
  'rien',
  'personne',
  'aucun',
  'aucune',
  'nulle part',
  'guère',
  'que',
  'ni',
  'nullement',
  'point',
] as const

export const INTERJECTIONS = [
  'ah',
  'oh',
  'hé',
  'eh',
  'ouf',
  'aïe',
  'ouille',
  'bravo',
  'chut',
  'stop',
  'allez',
  'tiens',
  'tiens donc',
  'mince',
  'zut',
  'flûte',
  'hourra',
  'ouais',
  'bah',
  'bof',
  'hein',
  'quoi',
  'attention',
  'help',
  'merci',
  'pardon',
  's’il vous plaît',
] as const

export type PhraseThemeId =
  | 'phrase-simple'
  | 'phrase-negation'
  | 'phrase-adjectif'
  | 'phrase-negation-adjectif'
  | 'phrase-determinants'
  | 'phrase-negation-determinants'
  | 'phrase-preposition'
  | 'phrase-negation-preposition'
  | 'phrase-adverbe'
  | 'phrase-negation-adverbe'
  | 'phrase-conjonctions'

/**
 * 15 consignes distinctes de production écrite par thème
 * (structure attendue de la phrase).
 */
export const PRODUCTION_PROMPTS_BY_THEME: Record<PhraseThemeId, readonly string[]> = {
  'phrase-simple': [
    'Écrivez des phrases simples (sujet + verbe + complément).',
    'Écrivez des phrases qui commencent par un pronom (je, tu, il, elle…).',
    'Écrivez des phrases avec un groupe nominal (déterminant + nom).',
    'Écrivez des phrases pour dire ce que vous faites aujourd’hui.',
    'Écrivez des phrases sur votre école.',
    'Écrivez des phrases pour décrire votre journée.',
    'Écrivez des phrases avec des animaux.',
    'Écrivez des phrases pour parler de votre famille.',
    'Écrivez des phrases sur ce que vous aimez.',
    'Écrivez des phrases sur un ami ou une amie.',
    'Écrivez des phrases sur le repas.',
    'Écrivez des phrases sur le sport.',
    'Écrivez des phrases sur les vacances.',
    'Écrivez des phrases sur un livre ou un film.',
    'Écrivez des phrases pour présenter votre chambre.',
  ],
  'phrase-negation': [
    'Écrivez des phrases négatives avec ne… pas.',
    'Écrivez des phrases négatives qui commencent par un pronom.',
    'Écrivez des phrases négatives avec un déterminant + nom comme sujet.',
    'Écrivez ce que vous ne faites pas le matin.',
    'Écrivez des phrases pour dire ce que vous n’aimez pas.',
    'Écrivez des phrases négatives sur l’école.',
    'Écrivez des phrases avec ne… jamais.',
    'Écrivez des phrases avec ne… plus.',
    'Écrivez ce que vous ne mangez pas.',
    'Écrivez des phrases négatives sur le week-end.',
    'Écrivez des phrases pour dire ce qui n’est pas vrai.',
    'Écrivez des phrases négatives sur les devoirs.',
    'Écrivez des phrases pour refuser poliment (ne… pas).',
    'Écrivez des phrases : nous / vous / ils ne… pas.',
    'Écrivez des phrases négatives sur un loisir.',
  ],
  'phrase-adjectif': [
    'Écrivez des phrases avec un adjectif pour décrire.',
    'Écrivez des phrases qui commencent par un pronom + adjectif dans le complément.',
    'Écrivez des phrases avec un déterminant + nom + adjectif.',
    'Écrivez des phrases pour décrire une personne (adjectif).',
    'Écrivez des phrases pour décrire un animal (adjectif).',
    'Écrivez des phrases pour décrire un objet (adjectif).',
    'Écrivez des phrases avec un adjectif de couleur.',
    'Écrivez des phrases avec grand / petit.',
    'Écrivez des phrases pour décrire votre maison.',
    'Écrivez des phrases pour décrire le temps (adjectif).',
    'Écrivez des phrases avec un adjectif de sentiment.',
    'Écrivez des phrases pour décrire un ami (adjectif).',
    'Écrivez des phrases avec beau / belle.',
    'Écrivez des phrases pour décrire un lieu (adjectif).',
    'Écrivez des phrases avec un adjectif avant ou après le nom.',
  ],
  'phrase-negation-determinants': [
    'Écrivez des phrases négatives avec mon, ma, tes, cette…',
    'Écrivez des phrases négatives avec un déterminant possessif.',
    'Écrivez des phrases négatives avec ce, cet, cette, ces.',
    'Écrivez ce que votre famille ne fait pas (mon, ma, notre…).',
    'Écrivez des phrases : mon / ma / mes + ne… pas.',
    'Écrivez des phrases négatives avec ton / ta / tes.',
    'Écrivez des phrases négatives avec son / sa / ses.',
    'Écrivez des phrases négatives avec leur / leurs.',
    'Écrivez des phrases pour dire ce que cet élève ne fait pas.',
    'Écrivez des phrases négatives avec notre / votre.',
    'Écrivez des phrases : cette personne ne… pas.',
    'Écrivez des phrases négatives pour parler d’un proche (déterminant).',
    'Écrivez des phrases : chaque enfant ne… pas.',
    'Écrivez des phrases négatives avec un article défini (le, la, l’).',
    'Écrivez des phrases négatives avec un article indéfini (un, une).',
  ],
  'phrase-determinants': [
    'Écrivez des phrases affirmatives avec des déterminants variés.',
    'Écrivez des phrases avec le, la, les, l’, un, une, des.',
    'Écrivez des phrases avec mon, ma, mes, ton, ta, tes.',
    'Écrivez des phrases avec son, sa, ses, notre, votre, leur.',
    'Écrivez des phrases avec ce, cet, cette, ces.',
    'Écrivez des phrases avec chaque, plusieurs, quelques.',
    'Écrivez des phrases pour parler de votre famille (mon, ma, nos…).',
    'Écrivez des phrases avec un déterminant démonstratif.',
    'Écrivez des phrases avec un déterminant possessif.',
    'Écrivez des phrases avec un article défini.',
    'Écrivez des phrases avec un article indéfini.',
    'Écrivez des phrases : cette personne + verbe + complément.',
    'Écrivez des phrases : mon frère / ma sœur + verbe.',
    'Écrivez des phrases avec leur enfant / notre maître.',
    'Écrivez des phrases : chaque élève + verbe + complément.',
  ],
  'phrase-negation-adjectif': [
    'Écrivez des phrases négatives avec un adjectif.',
    'Écrivez des phrases négatives qui commencent par un pronom.',
    'Écrivez des phrases négatives avec un déterminant + nom + adjectif.',
    'Écrivez ce qui n’est pas grand / petit (avec adjectif).',
    'Écrivez des phrases : ce n’est pas… + adjectif.',
    'Écrivez des phrases négatives pour décrire une personne.',
    'Écrivez des phrases négatives pour décrire un objet.',
    'Écrivez des phrases avec ne… pas + adjectif de couleur.',
    'Écrivez ce que vous n’êtes pas (adjectif).',
    'Écrivez des phrases négatives sur un animal (adjectif).',
    'Écrivez des phrases : ce n’est plus… + adjectif.',
    'Écrivez des phrases négatives pour corriger une description.',
    'Écrivez des phrases avec ne… jamais + adjectif.',
    'Écrivez des phrases négatives sur le temps (adjectif).',
    'Écrivez des phrases : elle / il n’est pas… + adjectif.',
  ],
  'phrase-preposition': [
    'Écrivez des phrases avec une préposition (dans, sur, sous…).',
    'Écrivez des phrases avec un pronom sujet et une préposition.',
    'Écrivez des phrases avec un déterminant + nom et une préposition.',
    'Écrivez des phrases avec dans.',
    'Écrivez des phrases avec sur / sous.',
    'Écrivez des phrases avec chez.',
    'Écrivez des phrases avec avec / sans.',
    'Écrivez des phrases avec pour.',
    'Écrivez des phrases avec devant / derrière.',
    'Écrivez des phrases avec entre.',
    'Écrivez des phrases pour situer un objet (préposition).',
    'Écrivez des phrases pour dire où vous allez (préposition).',
    'Écrivez des phrases avec près de / loin de.',
    'Écrivez des phrases avec pendant / depuis.',
    'Écrivez des phrases pour décrire un trajet (préposition).',
  ],
  'phrase-negation-preposition': [
    'Écrivez des phrases négatives avec une préposition.',
    'Écrivez des phrases négatives avec un pronom sujet et une préposition.',
    'Écrivez des phrases négatives avec un groupe nominal sujet.',
    'Écrivez des phrases : ne… pas + dans / sur / sous.',
    'Écrivez ce que vous ne faites pas chez quelqu’un.',
    'Écrivez des phrases négatives avec à / de.',
    'Écrivez des phrases : je ne vais pas à…',
    'Écrivez des phrases négatives avec avec / sans.',
    'Écrivez des phrases : il ne reste pas chez…',
    'Écrivez des phrases négatives pour situer (devant, derrière).',
    'Écrivez des phrases avec ne… pas + près de / loin de.',
    'Écrivez des phrases négatives sur le trajet (préposition).',
    'Écrivez des phrases : elle n’entre pas dans…',
    'Écrivez des phrases négatives avec après / avant.',
    'Écrivez des phrases : nous ne rentrons pas à…',
  ],
  'phrase-adverbe': [
    'Écrivez des phrases avec un adverbe (vite, bien, souvent…).',
    'Écrivez des phrases avec un pronom sujet et un adverbe.',
    'Écrivez des phrases avec un déterminant + nom et un adverbe.',
    'Écrivez des phrases avec bien / mal.',
    'Écrivez des phrases avec vite / lentement.',
    'Écrivez des phrases avec souvent / toujours.',
    'Écrivez des phrases avec aujourd’hui / demain.',
    'Écrivez des phrases avec ici / là.',
    'Écrivez des phrases avec très.',
    'Écrivez des phrases avec déjà / encore.',
    'Écrivez des phrases pour dire comment vous agissez (adverbe).',
    'Écrivez des phrases avec peut-être / vraiment.',
    'Écrivez des phrases avec hier / maintenant.',
    'Écrivez des phrases avec beaucoup / peu.',
    'Écrivez des phrases : ils / elles + verbe + adverbe.',
  ],
  'phrase-negation-adverbe': [
    'Écrivez des phrases négatives avec un adverbe.',
    'Écrivez des phrases négatives avec un pronom sujet et un adverbe.',
    'Écrivez des phrases négatives avec un groupe nominal sujet.',
    'Écrivez des phrases avec ne… pas + bien / mal.',
    'Écrivez des phrases avec ne… jamais + adverbe de temps.',
    'Écrivez ce que vous ne faites pas souvent.',
    'Écrivez des phrases : ne… pas vite / lentement.',
    'Écrivez des phrases négatives avec aujourd’hui / demain.',
    'Écrivez des phrases avec ne… plus + adverbe.',
    'Écrivez des phrases négatives avec ici / là.',
    'Écrivez des phrases : je ne… pas vraiment.',
    'Écrivez des phrases négatives pour dire comment vous n’agissez pas.',
    'Écrivez des phrases avec ne… pas encore.',
    'Écrivez des phrases négatives avec trop / assez.',
    'Écrivez des phrases : on ne… pas toujours.',
  ],
  'phrase-conjonctions': [
    'Écrivez des phrases avec et / ou / mais.',
    'Écrivez des phrases avec un pronom à gauche et un nom commun à droite.',
    'Écrivez des phrases avec deux groupes nominaux reliés par et.',
    'Écrivez des phrases avec parce que.',
    'Écrivez des phrases avec quand / si.',
    'Écrivez des phrases avec donc / car.',
    'Écrivez deux idées reliées par mais.',
    'Écrivez des phrases avec puis / ensuite.',
    'Écrivez des phrases avec bien que / même si (niveau avancé).',
    'Écrivez une cause avec parce que ou puisque.',
    'Écrivez une condition avec si.',
    'Écrivez des phrases avec ou pour proposer un choix.',
    'Écrivez des phrases complexes avec une conjonction de coordination.',
    'Écrivez des phrases complexes avec une conjonction de subordination.',
    'Écrivez une histoire courte en reliant les phrases (et, puis, donc).',
  ],
}

/** Toutes les consignes (165), utiles pour contrôles d’unicité. */
export const PRODUCTION_PROMPTS: readonly string[] = Object.values(PRODUCTION_PROMPTS_BY_THEME).flat()

for (const [theme, prompts] of Object.entries(PRODUCTION_PROMPTS_BY_THEME)) {
  if (prompts.length !== 15) {
    throw new Error(`${theme} : ${prompts.length} consignes de production (15 attendues)`)
  }
  if (new Set(prompts).size !== prompts.length) {
    throw new Error(`${theme} : consignes de production en double`)
  }
}
