/**
 * Prénoms Gattegno par nationalité (~15 chacun).
 * Aligné sur le vocabulaire « nationalités » (+ japonais pour les classes FLE).
 * Genre indiqué pour l’accord (être + adjectif, etc.).
 */

export type ProperGender = 'm' | 'f'

export type ProperEntry = { name: string; gender: ProperGender }

/** 15 prénoms par nationalité (mixte m/f). */
export const PROPER_BY_NATIONALITY: Record<string, readonly ProperEntry[]> = {
  afghan: [
    { name: 'Ahmad', gender: 'm' },
    { name: 'Omar', gender: 'm' },
    { name: 'Farid', gender: 'm' },
    { name: 'Karim', gender: 'm' },
    { name: 'Youssof', gender: 'm' },
    { name: 'Wahid', gender: 'm' },
    { name: 'Basir', gender: 'm' },
    { name: 'Najib', gender: 'm' },
    { name: 'Laila', gender: 'f' },
    { name: 'Zahra', gender: 'f' },
    { name: 'Maryam', gender: 'f' },
    { name: 'Soraya', gender: 'f' },
    { name: 'Freshta', gender: 'f' },
    { name: 'Malalai', gender: 'f' },
    { name: 'Roya', gender: 'f' },
  ],
  allemand: [
    { name: 'Hans', gender: 'm' },
    { name: 'Lukas', gender: 'm' },
    { name: 'Jonas', gender: 'm' },
    { name: 'Felix', gender: 'm' },
    { name: 'Tobias', gender: 'm' },
    { name: 'Niklas', gender: 'm' },
    { name: 'Paul', gender: 'm' },
    { name: 'Erik', gender: 'm' },
    { name: 'Greta', gender: 'f' },
    { name: 'Hannah', gender: 'f' },
    { name: 'Lena', gender: 'f' },
    { name: 'Mia', gender: 'f' },
    { name: 'Sophie', gender: 'f' },
    { name: 'Clara', gender: 'f' },
    { name: 'Emma', gender: 'f' },
  ],
  américain: [
    { name: 'James', gender: 'm' },
    { name: 'Michael', gender: 'm' },
    { name: 'David', gender: 'm' },
    { name: 'John', gender: 'm' },
    { name: 'William', gender: 'm' },
    { name: 'Daniel', gender: 'm' },
    { name: 'Christopher', gender: 'm' },
    { name: 'Anthony', gender: 'm' },
    { name: 'Emily', gender: 'f' },
    { name: 'Olivia', gender: 'f' },
    { name: 'Sophia', gender: 'f' },
    { name: 'Ava', gender: 'f' },
    { name: 'Isabella', gender: 'f' },
    { name: 'Madison', gender: 'f' },
    { name: 'Chloe', gender: 'f' },
  ],
  anglais: [
    { name: 'Oliver', gender: 'm' },
    { name: 'Harry', gender: 'm' },
    { name: 'George', gender: 'm' },
    { name: 'Jack', gender: 'm' },
    { name: 'Charlie', gender: 'm' },
    { name: 'Thomas', gender: 'm' },
    { name: 'Arthur', gender: 'm' },
    { name: 'Oscar', gender: 'm' },
    { name: 'Amelia', gender: 'f' },
    { name: 'Isla', gender: 'f' },
    { name: 'Emily', gender: 'f' },
    { name: 'Poppy', gender: 'f' },
    { name: 'Lily', gender: 'f' },
    { name: 'Freya', gender: 'f' },
    { name: 'Daisy', gender: 'f' },
  ],
  autrichien: [
    { name: 'Stefan', gender: 'm' },
    { name: 'Andreas', gender: 'm' },
    { name: 'Georg', gender: 'm' },
    { name: 'Matthias', gender: 'm' },
    { name: 'Sebastian', gender: 'm' },
    { name: 'Florian', gender: 'm' },
    { name: 'Markus', gender: 'm' },
    { name: 'Wolfgang', gender: 'm' },
    { name: 'Anna', gender: 'f' },
    { name: 'Julia', gender: 'f' },
    { name: 'Katharina', gender: 'f' },
    { name: 'Laura', gender: 'f' },
    { name: 'Theresa', gender: 'f' },
    { name: 'Elisabeth', gender: 'f' },
    { name: 'Magdalena', gender: 'f' },
  ],
  belge: [
    { name: 'Louis', gender: 'm' },
    { name: 'Arthur', gender: 'm' },
    { name: 'Noah', gender: 'm' },
    { name: 'Liam', gender: 'm' },
    { name: 'Jules', gender: 'm' },
    { name: 'Lucas', gender: 'm' },
    { name: 'Adam', gender: 'm' },
    { name: 'Victor', gender: 'm' },
    { name: 'Léa', gender: 'f' },
    { name: 'Emma', gender: 'f' },
    { name: 'Louise', gender: 'f' },
    { name: 'Alice', gender: 'f' },
    { name: 'Julie', gender: 'f' },
    { name: 'Manon', gender: 'f' },
    { name: 'Elise', gender: 'f' },
  ],
  canadien: [
    { name: 'Liam', gender: 'm' },
    { name: 'Noah', gender: 'm' },
    { name: 'Logan', gender: 'm' },
    { name: 'Jacob', gender: 'm' },
    { name: 'Ethan', gender: 'm' },
    { name: 'Benjamin', gender: 'm' },
    { name: 'Lucas', gender: 'm' },
    { name: 'Owen', gender: 'm' },
    { name: 'Olivia', gender: 'f' },
    { name: 'Emma', gender: 'f' },
    { name: 'Charlotte', gender: 'f' },
    { name: 'Ava', gender: 'f' },
    { name: 'Sophia', gender: 'f' },
    { name: 'Mia', gender: 'f' },
    { name: 'Amelia', gender: 'f' },
  ],
  chinois: [
    { name: 'Wei', gender: 'm' },
    { name: 'Ming', gender: 'm' },
    { name: 'Chen', gender: 'm' },
    { name: 'Jun', gender: 'm' },
    { name: 'Hao', gender: 'm' },
    { name: 'Lei', gender: 'm' },
    { name: 'Tao', gender: 'm' },
    { name: 'Yong', gender: 'm' },
    { name: 'Mei', gender: 'f' },
    { name: 'Ling', gender: 'f' },
    { name: 'Fang', gender: 'f' },
    { name: 'Xia', gender: 'f' },
    { name: 'Yan', gender: 'f' },
    { name: 'Jing', gender: 'f' },
    { name: 'Hua', gender: 'f' },
  ],
  erythreen: [
    { name: 'Yonas', gender: 'm' },
    { name: 'Amanuel', gender: 'm' },
    { name: 'Bereket', gender: 'm' },
    { name: 'Dawit', gender: 'm' },
    { name: 'Filmon', gender: 'm' },
    { name: 'Henok', gender: 'm' },
    { name: 'Kidane', gender: 'm' },
    { name: 'Meron', gender: 'm' },
    { name: 'Hanna', gender: 'f' },
    { name: 'Rahel', gender: 'f' },
    { name: 'Saba', gender: 'f' },
    { name: 'Senait', gender: 'f' },
    { name: 'Yordanos', gender: 'f' },
    { name: 'Lidya', gender: 'f' },
    { name: 'Ruth', gender: 'f' },
  ],
  espagnol: [
    { name: 'Pablo', gender: 'm' },
    { name: 'Diego', gender: 'm' },
    { name: 'Carlos', gender: 'm' },
    { name: 'Miguel', gender: 'm' },
    { name: 'Javier', gender: 'm' },
    { name: 'Antonio', gender: 'm' },
    { name: 'Hugo', gender: 'm' },
    { name: 'Mateo', gender: 'm' },
    { name: 'Sofia', gender: 'f' },
    { name: 'Lucia', gender: 'f' },
    { name: 'Maria', gender: 'f' },
    { name: 'Carmen', gender: 'f' },
    { name: 'Elena', gender: 'f' },
    { name: 'Paula', gender: 'f' },
    { name: 'Ana', gender: 'f' },
  ],
  français: [
    { name: 'Théo', gender: 'm' },
    { name: 'Hugo', gender: 'm' },
    { name: 'Lucas', gender: 'm' },
    { name: 'Louis', gender: 'm' },
    { name: 'Gabriel', gender: 'm' },
    { name: 'Raphaël', gender: 'm' },
    { name: 'Arthur', gender: 'm' },
    { name: 'Jules', gender: 'm' },
    { name: 'Léa', gender: 'f' },
    { name: 'Chloé', gender: 'f' },
    { name: 'Manon', gender: 'f' },
    { name: 'Camille', gender: 'f' },
    { name: 'Inès', gender: 'f' },
    { name: 'Jade', gender: 'f' },
    { name: 'Zoé', gender: 'f' },
  ],
  grec: [
    { name: 'Nikos', gender: 'm' },
    { name: 'Yannis', gender: 'm' },
    { name: 'Kostas', gender: 'm' },
    { name: 'Dimitris', gender: 'm' },
    { name: 'Alexandros', gender: 'm' },
    { name: 'Georgios', gender: 'm' },
    { name: 'Petros', gender: 'm' },
    { name: 'Andreas', gender: 'm' },
    { name: 'Eleni', gender: 'f' },
    { name: 'Maria', gender: 'f' },
    { name: 'Sofia', gender: 'f' },
    { name: 'Katerina', gender: 'f' },
    { name: 'Despina', gender: 'f' },
    { name: 'Georgia', gender: 'f' },
    { name: 'Anna', gender: 'f' },
  ],
  iranien: [
    { name: 'Reza', gender: 'm' },
    { name: 'Ali', gender: 'm' },
    { name: 'Hossein', gender: 'm' },
    { name: 'Mehdi', gender: 'm' },
    { name: 'Amir', gender: 'm' },
    { name: 'Saeed', gender: 'm' },
    { name: 'Parsa', gender: 'm' },
    { name: 'Kian', gender: 'm' },
    { name: 'Zahra', gender: 'f' },
    { name: 'Fatemeh', gender: 'f' },
    { name: 'Sara', gender: 'f' },
    { name: 'Narges', gender: 'f' },
    { name: 'Maryam', gender: 'f' },
    { name: 'Shirin', gender: 'f' },
    { name: 'Leila', gender: 'f' },
  ],
  italien: [
    { name: 'Marco', gender: 'm' },
    { name: 'Luca', gender: 'm' },
    { name: 'Andrea', gender: 'm' },
    { name: 'Matteo', gender: 'm' },
    { name: 'Alessandro', gender: 'm' },
    { name: 'Giovanni', gender: 'm' },
    { name: 'Francesco', gender: 'm' },
    { name: 'Lorenzo', gender: 'm' },
    { name: 'Giulia', gender: 'f' },
    { name: 'Sofia', gender: 'f' },
    { name: 'Chiara', gender: 'f' },
    { name: 'Francesca', gender: 'f' },
    { name: 'Valentina', gender: 'f' },
    { name: 'Elena', gender: 'f' },
    { name: 'Martina', gender: 'f' },
  ],
  japonais: [
    { name: 'Kenji', gender: 'm' },
    { name: 'Hiroshi', gender: 'm' },
    { name: 'Takeshi', gender: 'm' },
    { name: 'Haruto', gender: 'm' },
    { name: 'Sota', gender: 'm' },
    { name: 'Riku', gender: 'm' },
    { name: 'Kaito', gender: 'm' },
    { name: 'Ren', gender: 'm' },
    { name: 'Hana', gender: 'f' },
    { name: 'Aiko', gender: 'f' },
    { name: 'Sakura', gender: 'f' },
    { name: 'Yui', gender: 'f' },
    { name: 'Mio', gender: 'f' },
    { name: 'Akari', gender: 'f' },
    { name: 'Yukiko', gender: 'f' },
  ],
  polonais: [
    { name: 'Jakub', gender: 'm' },
    { name: 'Mateusz', gender: 'm' },
    { name: 'Piotr', gender: 'm' },
    { name: 'Tomasz', gender: 'm' },
    { name: 'Krzysztof', gender: 'm' },
    { name: 'Adam', gender: 'm' },
    { name: 'Michal', gender: 'm' },
    { name: 'Pawel', gender: 'm' },
    { name: 'Anna', gender: 'f' },
    { name: 'Maria', gender: 'f' },
    { name: 'Katarzyna', gender: 'f' },
    { name: 'Magdalena', gender: 'f' },
    { name: 'Agnieszka', gender: 'f' },
    { name: 'Joanna', gender: 'f' },
    { name: 'Zofia', gender: 'f' },
  ],
  portugais: [
    { name: 'João', gender: 'm' },
    { name: 'Pedro', gender: 'm' },
    { name: 'Tiago', gender: 'm' },
    { name: 'Miguel', gender: 'm' },
    { name: 'Rui', gender: 'm' },
    { name: 'André', gender: 'm' },
    { name: 'Bruno', gender: 'm' },
    { name: 'Diogo', gender: 'm' },
    { name: 'Ana', gender: 'f' },
    { name: 'Maria', gender: 'f' },
    { name: 'Inês', gender: 'f' },
    { name: 'Beatriz', gender: 'f' },
    { name: 'Sofia', gender: 'f' },
    { name: 'Carla', gender: 'f' },
    { name: 'Rita', gender: 'f' },
  ],
  russe: [
    { name: 'Ivan', gender: 'm' },
    { name: 'Dmitri', gender: 'm' },
    { name: 'Alexei', gender: 'm' },
    { name: 'Sergei', gender: 'm' },
    { name: 'Nikolai', gender: 'm' },
    { name: 'Andrei', gender: 'm' },
    { name: 'Maxim', gender: 'm' },
    { name: 'Pavel', gender: 'm' },
    { name: 'Olga', gender: 'f' },
    { name: 'Elena', gender: 'f' },
    { name: 'Natalia', gender: 'f' },
    { name: 'Svetlana', gender: 'f' },
    { name: 'Irina', gender: 'f' },
    { name: 'Tatiana', gender: 'f' },
    { name: 'Anastasia', gender: 'f' },
  ],
  somalien: [
    { name: 'Abdi', gender: 'm' },
    { name: 'Hassan', gender: 'm' },
    { name: 'Mohamed', gender: 'm' },
    { name: 'Ahmed', gender: 'm' },
    { name: 'Omar', gender: 'm' },
    { name: 'Ibrahim', gender: 'm' },
    { name: 'Yusuf', gender: 'm' },
    { name: 'Farah', gender: 'm' },
    { name: 'Amina', gender: 'f' },
    { name: 'Fatima', gender: 'f' },
    { name: 'Hawa', gender: 'f' },
    { name: 'Sahra', gender: 'f' },
    { name: 'Khadija', gender: 'f' },
    { name: 'Nasra', gender: 'f' },
    { name: 'Hodan', gender: 'f' },
  ],
  suisse: [
    { name: 'Noah', gender: 'm' },
    { name: 'Liam', gender: 'm' },
    { name: 'Leon', gender: 'm' },
    { name: 'Luca', gender: 'm' },
    { name: 'Elias', gender: 'm' },
    { name: 'David', gender: 'm' },
    { name: 'Jonas', gender: 'm' },
    { name: 'Matteo', gender: 'm' },
    { name: 'Emma', gender: 'f' },
    { name: 'Mia', gender: 'f' },
    { name: 'Lina', gender: 'f' },
    { name: 'Sofia', gender: 'f' },
    { name: 'Lara', gender: 'f' },
    { name: 'Nina', gender: 'f' },
    { name: 'Elena', gender: 'f' },
  ],
  syrien: [
    { name: 'Omar', gender: 'm' },
    { name: 'Hassan', gender: 'm' },
    { name: 'Samir', gender: 'm' },
    { name: 'Rami', gender: 'm' },
    { name: 'Fadi', gender: 'm' },
    { name: 'Walid', gender: 'm' },
    { name: 'Tarek', gender: 'm' },
    { name: 'Nabil', gender: 'm' },
    { name: 'Rania', gender: 'f' },
    { name: 'Lina', gender: 'f' },
    { name: 'Nour', gender: 'f' },
    { name: 'Hala', gender: 'f' },
    { name: 'Dima', gender: 'f' },
    { name: 'Yasmin', gender: 'f' },
    { name: 'Maya', gender: 'f' },
  ],
  turc: [
    { name: 'Mehmet', gender: 'm' },
    { name: 'Ahmet', gender: 'm' },
    { name: 'Mustafa', gender: 'm' },
    { name: 'Ali', gender: 'm' },
    { name: 'Emre', gender: 'm' },
    { name: 'Can', gender: 'm' },
    { name: 'Burak', gender: 'm' },
    { name: 'Yusuf', gender: 'm' },
    { name: 'Ayşe', gender: 'f' },
    { name: 'Fatma', gender: 'f' },
    { name: 'Elif', gender: 'f' },
    { name: 'Zeynep', gender: 'f' },
    { name: 'Hatice', gender: 'f' },
    { name: 'Merve', gender: 'f' },
    { name: 'Selin', gender: 'f' },
  ],
  ukrainien: [
    { name: 'Oleksandr', gender: 'm' },
    { name: 'Andriy', gender: 'm' },
    { name: 'Dmytro', gender: 'm' },
    { name: 'Mykola', gender: 'm' },
    { name: 'Ivan', gender: 'm' },
    { name: 'Serhiy', gender: 'm' },
    { name: 'Vadym', gender: 'm' },
    { name: 'Taras', gender: 'm' },
    { name: 'Olena', gender: 'f' },
    { name: 'Oksana', gender: 'f' },
    { name: 'Nataliya', gender: 'f' },
    { name: 'Iryna', gender: 'f' },
    { name: 'Yulia', gender: 'f' },
    { name: 'Kateryna', gender: 'f' },
    { name: 'Sofiya', gender: 'f' },
  ],
  vietnamien: [
    { name: 'Minh', gender: 'm' },
    { name: 'Hung', gender: 'm' },
    { name: 'Duc', gender: 'm' },
    { name: 'Quang', gender: 'm' },
    { name: 'Tuan', gender: 'm' },
    { name: 'Nam', gender: 'm' },
    { name: 'Long', gender: 'm' },
    { name: 'Khoa', gender: 'm' },
    { name: 'Lan', gender: 'f' },
    { name: 'Mai', gender: 'f' },
    { name: 'Hoa', gender: 'f' },
    { name: 'Linh', gender: 'f' },
    { name: 'Trang', gender: 'f' },
    { name: 'Huong', gender: 'f' },
    { name: 'Thao', gender: 'f' },
  ],
}

/** Liste plate unique (ordre de première occurrence). */
export const ALL_PROPER_ENTRIES: readonly ProperEntry[] = (() => {
  const seen = new Set<string>()
  const out: ProperEntry[] = []
  for (const list of Object.values(PROPER_BY_NATIONALITY)) {
    for (const entry of list) {
      if (seen.has(entry.name)) continue
      seen.add(entry.name)
      out.push(entry)
    }
  }
  return out
})()

/** Jetons « Prénom/nom » pour les sujets Gattegno. */
export const PROPER_TAGGED = ALL_PROPER_ENTRIES.map((entry) => `${entry.name}/nom` as const)

/** Noms propres (majuscule conservée). */
export const PROPER_NAMES = new Set(ALL_PROPER_ENTRIES.map((entry) => entry.name))

/** Prénoms féminins pour l’accord. */
export const FEMALE_PROPER_NAMES = new Set(
  ALL_PROPER_ENTRIES.filter((entry) => entry.gender === 'f').map((entry) => entry.name),
)
