import type { ExerciseType, Topic } from '@/math/types'
import { GRAMMAIRE_THEORY_DOCS } from './theory'

export const GRAMMAIRE_DOMAIN = 'grammaire' as const

export const GRAMMAIRE_TOPICS: Topic[] = [
  { id: 'gram-se-presenter', label: 'Se présenter', domain: 'grammaire' },
  { id: 'gram-entrer-contact', label: 'Entrer en contact', domain: 'grammaire' },
  { id: 'gram-questions', label: 'Poser une question', domain: 'grammaire' },
  { id: 'gram-activite', label: 'Parler d’une activité', domain: 'grammaire' },
  { id: 'gram-espace', label: 'Se situer dans l’espace', domain: 'grammaire' },
  { id: 'gram-temps', label: 'Se situer dans le temps', domain: 'grammaire' },
  { id: 'gram-demander', label: 'Demander et proposer', domain: 'grammaire' },
  { id: 'gram-decrire', label: 'Décrire', domain: 'grammaire' },
  { id: 'gram-conseiller', label: 'Conseiller quelqu’un', domain: 'grammaire' },
  { id: 'gram-aliments', label: 'Parler des aliments', domain: 'grammaire' },
  { id: 'gram-passe', label: 'Parler du passé', domain: 'grammaire' },
  { id: 'gram-pronoms', label: 'Les pronoms', domain: 'grammaire' },
  { id: 'gram-action', label: 'Parler d’une action', domain: 'grammaire' },
  { id: 'gram-avenir', label: 'Parler de l’avenir', domain: 'grammaire' },
  { id: 'gram-faits', label: 'Parler des faits divers', domain: 'grammaire' },
  { id: 'gram-argumenter', label: 'S’expliquer et argumenter', domain: 'grammaire' },
  { id: 'gram-exprimer', label: 'Exprimer quelque chose', domain: 'grammaire' },
  { id: 'gram-aide', label: 'Aide-mémoire', domain: 'grammaire' },
]

/** Un type « Théorie » par fiche ; les exercices liés seront ajoutés ensuite. */
export const GRAMMAIRE_EXERCISE_TYPES: ExerciseType[] = [
  {
    id: 'gram-a1-theorie',
    topic: 'gram-se-presenter',
    label: 'Qui suis-je ?',
    description: 'Théorie FALC — Me présenter avec être, habiter, parler, s’appeler. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-a2-theorie',
    topic: 'gram-se-presenter',
    label: 'Les adjectifs de nationalité',
    description: 'Théorie FALC — Accorder l’adjectif de nationalité. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-a3-theorie',
    topic: 'gram-se-presenter',
    label: 'Aller : destination (pays et villes)',
    description: 'Théorie FALC — Dire où je vais (pays, continent, ville). Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-a4-theorie',
    topic: 'gram-se-presenter',
    label: 'Aller : destination (lieux et chez)',
    description: 'Théorie FALC — Dire où je vais (lieux, chez quelqu’un). Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-a5-theorie',
    topic: 'gram-se-presenter',
    label: 'Venir de : provenance',
    description: 'Théorie FALC — Dire d’où je viens. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-a6-theorie',
    topic: 'gram-se-presenter',
    label: 'Dire son âge',
    description: 'Théorie FALC — Dire mon âge avec avoir + ans. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-a7-theorie',
    topic: 'gram-se-presenter',
    label: 'La négation ne … pas',
    description: 'Théorie FALC — Former une phrase négative avec ne … pas. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-a8-theorie',
    topic: 'gram-se-presenter',
    label: 'Autres négations',
    description: 'Théorie FALC — Utiliser jamais, plus, rien, personne… Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-b1-theorie',
    topic: 'gram-entrer-contact',
    label: 'Tu et vous',
    description: 'Théorie FALC — Choisir tu ou vous. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-b2-theorie',
    topic: 'gram-entrer-contact',
    label: 'Les salutations',
    description: 'Théorie FALC — Saluer à l’arrivée et au départ. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-b3-theorie',
    topic: 'gram-entrer-contact',
    label: 'Les remerciements',
    description: 'Théorie FALC — Dire merci et répondre. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-c1-theorie',
    topic: 'gram-questions',
    label: 'Trois façons de poser une question',
    description: 'Théorie FALC — Former une question de trois façons. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-c2-theorie',
    topic: 'gram-questions',
    label: 'Questions fermées et ouvertes',
    description: 'Théorie FALC — Distinguer oui/non et mots interrogatifs. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-c3-theorie',
    topic: 'gram-questions',
    label: 'Les questions avec quel',
    description: 'Théorie FALC — Accorder quel / quelle / quels / quelles. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-d1-theorie',
    topic: 'gram-activite',
    label: 'Faire une activité',
    description: 'Théorie FALC — Parler d’un loisir avec faire du / de la / de l’. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-d2-theorie',
    topic: 'gram-activite',
    label: 'Les verbes pronominaux',
    description: 'Théorie FALC — Conjuguer un verbe avec me, te, se… Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-d3-theorie',
    topic: 'gram-activite',
    label: 'Les pronoms toniques',
    description: 'Théorie FALC — Utiliser moi, toi, lui, elle… Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-e1-theorie',
    topic: 'gram-espace',
    label: 'Les prépositions de lieu',
    description: 'Théorie FALC — Situer une personne ou une chose. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-e2-theorie',
    topic: 'gram-temps',
    label: 'Le moment',
    description: 'Théorie FALC — Dire l’heure, la date, le moment. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-e3-theorie',
    topic: 'gram-temps',
    label: 'La durée',
    description: 'Théorie FALC — Dire combien de temps. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-e4-theorie',
    topic: 'gram-temps',
    label: 'La fréquence',
    description: 'Théorie FALC — Dire à quelle fréquence. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-e5-theorie',
    topic: 'gram-temps',
    label: 'La succession',
    description: 'Théorie FALC — Ordonner des actions dans le temps. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-f1-theorie',
    topic: 'gram-demander',
    label: 'Les déterminants démonstratifs',
    description: 'Théorie FALC — Utiliser ce, cet, cette, ces. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-f2-theorie',
    topic: 'gram-demander',
    label: 'Pouvoir, devoir, vouloir',
    description: 'Théorie FALC — Exprimer capacité, obligation, volonté. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-f3-theorie',
    topic: 'gram-demander',
    label: 'Accepter et refuser',
    description: 'Théorie FALC — Accepter ou refuser une proposition. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-f4-theorie',
    topic: 'gram-decrire',
    label: 'La météo',
    description: 'Théorie FALC — Décrire le temps qu’il fait. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-f5-theorie',
    topic: 'gram-decrire',
    label: 'C’est, il est, il y a',
    description: 'Théorie FALC — Choisir c’est, il est ou il y a. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-f6-theorie',
    topic: 'gram-decrire',
    label: 'Les déterminants possessifs',
    description: 'Théorie FALC — Utiliser mon, ton, son… Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-f7-theorie',
    topic: 'gram-decrire',
    label: 'Les adjectifs qualificatifs',
    description: 'Théorie FALC — Placer et accorder un adjectif. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-f8-theorie',
    topic: 'gram-decrire',
    label: 'Les professions',
    description: 'Théorie FALC — Dire mon métier. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-f9-theorie',
    topic: 'gram-decrire',
    label: 'La comparaison',
    description: 'Théorie FALC — Comparer avec plus, moins, aussi. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-f10-theorie',
    topic: 'gram-conseiller',
    label: 'Devoir et pouvoir au conditionnel',
    description: 'Théorie FALC — Conseiller avec devrait / pourrait. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-f11-theorie',
    topic: 'gram-conseiller',
    label: 'L’impératif',
    description: 'Théorie FALC — Donner un ordre ou un conseil à l’impératif. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-g1-theorie',
    topic: 'gram-aliments',
    label: 'Les articles indéfinis',
    description: 'Théorie FALC — Utiliser un, une, des. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-g2-theorie',
    topic: 'gram-aliments',
    label: 'Les articles définis',
    description: 'Théorie FALC — Utiliser le, la, l’, les. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-g3-theorie',
    topic: 'gram-aliments',
    label: 'Les articles partitifs',
    description: 'Théorie FALC — Parler d’une quantité non comptée. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-g4-theorie',
    topic: 'gram-aliments',
    label: 'Les quantités',
    description: 'Théorie FALC — Exprimer une quantité. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-g5-theorie',
    topic: 'gram-aliments',
    label: 'Les déterminants indéfinis',
    description: 'Théorie FALC — Utiliser tout, chaque, plusieurs… Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-h1-theorie',
    topic: 'gram-passe',
    label: 'Le passé composé (idée)',
    description: 'Théorie FALC — Comprendre le passé composé. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-h2-theorie',
    topic: 'gram-passe',
    label: 'Passé composé avec avoir',
    description: 'Théorie FALC — Conjuguer le passé composé avec avoir. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-h3-theorie',
    topic: 'gram-passe',
    label: 'Passé composé avec être',
    description: 'Théorie FALC — Conjuguer le passé composé avec être. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-h4-theorie',
    topic: 'gram-passe',
    label: 'L’imparfait',
    description: 'Théorie FALC — Décrire le passé avec l’imparfait. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-h5-theorie',
    topic: 'gram-passe',
    label: 'Le plus-que-parfait',
    description: 'Théorie FALC — Dire qu’une action est avant une autre dans le passé. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-i1-theorie',
    topic: 'gram-pronoms',
    label: 'Les pronoms relatifs',
    description: 'Théorie FALC — Relier deux idées avec qui, que, où… Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-i2-theorie',
    topic: 'gram-pronoms',
    label: 'Les pronoms possessifs',
    description: 'Théorie FALC — Remplacer mon / ton / son par le mien… Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-i3-theorie',
    topic: 'gram-pronoms',
    label: 'Les pronoms démonstratifs',
    description: 'Théorie FALC — Utiliser celui, celle, ceux, celles. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-i4-theorie',
    topic: 'gram-pronoms',
    label: 'Les pronoms COD',
    description: 'Théorie FALC — Remplacer le complément d’objet direct. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-i5-theorie',
    topic: 'gram-pronoms',
    label: 'Les pronoms COI',
    description: 'Théorie FALC — Remplacer le complément d’objet indirect. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-i6-theorie',
    topic: 'gram-pronoms',
    label: 'Les pronoms indéfinis',
    description: 'Théorie FALC — Utiliser quelqu’un, quelque chose, rien… Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-i7-theorie',
    topic: 'gram-pronoms',
    label: 'En et y',
    description: 'Théorie FALC — Utiliser les pronoms en et y. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-j1-theorie',
    topic: 'gram-action',
    label: 'Le présent progressif',
    description: 'Théorie FALC — Dire qu’une action est en cours. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-j2-theorie',
    topic: 'gram-action',
    label: 'Le passé récent',
    description: 'Théorie FALC — Dire qu’une action vient d’arriver. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-j3-theorie',
    topic: 'gram-action',
    label: 'Le gérondif',
    description: 'Théorie FALC — Exprimer la simultanéité avec en + -ant. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-j4-theorie',
    topic: 'gram-avenir',
    label: 'Le futur proche',
    description: 'Théorie FALC — Parler d’un avenir proche. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-j5-theorie',
    topic: 'gram-avenir',
    label: 'Le futur simple',
    description: 'Théorie FALC — Parler de l’avenir avec le futur simple. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-j6-theorie',
    topic: 'gram-faits',
    label: 'La forme passive',
    description: 'Théorie FALC — Transformer une phrase active en passive. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-j7-theorie',
    topic: 'gram-faits',
    label: 'Discours direct et indirect',
    description: 'Théorie FALC — Rapporter des paroles. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-j8-theorie',
    topic: 'gram-faits',
    label: 'Le conditionnel (emploi)',
    description: 'Théorie FALC — Exprimer un souhait ou une hypothèse. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-j9-theorie',
    topic: 'gram-faits',
    label: 'L’hypothèse avec si',
    description: 'Théorie FALC — Construire une hypothèse avec si. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-k1-theorie',
    topic: 'gram-argumenter',
    label: 'Approuver et désapprouver',
    description: 'Théorie FALC — Donner mon avis pour ou contre. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-k2-theorie',
    topic: 'gram-argumenter',
    label: 'Les connecteurs',
    description: 'Théorie FALC — Organiser mon texte avec des connecteurs. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-k3-theorie',
    topic: 'gram-exprimer',
    label: 'Exprimer la cause',
    description: 'Théorie FALC — Dire pourquoi. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-k4-theorie',
    topic: 'gram-exprimer',
    label: 'Exprimer la conséquence',
    description: 'Théorie FALC — Dire le résultat. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-k5-theorie',
    topic: 'gram-exprimer',
    label: 'Exprimer le but',
    description: 'Théorie FALC — Dire dans quel but. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-k6-theorie',
    topic: 'gram-exprimer',
    label: 'Exprimer l’opposition',
    description: 'Théorie FALC — Opposer deux idées. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-k7-theorie',
    topic: 'gram-exprimer',
    label: 'Exprimer la concession',
    description: 'Théorie FALC — Concéder un fait puis opposer. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-k8-theorie',
    topic: 'gram-exprimer',
    label: 'Pronoms relatifs neutres',
    description: 'Théorie FALC — Utiliser ce qui, ce que, ce dont. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-k9-theorie',
    topic: 'gram-exprimer',
    label: 'Les doubles pronoms',
    description: 'Théorie FALC — Placer deux pronoms devant le verbe. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-k10-theorie',
    topic: 'gram-exprimer',
    label: 'Le subjonctif (emplois principaux)',
    description: 'Théorie FALC — Reconnaître quand utiliser le subjonctif. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-k11-theorie',
    topic: 'gram-exprimer',
    label: 'Verbes avec préposition',
    description: 'Théorie FALC — Choisir à ou de après un verbe. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-l1-theorie',
    topic: 'gram-aide',
    label: 'L’apostrophe',
    description: 'Théorie FALC — Utiliser l’apostrophe. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-l2-theorie',
    topic: 'gram-aide',
    label: 'Le genre des noms',
    description: 'Théorie FALC — Former le féminin des noms. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-l3-theorie',
    topic: 'gram-aide',
    label: 'Le nombre des noms',
    description: 'Théorie FALC — Former le pluriel des noms. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-l4-theorie',
    topic: 'gram-aide',
    label: 'Le genre des adjectifs',
    description: 'Théorie FALC — Accorder l’adjectif au féminin. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-l5-theorie',
    topic: 'gram-aide',
    label: 'Le nombre des adjectifs',
    description: 'Théorie FALC — Mettre l’adjectif au pluriel. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-l6-theorie',
    topic: 'gram-aide',
    label: 'Les lettres G et C',
    description: 'Théorie FALC — Comprendre les sons de g et c. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-l7-theorie',
    topic: 'gram-aide',
    label: 'Les lettres S et M',
    description: 'Théorie FALC — Repères sur s et m. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-l8-theorie',
    topic: 'gram-aide',
    label: 'Les accents',
    description: 'Théorie FALC — Reconnaître les accents courants. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-l9-theorie',
    topic: 'gram-aide',
    label: 'Les classes grammaticales',
    description: 'Théorie FALC — Nommer les classes de mots. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-l10-theorie',
    topic: 'gram-aide',
    label: 'La ponctuation',
    description: 'Théorie FALC — Utiliser la ponctuation de base. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
  {
    id: 'gram-l11-theorie',
    topic: 'gram-aide',
    label: 'Les homophones (sélection)',
    description: 'Théorie FALC — Distinguer les homophones courants. Exercices à venir.',
    instruction: 'Lisez la théorie.',
    visual: 'texte',
    preferredColumns: 1,
  },
]

/** Vérifie la cohérence catalogue ↔ banques théorie. */
export function assertGrammaireCatalog(): void {
  const typeIds = new Set(GRAMMAIRE_EXERCISE_TYPES.map((t) => t.id))
  for (const doc of GRAMMAIRE_THEORY_DOCS) {
    if (!typeIds.has(doc.typeId)) {
      throw new Error(`Théorie sans type catalogue: ${doc.typeId}`)
    }
  }
}
