/** Un modèle = un verbe / une construction. Sujet et complément varient à l’instanciation. */
export type SimpleFrame = {
  id: string
  preds: readonly string[]
}

function frame(id: string, preds: readonly string[]): SimpleFrame {
  return { id, preds }
}

/** 100 modèles du 1er groupe + avoir. Pas de « être ». */
export const SIMPLE_FRAMES_ER: readonly SimpleFrame[] = [
  frame('manger', ['mange/verbe une/determinant pomme/nom', 'mange/verbe un/determinant sandwich/nom', 'mange/verbe une/determinant soupe/nom', 'mange/verbe une/determinant salade/nom']),
  frame('goûter', ['goûte/verbe un/determinant gâteau/nom', 'goûte/verbe une/determinant tarte/nom', 'goûte/verbe un/determinant yaourt/nom']),
  frame('préparer', ['prépare/verbe le/determinant dîner/nom', 'prépare/verbe un/determinant gâteau/nom', 'prépare/verbe le/determinant petit-déjeuner/nom']),
  frame('cuisiner', ['cuisine/verbe un/determinant plat/nom', 'cuisine/verbe une/determinant soupe/nom', 'cuisine/verbe des/determinant légumes/nom']),
  frame('couper', ['coupe/verbe le/determinant pain/nom', 'coupe/verbe une/determinant tomate/nom', 'coupe/verbe le/determinant fromage/nom']),
  frame('mélanger', ['mélange/verbe la/determinant farine/nom', 'mélange/verbe les/determinant œufs/nom', 'mélange/verbe la/determinant salade/nom']),
  frame('griller', ['grille/verbe le/determinant pain/nom', 'grille/verbe un/determinant steak/nom', 'grille/verbe du/determinant fromage/nom']),
  frame('décorer', ['décore/verbe un/determinant gâteau/nom', 'décore/verbe la/determinant classe/nom', 'décore/verbe une/determinant carte/nom']),
  frame('acheter', ['achète/verbe du/determinant pain/nom', 'achète/verbe une/determinant glace/nom', 'achète/verbe des/determinant fleurs/nom', 'achète/verbe un/determinant journal/nom']),
  frame('fêter', ['fête/verbe un/determinant anniversaire/nom', 'fête/verbe une/determinant victoire/nom', 'fête/verbe un/determinant mariage/nom']),
  frame('payer', ['paie/verbe la/determinant note/nom', 'paie/verbe le/determinant ticket/nom', 'paie/verbe le/determinant loyer/nom']),
  frame('accrocher', ['accroche/verbe un/determinant manteau/nom', 'accroche/verbe un/determinant tableau/nom', 'accroche/verbe une/determinant photo/nom']),
  frame('apporter', ['apporte/verbe un/determinant gâteau/nom', 'apporte/verbe le/determinant courrier/nom', 'apporte/verbe une/determinant chaise/nom']),
  frame('emporter', ['emporte/verbe un/determinant sandwich/nom', 'emporte/verbe son/determinant sac/nom', 'emporte/verbe une/determinant bouteille/nom']),
  frame('rapporter', ['rapporte/verbe un/determinant souvenir/nom', 'rapporte/verbe le/determinant ballon/nom', 'rapporte/verbe un/determinant livre/nom']),
  frame('porter', ['porte/verbe un/determinant manteau/nom', 'porte/verbe un/determinant chapeau/nom', 'porte/verbe une/determinant écharpe/nom', 'porte/verbe un/determinant pull/nom']),
  frame('enfiler', ['enfile/verbe un/determinant manteau/nom', 'enfile/verbe un/determinant pull/nom', 'enfile/verbe des/determinant gants/nom']),
  frame('laver', ['lave/verbe la/determinant vaisselle/nom', 'lave/verbe la/determinant voiture/nom', 'lave/verbe le/determinant linge/nom']),
  frame('nettoyer', ['nettoie/verbe la/determinant table/nom', 'nettoie/verbe la/determinant vitre/nom', 'nettoie/verbe le/determinant sol/nom']),
  frame('essuyer', ['essuie/verbe la/determinant table/nom', 'essuie/verbe un/determinant verre/nom', 'essuie/verbe le/determinant tableau/nom']),
  frame('sécher', ['sèche/verbe le/determinant linge/nom', 'sèche/verbe ses/determinant cheveux/nom', 'sèche/verbe une/determinant assiette/nom']),
  frame('repasser', ['repasse/verbe une/determinant chemise/nom', 'repasse/verbe un/determinant pantalon/nom', 'repasse/verbe une/determinant robe/nom']),
  frame('ranger', ['range/verbe sa/determinant chambre/nom', 'range/verbe les/determinant jouets/nom', 'range/verbe la/determinant classe/nom']),
  frame('poser', ['pose/verbe le/determinant sac/nom', 'pose/verbe un/determinant vase/nom', 'pose/verbe le/determinant livre/nom']),
  frame('cacher', ['cache/verbe un/determinant trésor/nom', 'cache/verbe un/determinant cadeau/nom', 'cache/verbe la/determinant clé/nom']),
  frame('montrer', ['montre/verbe une/determinant photo/nom', 'montre/verbe un/determinant dessin/nom', 'montre/verbe le/determinant chemin/nom']),
  frame('chercher', ['cherche/verbe un/determinant stylo/nom', 'cherche/verbe le/determinant chat/nom', 'cherche/verbe ses/determinant clés/nom']),
  frame('trouver', ['trouve/verbe une/determinant pièce/nom', 'trouve/verbe un/determinant trésor/nom', 'trouve/verbe son/determinant cartable/nom']),
  frame('ramasser', ['ramasse/verbe les/determinant feuilles/nom', 'ramasse/verbe un/determinant papier/nom', 'ramasse/verbe des/determinant cailloux/nom']),
  frame('attraper', ['attrape/verbe le/determinant ballon/nom', 'attrape/verbe un/determinant papillon/nom', 'attrape/verbe le/determinant chat/nom']),
  frame('lancer', ['lance/verbe le/determinant ballon/nom', 'lance/verbe une/determinant pierre/nom', 'lance/verbe un/determinant frisbee/nom']),
  frame('jeter', ['jette/verbe un/determinant papier/nom', 'jette/verbe la/determinant balle/nom', 'jette/verbe des/determinant miettes/nom']),
  frame('pousser', ['pousse/verbe la/determinant porte/nom', 'pousse/verbe le/determinant chariot/nom', 'pousse/verbe une/determinant chaise/nom']),
  frame('tirer', ['tire/verbe la/determinant porte/nom', 'tire/verbe le/determinant chariot/nom', 'tire/verbe un/determinant rideau/nom']),
  frame('lever', ['lève/verbe la/determinant main/nom', 'lève/verbe le/determinant rideau/nom', 'lève/verbe un/determinant carton/nom']),
  frame('baisser', ['baisse/verbe le/determinant store/nom', 'baisse/verbe la/determinant vitre/nom', 'baisse/verbe le/determinant volume/nom']),
  frame('dessiner', ['dessine/verbe un/determinant arbre/nom', 'dessine/verbe un/determinant chat/nom', 'dessine/verbe une/determinant maison/nom']),
  frame('colorier', ['colorie/verbe un/determinant dessin/nom', 'colorie/verbe une/determinant carte/nom', 'colorie/verbe un/determinant mandala/nom']),
  frame('regarder', ['regarde/verbe un/determinant film/nom', 'regarde/verbe un/determinant match/nom', 'regarde/verbe la/determinant télé/nom']),
  frame('observer', ['observe/verbe un/determinant oiseau/nom', 'observe/verbe les/determinant étoiles/nom', 'observe/verbe un/determinant insecte/nom']),
  frame('admirer', ['admire/verbe un/determinant tableau/nom', 'admire/verbe le/determinant paysage/nom', 'admire/verbe une/determinant danse/nom']),
  frame('filmer', ['filme/verbe un/determinant match/nom', 'filme/verbe une/determinant fête/nom', 'filme/verbe le/determinant spectacle/nom']),
  frame('photographier', ['photographie/verbe un/determinant paysage/nom', 'photographie/verbe un/determinant ami/nom', 'photographie/verbe une/determinant fleur/nom']),
  frame('écouter', ['écoute/verbe une/determinant chanson/nom', 'écoute/verbe une/determinant histoire/nom', 'écoute/verbe la/determinant radio/nom']),
  frame('chanter', ['chante/verbe une/determinant chanson/nom', 'chante/verbe un/determinant refrain/nom', 'chante/verbe une/determinant berceuse/nom']),
  frame('danser', ['danse/verbe une/determinant valse/nom', 'danse/verbe une/determinant salsa/nom', 'danse/verbe un/determinant ballet/nom']),
  frame('aimer', ['aime/verbe les/determinant gâteaux/nom', 'aime/verbe le/determinant football/nom', 'aime/verbe la/determinant musique/nom', 'aime/verbe les/determinant livres/nom']),
  frame('adorer', ['adore/verbe le/determinant chocolat/nom', 'adore/verbe les/determinant chats/nom', 'adore/verbe la/determinant danse/nom']),
  frame('détester', ['déteste/verbe le/determinant bruit/nom', 'déteste/verbe les/determinant épinards/nom', 'déteste/verbe le/determinant froid/nom']),
  frame('préférer', ['préfère/verbe le/determinant thé/nom', 'préfère/verbe le/determinant train/nom', 'préfère/verbe la/determinant mer/nom']),
  frame('avoir', ['a/verbe un/determinant chien/nom', 'a/verbe un/determinant vélo/nom', 'a/verbe une/determinant sœur/nom', 'a/verbe un/determinant ballon/nom']),
  frame('habiter', ['habite/verbe dans/preposition une/determinant maison/nom', 'habite/verbe dans/preposition un/determinant village/nom', 'habite/verbe dans/preposition un/determinant appartement/nom']),
  frame('visiter', ['visite/verbe la/determinant ferme/nom', 'visite/verbe un/determinant musée/nom', 'visite/verbe une/determinant île/nom']),
  frame('traverser', ['traverse/verbe la/determinant rue/nom', 'traverse/verbe le/determinant pont/nom', 'traverse/verbe le/determinant parc/nom']),
  frame('longer', ['longe/verbe la/determinant rivière/nom', 'longe/verbe le/determinant mur/nom', 'longe/verbe la/determinant plage/nom']),
  frame('contourner', ['contourne/verbe le/determinant lac/nom', 'contourne/verbe un/determinant obstacle/nom', 'contourne/verbe la/determinant place/nom']),
  frame('grimper', ['grimpe/verbe un/determinant arbre/nom', 'grimpe/verbe une/determinant colline/nom', 'grimpe/verbe l’/determinant échelle/nom']),
  frame('inviter', ['invite/verbe un/determinant ami/nom', 'invite/verbe une/determinant cousine/nom', 'invite/verbe le/determinant voisin/nom']),
  frame('aider', ['aide/verbe la/determinant voisine/nom', 'aide/verbe un/determinant élève/nom', 'aide/verbe le/determinant maître/nom']),
  frame('remercier', ['remercie/verbe le/determinant facteur/nom', 'remercie/verbe une/determinant amie/nom', 'remercie/verbe le/determinant chauffeur/nom']),
  frame('saluer', ['salue/verbe le/determinant voisin/nom', 'salue/verbe la/determinant maîtresse/nom', 'salue/verbe un/determinant copain/nom']),
  frame('appeler', ['appelle/verbe un/determinant ami/nom', 'appelle/verbe le/determinant médecin/nom', 'appelle/verbe sa/determinant maman/nom']),
  frame('embrasser', ['embrasse/verbe sa/determinant maman/nom', 'embrasse/verbe le/determinant bébé/nom', 'embrasse/verbe sa/determinant sœur/nom']),
  frame('caresser', ['caresse/verbe le/determinant chat/nom', 'caresse/verbe un/determinant chien/nom', 'caresse/verbe un/determinant lapin/nom']),
  frame('soigner', ['soigne/verbe un/determinant oiseau/nom', 'soigne/verbe le/determinant chien/nom', 'soigne/verbe une/determinant plaie/nom']),
  frame('consoler', ['console/verbe un/determinant ami/nom', 'console/verbe sa/determinant sœur/nom', 'console/verbe le/determinant bébé/nom']),
  frame('garder', ['garde/verbe le/determinant secret/nom', 'garde/verbe un/determinant trésor/nom', 'garde/verbe la/determinant clé/nom']),
  frame('surveiller', ['surveille/verbe les/determinant enfants/nom', 'surveille/verbe le/determinant feu/nom', 'surveille/verbe la/determinant classe/nom']),
  frame('protéger', ['protège/verbe un/determinant ami/nom', 'protège/verbe la/determinant forêt/nom', 'protège/verbe le/determinant bébé/nom']),
  frame('sauver', ['sauve/verbe un/determinant chat/nom', 'sauve/verbe un/determinant oiseau/nom', 'sauve/verbe la/determinant partie/nom']),
  frame('réparer', ['répare/verbe un/determinant vélo/nom', 'répare/verbe une/determinant chaise/nom', 'répare/verbe le/determinant jouet/nom']),
  frame('bricoler', ['bricole/verbe une/determinant étagère/nom', 'bricole/verbe un/determinant nichoir/nom', 'bricole/verbe une/determinant cabane/nom']),
  frame('coller', ['colle/verbe un/determinant papier/nom', 'colle/verbe une/determinant étiquette/nom', 'colle/verbe une/determinant photo/nom']),
  frame('plier', ['plie/verbe une/determinant lettre/nom', 'plie/verbe un/determinant linge/nom', 'plie/verbe une/determinant carte/nom']),
  frame('déchirer', ['déchire/verbe un/determinant papier/nom', 'déchire/verbe une/determinant feuille/nom', 'déchire/verbe un/determinant ticket/nom']),
  frame('étudier', ['étudie/verbe une/determinant leçon/nom', 'étudie/verbe une/determinant carte/nom', 'étudie/verbe un/determinant poème/nom']),
  frame('réviser', ['révise/verbe sa/determinant leçon/nom', 'révise/verbe un/determinant verbe/nom', 'révise/verbe les/determinant tables/nom']),
  frame('recopier', ['recopie/verbe un/determinant texte/nom', 'recopie/verbe une/determinant phrase/nom', 'recopie/verbe un/determinant poème/nom']),
  frame('corriger', ['corrige/verbe un/determinant devoir/nom', 'corrige/verbe une/determinant faute/nom', 'corrige/verbe un/determinant exercice/nom']),
  frame('compter', ['compte/verbe les/determinant pommes/nom', 'compte/verbe les/determinant élèves/nom', 'compte/verbe les/determinant pièces/nom']),
  frame('calculer', ['calcule/verbe un/determinant total/nom', 'calcule/verbe une/determinant distance/nom', 'calcule/verbe le/determinant prix/nom']),
  frame('mesurer', ['mesure/verbe une/determinant table/nom', 'mesure/verbe le/determinant mur/nom', 'mesure/verbe une/determinant corde/nom']),
  frame('raconter', ['raconte/verbe une/determinant histoire/nom', 'raconte/verbe un/determinant rêve/nom', 'raconte/verbe une/determinant blague/nom']),
  frame('demander', ['demande/verbe une/determinant explication/nom', 'demande/verbe un/determinant service/nom', 'demande/verbe une/determinant permission/nom']),
  frame('expliquer', ['explique/verbe une/determinant règle/nom', 'explique/verbe un/determinant jeu/nom', 'explique/verbe le/determinant chemin/nom']),
  frame('allumer', ['allume/verbe la/determinant lampe/nom', 'allume/verbe une/determinant bougie/nom', 'allume/verbe le/determinant feu/nom']),
  frame('fermer', ['ferme/verbe la/determinant porte/nom', 'ferme/verbe la/determinant fenêtre/nom', 'ferme/verbe le/determinant cahier/nom']),
  frame('commencer', ['commence/verbe un/determinant dessin/nom', 'commence/verbe une/determinant histoire/nom', 'commence/verbe un/determinant jeu/nom']),
  frame('terminer', ['termine/verbe un/determinant devoir/nom', 'termine/verbe un/determinant puzzle/nom', 'termine/verbe une/determinant lettre/nom']),
  frame('continuer', ['continue/verbe le/determinant chemin/nom', 'continue/verbe une/determinant histoire/nom', 'continue/verbe le/determinant jeu/nom']),
  frame('répéter', ['répète/verbe une/determinant phrase/nom', 'répète/verbe un/determinant mot/nom', 'répète/verbe une/determinant consigne/nom']),
  frame('gagner', ['gagne/verbe un/determinant match/nom', 'gagne/verbe un/determinant prix/nom', 'gagne/verbe une/determinant médaille/nom']),
  frame('perdre', ['perd/verbe un/determinant ballon/nom', 'perd/verbe un/determinant ticket/nom', 'perd/verbe une/determinant clé/nom']),
  frame('marquer', ['marque/verbe un/determinant but/nom', 'marque/verbe un/determinant point/nom', 'marque/verbe une/determinant page/nom']),
  frame('emprunter', ['emprunte/verbe un/determinant livre/nom', 'emprunte/verbe un/determinant vélo/nom', 'emprunte/verbe un/determinant crayon/nom']),
  frame('prêter', ['prête/verbe un/determinant stylo/nom', 'prête/verbe un/determinant livre/nom', 'prête/verbe un/determinant jouet/nom']),
  frame('oublier', ['oublie/verbe un/determinant sac/nom', 'oublie/verbe une/determinant clé/nom', 'oublie/verbe un/determinant rendez-vous/nom']),
  frame('utiliser', ['utilise/verbe un/determinant ordinateur/nom', 'utilise/verbe une/determinant règle/nom', 'utilise/verbe un/determinant dictionnaire/nom']),
  frame('partager', ['partage/verbe un/determinant gâteau/nom', 'partage/verbe un/determinant secret/nom', 'partage/verbe des/determinant bonbons/nom']),
  frame('planter', ['plante/verbe une/determinant fleur/nom', 'plante/verbe un/determinant arbre/nom', 'plante/verbe des/determinant graines/nom']),
  frame('arroser', ['arrose/verbe une/determinant plante/nom', 'arrose/verbe le/determinant jardin/nom', 'arrose/verbe des/determinant fleurs/nom']),
  frame('semer', ['sème/verbe des/determinant graines/nom', 'sème/verbe du/determinant blé/nom', 'sème/verbe des/determinant fleurs/nom']),
  frame('envelopper', ['enveloppe/verbe un/determinant cadeau/nom', 'enveloppe/verbe un/determinant livre/nom', 'enveloppe/verbe un/determinant sandwich/nom']),
  frame('signer', ['signe/verbe une/determinant lettre/nom', 'signe/verbe un/determinant dessin/nom', 'signe/verbe une/determinant carte/nom']),
  frame('souligner', ['souligne/verbe un/determinant mot/nom', 'souligne/verbe une/determinant phrase/nom', 'souligne/verbe un/determinant titre/nom']),
]

/** 2e et 3e groupes : un modèle par verbe. */
export const SIMPLE_FRAMES_AUTRES: readonly SimpleFrame[] = [
  frame('lire', ['lit/verbe un/determinant journal/nom', 'lit/verbe une/determinant recette/nom', 'lit/verbe une/determinant revue/nom', 'lit/verbe un/determinant roman/nom']),
  frame('boire', ['boit/verbe un/determinant jus/nom', 'boit/verbe un/determinant thé/nom', 'boit/verbe un/determinant chocolat/nom']),
  frame('écrire', ['écrit/verbe une/determinant lettre/nom', 'écrit/verbe un/determinant poème/nom', 'écrit/verbe un/determinant message/nom']),
  frame('ouvrir', ['ouvre/verbe la/determinant fenêtre/nom', 'ouvre/verbe la/determinant porte/nom', 'ouvre/verbe la/determinant boîte/nom']),
  frame('prendre', ['prend/verbe le/determinant bus/nom', 'prend/verbe le/determinant train/nom', 'prend/verbe une/determinant photo/nom']),
  frame('finir', ['finit/verbe un/determinant puzzle/nom', 'finit/verbe un/determinant devoir/nom', 'finit/verbe un/determinant dessin/nom']),
  frame('choisir', ['choisit/verbe une/determinant robe/nom', 'choisit/verbe un/determinant film/nom', 'choisit/verbe une/determinant pomme/nom']),
  frame('voir', ['voit/verbe un/determinant oiseau/nom', 'voit/verbe un/determinant chat/nom', 'voit/verbe la/determinant mer/nom']),
  frame('faire', ['fait/verbe un/determinant bricolage/nom', 'fait/verbe la/determinant vaisselle/nom', 'fait/verbe un/determinant gâteau/nom']),
  frame('mettre', ['met/verbe une/determinant écharpe/nom', 'met/verbe un/determinant chapeau/nom', 'met/verbe la/determinant table/nom']),
  frame('apprendre', ['apprend/verbe une/determinant leçon/nom', 'apprend/verbe un/determinant poème/nom', 'apprend/verbe une/determinant chanson/nom']),
  frame('comprendre', ['comprend/verbe une/determinant règle/nom', 'comprend/verbe un/determinant problème/nom', 'comprend/verbe la/determinant consigne/nom']),
  frame('descendre', ['descend/verbe l’/determinant escalier/nom', 'descend/verbe la/determinant rue/nom', 'descend/verbe la/determinant colline/nom']),
  frame('attendre', ['attend/verbe le/determinant bus/nom', 'attend/verbe un/determinant ami/nom', 'attend/verbe le/determinant train/nom']),
  frame('vendre', ['vend/verbe un/determinant vélo/nom', 'vend/verbe des/determinant fleurs/nom', 'vend/verbe un/determinant journal/nom']),
  frame('perdre', ['perd/verbe un/determinant ticket/nom', 'perd/verbe une/determinant clé/nom', 'perd/verbe un/determinant gant/nom']),
  frame('dire', ['dit/verbe la/determinant vérité/nom', 'dit/verbe un/determinant mot/nom', 'dit/verbe une/determinant blague/nom']),
  frame('suivre', ['suit/verbe un/determinant chemin/nom', 'suit/verbe le/determinant guide/nom', 'suit/verbe une/determinant piste/nom']),
  frame('vivre', ['vit/verbe une/determinant aventure/nom', 'vit/verbe une/determinant histoire/nom', 'vit/verbe un/determinant rêve/nom']),
  frame('conduire', ['conduit/verbe une/determinant voiture/nom', 'conduit/verbe un/determinant bus/nom', 'conduit/verbe un/determinant tracteur/nom']),
  frame('construire', ['construit/verbe une/determinant cabane/nom', 'construit/verbe un/determinant pont/nom', 'construit/verbe une/determinant tour/nom']),
  frame('peindre', ['peint/verbe un/determinant mur/nom', 'peint/verbe une/determinant porte/nom', 'peint/verbe un/determinant tableau/nom']),
  frame('cueillir', ['cueille/verbe une/determinant fleur/nom', 'cueille/verbe des/determinant cerises/nom', 'cueille/verbe une/determinant pomme/nom']),
  frame('offrir', ['offre/verbe un/determinant cadeau/nom', 'offre/verbe une/determinant fleur/nom', 'offre/verbe un/determinant jouet/nom']),
  frame('couvrir', ['couvre/verbe la/determinant table/nom', 'couvre/verbe le/determinant bébé/nom', 'couvre/verbe un/determinant cahier/nom']),
  frame('découvrir', ['découvre/verbe un/determinant secret/nom', 'découvre/verbe un/determinant sentier/nom', 'découvre/verbe une/determinant grotte/nom']),
  frame('tenir', ['tient/verbe un/determinant ballon/nom', 'tient/verbe une/determinant corde/nom', 'tient/verbe le/determinant chien/nom']),
  frame('sentir', ['sent/verbe une/determinant fleur/nom', 'sent/verbe le/determinant pain/nom', 'sent/verbe un/determinant parfum/nom']),
  frame('servir', ['sert/verbe le/determinant repas/nom', 'sert/verbe le/determinant thé/nom', 'sert/verbe un/determinant gâteau/nom']),
  frame('connaître', ['connaît/verbe un/determinant chemin/nom', 'connaît/verbe une/determinant chanson/nom', 'connaît/verbe le/determinant quartier/nom']),
  frame('savoir', ['sait/verbe la/determinant leçon/nom', 'sait/verbe un/determinant poème/nom', 'sait/verbe une/determinant recette/nom']),
  frame('vouloir', ['veut/verbe une/determinant glace/nom', 'veut/verbe un/determinant vélo/nom', 'veut/verbe une/determinant pomme/nom']),
  frame('recevoir', ['reçoit/verbe un/determinant colis/nom', 'reçoit/verbe une/determinant lettre/nom', 'reçoit/verbe un/determinant cadeau/nom']),
  frame('battre', ['bat/verbe un/determinant record/nom', 'bat/verbe les/determinant œufs/nom', 'bat/verbe un/determinant tapis/nom']),
  frame('éteindre', ['éteint/verbe la/determinant lampe/nom', 'éteint/verbe la/determinant télé/nom', 'éteint/verbe le/determinant feu/nom']),
  frame('traduire', ['traduit/verbe un/determinant mot/nom', 'traduit/verbe une/determinant phrase/nom', 'traduit/verbe un/determinant texte/nom']),
  frame('coudre', ['coud/verbe un/determinant bouton/nom', 'coud/verbe une/determinant robe/nom', 'coud/verbe un/determinant ourlet/nom']),
  frame('joindre', ['joint/verbe une/determinant photo/nom', 'joint/verbe un/determinant document/nom', 'joint/verbe une/determinant carte/nom']),
  frame('atteindre', ['atteint/verbe le/determinant sommet/nom', 'atteint/verbe un/determinant but/nom', 'atteint/verbe la/determinant rive/nom']),
  frame('résoudre', ['résout/verbe un/determinant problème/nom', 'résout/verbe une/determinant énigme/nom', 'résout/verbe un/determinant calcul/nom']),
]

function assertUniqueFrames(frames: readonly SimpleFrame[], label: string) {
  const ids = new Set<string>()
  for (const frame of frames) {
    if (ids.has(frame.id)) throw new Error(`${label} : modèle en double — ${frame.id}`)
    if (frame.preds.length < 2) throw new Error(`${label} : ${frame.id} doit avoir au moins 2 compléments`)
    ids.add(frame.id)
  }
}

assertUniqueFrames(SIMPLE_FRAMES_ER, 'phrase-simple -er')
assertUniqueFrames(SIMPLE_FRAMES_AUTRES, 'phrase-simple autres')

export function simpleFramesFor(group: 'er' | 'autres'): readonly SimpleFrame[] {
  return group === 'autres' ? SIMPLE_FRAMES_AUTRES : SIMPLE_FRAMES_ER
}
