import type { PhraseCategory } from './types'

/** Couleurs Gattegno — grammaire en couleur (imprimables, contrastées). */
export const PHRASE_COLORS: Record<PhraseCategory, string> = {
  pronom: '#8b5a2b',
  verbe: '#e67e22',
  nom: '#2e8b57',
  determinant: '#d4a017',
  adjectif: '#9b4dca',
  adverbe: '#3d9bc9',
  preposition: '#c0392b',
  conjonction: '#1a1a1a',
  negation: '#1a1a1a',
  interjection: '#7a7a7a',
}

export const PHRASE_CATEGORY_LABELS: Record<PhraseCategory, string> = {
  pronom: 'Pronoms',
  verbe: 'Verbes',
  nom: 'Noms',
  determinant: 'Déterminants',
  adjectif: 'Adjectifs',
  adverbe: 'Adverbes',
  preposition: 'Prépositions',
  conjonction: 'Conjonctions',
  negation: 'Négation',
  interjection: 'Interjections',
}

/** Exemples affichés dans le tableau « mots » (extraits des banques). */
export const CHART_WORD_SAMPLES: Record<PhraseCategory, string> = {
  pronom:
    'je, tu, il, elle, on, nous, vous, ils, elles, me, te, se, le, la, les, lui, leur, y, en, moi, toi, soi, qui, que, où, dont…',
  verbe: 'être, avoir, aller, faire, prendre, venir, dire, voir, lire, écrire, manger, boire…',
  nom: 'chat, chien, maison, école, livre, fille, garçon, voiture, arbre, montagne…',
  determinant:
    'le, la, l’, les, un, une, des, du, de la, ce, cet, cette, ces, mon, ma, mes, ton, ta, tes, son, sa, ses, notre, nos, votre, vos, leur, leurs, quel, quelle, quelques, plusieurs, chaque, tout, toute…',
  adjectif:
    'grand, petit, beau, belle, joli, long, court, haut, bas, jeune, vieux, nouveau, vieux, bon, mauvais, chaud, froid, rapide, lent, heureux, triste, rouge, bleu, vert, noir, blanc, intelligent, sympa…',
  adverbe:
    'très, trop, assez, peu, bien, mal, vite, lentement, souvent, toujours, jamais, parfois, ici, là, ailleurs, aujourd’hui, demain, hier, maintenant, bientôt, déjà, encore, aussi, peut-être, vraiment…',
  preposition:
    'à, de, en, dans, sur, sous, chez, avec, sans, pour, par, entre, parmi, devant, derrière, avant, après, depuis, pendant, vers, jusqu’à, contre, selon, malgré, près de, loin de…',
  conjonction:
    'et, ou, mais, donc, or, ni, car, puis, cependant, pourtant, quand, lorsque, si, comme, parce que, puisque, bien que, afin que, pour que, tandis que…',
  negation: 'ne, n’, pas, plus, jamais, rien, personne, aucun, aucune, nulle part, guère, que…',
  interjection: 'ah, oh, hé, eh, ouf, aïe, bravo, chut, stop, allez, tiens, mince, zut, hourra…',
}

/** Pronoms sujets (génération de phrases). */
export const PRONOMS = [
  'je',
  'tu',
  'il',
  'elle',
  'on',
  'nous',
  'vous',
  'ils',
  'elles',
] as const

/** Pronoms objets / toniques / relatifs (référence tableau & enrichissement). */
export const PRONOMS_COMPLETS = [
  'je',
  'tu',
  'il',
  'elle',
  'on',
  'nous',
  'vous',
  'ils',
  'elles',
  'me',
  'te',
  'se',
  'le',
  'la',
  'les',
  'lui',
  'leur',
  'y',
  'en',
  'moi',
  'toi',
  'soi',
  'eux',
  'elles',
  'qui',
  'que',
  'quoi',
  'où',
  'dont',
  'lequel',
  'laquelle',
  'lesquels',
  'lesquelles',
  'celui',
  'celle',
  'ceux',
  'celles',
  'ceci',
  'cela',
  'ça',
] as const

export const NOMS_PROPRES = [
  'Fanny',
  'Thomas',
  'Sophie',
  'Déborah',
  'Iryna',
  'Hugo',
  'Léa',
  'Noah',
  'Maya',
  'Sami',
  'Amira',
  'Lucas',
  'Nina',
  'Omar',
  'Clara',
  'Adam',
  'Inès',
  'Yanis',
  'Lina',
  'Rayan',
] as const

export const DETERMINANTS = {
  m_sing: [
    'le',
    'un',
    'mon',
    'ton',
    'son',
    'notre',
    'votre',
    'leur',
    'ce',
    'cet',
    'quel',
    'chaque',
    'tout',
    'aucun',
  ],
  f_sing: [
    'la',
    'une',
    'ma',
    'ta',
    'sa',
    'notre',
    'votre',
    'leur',
    'cette',
    'quelle',
    'chaque',
    'toute',
    'aucune',
  ],
  plur: [
    'les',
    'des',
    'mes',
    'tes',
    'ses',
    'nos',
    'vos',
    'leurs',
    'ces',
    'quels',
    'quelles',
    'quelques',
    'plusieurs',
    'tous',
    'toutes',
    'certains',
    'certaines',
    'beaucoup de',
  ],
} as const

export const DETERMINANTS_TOUS = [
  'le',
  'la',
  'l’',
  'les',
  'un',
  'une',
  'des',
  'du',
  'de la',
  'de l’',
  'ce',
  'cet',
  'cette',
  'ces',
  'mon',
  'ma',
  'mes',
  'ton',
  'ta',
  'tes',
  'son',
  'sa',
  'ses',
  'notre',
  'nos',
  'votre',
  'vos',
  'leur',
  'leurs',
  'quel',
  'quelle',
  'quels',
  'quelles',
  'chaque',
  'tout',
  'toute',
  'tous',
  'toutes',
  'quelques',
  'plusieurs',
  'certains',
  'certaines',
  'aucun',
  'aucune',
  'beaucoup de',
  'peu de',
  'assez de',
  'trop de',
] as const

export type NounEntry = { text: string; gender: 'm' | 'f'; number: 'sing' | 'plur' }

/** Noms : liste pédagogique limitée (pas exhaustive). */
export const NOMS: NounEntry[] = [
  { text: 'chat', gender: 'm', number: 'sing' },
  { text: 'chien', gender: 'm', number: 'sing' },
  { text: 'garçon', gender: 'm', number: 'sing' },
  { text: 'livre', gender: 'm', number: 'sing' },
  { text: 'crayon', gender: 'm', number: 'sing' },
  { text: 'train', gender: 'm', number: 'sing' },
  { text: 'poisson', gender: 'm', number: 'sing' },
  { text: 'chapeau', gender: 'm', number: 'sing' },
  { text: 'ballon', gender: 'm', number: 'sing' },
  { text: 'sac', gender: 'm', number: 'sing' },
  { text: 'fille', gender: 'f', number: 'sing' },
  { text: 'maison', gender: 'f', number: 'sing' },
  { text: 'école', gender: 'f', number: 'sing' },
  { text: 'voiture', gender: 'f', number: 'sing' },
  { text: 'chemise', gender: 'f', number: 'sing' },
  { text: 'pomme', gender: 'f', number: 'sing' },
  { text: 'fleur', gender: 'f', number: 'sing' },
  { text: 'table', gender: 'f', number: 'sing' },
  { text: 'fenêtre', gender: 'f', number: 'sing' },
  { text: 'télé', gender: 'f', number: 'sing' },
  { text: 'chats', gender: 'm', number: 'plur' },
  { text: 'livres', gender: 'm', number: 'plur' },
  { text: 'pommes', gender: 'f', number: 'plur' },
  { text: 'fleurs', gender: 'f', number: 'plur' },
]

export type AdjEntry = { m: string; f: string }

export const ADJECTIFS: AdjEntry[] = [
  { m: 'grand', f: 'grande' },
  { m: 'petit', f: 'petite' },
  { m: 'beau', f: 'belle' },
  { m: 'joli', f: 'jolie' },
  { m: 'long', f: 'longue' },
  { m: 'court', f: 'courte' },
  { m: 'haut', f: 'haute' },
  { m: 'bas', f: 'basse' },
  { m: 'jeune', f: 'jeune' },
  { m: 'vieux', f: 'vieille' },
  { m: 'nouveau', f: 'nouvelle' },
  { m: 'bon', f: 'bonne' },
  { m: 'mauvais', f: 'mauvaise' },
  { m: 'chaud', f: 'chaude' },
  { m: 'froid', f: 'froide' },
  { m: 'rapide', f: 'rapide' },
  { m: 'lent', f: 'lente' },
  { m: 'heureux', f: 'heureuse' },
  { m: 'triste', f: 'triste' },
  { m: 'content', f: 'contente' },
  { m: 'fatigué', f: 'fatiguée' },
  { m: 'calme', f: 'calme' },
  { m: 'bruyant', f: 'bruyante' },
  { m: 'propre', f: 'propre' },
  { m: 'sale', f: 'sale' },
  { m: 'plein', f: 'pleine' },
  { m: 'vide', f: 'vide' },
  { m: 'ouvert', f: 'ouverte' },
  { m: 'fermé', f: 'fermée' },
  { m: 'facile', f: 'facile' },
  { m: 'difficile', f: 'difficile' },
  { m: 'important', f: 'importante' },
  { m: 'intéressant', f: 'intéressante' },
  { m: 'intelligent', f: 'intelligente' },
  { m: 'sympa', f: 'sympa' },
  { m: 'gentil', f: 'gentille' },
  { m: 'méchant', f: 'méchante' },
  { m: 'fort', f: 'forte' },
  { m: 'faible', f: 'faible' },
  { m: 'lourd', f: 'lourde' },
  { m: 'léger', f: 'légère' },
  { m: 'rond', f: 'ronde' },
  { m: 'carré', f: 'carrée' },
  { m: 'rouge', f: 'rouge' },
  { m: 'bleu', f: 'bleue' },
  { m: 'vert', f: 'verte' },
  { m: 'jaune', f: 'jaune' },
  { m: 'noir', f: 'noire' },
  { m: 'blanc', f: 'blanche' },
  { m: 'gris', f: 'grise' },
  { m: 'rose', f: 'rose' },
  { m: 'orange', f: 'orange' },
  { m: 'marron', f: 'marron' },
  { m: 'violet', f: 'violette' },
  { m: 'clair', f: 'claire' },
  { m: 'sombre', f: 'sombre' },
  { m: 'doux', f: 'douce' },
  { m: 'dur', f: 'dure' },
  { m: 'sec', f: 'sèche' },
  { m: 'mouillé', f: 'mouillée' },
  { m: 'premier', f: 'première' },
  { m: 'dernier', f: 'dernière' },
  { m: 'autre', f: 'autre' },
  { m: 'même', f: 'même' },
  { m: 'seul', f: 'seule' },
  { m: 'entier', f: 'entière' },
]

/** Verbes : liste pédagogique limitée (pas exhaustive). */
export const VERBES = [
  { infinitive: 'manger', forms: { je: 'mange', tu: 'manges', il: 'mange', nous: 'mangeons', vous: 'mangez', ils: 'mangent' } },
  { infinitive: 'porter', forms: { je: 'porte', tu: 'portes', il: 'porte', nous: 'portons', vous: 'portez', ils: 'portent' } },
  { infinitive: 'regarder', forms: { je: 'regarde', tu: 'regardes', il: 'regarde', nous: 'regardons', vous: 'regardez', ils: 'regardent' } },
  { infinitive: 'acheter', forms: { je: 'achète', tu: 'achètes', il: 'achète', nous: 'achetons', vous: 'achetez', ils: 'achètent' } },
  { infinitive: 'prendre', forms: { je: 'prends', tu: 'prends', il: 'prend', nous: 'prenons', vous: 'prenez', ils: 'prennent' } },
  { infinitive: 'avoir', forms: { je: 'ai', tu: 'as', il: 'a', nous: 'avons', vous: 'avez', ils: 'ont' } },
  { infinitive: 'aimer', forms: { je: 'aime', tu: 'aimes', il: 'aime', nous: 'aimons', vous: 'aimez', ils: 'aiment' } },
  { infinitive: 'lire', forms: { je: 'lis', tu: 'lis', il: 'lit', nous: 'lisons', vous: 'lisez', ils: 'lisent' } },
  { infinitive: 'voir', forms: { je: 'vois', tu: 'vois', il: 'voit', nous: 'voyons', vous: 'voyez', ils: 'voient' } },
  { infinitive: 'trouver', forms: { je: 'trouve', tu: 'trouves', il: 'trouve', nous: 'trouvons', vous: 'trouvez', ils: 'trouvent' } },
  { infinitive: 'ouvrir', forms: { je: 'ouvre', tu: 'ouvres', il: 'ouvre', nous: 'ouvrons', vous: 'ouvrez', ils: 'ouvrent' } },
  { infinitive: 'dessiner', forms: { je: 'dessine', tu: 'dessines', il: 'dessine', nous: 'dessinons', vous: 'dessinez', ils: 'dessinent' } },
  { infinitive: 'lancer', forms: { je: 'lance', tu: 'lances', il: 'lance', nous: 'lançons', vous: 'lancez', ils: 'lancent' } },
  { infinitive: 'chercher', forms: { je: 'cherche', tu: 'cherches', il: 'cherche', nous: 'cherchons', vous: 'cherchez', ils: 'cherchent' } },
  { infinitive: 'écrire', forms: { je: 'écris', tu: 'écris', il: 'écrit', nous: 'écrivons', vous: 'écrivez', ils: 'écrivent' } },
  { infinitive: 'boire', forms: { je: 'bois', tu: 'bois', il: 'boit', nous: 'buvons', vous: 'buvez', ils: 'boivent' } },
] as const

export const ADVERBES = [
  'très',
  'trop',
  'assez',
  'peu',
  'beaucoup',
  'bien',
  'mal',
  'mieux',
  'vite',
  'lentement',
  'doucement',
  'fort',
  'souvent',
  'toujours',
  'jamais',
  'parfois',
  'quelquefois',
  'rarement',
  'déjà',
  'encore',
  'enfin',
  'soudain',
  'maintenant',
  'aujourd’hui',
  'demain',
  'hier',
  'bientôt',
  'tard',
  'tôt',
  'ici',
  'là',
  'ailleurs',
  'partout',
  'dehors',
  'dedans',
  'loin',
  'près',
  'ensemble',
  'seul',
  'aussi',
  'également',
  'surtout',
  'seulement',
  'vraiment',
  'sûrement',
  'peut-être',
  'probablement',
  'certainement',
  'clairement',
  'facilement',
  'difficilement',
  'heureusement',
  'malheureusement',
  'simplement',
  'exactement',
  'complètement',
  'presque',
  'environ',
  'ainsi',
  'puis',
  'ensuite',
  'alors',
  'pourtant',
  'cependant',
] as const

export const PREPOSITIONS = [
  'à',
  'de',
  'en',
  'dans',
  'sur',
  'sous',
  'chez',
  'avec',
  'sans',
  'pour',
  'par',
  'entre',
  'parmi',
  'devant',
  'derrière',
  'avant',
  'après',
  'depuis',
  'pendant',
  'durant',
  'vers',
  'jusqu’à',
  'contre',
  'selon',
  'malgré',
  'sauf',
  'hormis',
  'près de',
  'loin de',
  'à côté de',
  'au-dessus de',
  'au-dessous de',
  'autour de',
  'au milieu de',
  'en face de',
  'à cause de',
  'grâce à',
  'afin de',
  'avant de',
  'jusque',
  'envers',
  'vis-à-vis de',
  'quant à',
] as const

export const CONJONCTIONS_COORD = [
  'et',
  'ou',
  'mais',
  'donc',
  'or',
  'ni',
  'car',
  'puis',
  'ensuite',
  'cependant',
  'pourtant',
  'toutefois',
  'néanmoins',
  'aussi',
  'ainsi',
] as const

export const CONJONCTIONS_SUB = [
  'quand',
  'lorsque',
  'si',
  'comme',
  'parce que',
  'puisque',
  'car',
  'bien que',
  'quoique',
  'afin que',
  'pour que',
  'de sorte que',
  'tandis que',
  'pendant que',
  'avant que',
  'après que',
  'dès que',
  'aussitôt que',
  'tant que',
  'jusqu’à ce que',
  'sans que',
  'à moins que',
  'pourvu que',
  'que',
] as const

export const NEGATIONS = [
  'ne',
  'n’',
  'pas',
  'plus',
  'jamais',
  'rien',
  'personne',
  'aucun',
  'aucune',
  'nulle part',
  'guère',
  'que',
  'ni',
  'nullement',
  'point',
] as const

export const INTERJECTIONS = [
  'ah',
  'oh',
  'hé',
  'eh',
  'ouf',
  'aïe',
  'ouille',
  'bravo',
  'chut',
  'stop',
  'allez',
  'tiens',
  'tiens donc',
  'mince',
  'zut',
  'flûte',
  'hourra',
  'ouais',
  'bah',
  'bof',
  'hein',
  'quoi',
  'attention',
  'help',
  'merci',
  'pardon',
  's’il vous plaît',
] as const

export type PhraseThemeId =
  | 'phrase-simple'
  | 'phrase-negation'
  | 'phrase-adjectif'
  | 'phrase-negation-adjectif'
  | 'phrase-preposition'
  | 'phrase-adverbe'
  | 'phrase-negation-adverbe'
  | 'phrase-conjonctions'

/**
 * 100 consignes de production écrite, uniques, adaptées au thème
 * (structure attendue de la phrase).
 */
export const PRODUCTION_PROMPTS_BY_THEME: Record<PhraseThemeId, readonly string[]> = {
  'phrase-simple': [
    'Écrivez des phrases simples (sujet + verbe + complément).',
    'Écrivez des phrases pour dire ce que vous faites aujourd’hui.',
    'Écrivez des phrases sur votre école.',
    'Écrivez des phrases pour décrire votre journée.',
    'Écrivez des phrases avec des animaux.',
    'Écrivez des phrases pour parler de votre famille.',
    'Écrivez des phrases sur ce que vous aimez.',
    'Écrivez des phrases sur un ami ou une amie.',
    'Écrivez des phrases sur le repas.',
    'Écrivez des phrases sur le sport.',
    'Écrivez des phrases sur les vacances.',
    'Écrivez des phrases sur un livre ou un film.',
    'Écrivez des phrases pour présenter votre chambre.',
  ],
  'phrase-negation': [
    'Écrivez des phrases négatives avec ne… pas.',
    'Écrivez ce que vous ne faites pas le matin.',
    'Écrivez des phrases pour dire ce que vous n’aimez pas.',
    'Écrivez des phrases négatives sur l’école.',
    'Écrivez des phrases avec ne… jamais.',
    'Écrivez des phrases avec ne… plus.',
    'Écrivez ce que vous ne mangez pas.',
    'Écrivez des phrases négatives sur le week-end.',
    'Écrivez des phrases pour dire ce qui n’est pas vrai.',
    'Écrivez des phrases négatives avec un pronom sujet.',
    'Écrivez des phrases négatives sur les devoirs.',
    'Écrivez des phrases pour refuser poliment (ne… pas).',
  ],
  'phrase-adjectif': [
    'Écrivez des phrases avec un adjectif pour décrire.',
    'Écrivez des phrases pour décrire une personne (adjectif).',
    'Écrivez des phrases pour décrire un animal (adjectif).',
    'Écrivez des phrases pour décrire un objet (adjectif).',
    'Écrivez des phrases avec un adjectif de couleur.',
    'Écrivez des phrases avec grand / petit.',
    'Écrivez des phrases pour décrire votre maison.',
    'Écrivez des phrases pour décrire le temps (adjectif).',
    'Écrivez des phrases avec un adjectif de sentiment.',
    'Écrivez des phrases pour décrire un ami (adjectif).',
    'Écrivez des phrases avec beau / belle.',
    'Écrivez des phrases pour décrire un lieu (adjectif).',
    'Écrivez des phrases avec un adjectif avant ou après le nom.',
  ],
  'phrase-negation-adjectif': [
    'Écrivez des phrases négatives avec un adjectif.',
    'Écrivez ce qui n’est pas grand / petit (avec adjectif).',
    'Écrivez des phrases : ce n’est pas… + adjectif.',
    'Écrivez des phrases négatives pour décrire une personne.',
    'Écrivez des phrases négatives pour décrire un objet.',
    'Écrivez des phrases avec ne… pas + adjectif de couleur.',
    'Écrivez ce que vous n’êtes pas (adjectif).',
    'Écrivez des phrases négatives sur un animal (adjectif).',
    'Écrivez des phrases : ce n’est plus… + adjectif.',
    'Écrivez des phrases négatives pour corriger une description.',
    'Écrivez des phrases avec ne… jamais + adjectif.',
    'Écrivez des phrases négatives sur le temps (adjectif).',
  ],
  'phrase-preposition': [
    'Écrivez des phrases avec une préposition (dans, sur, sous…).',
    'Écrivez des phrases avec dans.',
    'Écrivez des phrases avec sur / sous.',
    'Écrivez des phrases avec chez.',
    'Écrivez des phrases avec avec / sans.',
    'Écrivez des phrases avec pour.',
    'Écrivez des phrases avec devant / derrière.',
    'Écrivez des phrases avec entre.',
    'Écrivez des phrases pour situer un objet (préposition).',
    'Écrivez des phrases pour dire où vous allez (préposition).',
    'Écrivez des phrases avec près de / loin de.',
    'Écrivez des phrases avec pendant / depuis.',
    'Écrivez des phrases pour décrire un trajet (préposition).',
  ],
  'phrase-adverbe': [
    'Écrivez des phrases avec un adverbe (vite, bien, souvent…).',
    'Écrivez des phrases avec bien / mal.',
    'Écrivez des phrases avec vite / lentement.',
    'Écrivez des phrases avec souvent / toujours.',
    'Écrivez des phrases avec aujourd’hui / demain.',
    'Écrivez des phrases avec ici / là.',
    'Écrivez des phrases avec très.',
    'Écrivez des phrases avec déjà / encore.',
    'Écrivez des phrases pour dire comment vous agissez (adverbe).',
    'Écrivez des phrases avec peut-être / vraiment.',
    'Écrivez des phrases avec hier / maintenant.',
    'Écrivez des phrases avec beaucoup / peu.',
  ],
  'phrase-negation-adverbe': [
    'Écrivez des phrases négatives avec un adverbe.',
    'Écrivez des phrases avec ne… pas + bien / mal.',
    'Écrivez des phrases avec ne… jamais + adverbe de temps.',
    'Écrivez ce que vous ne faites pas souvent.',
    'Écrivez des phrases : ne… pas vite / lentement.',
    'Écrivez des phrases négatives avec aujourd’hui / demain.',
    'Écrivez des phrases avec ne… plus + adverbe.',
    'Écrivez des phrases négatives avec ici / là.',
    'Écrivez des phrases : je ne… pas vraiment.',
    'Écrivez des phrases négatives pour dire comment vous n’agissez pas.',
    'Écrivez des phrases avec ne… pas encore.',
    'Écrivez des phrases négatives avec trop / assez.',
  ],
  'phrase-conjonctions': [
    'Écrivez des phrases avec et / ou / mais.',
    'Écrivez des phrases avec parce que.',
    'Écrivez des phrases avec quand / si.',
    'Écrivez des phrases avec donc / car.',
    'Écrivez deux idées reliées par mais.',
    'Écrivez des phrases avec puis / ensuite.',
    'Écrivez des phrases avec bien que / même si (niveau avancé).',
    'Écrivez une cause avec parce que ou puisque.',
    'Écrivez une condition avec si.',
    'Écrivez des phrases avec ou pour proposer un choix.',
    'Écrivez des phrases complexes avec une conjonction de coordination.',
    'Écrivez des phrases complexes avec une conjonction de subordination.',
    'Écrivez une histoire courte en reliant les phrases (et, puis, donc).',
  ],
}

/** Toutes les consignes (100), utiles pour contrôles d’unicité. */
export const PRODUCTION_PROMPTS: readonly string[] = Object.values(PRODUCTION_PROMPTS_BY_THEME).flat()
