import type { TcfNiveau } from './types'

/** Test blanc complet : suite ordonnée d’exercices de la banque (ids). */
export type TcfSerie = {
  id: string
  label: string
  niveau: TcfNiveau
  exercices: readonly string[]
}

const PREP_A1_SUJETS_ORAL = [
  ['', 'hôtel'],
  ['b', 'magasin de vêtements'],
  ['c', 'club de vacances'],
  ['d', 'marché'],
  ['e', 'théâtre'],
  ['f', 'café'],
  ['g', 'gare'],
  ['h', 'magasin de fournitures'],
  ['i', 'école'],
  ['j', 'magasin de livres'],
] as const

const prepIds = (p: string, k: number, c: string) => Array.from({ length: k }, (_, i) => `${p}${c}-${i + 1}`)

/** Préparation A2 (format DELF) : les sujets d’oral sont listés sur la fiche. */
function prepA2Serie(n: number): TcfSerie {
  const p = `tcf-a2p-s${n}-`
  return {
    id: `a2p-serie-${n}`,
    label: `Préparation A2 · série ${n}`,
    niveau: 'A1-A2',
    exercices: [...prepIds(p, 4, 'co'), ...prepIds(p, 4, 'ce'), ...prepIds(p, 2, 'pe'), ...prepIds(p, 3, 'po')],
  }
}

/** Préparation A1 (format DELF) : une série par sujet de dialogue simulé. */
function prepA1Series(n: number, nbCo: number): TcfSerie[] {
  const p = `tcf-a1p-s${n}-`
  const range = (k: number, c: string) => prepIds(p, k, c)
  return PREP_A1_SUJETS_ORAL.map(([v, sujet], i) => ({
    id: i === 0 ? `a1p-serie-${n}` : `a1p-serie-${n}-sujet-${i + 1}`,
    label: `Préparation A1 · série ${n} (oral : ${sujet})`,
    niveau: 'A0-A1',
    exercices: [...range(nbCo, 'co'), ...range(4, 'ce'), ...range(2, 'pe'), `${p}po-1`, `${p}po-2`, `${p}po-3${v}`],
  }))
}

export const TCF_SERIES: readonly TcfSerie[] = [
  {
    id: 'a1j-serie-1',
    label: 'Test blanc A1 Junior · série 1',
    niveau: 'A0-A1',
    exercices: [
      'tcf-a1j-s1-co-1',
      'tcf-a1j-s1-co-2',
      'tcf-a1j-s1-co-3',
      'tcf-a1j-s1-co-4',
      'tcf-a1j-s1-ce-1',
      'tcf-a1j-s1-ce-2',
      'tcf-a1j-s1-ce-3',
      'tcf-a1j-s1-ce-4',
      'tcf-a1j-s1-pe-1',
      'tcf-a1j-s1-pe-2',
      'tcf-a1j-s1-po-1',
      'tcf-a1j-s1-po-2',
      'tcf-a1j-s1-po-3',
    ],
  },
  {
    id: 'a1j-serie-2',
    label: 'Test blanc A1 Junior · série 2',
    niveau: 'A0-A1',
    exercices: [
      'tcf-a1j-s2-co-1',
      'tcf-a1j-s2-co-2',
      'tcf-a1j-s2-co-3',
      'tcf-a1j-s2-co-4',
      'tcf-a1j-s2-co-5',
      'tcf-a1j-s2-ce-1',
      'tcf-a1j-s2-ce-2',
      'tcf-a1j-s2-ce-3',
      'tcf-a1j-s2-ce-4',
      'tcf-a1j-s2-pe-1',
      'tcf-a1j-s2-pe-2',
      'tcf-a1j-s2-po-1',
      'tcf-a1j-s2-po-2',
      'tcf-a1j-s2-po-3',
    ],
  },
  {
    id: 'a1j-serie-3',
    label: 'Test blanc A1 Junior · série 3',
    niveau: 'A0-A1',
    exercices: [
      'tcf-a1j-s3-co-1',
      'tcf-a1j-s3-co-2',
      'tcf-a1j-s3-co-3',
      'tcf-a1j-s3-co-4',
      'tcf-a1j-s3-co-5',
      'tcf-a1j-s3-ce-1',
      'tcf-a1j-s3-ce-2',
      'tcf-a1j-s3-ce-3',
      'tcf-a1j-s3-ce-4',
      'tcf-a1j-s3-pe-1',
      'tcf-a1j-s3-pe-2',
      'tcf-a1j-s3-po-1',
      'tcf-a1j-s3-po-2',
      'tcf-a1j-s3-po-3',
    ],
  },
  {
    id: 'a1-serie-1',
    label: 'Test blanc A1 · série 1',
    niveau: 'A0-A1',
    exercices: [
      'tcf-a1-s1-co-1',
      'tcf-a1-s1-co-2',
      'tcf-a1-s1-co-3',
      'tcf-a1-s1-co-4',
      'tcf-a1-s1-co-5',
      'tcf-a1-s1-ce-1',
      'tcf-a1-s1-ce-2',
      'tcf-a1-s1-ce-3',
      'tcf-a1-s1-ce-4',
      'tcf-a1-s1-pe-1',
      'tcf-a1-s1-pe-2',
      'tcf-a1-s1-pe-3',
      'tcf-a1-s1-po-1',
      'tcf-a1-s1-po-2',
      'tcf-a1-s1-po-3',
    ],
  },
  {
    id: 'a1-serie-1-variante',
    label: 'Test blanc A1 · série 1 (oral variante : chez le docteur)',
    niveau: 'A0-A1',
    exercices: [
      'tcf-a1-s1-co-1',
      'tcf-a1-s1-co-2',
      'tcf-a1-s1-co-3',
      'tcf-a1-s1-co-4',
      'tcf-a1-s1-co-5',
      'tcf-a1-s1-ce-1',
      'tcf-a1-s1-ce-2',
      'tcf-a1-s1-ce-3',
      'tcf-a1-s1-ce-4',
      'tcf-a1-s1-pe-1',
      'tcf-a1-s1-pe-2',
      'tcf-a1-s1-pe-3',
      'tcf-a1-s1-po-1',
      'tcf-a1-s1-po-2b',
      'tcf-a1-s1-po-3b',
    ],
  },
  {
    id: 'a1-serie-2',
    label: 'Test blanc A1 · série 2',
    niveau: 'A0-A1',
    exercices: [
      'tcf-a1-s2-co-1',
      'tcf-a1-s2-co-2',
      'tcf-a1-s2-co-3',
      'tcf-a1-s2-co-4',
      'tcf-a1-s2-co-5',
      'tcf-a1-s2-ce-1',
      'tcf-a1-s2-ce-2',
      'tcf-a1-s2-ce-3',
      'tcf-a1-s2-ce-4',
      'tcf-a1-s2-pe-1',
      'tcf-a1-s2-pe-2',
      'tcf-a1-s2-pe-3',
      'tcf-a1-s2-po-1',
      'tcf-a1-s2-po-2',
      'tcf-a1-s2-po-3',
    ],
  },
  {
    id: 'a1-serie-2-variante',
    label: 'Test blanc A1 · série 2 (oral variante : magasin de sport)',
    niveau: 'A0-A1',
    exercices: [
      'tcf-a1-s2-co-1',
      'tcf-a1-s2-co-2',
      'tcf-a1-s2-co-3',
      'tcf-a1-s2-co-4',
      'tcf-a1-s2-co-5',
      'tcf-a1-s2-ce-1',
      'tcf-a1-s2-ce-2',
      'tcf-a1-s2-ce-3',
      'tcf-a1-s2-ce-4',
      'tcf-a1-s2-pe-1',
      'tcf-a1-s2-pe-2',
      'tcf-a1-s2-pe-3',
      'tcf-a1-s2-po-1',
      'tcf-a1-s2-po-2b',
      'tcf-a1-s2-po-3b',
    ],
  },
  {
    id: 'a1-serie-3',
    label: 'Test blanc A1 · série 3',
    niveau: 'A0-A1',
    exercices: [
      'tcf-a1-s3-co-1',
      'tcf-a1-s3-co-2',
      'tcf-a1-s3-co-3',
      'tcf-a1-s3-co-4',
      'tcf-a1-s3-co-5',
      'tcf-a1-s3-ce-1',
      'tcf-a1-s3-ce-2',
      'tcf-a1-s3-ce-3',
      'tcf-a1-s3-ce-4',
      'tcf-a1-s3-pe-1',
      'tcf-a1-s3-pe-2',
      'tcf-a1-s3-po-1',
      'tcf-a1-s3-po-2',
      'tcf-a1-s3-po-3',
    ],
  },
  {
    id: 'a1-serie-4',
    label: 'Test blanc A1 · série 4',
    niveau: 'A0-A1',
    exercices: [
      'tcf-a1-s4-co-1',
      'tcf-a1-s4-co-2',
      'tcf-a1-s4-co-3',
      'tcf-a1-s4-co-4',
      'tcf-a1-s4-ce-1',
      'tcf-a1-s4-ce-2',
      'tcf-a1-s4-ce-3',
      'tcf-a1-s4-ce-4',
      'tcf-a1-s4-pe-1',
      'tcf-a1-s4-pe-2',
      'tcf-a1-s4-po-1',
      'tcf-a1-s4-po-2',
      'tcf-a1-s4-po-3',
    ],
  },
  {
    id: 'a2j-serie-1',
    label: 'Test blanc A2 Junior · série 1',
    niveau: 'A1-A2',
    exercices: [
      'tcf-a2j-s1-co-1',
      'tcf-a2j-s1-co-2',
      'tcf-a2j-s1-co-3',
      'tcf-a2j-s1-co-4',
      'tcf-a2j-s1-ce-1',
      'tcf-a2j-s1-ce-2',
      'tcf-a2j-s1-ce-3',
      'tcf-a2j-s1-ce-4',
      'tcf-a2j-s1-pe-1',
      'tcf-a2j-s1-pe-2',
      'tcf-a2j-s1-po-1',
      'tcf-a2j-s1-po-2',
      'tcf-a2j-s1-po-3',
    ],
  },
  {
    id: 'a2j-serie-2',
    label: 'Test blanc A2 Junior · série 2',
    niveau: 'A1-A2',
    exercices: [
      'tcf-a2j-s2-co-1',
      'tcf-a2j-s2-co-2',
      'tcf-a2j-s2-co-3',
      'tcf-a2j-s2-co-4',
      'tcf-a2j-s2-ce-1',
      'tcf-a2j-s2-ce-2',
      'tcf-a2j-s2-ce-3',
      'tcf-a2j-s2-ce-4',
      'tcf-a2j-s2-pe-1',
      'tcf-a2j-s2-pe-2',
      'tcf-a2j-s2-po-1',
      'tcf-a2j-s2-po-2',
      'tcf-a2j-s2-po-3',
    ],
  },
  ...(
    [
      ['a2-serie-1', 'banque', ''],
      ['a2-serie-1-sujet-2', 'médiathèque', 'b'],
      ['a2-serie-1-sujet-3', 'poste', 'c'],
    ] as const
  ).map(([id, sujet, v]) => ({
    id,
    label: `Test blanc A2 · série 1 (oral : ${sujet})`,
    niveau: 'A1-A2' as const,
    exercices: [
      'tcf-a2-s1-co-1',
      'tcf-a2-s1-co-2',
      'tcf-a2-s1-co-3',
      'tcf-a2-s1-co-4',
      'tcf-a2-s1-ce-1',
      'tcf-a2-s1-ce-2',
      'tcf-a2-s1-ce-3',
      'tcf-a2-s1-ce-4',
      'tcf-a2-s1-pe-1',
      'tcf-a2-s1-pe-2',
      'tcf-a2-s1-pe-3',
      'tcf-a2-s1-po-1',
      `tcf-a2-s1-po-2${v}`,
      `tcf-a2-s1-po-3${v}`,
    ],
  })),
  ...prepA1Series(3, 4),
  ...prepA1Series(4, 5),
  prepA2Serie(1),
  prepA2Serie(2),
]
