/** Banques Soutien FR — voyelles (livret CSC). Images résolues via vocabulaire. */
import type { VowelId } from '../lecture-banks'

export type SoutienScramble = { sentence: string; word: string; letters: string }
/** Mot à compléter : Un/Une + [before]____[after] → word (syllabe = consonant+voyelle). */
export type SoutienComplete = {
  article: 'Un' | 'Une'
  word: string
  /** Préfixe affiché avant le trait (ex. « aspi »). */
  before: string
  /** Syllabe manquante (corrigé). */
  blank: string
  /** Suite du mot après le trait (ex. « teur », « teau »). */
  after: string
}
export type SoutienDet = { blank: string; rest: string; sentence: string }
export type SoutienAudio = { word: string; other: string }
export type SoutienCompound = { parts: readonly [string, string]; word: string }
/** Mot + découpe syllabique correcte (type 8). */
export type SoutienSyllableItem = { word: string; parts: readonly string[] }

export type SoutienVowelBank = {
  id: VowelId
  topic: string
  letterUpper: string
  letterLower: string
  sound: string
  label: string
  graphemes: readonly string[]
  words: readonly string[]
  syllables: readonly string[]
  compounds: readonly SoutienCompound[]
  completes: readonly SoutienComplete[]
  scrambles: readonly SoutienScramble[]
  determinants: readonly SoutienDet[]
  countPhrases: readonly string[]
  readPhrases: readonly string[]
  audioPairs: readonly SoutienAudio[]
  syllableItems: readonly SoutienSyllableItem[]
  orderSentences: readonly (readonly string[])[]
}

export const SOUTIEN_VOWEL_BANKS: readonly SoutienVowelBank[] = [
  {
    id: 'a',
    topic: 'soutien-a',
    letterUpper: 'A',
    letterLower: 'a',
    sound: '/a/',
    label: 'Voyelle A',
    graphemes: ["a", "à", "â"],
    words: ["bateau", "café", "avion", "arbre", "abricot", "quatre", "rat", "papier", "abeille", "arrosoir", "parapluie", "gâteau", "ananas", "datte", "vase", "âne"],
    syllables: ["ta", "ar", "la", "pa", "va", "ca", "sa", "fa", "ga", "ab", "papa", "kal", "vac", "lab", "arab", "lap", "nab", "bar", "zag", "jata", "ba", "ra", "da", "ga", "pa", "pa", "af", "av", "na", "ma"],
    compounds: [
      { parts: ['pa', 'pier'] as const, word: 'papier' },
      { parts: ['para', 'pluie'] as const, word: 'parapluie' },
      { parts: ['ab', 'eille'] as const, word: 'abeille' },
      { parts: ['gâ', 'teau'] as const, word: 'gâteau' },
      { parts: ['ana', 'nas'] as const, word: 'ananas' },
      { parts: ['va', 'se'] as const, word: 'vase' },
      { parts: ['abri', 'cot'] as const, word: 'abricot' },
      { parts: ['ba', 'teau'] as const, word: 'bateau' },
      { parts: ['ca', 'fé'] as const, word: 'café' },
      { parts: ['a', 'vion'] as const, word: 'avion' },
    ],
    completes: [
      { article: 'Un', word: 'bateau', before: '', blank: 'ba', after: 'teau' },
      { article: 'Un', word: 'animal', before: '', blank: 'an', after: 'imal' },
      { article: 'Un', word: 'arbre', before: '', blank: 'ar', after: 'bre' },
      { article: 'Une', word: 'famille', before: '', blank: 'fa', after: 'mille' },
      { article: 'Un', word: 'vase', before: '', blank: 'va', after: 'se' },
      { article: 'Un', word: 'ballon', before: '', blank: 'ba', after: 'llon' },
      { article: 'Une', word: 'datte', before: '', blank: 'da', after: 'tte' },
      { article: 'Un', word: 'aspirateur', before: 'aspi', blank: 'ra', after: 'teur' },
      { article: 'Un', word: 'avion', before: '', blank: 'av', after: 'ion' },
      { article: 'Une', word: 'allumette', before: '', blank: 'al', after: 'lumette' },
    ],
    scrambles: [
      { sentence: 'Le chat noir marche près de la plage', word: 'plage', letters: 'GLPEA' },
      { sentence: 'La girafe mange des feuilles de l’arbre', word: 'girafe', letters: 'FAREGI' },
      { sentence: 'Les flamants roses sont très calmes', word: 'flamants', letters: 'MAATNSLF' },
      { sentence: 'Les lapins sautent dans le jardin', word: 'lapins', letters: 'IANLPS' },
      { sentence: 'Anna achète des bananes au marché', word: 'bananes', letters: 'ENANSBA' },
      { sentence: 'Mon papa nage à la piscine de Martigny', word: 'nage', letters: 'ENGA' },
      { sentence: 'La salade est dans le panier de maman', word: 'salade', letters: 'ASDEAL' },
    ],
    determinants: [
      { blank: 'Le', rest: 'bateau avance sur le lac.', sentence: 'Le bateau avance sur le lac.' },
      { blank: 'Les', rest: 'animaux jouent avec le ballon.', sentence: 'Les animaux jouent avec le ballon.' },
      { blank: 'L’', rest: 'avion vole au-dessus de l’ arbre.', sentence: 'L’ avion vole au-dessus de l’ arbre.' },
      { blank: 'La', rest: 'famille de Sara mange une salade.', sentence: 'La famille de Sara mange une salade.' },
      { blank: 'le', rest: 'Je pose le vase et l’allumette sur une table.', sentence: 'Je pose le vase et l’allumette sur une table.' },
      { blank: 'L’', rest: 'aspirateur est dans un placard.', sentence: 'L’ aspirateur est dans un placard.' },
      { blank: 'La', rest: 'datte est dans mon assiette.', sentence: 'La datte est dans mon assiette.' },
      { blank: 'le', rest: 'Je n’arrive pas à allumer les allumettes.', sentence: 'Je n’arrive pas à allumer les allumettes.' },
    ],
    countPhrases: ["Clara habite dans une maison à côté de l’école.", "Sous un arbre il y a des animaux : des chiens et des chats.", "Ils achètent des légumes frais pour préparer le repas.", "Isabelle lit un roman à haute voix.", "Ma girafe mange des feuilles et boit de l’eau près du lac.", "Papa va prendre la chatte et son chaton."],
    readPhrases: ["Je m'appelle Anastasia.", "Le chat dort sur le canapé.", "Maman prépare une salade.", "Ma famille chante à la maison.", "J'achète des carottes et des patates.", "Le samedi, je vais au marché.", "Alicia joue au football avec mes amis.", "Adna va au théâtre regarder un spectacle.", "J'aime les animaux.", "Nous allons au parc avec Max.", "Je suis l'amie d'Alexandre.", "Monica va au cinéma.", "Sara lave sa voiture.", "Marc un sac à la main.", "Le papa va à la gare.", "Le garçon joue avec sa balle."],
    audioPairs: [
      { word: 'chat', other: 'abeille' },
      { word: 'abricot', other: 'girafe' },
      { word: 'girafe', other: 'salade' },
      { word: 'animal', other: 'chat' },
      { word: 'abeille', other: 'bateau' },
      { word: 'bateau', other: 'animal' },
      { word: 'lapin', other: 'abricot' },
      { word: 'salade', other: 'lapin' },
    ],
    syllableItems: [
      { word: 'Plante', parts: ['Plan', 'te'] },
      { word: 'Patin', parts: ['Pa', 'tin'] },
      { word: 'Caméra', parts: ['Ca', 'mé', 'ra'] },
      { word: 'Château', parts: ['Châ', 'teau'] },
      { word: 'Matelas', parts: ['Ma', 'te', 'las'] },
      { word: 'Chandelier', parts: ['Chan', 'de', 'lier'] },
      { word: 'Magasin', parts: ['Ma', 'ga', 'sin'] },
      { word: 'Caneton', parts: ['Ca', 'ne', 'ton'] },
      { word: 'Papillon', parts: ['Pa', 'pil', 'lon'] },
      { word: 'Chanteuse', parts: ['Chan', 'teuse'] },
      { word: 'Automne', parts: ['Au', 'tomne'] },
      { word: 'Ordinateur', parts: ['Or', 'di', 'na', 'teur'] },
    ],
    orderSentences: [
      ["La", "classe", "est", "pleine."],
      ["Mario", "part", "en", "vacances."],
      ["Il", "y", "a", "quatre", "garçons."],
      ["L’", "adulte", "achète", "une", "salade."],
      ["Alona", "a", "des", "chats", "à", "la", "maison."],
      ["Mon", "ami", "s’appelle", "Marc."],
    ],
  },
  {
    id: 'o',
    topic: 'soutien-o',
    letterUpper: 'O',
    letterLower: 'o',
    sound: '/o/',
    label: 'Voyelle O',
    graphemes: ["o", "ô"],
    words: ["tomate", "loto", "numéro", "robot", "omelette", "vélo", "orange", "orage", "ordinateur", "collier", "bonnet", "ordures", "cochon", "oreille", "koala", "olive"],
    syllables: ["mo", "no", "to", "po", "vo", "ob", "co", "or", "ov", "jo", "jog", "gob", "lop", "zo", "poq", "odo", "toto", "dol", "polo", "fobo", "qo", "ro", "oc", "od", "op", "go", "ko", "ol", "ot", "po"],
    compounds: [
      { parts: ['to', 'mate'] as const, word: 'tomate' },
      { parts: ['lo', 'to'] as const, word: 'loto' },
      { parts: ['nu', 'méro'] as const, word: 'numéro' },
      { parts: ['ro', 'bot'] as const, word: 'robot' },
      { parts: ['o', 'melette'] as const, word: 'omelette' },
      { parts: ['vé', 'lo'] as const, word: 'vélo' },
      { parts: ['o', 'range'] as const, word: 'orange' },
      { parts: ['o', 'rage'] as const, word: 'orage' },
      { parts: ['ko', 'ala'] as const, word: 'koala' },
      { parts: ['o', 'live'] as const, word: 'olive' },
    ],
    completes: [
      { article: 'Un', word: 'piano', before: '', blank: 'pi', after: 'ano' },
      { article: 'Une', word: 'otarie', before: '', blank: 'o', after: 'tarie' },
      { article: 'Un', word: 'cobra', before: '', blank: 'co', after: 'bra' },
      { article: 'Un', word: 'fromage', before: 'fro', blank: 'ma', after: 'ge' },
      { article: 'Une', word: 'moto', before: '', blank: 'mo', after: 'to' },
      { article: 'Un', word: 'donut', before: '', blank: 'do', after: 'nut' },
      { article: 'Une', word: 'robe', before: '', blank: 'ro', after: 'be' },
      { article: 'Une', word: 'coccinelle', before: '', blank: 'co', after: 'ccinelle' },
      { article: 'Un', word: 'flocon', before: '', blank: 'flo', after: 'con' },
      { article: 'Un', word: 'losange', before: '', blank: 'lo', after: 'sange' },
    ],
    scrambles: [
      { sentence: 'Le soleil brille sur le robot', word: 'soleil', letters: 'LEIOLS' },
      { sentence: 'Mes bottes sont dans le coffre', word: 'bottes', letters: 'TOBTES' },
      { sentence: 'La corde est autour du poteau', word: 'corde', letters: 'EDRCO' },
      { sentence: 'La tortue dort sur son dos', word: 'tortue', letters: 'TURTOE' },
      { sentence: 'L’arrosoir est à côté de la moto', word: 'arrosoir', letters: 'RROIOSAR' },
      { sentence: 'Les carottes sont dans le pot', word: 'carottes', letters: 'TCAORTES' },
      { sentence: 'Le violon est posé sur le sol', word: 'violon', letters: 'OLOVIN' },
    ],
    determinants: [
      { blank: 'La', rest: 'moto est devant la maison.', sentence: 'La moto est devant la maison.' },
      { blank: 'le', rest: 'Elle coupe le fromage en gros morceaux.', sentence: 'Elle coupe le fromage en gros morceaux.' },
      { blank: 'La', rest: 'coccinelle est sur une tomate.', sentence: 'La coccinelle est sur une tomate.' },
      { blank: 'le', rest: 'L’otarie nage dans l’océan.', sentence: 'L’otarie nage dans l’océan.' },
      { blank: 'Les', rest: 'donuts au chocolat sont sur la table.', sentence: 'Les donuts au chocolat sont sur la table.' },
      { blank: 'le', rest: 'Je pose le piano près du vélo.', sentence: 'Je pose le piano près du vélo.' },
      { blank: 'Le', rest: 'cobra dort dans son abri.', sentence: 'Le cobra dort dans son abri.' },
      { blank: 'Les', rest: 'losanges sont de couleur rose.', sentence: 'Les losanges sont de couleur rose.' },
    ],
    countPhrases: ["Le gorille mange une pomme dans le zoo.", "Le cochon rose porte un bonnet dans son enclos.", "Le poisson orange tourne autour du rocher au fond de l’eau.", "Le coq picore des graines près du portail.", "Le docteur fait tomber les dominos sur le sol.", "Le motard prend des photos de son vélo."],
    readPhrases: ["Après le loto, Tom boit un soda et fait dodo.", "Le parasol est posé près du vélo.", "Le métro ne passe pas à Vétroz.", "Paul porte le javelot jusqu’au rocher.", "L’homme va à l’hôpital avec sa moto.", "Je mets ma culotte et mon maillot.", "Le pilote joue du piano avant le vol.", "Le crocodile dort au bord de l’eau.", "Hugo vole des brocolis et des abricots.", "La brosse est dans le bocal.", "Rosa croque le chocolat devant le zoo.", "Le koala mange du  fromage orange.", "Le rocher rose est au bord de l’océan.", "L’otarie montre son oreille au docteur.", "Le lavabo n’est pas propre.", "Le professeur donne une limonade à Noé"],
    audioPairs: [
      { word: 'coffre', other: 'avocate' },
      { word: 'boxeur', other: 'corbeau' },
      { word: 'tomate', other: 'boxeur' },
      { word: 'bottes', other: 'bottes' },
      { word: 'avocate', other: 'tomate' },
      { word: 'corbeau', other: 'parasol' },
      { word: 'flocon', other: 'coffre' },
      { word: 'parasol', other: 'flocon' },
    ],
    syllableItems: [
      { word: 'Abricot', parts: ['A', 'bri', 'cot'] },
      { word: 'Boxe', parts: ['Boxe'] },
      { word: 'Brocoli', parts: ['Bro', 'co', 'li'] },
      { word: 'Chorizo', parts: ['Cho', 'ri', 'zo'] },
      { word: 'Forêt', parts: ['Fo', 'rêt'] },
      { word: 'Serveuse', parts: ['Ser', 'veuse'] },
      { word: 'Homard', parts: ['Ho', 'mard'] },
      { word: 'Pantalon', parts: ['Pan', 'ta', 'lon'] },
      { word: 'Colibri', parts: ['Co', 'li', 'bri'] },
      { word: 'Échalote', parts: ['É', 'cha', 'lote'] },
      { word: 'Judo', parts: ['Ju', 'do'] },
      { word: 'Lavabo', parts: ['La', 'va', 'bo'] },
    ],
    orderSentences: [
      ["Le", "cochon", "dort", "dans", "son", "abri."],
      ["Le", "robot", "est", "sur", "la", "table."],
      ["Mon", "vélo", "est", "orange."],
      ["Le", "soleil", "brille", "fort."],
      ["Elle", "pose", "son", "chapeau."],
      ["Le", "koala", "mange", "des", "feuilles."],
    ],
  },
  {
    id: 'i',
    topic: 'soutien-i',
    letterUpper: 'I',
    letterLower: 'i',
    sound: '/i/',
    label: 'Voyelle I',
    graphemes: ["i", "î", "ï"],
    words: ["ami", "piment", "miroir", "bijou", "basilic", "miel", "riz", "nid", "chemise", "limace", "brocoli", "cahier", "hiver", "fourmi", "bille", "guitare"],
    syllables: ["mi", "ni", "ti", "pi", "iv", "ib", "ci", "ir", "li", "si", "qid", "nib", "itit", "pic", "vir", "midi", "fig", "fidi", "siti", "sis", "ki", "pi", "il", "ni", "ti", "ri", "is", "mi", "ip", "li"],
    compounds: [
      { parts: ['pi', 'ment'] as const, word: 'piment' },
      { parts: ['mi', 'roir'] as const, word: 'miroir' },
      { parts: ['bi', 'jou'] as const, word: 'bijou' },
      { parts: ['ba', 'silic'] as const, word: 'basilic' },
      { parts: ['mi', 'el'] as const, word: 'miel' },
      { parts: ['che', 'mise'] as const, word: 'chemise' },
      { parts: ['li', 'mace'] as const, word: 'limace' },
      { parts: ['bro', 'coli'] as const, word: 'brocoli' },
    ],
    completes: [
      { article: 'Un', word: 'tigre', before: '', blank: 'ti', after: 'gre' },
      { article: 'Un', word: 'briquet', before: '', blank: 'bri', after: 'quet' },
      { article: 'Un', word: 'cookie', before: '', blank: 'coo', after: 'kie' },
      { article: 'Un', word: 'canari', before: '', blank: 'ca', after: 'nari' },
      { article: 'Un', word: 'kiwi', before: '', blank: 'ki', after: 'wi' },
      { article: 'Un', word: 'épinard', before: '', blank: 'épi', after: 'nard' },
      { article: 'Un', word: 'citron', before: '', blank: 'ci', after: 'tron' },
      { article: 'Une', word: 'cerise', before: '', blank: 'ce', after: 'rise' },
      { article: 'Une', word: 'viande', before: '', blank: 'vi', after: 'ande' },
      { article: 'Un', word: 'hérisson', before: '', blank: 'hé', after: 'risson' },
    ],
    scrambles: [
      { sentence: 'Le biberon est bien rempli', word: 'biberon', letters: 'RBOINBE' },
      { sentence: 'Melina a mis une image sur son ordi', word: 'image', letters: 'GIMAE' },
      { sentence: 'Les cerises sont sous le cerisier', word: 'cerisier', letters: 'ERICSERI' },
      { sentence: 'Cécile a choisi le litchi', word: 'litchi', letters: 'HILCIT' },
      { sentence: 'Qui descend les escaliers avec mon ami', word: 'escaliers', letters: 'LESCRIASE' },
      { sentence: 'Le navire de Lisa avance vite', word: 'navire', letters: 'RAVINE' },
      { sentence: 'Le hibou crie dans la nuit', word: 'hibou', letters: 'OHIUB' },
    ],
    determinants: [
      { blank: 'La', rest: 'petite fille mange la cerise.', sentence: 'La petite fille mange la cerise.' },
      { blank: 'L’', rest: 'hérisson finit le citron.', sentence: 'L’ hérisson finit le citron.' },
      { blank: 'Les', rest: 'cuisiniers coupent le kiwi.', sentence: 'Les cuisiniers coupent le kiwi.' },
      { blank: 'Le', rest: 'tigre dévore la viande.', sentence: 'Le tigre dévore la viande.' },
      { blank: 'Le', rest: 'canari picore l’ épinard.', sentence: 'Le canari picore l’ épinard.' },
      { blank: 'le', rest: 'Emilie partage le cookie avec son ami.', sentence: 'Emilie partage le cookie avec son ami.' },
      { blank: 'le', rest: 'Lili n’aime pas le briquet gris.', sentence: 'Lili n’aime pas le briquet gris.' },
      { blank: 'La', rest: 'jolie girafe visite les îles de Sion.', sentence: 'La jolie girafe visite les îles de Sion.' },
    ],
    countPhrases: ["La fille visite la ville avec son ami.", "Le piano joue une jolie mélodie.", "Elise met une chemise grise dans sa valise.", "Qui a mis le crayon ici ?", "La vitrine est remplie de figurines d’animaux.", "Michel n’a pas fini son bol de riz."],
    readPhrases: ["Elle fait un exercice difficile.", "Lili choisit une jolie tulipe.", "Le cuisinier prépare du riz et des épinards.", "J’admire les photographies.", "Iris lit un livre illustré.", "La jolie fille colorie une image.", "Dimitri finit son dîner dans huit minutes.", "La petite souris grignote du riz.", "Il choisit des lilas et des jonquilles", "Nina a mis une liste sur la vitre", "Le pirate visite une île.", "La souris file dans la cuisine.", "Mimi porte un costume gris.", "Emilie dessine une pie et un dinosaure.", "La rapide fourmi transporte des sucreries.", "Rémi est timide quand il imite le tigre."],
    audioPairs: [
      { word: 'zipper', other: 'panier' },
      { word: 'tennis', other: 'surligneur' },
      { word: 'penderie', other: 'zipper' },
      { word: 'panier', other: 'tennis' },
      { word: 'surligneur', other: 'vitrine' },
      { word: 'vitrine', other: 'penderie' },
      { word: 'soulier', other: 'grizzly' },
      { word: 'grizzly', other: 'soulier' },
    ],
    syllableItems: [
      { word: 'Artichaut', parts: ['Ar', 'ti', 'chaut'] },
      { word: 'Mixeur', parts: ['Mi', 'xeur'] },
      { word: 'Balai', parts: ['Ba', 'lai'] },
      { word: 'glacier', parts: ['gla', 'cier'] },
      { word: 'moustique', parts: ['mous', 'tique'] },
      { word: 'clarinette', parts: ['cla', 'ri', 'nette'] },
      { word: 'cassis', parts: ['cas', 'sis'] },
      { word: 'imprimante', parts: ['im', 'pri', 'mante'] },
      { word: 'kangourou', parts: ['kan', 'gou', 'rou'] },
      { word: 'dentifrice', parts: ['den', 'ti', 'frice'] },
      { word: 'frite', parts: ['fri', 'te'] },
      { word: 'chien', parts: ['chien'] },
    ],
    orderSentences: [
      ["Nina", "a", "mis", "une", "liste", "sur", "la", "vitre."],
      ["Michel", "n’a", "pas", "fini", "son", "bol", "de", "riz."],
      ["La", "fille", "visite", "la", "ville", "avec", "son", "ami."],
      ["Qui", "a", "mis", "le", "crayon", "ici", "?"],
      ["Emilie", "partage", "le", "cookie", "avec", "son", "ami."],
      ["L’", "hérisson", "finit", "le", "citron."],
    ],
  },
  {
    id: 'u',
    topic: 'soutien-u',
    letterUpper: 'U',
    letterLower: 'u',
    sound: '/y/',
    label: 'Voyelle U',
    graphemes: ["u", "û"],
    words: ["alumette", "voiture", "jumelles", "laitue", "jus", "buffet", "usine", "flûte", "fruit", "ambulance", "zébu", "jupe", "chaussure", "tulipe", "bus", "légume"],
    syllables: ["mu", "nu", "tu", "pu", "vu", "bu", "cu", "ru", "lu", "su", "qud", "nub", "utut", "pup", "vur", "mudu", "fug", "fudu", "sutu", "muc", "um", "up", "ul", "nu", "tu", "ru", "us", "mu", "uq", "lu"],
    compounds: [
      { parts: ['a', 'lumette'] as const, word: 'alumette' },
      { parts: ['voi', 'ture'] as const, word: 'voiture' },
      { parts: ['ju', 'melles'] as const, word: 'jumelles' },
      { parts: ['lai', 'tue'] as const, word: 'laitue' },
      { parts: ['buf', 'fet'] as const, word: 'buffet' },
      { parts: ['u', 'sine'] as const, word: 'usine' },
      { parts: ['tu', 'lipe'] as const, word: 'tulipe' },
      { parts: ['chaus', 'sure'] as const, word: 'chaussure' },
      { parts: ['lé', 'gume'] as const, word: 'légume' },
      { parts: ['am', 'bulance'] as const, word: 'ambulance' },
    ],
    completes: [
      { article: 'Un', word: 'uniforme', before: '', blank: 'u', after: 'niforme' },
      { article: 'Une', word: 'sucette', before: '', blank: 'su', after: 'cette' },
      { article: 'Un', word: 'biscuit', before: '', blank: 'bis', after: 'cuit' },
      { article: 'Une', word: 'prune', before: '', blank: 'pru', after: 'ne' },
      { article: 'Un', word: 'nuage', before: '', blank: 'nu', after: 'age' },
      { article: 'Une', word: 'huile', before: '', blank: 'hui', after: 'le' },
      { article: 'Une', word: 'plume', before: '', blank: 'plu', after: 'me' },
      { article: 'Un', word: 'muguet', before: '', blank: 'mu', after: 'guet' },
      { article: 'Une', word: 'luciole', before: '', blank: 'lu', after: 'ciole' },
      { article: 'Une', word: 'peinture', before: 'pein', blank: 'tu', after: 're' },
    ],
    scrambles: [
      { sentence: 'La dune surplombe un petit refuge', word: 'dune', letters: 'NDUE' },
      { sentence: 'Le minuscule walrus nage sous la brume', word: 'walrus', letters: 'SUWALR' },
      { sentence: 'Un ruisseau murmure dans la verdure', word: 'ruisseau', letters: 'SEARUSIU' },
      { sentence: 'La méduse est curieuse et rusée', word: 'méduse', letters: 'SDEUMÉ' },
      { sentence: 'Les joueurs musclés de rugby courent sous la pluie', word: 'rugby', letters: 'GBYUR' },
      { sentence: 'Mon pull turquoise est unique', word: 'pull', letters: 'LLPU' },
      { sentence: 'Le musicien joue du tuba dans la rue', word: 'musicien', letters: 'IUSCINEM' },
    ],
    determinants: [
      { blank: 'le', rest: 'Lenuage obscur couvre la lune.', sentence: 'Lenuage obscur couvre la lune.' },
      { blank: 'le', rest: 'Lesprunes mûres sont dans le fruitier.', sentence: 'Lesprunes mûres sont dans le fruitier.' },
      { blank: 'le', rest: 'Lemuguet parfumé pousse dans la nature.', sentence: 'Lemuguet parfumé pousse dans la nature.' },
      { blank: 'le', rest: 'L’uniforme écru est devenu trop court.', sentence: 'L’uniforme écru est devenu trop court.' },
      { blank: 'le', rest: 'Laplume brune tombe sur le mur.', sentence: 'Laplume brune tombe sur le mur.' },
      { blank: 'le', rest: 'Lesbiscuits sucrés sont sur le bureau.', sentence: 'Lesbiscuits sucrés sont sur le bureau.' },
      { blank: 'le', rest: 'Lapeinture de la  sucette brille dans la nuit', sentence: 'Lapeinture de la  sucette brille dans la nuit' },
      { blank: 'le', rest: 'L’huile pure est utile en cuisine.', sentence: 'L’huile pure est utile en cuisine.' },
    ],
    countPhrases: ["La fusée monte au-dessus des nuages.", "Le renard a trouvé une plume brune.", "La musique résonne dans la rue.", "Une tortue avance doucement sous la pluie.", "Le juge écoute le début du procès.", "Le curé discute avec plusieurs habitants du village."],
    readPhrases: ["Ursula porte une jupe sur mesure.", "Le début du film surprend le public.", "Le costume du danseur est de couleur prune.", "Luc ajoute du sucre dans son jus.", "La bûche brûle dans la cheminée.", "Un curieux étudiant observe la plume tomber.", "Julie écoute de la musique dans sa voiture.", "Il cherche une solution pour aller sur la lune.", "Les cuisiniers épluchent des légumes.", "La pluie tombe sur les tuiles.", "Le futur médecin étudie beaucoup.", "Une tortue se réfugie sous un buisson.", "Au menu, il y a des fruits et des légumes", "Le bus passe dans un tunnel.", "La lumière du soleil illumine la clôture.", "Lucie ne met pas sa couverture la nuit."],
    audioPairs: [
      { word: 'huitre', other: 'lunette' },
      { word: 'calculatrice', other: 'huitre' },
      { word: 'bulldozer', other: 'calculatrice' },
      { word: 'bureau', other: 'juge' },
      { word: 'libellule', other: 'cuisinière' },
      { word: 'cuisinière', other: 'libellule' },
      { word: 'lunette', other: 'bureau' },
      { word: 'juge', other: 'bulldozer' },
    ],
    syllableItems: [
      { word: 'agriculteur', parts: ['a', 'gri', 'cul', 'teur'] },
      { word: 'peluche', parts: ['pe', 'luche'] },
      { word: 'balai', parts: ['ba', 'lai'] },
      { word: 'ciseaux', parts: ['ci', 'seaux'] },
      { word: 'surligneur', parts: ['sur', 'li', 'gneur'] },
      { word: 'clarinette', parts: ['cla', 'ri', 'nette'] },
      { word: 'gazoduc', parts: ['ga', 'zo', 'duc'] },
      { word: 'écureuil', parts: ['é', 'cu', 'reuil'] },
      { word: 'tortue', parts: ['tor', 'tue'] },
      { word: 'culotte', parts: ['cu', 'lotte'] },
      { word: 'hirondelle', parts: ['hi', 'ron', 'delle'] },
      { word: 'fusée', parts: ['fu', 'sée'] },
    ],
    orderSentences: [
      ["Luc", "ajoute", "du", "sucre", "dans", "son", "jus."],
      ["Le", "renard", "a", "trouvé", "une", "plume", "brune."],
      ["Au", "menu,", "il", "y", "a", "des", "fruits", "et", "des", "légumes."],
      ["La", "jupe", "bleue", "est", "sur", "le", "lit."],
      ["Le", "bus", "passe", "dans", "la", "rue."],
      ["Une", "tulipe", "pousse", "dans", "le", "jardin."],
    ],
  },
  {
    id: 'e',
    topic: 'soutien-e',
    letterUpper: 'E',
    letterLower: 'e',
    sound: '/ə/',
    label: 'Voyelle E',
    graphemes: ["e", "é", "è", "ê", "ë"],
    words: ["biberon", "renard", "cheval", "semelle", "brebis", "genou", "recyclage", "cheminée", "chenille", "meringue", "enveloppe", "semaine", "secrétaire", "cerise", "fenouil", "cheveux"],
    syllables: ["me", "ne", "te", "pe", "ve", "be", "ce", "re", "le", "se", "kede", "fel", "pefe", "zev", "ned", "mebe", "rep", "tepe", "eve", "jede", "fe", "je", "qe", "eg", "de", "er", "el", "es", "ez", "eq"],
    compounds: [
      { parts: ['bi', 'beron'] as const, word: 'biberon' },
      { parts: ['re', 'nard'] as const, word: 'renard' },
      { parts: ['che', 'val'] as const, word: 'cheval' },
      { parts: ['se', 'melle'] as const, word: 'semelle' },
      { parts: ['bre', 'bis'] as const, word: 'brebis' },
      { parts: ['ge', 'nou'] as const, word: 'genou' },
      { parts: ['re', 'cyclage'] as const, word: 'recyclage' },
      { parts: ['che', 'minée'] as const, word: 'cheminée' },
      { parts: ['se', 'maine'] as const, word: 'semaine' },
      { parts: ['ce', 'rise'] as const, word: 'cerise' },
    ],
    completes: [
      { article: 'Une', word: 'crevette', before: '', blank: 'cre', after: 'vette' },
      { article: 'Une', word: 'fenêtre', before: '', blank: 'fe', after: 'nêtre' },
      { article: 'Une', word: 'pelote', before: '', blank: 'pe', after: 'lote' },
      { article: 'Un', word: 'requin', before: '', blank: 're', after: 'quin' },
      { article: 'Une', word: 'recette', before: '', blank: 're', after: 'cette' },
      { article: 'Une', word: 'chemise', before: '', blank: 'che', after: 'mise' },
      { article: 'Une', word: 'peluche', before: '', blank: 'pe', after: 'luche' },
      { article: 'Une', word: 'grenade', before: '', blank: 'gre', after: 'nade' },
      { article: 'Un', word: 'chemin', before: '', blank: 'che', after: 'min' },
      { article: 'Un', word: 'repas', before: '', blank: 're', after: 'pas' },
    ],
    scrambles: [
      { sentence: 'Le melon n’est pas pour eux', word: 'melon', letters: 'NOLEM' },
      { sentence: 'C’est le premier de la classe', word: 'premier', letters: 'REMIERP' },
      { sentence: 'Elle regarde la pelote de laine', word: 'regarde', letters: 'DEGARER' },
      { sentence: 'Le petit grelot a deux rubans', word: 'grelot', letters: 'TORGEL' },
      { sentence: 'Le venin de ce serpent est fort', word: 'venin', letters: 'NIVEN' },
      { sentence: 'Le grenier est plein de vieux meubles', word: 'grenier', letters: 'RENIGRE' },
      { sentence: 'La chenille trouve une cerise sur la pelouse', word: 'pelouse', letters: 'SEOUPLE' },
    ],
    determinants: [
      { blank: 'le', rest: 'Je me demande où se trouve la chemise bleue.', sentence: 'Je me demande où se trouve la chemise bleue.' },
      { blank: 'le', rest: 'Deux enfants regardent par la fenêtre.', sentence: 'Deux enfants regardent par la fenêtre.' },
      { blank: 'le', rest: 'Je me lève pour manger le repas.', sentence: 'Je me lève pour manger le repas.' },
      { blank: 'le', rest: 'Je mets les petites crevettes dans le feu.', sentence: 'Je mets les petites crevettes dans le feu.' },
      { blank: 'Le', rest: 'chemin devient étroit après le cerisier.', sentence: 'Le chemin devient étroit après le cerisier.' },
      { blank: 'le', rest: 'Je veux la recette de gâteau de Déborah.', sentence: 'Je veux la recette de gâteau de Déborah.' },
      { blank: 'le', rest: 'L’oiseau se pose sur la peluche.', sentence: 'L’oiseau se pose sur la peluche.' },
      { blank: 'le', rest: 'Nous pesons les grenades sur la balance.', sentence: 'Nous pesons les grenades sur la balance.' },
    ],
    countPhrases: ["Je veux acheter deux œufs.", "Ma mère mesure le niveau de l’eau.", "Vous semez les graines sur la pelouse ?", "Je peux mettre le jeu sur la table.", "Le cheval peut venir avec nous.", "Alicia n’est pas heureuse quand elle regarde le feu."],
    readPhrases: ["Le petit cheval regarde la grenouille.", "Je me demande ce que je vais faire ce soir.", "Le renard se promène le long de la rivière.", "Ce que tu me dis me semble étrange.", "Le redoutable chevalier se repose sur le sol.", "Le second chat retourne sur la pelouse.", "Je le retrouve devant le magasin de fleurs.", "Ne me dérange pas, je regarde le ciel se colorer.", "Que ferons-nous demain, se demande le fermier ?", "Le chemin de terre mène vers le reposant village.", "Ce remède laisse un léger regret.", "Le refuge du chevreau velu est près de la colline.", "Les revenants se retrouve chaque nuit.", "Après le repas, le renard retourne à son refuge.", "Elle se remet de son retard.", "Je regarde le reflet de ma femme dans l'eau."],
    audioPairs: [
      { word: 'médecin', other: 'relax' },
      { word: 'casserole', other: 'pansement' },
      { word: 'rejoindre', other: 'rejoindre' },
      { word: 'relax', other: 'sonnerie' },
      { word: 'pansement', other: 'médecin' },
      { word: 'reflet', other: 'remix' },
      { word: 'remix', other: 'reflet' },
      { word: 'sonnerie', other: 'casserole' },
    ],
    syllableItems: [
      { word: 'betterave', parts: ['bet', 'te', 'rave'] },
      { word: 'baignoire', parts: ['bai', 'gnoire'] },
      { word: 'madelaine', parts: ['ma', 'de', 'laine'] },
      { word: 'cadenas', parts: ['ca', 'de', 'nas'] },
      { word: 'harmonica', parts: ['har', 'mo', 'ni', 'ca'] },
      { word: 'fenouil', parts: ['fe', 'nouil'] },
      { word: 'hanneton', parts: ['han', 'ne', 'ton'] },
      { word: 'grenouille', parts: ['gre', 'nouille'] },
      { word: 'caleçon', parts: ['ca', 'le', 'çon'] },
      { word: 'coquelicot', parts: ['co', 'que', 'li', 'cot'] },
      { word: 'hexagone', parts: ['hex', 'a', 'gone'] },
      { word: 'cerise', parts: ['ce', 'rise'] },
    ],
    orderSentences: [
      ["Après", "le", "repas,", "le", "renard", "retourne", "à", "son", "refuge."],
      ["Elle", "se", "remet", "de", "son", "retard."],
      ["Le", "cheval", "mange", "dans", "le", "pré."],
      ["La", "chenille", "est", "sur", "la", "feuille."],
      ["Cette", "semaine,", "je", "vais", "à", "l’école."],
      ["Le", "menu", "est", "sur", "la", "table."],
    ],
  },
  {
    id: 'y',
    topic: 'soutien-y',
    letterUpper: 'Y',
    letterLower: 'y',
    sound: '/i/',
    label: 'Voyelle Y',
    graphemes: ["y"],
    words: ["stylo", "pyjama", "bicyclette", "cygne", "gymnaste", "pyramide", "encyclopédie", "myrtille", "cyclone", "gymnase", "mythologie", "dyslexie", "hydrogène", "motocyclette", "hygiène", "cylindre"],
    syllables: ["my", "ny", "ty", "yp", "vy", "yb", "yk", "ys", "ly", "zy", "myk", "tyf", "pyzy", "vyl", "ysyd", "ykyr", "fyby", "ryta", "ysny", "yrpy", "yf", "yl", "ys", "ny", "qy", "dy", "yj", "my", "yg", "ry"],
    compounds: [
      { parts: ['sty', 'lo'] as const, word: 'stylo' },
      { parts: ['py', 'jama'] as const, word: 'pyjama' },
      { parts: ['bicy', 'clette'] as const, word: 'bicyclette' },
      { parts: ['cy', 'gne'] as const, word: 'cygne' },
      { parts: ['gym', 'naste'] as const, word: 'gymnaste' },
      { parts: ['py', 'ramide'] as const, word: 'pyramide' },
      { parts: ['encyclo', 'pédie'] as const, word: 'encyclopédie' },
      { parts: ['myr', 'tille'] as const, word: 'myrtille' },
      { parts: ['cy', 'clone'] as const, word: 'cyclone' },
      { parts: ['gym', 'nase'] as const, word: 'gymnase' },
    ],
    completes: [
      { article: 'Un', word: 'stylo', before: '', blank: 'sty', after: 'lo' },
      { article: 'Un', word: 'pyjama', before: '', blank: 'py', after: 'jama' },
      { article: 'Une', word: 'bicyclette', before: '', blank: 'bi', after: 'cyclette' },
      { article: 'Un', word: 'cygne', before: '', blank: 'cy', after: 'gne' },
      { article: 'Un', word: 'gymnaste', before: '', blank: 'gym', after: 'naste' },
      { article: 'Une', word: 'pyramide', before: '', blank: 'py', after: 'ramide' },
      { article: 'Une', word: 'encyclopédie', before: 'ency', blank: 'clo', after: 'pédie' },
      { article: 'Une', word: 'myrtille', before: '', blank: 'myr', after: 'tille' },
      { article: 'Un', word: 'cyclone', before: '', blank: 'cy', after: 'clone' },
      { article: 'Un', word: 'gymnase', before: '', blank: 'gym', after: 'nase' },
    ],
    scrambles: [
      { sentence: 'Le papyrus est un vieux document', word: 'papyrus', letters: 'YRUSAPP' },
      { sentence: 'Le gyrophare brille vite dans la nuit', word: 'gyrophare', letters: 'ROHYGRAPE' },
      { sentence: 'L’hydravion atterrit à midi', word: 'hydravion', letters: 'VAYHDRION' },
      { sentence: 'La styliste dessine un bikini', word: 'styliste', letters: 'TSLIYSTE' },
      { sentence: 'Il est professeur de physique', word: 'physique', letters: 'SYUQIPEH' },
      { sentence: 'Le rugby est mon hobby favori', word: 'rugby', letters: 'YGRBU' },
      { sentence: 'L’Égypte a de grandes pyramides', word: 'Égypte', letters: 'PGÉTYE' },
    ],
    determinants: [
      { blank: 'Le', rest: 'labyrinthe est si difficile.', sentence: 'Le labyrinthe est si difficile.' },
      { blank: 'La', rest: 'dynamo produit de l’électricité.', sentence: 'La dynamo produit de l’électricité.' },
      { blank: 'le', rest: 'Je sers le curry avec du riz.', sentence: 'Je sers le curry avec du riz.' },
      { blank: 'le', rest: 'Sur la piste, le cycliste roule très vite.', sentence: 'Sur la piste, le cycliste roule très vite.' },
      { blank: 'Le', rest: 'papillon sort de la chrysalide.', sentence: 'Le papillon sort de la chrysalide.' },
      { blank: 'Le', rest: 'python vit dans la rivière.', sentence: 'Le python vit dans la rivière.' },
      { blank: 'le', rest: 'Où est le whysky que tu as pris ?', sentence: 'Où est le whysky que tu as pris ?' },
      { blank: 'le', rest: 'Dans l’histoire, les cyclopes vivent dans des grottes.', sentence: 'Dans l’histoire, les cyclopes vivent dans des grottes.' },
    ],
    countPhrases: ["Le gymnase est fermé aujourd'hui.", "Ce type d'oiseau vole trop vite.", "La glycémie de l’infirmière est stable.", "Ce polyglotte parle six langues différentes.", "Voici les règles d'hygiène du lycée.", "Je n’aime pas du tout la gymnastique."],
    readPhrases: ["Il y a un stylo, un livre et un pyjama ici.", "Mon ami a remis sa bicyclette à minuit.", "Le jury analyse le mystère de ce crime.", "À midi, il y a un joli cygne dans la ville.", "Le physicien étudie le système avec un style précis.", "Six amis roulent à motocyclette.", "Ce polygone a une belle symétrie.", "La cycliste et l'infirmière habitent près du lycée.", "La pyramide est immense et ancienne.", "Qui a pris mon cylindre gris ?", "Ils ont pris rapidement un tricycle.", "Son hobby favori, c'est la dactylo.", "La syllabe finale est difficile à lire.", "La fille lit un mythe ancien dans son lit.", "Quel type de films aimes-tu ?", "Le rythme de sa vie est calme."],
    audioPairs: [
      { word: 'sytème', other: 'typique' },
      { word: 'mystère', other: 'myopie' },
      { word: 'analyse', other: 'paysage' },
      { word: 'physicien', other: 'syllabe' },
    ],
    syllableItems: [
      { word: 'polygone', parts: ['po', 'ly', 'gone'] },
      { word: 'cyclisme', parts: ['cy', 'clisme'] },
      { word: 'polystyrène', parts: ['po', 'ly', 'sty', 'rène'] },
      { word: 'symétrie', parts: ['sy', 'mé', 'trie'] },
      { word: 'rythme', parts: ['ryth', 'me'] },
      { word: 'dynamite', parts: ['dy', 'na', 'mite'] },
      { word: 'recycler', parts: ['re', 'cy', 'cler'] },
      { word: 'oxygène', parts: ['ox', 'y', 'gène'] },
      { word: 'pyramide', parts: ['py', 'ra', 'mide'] },
      { word: 'stylo', parts: ['sty', 'lo'] },
      { word: 'cygne', parts: ['cy', 'gne'] },
      { word: 'gymnase', parts: ['gym', 'nase'] },
    ],
    orderSentences: [
      ["Il", "y", "a", "un", "stylo,", "un", "livre", "et", "un", "pyjama", "ici."],
      ["Mon", "ami", "a", "remis", "sa", "bicyclette", "à", "minuit."],
      ["À", "midi,", "il", "y", "a", "un", "joli", "cygne", "dans", "la", "ville."],
      ["Ce", "polygone", "a", "une", "belle", "symétrie."],
      ["Qui", "a", "pris", "mon", "cylindre", "gris", "?"],
      ["Son", "hobby", "favori,", "c’est", "la", "dactylo."],
    ],
  },
]

export function soutienBankByTopic(topic: string): SoutienVowelBank | undefined {
  return SOUTIEN_VOWEL_BANKS.find((b) => b.topic === topic)
}

