/** Banques Soutien FR — voyelles (livret CSC). Images résolues via vocabulaire. */
import type { VowelId } from '../lecture-banks'

export type SoutienScramble = { sentence: string; word: string; letters: string }
/** Mot à compléter : Un/Une + [before]____[after] → word (syllabe = consonant+voyelle). */
export type SoutienComplete = {
  article: 'Un' | 'Une'
  word: string
  /** Préfixe affiché avant le trait (ex. « aspi »). */
  before: string
  /** Syllabe manquante (corrigé). */
  blank: string
  /** Suite du mot après le trait (ex. « teur », « teau »). */
  after: string
}
/** Segment de phrase déterminants : texte (évent. souligné) ou blanc. */
export type SoutienDetPart =
  | { t: string; u?: boolean }
  | { blank: string }
export type SoutienDet = {
  parts: readonly SoutienDetPart[]
  /** Phrase complète (corrigé). */
  sentence: string
}
export type SoutienAudio = { word: string; other: string }
export type SoutienCompound = { parts: readonly [string, string]; word: string }
/** Mot + découpe syllabique correcte (type 8). */
export type SoutienSyllableItem = { word: string; parts: readonly string[] }

export type SoutienVowelBank = {
  id: VowelId
  topic: string
  letterUpper: string
  letterLower: string
  sound: string
  label: string
  graphemes: readonly string[]
  words: readonly string[]
  syllables: readonly string[]
  compounds: readonly SoutienCompound[]
  completes: readonly SoutienComplete[]
  scrambles: readonly SoutienScramble[]
  determinants: readonly SoutienDet[]
  countPhrases: readonly string[]
  readPhrases: readonly string[]
  audioPairs: readonly SoutienAudio[]
  syllableItems: readonly SoutienSyllableItem[]
  /**
   * Type 13 — phrases à remettre en ordre.
   * Chaque jeton : `mot/catégorie` (couleurs Gattegno).
   */
  orderSentences: readonly (readonly string[])[]
  /** Type 16 — mots mêlés (12 mots, grille 15×15). */
  wordSearchWords: readonly string[]
}

export const SOUTIEN_VOWEL_BANKS: readonly SoutienVowelBank[] = [
  {
    id: 'a',
    topic: 'soutien-a',
    letterUpper: 'A',
    letterLower: 'a',
    sound: '/a/',
    label: 'Voyelle A',
    graphemes: ["a", "à", "â"],
    words: ["bateau", "café", "avion", "arbre", "abricot", "quatre", "rat", "papier", "abeille", "arrosoir", "parapluie", "gâteau", "ananas", "datte", "vase", "âne"],
    syllables: ["ta", "ar", "la", "pa", "va", "ca", "sa", "fa", "ga", "ab", "papa", "kal", "vac", "lab", "arab", "lap", "nab", "bar", "zag", "jata", "ba", "ra", "da", "ga", "pa", "pa", "af", "av", "na", "ma"],
    compounds: [
      { parts: ['pa', 'pier'] as const, word: 'papier' },
      { parts: ['para', 'pluie'] as const, word: 'parapluie' },
      { parts: ['ab', 'eille'] as const, word: 'abeille' },
      { parts: ['gâ', 'teau'] as const, word: 'gâteau' },
      { parts: ['ana', 'nas'] as const, word: 'ananas' },
      { parts: ['va', 'se'] as const, word: 'vase' },
      { parts: ['abri', 'cot'] as const, word: 'abricot' },
      { parts: ['ba', 'teau'] as const, word: 'bateau' },
      { parts: ['ca', 'fé'] as const, word: 'café' },
      { parts: ['a', 'vion'] as const, word: 'avion' },
    ],
    completes: [
      { article: 'Un', word: 'bateau', before: '', blank: 'ba', after: 'teau' },
      { article: 'Un', word: 'animal', before: '', blank: 'an', after: 'imal' },
      { article: 'Un', word: 'arbre', before: '', blank: 'ar', after: 'bre' },
      { article: 'Une', word: 'famille', before: '', blank: 'fa', after: 'mille' },
      { article: 'Un', word: 'vase', before: '', blank: 'va', after: 'se' },
      { article: 'Un', word: 'ballon', before: '', blank: 'ba', after: 'llon' },
      { article: 'Une', word: 'datte', before: '', blank: 'da', after: 'tte' },
      { article: 'Un', word: 'aspirateur', before: 'aspi', blank: 'ra', after: 'teur' },
      { article: 'Un', word: 'avion', before: '', blank: 'av', after: 'ion' },
      { article: 'Une', word: 'allumette', before: '', blank: 'al', after: 'lumette' },
    ],
    scrambles: [
      { sentence: 'Le chat noir marche près de la plage', word: 'plage', letters: 'LAGEP' },
      { sentence: 'La girafe mange des feuilles de l’arbre', word: 'girafe', letters: 'IRAFEG' },
      { sentence: 'Les flamants roses sont très calmes', word: 'flamants', letters: 'LAMANTSF' },
      { sentence: 'Les lapins sautent dans le jardin', word: 'lapins', letters: 'APINSL' },
      { sentence: 'Anna achète des bananes au marché', word: 'bananes', letters: 'ANANESB' },
      { sentence: 'Mon papa nage à la piscine de Martigny', word: 'nage', letters: 'AGEN' },
      { sentence: 'La salade est dans le panier de maman', word: 'salade', letters: 'ALADES' },
      { sentence: 'L’avion vole au-dessus du lac', word: 'avion', letters: 'VIONA' },
      { sentence: 'Le bateau avance lentement sur l’eau', word: 'bateau', letters: 'ATEAUB' },
      { sentence: 'Un grand arbre pousse dans le parc', word: 'arbre', letters: 'RBREA' },
      { sentence: 'Le ballon rouge roule dans la cour', word: 'ballon', letters: 'ALLONB' },
      { sentence: 'Maman coupe un ananas bien mûr', word: 'ananas', letters: 'NANASA' },
      { sentence: 'Le café est encore trop chaud', word: 'café', letters: 'AFÉC' },
      { sentence: 'Le canard nage près du rivage', word: 'canard', letters: 'ANARDC' },
      { sentence: 'Un papillon jaune se pose sur la table', word: 'papillon', letters: 'APILLONP' },
      { sentence: 'La table est prête pour le repas', word: 'table', letters: 'ABLET' },
      { sentence: 'Le chat dort sur le tapis', word: 'chat', letters: 'HATC' },
      { sentence: 'Sara range son cartable à l’école', word: 'cartable', letters: 'ARTABLEC' },
      { sentence: 'Le train part de la gare à midi', word: 'gare', letters: 'AREG' },
      { sentence: 'Paul mange une pomme dans le jardin', word: 'pomme', letters: 'OMMEP' },
      { sentence: 'La valise est trop lourde à porter', word: 'valise', letters: 'ALISEV' },
      { sentence: 'Le panda mange du bambou au zoo', word: 'panda', letters: 'ANDAP' },
      { sentence: 'Une caravane est garée devant la maison', word: 'caravane', letters: 'ARAVANEC' },
      { sentence: 'Le marathon traverse toute la ville', word: 'marathon', letters: 'ARATHONM' },
      { sentence: 'Lara dessine une carte de la Suisse', word: 'carte', letters: 'ARTEC' },
    ],
    determinants: [
      {
        parts: [{ blank: 'Le' }, { t: ' bateau', u: true }, { t: ' avance sur le lac.' }],
        sentence: 'Le bateau avance sur le lac.',
      },
      {
        parts: [
          { blank: 'Les' },
          { t: ' animaux', u: true },
          { t: ' jouent avec ' },
          { blank: 'le' },
          { t: ' ballon.' },
        ],
        sentence: 'Les animaux jouent avec le ballon.',
      },
      {
        parts: [
          { blank: 'L’' },
          { t: ' avion', u: true },
          { t: ' vole au-dessus de ' },
          { blank: 'l’' },
          { t: ' arbre.' },
        ],
        sentence: 'L’avion vole au-dessus de l’arbre.',
      },
      {
        parts: [{ blank: 'La' }, { t: ' famille', u: true }, { t: ' de Sara mange une salade.' }],
        sentence: 'La famille de Sara mange une salade.',
      },
      {
        parts: [
          { t: 'Je pose ' },
          { blank: 'le' },
          { t: ' vase et ' },
          { blank: 'l’' },
          { t: ' allumette sur une table.' },
        ],
        sentence: 'Je pose le vase et l’allumette sur une table.',
      },
      {
        parts: [{ blank: 'L’' }, { t: ' aspirateur', u: true }, { t: ' est dans un placard.' }],
        sentence: 'L’aspirateur est dans un placard.',
      },
      {
        parts: [{ blank: 'La' }, { t: ' datte', u: true }, { t: ' est dans mon assiette.' }],
        sentence: 'La datte est dans mon assiette.',
      },
      {
        parts: [{ t: 'Je n’arrive pas à allumer ' }, { blank: 'les' }, { t: ' allumettes.' }],
        sentence: 'Je n’arrive pas à allumer les allumettes.',
      },
    ],
    countPhrases: ["Clara habite dans une maison à côté de l’école.", "Sous un arbre il y a des animaux : des chiens et des chats.", "Ils achètent des légumes frais pour préparer le repas.", "Isabelle lit un roman à haute voix.", "Ma girafe mange des feuilles et boit de l’eau près du lac.", "Papa va prendre la chatte et son chaton."],
    readPhrases: [
      "Je m’appelle Anastasia.",
      "Le chat dort sur le canapé.",
      "Maman prépare une salade.",
      "Ma famille chante à la maison.",
      "J’achète des carottes et des patates.",
      "Le samedi, je vais au marché.",
      "Alicia joue au football avec mes amis.",
      "Adna va au théâtre regarder un spectacle.",
      "J’aime les animaux.",
      "Nous allons au parc avec Max.",
      "Je suis l’amie d’Alexandre.",
      "Monica va au cinéma.",
      "Sara lave sa voiture.",
      "Marc un sac à la main.",
      "Le papa va à la gare.",
      "Le garçon joue avec sa balle.",
      "Anna range sa valise avant le départ.",
      "Le bateau avance lentement sur le lac.",
      "La table est prête pour le repas.",
      "Papa coupe un ananas bien mûr.",
      "Le ballon rouge roule dans la cour.",
      "Sara achète une salade au marché.",
      "Le chat noir marche près de la plage.",
      "Ma girafe mange des feuilles vertes.",
      "Clara habite dans une maison calme.",
      "Le train part de la gare à midi.",
      "Lara dessine une carte de la Suisse.",
      "Le panda mange du bambou au zoo.",
      "Une caravane est garée devant la maison.",
      "Le marathon traverse toute la ville.",
      "Paul mange une pomme dans le jardin.",
      "La valise est trop lourde à porter.",
      "Le café est encore trop chaud.",
      "Un papillon jaune se pose sur la table.",
      "Le canard nage près du rivage.",
      "Maman range le cartable à l’école.",
      "Le rat court sous le placard.",
      "Anita lit un magazine sur le sofa.",
      "La famille part en vacances demain.",
      "Le parapluie est dans le placard.",
      "Ada lave la casserole après le repas.",
      "Le garage est fermé le samedi.",
      "Ma tante apporte un gâteau à la fête.",
      "Le chaton dort dans la casserole vide.",
      "Sandra appelle sa maman au téléphone.",
      "Le bateau jaune quitte le port.",
      "La classe chante une chanson à l’école.",
      "Adam marche jusqu’à la place du village.",
      "Le vase est plein d’eau fraîche.",
      "Nadia range les cartables dans le placard.",
    ],
    audioPairs: [
      { word: 'chat', other: 'abeille' },
      { word: 'abricot', other: 'girafe' },
      { word: 'girafe', other: 'salade' },
      { word: 'animal', other: 'chat' },
      { word: 'abeille', other: 'bateau' },
      { word: 'bateau', other: 'animal' },
      { word: 'lapin', other: 'abricot' },
      { word: 'salade', other: 'lapin' },
    ],
    syllableItems: [
      { word: 'Plante', parts: ['Plan', 'te'] },
      { word: 'Patin', parts: ['Pa', 'tin'] },
      { word: 'Caméra', parts: ['Ca', 'mé', 'ra'] },
      { word: 'Château', parts: ['Châ', 'teau'] },
      { word: 'Matelas', parts: ['Ma', 'te', 'las'] },
      { word: 'Chandelier', parts: ['Chan', 'de', 'lier'] },
      { word: 'Magasin', parts: ['Ma', 'ga', 'sin'] },
      { word: 'Caneton', parts: ['Ca', 'ne', 'ton'] },
      { word: 'Papillon', parts: ['Pa', 'pil', 'lon'] },
      { word: 'Chanteuse', parts: ['Chan', 'teuse'] },
      { word: 'Automne', parts: ['Au', 'tomne'] },
      { word: 'Ordinateur', parts: ['Or', 'di', 'na', 'teur'] },
    ],
    orderSentences: [
      ['La/determinant', 'classe/nom', 'est/verbe', 'pleine./adjectif'],
      ['Mario/nom', 'part/verbe', 'en/preposition', 'vacances./nom'],
      ['Il/pronom', 'y/pronom', 'a/verbe', 'quatre/determinant', 'garçons./nom'],
      ['L’/determinant', 'adulte/nom', 'achète/verbe', 'une/determinant', 'salade./nom'],
      [
        'Alona/nom',
        'a/verbe',
        'des/determinant',
        'chats/nom',
        'à/preposition',
        'la/determinant',
        'maison./nom',
      ],
      ['Mon/determinant', 'ami/nom', 's’appelle/verbe', 'Marc./nom'],
    ],
    wordSearchWords: [
      'bataille',
      'agriculture',
      'canapé',
      'accident',
      'lavabo',
      'avantage',
      'personnalité',
      'camarade',
      'accélérer',
      'nationalité',
      'maths',
      'ambulance',
      'papillon',
      'salade',
      'girafe',
      'abricot',
    ],
  },
  {
    id: 'o',
    topic: 'soutien-o',
    letterUpper: 'O',
    letterLower: 'o',
    sound: '/o/',
    label: 'Voyelle O',
    graphemes: ["o", "ô"],
    words: ["tomate", "loto", "numéro", "robot", "omelette", "vélo", "orange", "orage", "ordinateur", "collier", "bonnet", "ordures", "cochon", "oreille", "koala", "olive"],
    syllables: ["mo", "no", "to", "po", "vo", "ob", "co", "or", "ov", "jo", "jog", "gob", "lop", "zo", "poq", "odo", "toto", "dol", "polo", "fobo", "qo", "ro", "oc", "od", "op", "go", "ko", "ol", "ot", "po"],
    compounds: [
      { parts: ['to', 'mate'] as const, word: 'tomate' },
      { parts: ['lo', 'to'] as const, word: 'loto' },
      { parts: ['nu', 'méro'] as const, word: 'numéro' },
      { parts: ['ro', 'bot'] as const, word: 'robot' },
      { parts: ['o', 'melette'] as const, word: 'omelette' },
      { parts: ['vé', 'lo'] as const, word: 'vélo' },
      { parts: ['o', 'range'] as const, word: 'orange' },
      { parts: ['o', 'rage'] as const, word: 'orage' },
      { parts: ['ko', 'ala'] as const, word: 'koala' },
      { parts: ['o', 'live'] as const, word: 'olive' },
    ],
    completes: [
      { article: 'Un', word: 'piano', before: '', blank: 'pi', after: 'ano' },
      { article: 'Une', word: 'otarie', before: '', blank: 'o', after: 'tarie' },
      { article: 'Un', word: 'cobra', before: '', blank: 'co', after: 'bra' },
      { article: 'Un', word: 'fromage', before: 'fro', blank: 'ma', after: 'ge' },
      { article: 'Une', word: 'moto', before: '', blank: 'mo', after: 'to' },
      { article: 'Un', word: 'donut', before: '', blank: 'do', after: 'nut' },
      { article: 'Une', word: 'robe', before: '', blank: 'ro', after: 'be' },
      { article: 'Une', word: 'coccinelle', before: '', blank: 'co', after: 'ccinelle' },
      { article: 'Un', word: 'flocon', before: '', blank: 'flo', after: 'con' },
      { article: 'Un', word: 'losange', before: '', blank: 'lo', after: 'sange' },
    ],
    scrambles: [
      { sentence: 'Le soleil brille sur le robot', word: 'soleil', letters: 'OLEILS' },
      { sentence: 'Mes bottes sont dans le coffre', word: 'bottes', letters: 'OTTESB' },
      { sentence: 'La corde est autour du poteau', word: 'corde', letters: 'ORDEC' },
      { sentence: 'La tortue dort sur son dos', word: 'tortue', letters: 'ORTUET' },
      { sentence: 'L’arrosoir est à côté de la moto', word: 'arrosoir', letters: 'RROSOIRA' },
      { sentence: 'Les carottes sont dans le pot', word: 'carottes', letters: 'AROTTESC' },
      { sentence: 'Le violon est posé sur le sol', word: 'violon', letters: 'IOLONV' },
      { sentence: 'Le robot marche tout seul', word: 'robot', letters: 'OBOTR' },
      { sentence: 'Tom mange une tomate rouge', word: 'tomate', letters: 'OMATET' },
      { sentence: 'La moto file sur la route', word: 'moto', letters: 'OTOM' },
      { sentence: 'L’orange est juteuse et ronde', word: 'orange', letters: 'RANGEO' },
      { sentence: 'Le vélo est dans le garage', word: 'vélo', letters: 'ÉLOV' },
      { sentence: 'Un koala dort dans l’arbre', word: 'koala', letters: 'OALAK' },
      { sentence: 'L’ordinateur est sur le bureau', word: 'ordinateur', letters: 'RDINATEURO' },
      { sentence: 'La coccinelle marche sur la rose', word: 'coccinelle', letters: 'OCCINELLEC' },
      { sentence: 'Le cochon joue dans la boue', word: 'cochon', letters: 'OCHONC' },
      { sentence: 'Nora porte un collier doré', word: 'collier', letters: 'OLLIERC' },
      { sentence: 'Le bonnet chaud protège du froid', word: 'bonnet', letters: 'ONNETB' },
      { sentence: 'Une omelette est prête pour midi', word: 'omelette', letters: 'MELETTEO' },
      { sentence: 'Le piano est trop lourd à porter', word: 'piano', letters: 'IANOP' },
      { sentence: 'Le flocon tombe sur le manteau', word: 'flocon', letters: 'LOCONF' },
      { sentence: 'Olivia ouvre une boîte de chocolat', word: 'chocolat', letters: 'HOCOLATC' },
      { sentence: 'Le potager a besoin d’eau', word: 'potager', letters: 'OTAGERP' },
      { sentence: 'Le crocodile nage dans le fleuve', word: 'crocodile', letters: 'ROCODILEC' },
      { sentence: 'Le dodo est un oiseau disparu', word: 'dodo', letters: 'ODOD' },
    ],
    determinants: [
      {
        parts: [{ blank: 'La' }, { t: ' moto', u: true }, { t: ' est devant la maison.' }],
        sentence: 'La moto est devant la maison.',
      },
      {
        parts: [
          { t: 'Elle coupe ' },
          { blank: 'le' },
          { t: ' fromage', u: true },
          { t: ' en gros morceaux.' },
        ],
        sentence: 'Elle coupe le fromage en gros morceaux.',
      },
      {
        parts: [{ blank: 'La' }, { t: ' coccinelle', u: true }, { t: ' est sur une tomate.' }],
        sentence: 'La coccinelle est sur une tomate.',
      },
      {
        parts: [
          { blank: 'L’' },
          { t: ' otarie', u: true },
          { t: ' nage dans ' },
          { blank: 'l’' },
          { t: ' océan.' },
        ],
        sentence: 'L’otarie nage dans l’océan.',
      },
      {
        parts: [{ blank: 'Les' }, { t: ' donuts', u: true }, { t: ' au chocolat sont sur la table.' }],
        sentence: 'Les donuts au chocolat sont sur la table.',
      },
      {
        parts: [
          { t: 'Je pose ' },
          { blank: 'le' },
          { t: ' piano', u: true },
          { t: ' près du vélo.' },
        ],
        sentence: 'Je pose le piano près du vélo.',
      },
      {
        parts: [{ blank: 'Le' }, { t: ' cobra', u: true }, { t: ' dort dans son abri.' }],
        sentence: 'Le cobra dort dans son abri.',
      },
      {
        parts: [{ blank: 'Les' }, { t: ' losanges', u: true }, { t: ' sont de couleur rose.' }],
        sentence: 'Les losanges sont de couleur rose.',
      },
    ],
    countPhrases: ["Le gorille mange une pomme dans le zoo.", "Le cochon rose porte un bonnet dans son enclos.", "Le poisson orange tourne autour du rocher au fond de l’eau.", "Le coq picore des graines près du portail.", "Le docteur fait tomber les dominos sur le sol.", "Le motard prend des photos de son vélo."],
    readPhrases: [
      "Après le loto, Tom boit un soda et fait dodo.",
      "Le parasol est posé près du vélo.",
      "Le métro ne passe pas à Vétroz.",
      "Paul porte le javelot jusqu’au rocher.",
      "L’homme va à l’hôpital avec sa moto.",
      "Je mets ma culotte et mon maillot.",
      "Le pilote joue du piano avant le vol.",
      "Le crocodile dort au bord de l’eau.",
      "Hugo vole des brocolis et des abricots.",
      "La brosse est dans le bocal.",
      "Rosa croque le chocolat devant le zoo.",
      "Le koala mange du fromage orange.",
      "Le rocher rose est au bord de l’océan.",
      "L’otarie montre son oreille au docteur.",
      "Le lavabo n’est pas propre.",
      "Le professeur donne une limonade à Noé.",
      "Le robot marche tout seul dans le salon.",
      "Olivia pose son manteau près de la porte.",
      "Le poisson orange tourne autour du rocher.",
      "Tom mange une tomate dans le jardin.",
      "La moto file sur la route du village.",
      "Nora ouvre la boîte de chocolats.",
      "Le cochon rose porte un bonnet.",
      "Le soleil brille fort sur le zoo.",
      "Le docteur regarde le dossier du patient.",
      "Le motard prend des photos de son vélo.",
      "Le flocon tombe sur le manteau.",
      "Le losange est dessiné au tableau.",
      "L’orange est juteuse et ronde.",
      "Le cobra se cache sous la pierre.",
      "Le fromage est dans le frigo.",
      "La robe bleue est dans l’armoire.",
      "La coccinelle marche sur la rose.",
      "Le piano est trop lourd à porter.",
      "Le donut est sur l’assiette.",
      "Le portail du zoo est encore ouvert.",
      "Noé range ses photos dans le tiroir.",
      "Le bol de riz est sur la table ronde.",
      "Le clown jette des bonbons dans la foule.",
      "Le mot « photo » est écrit au tableau.",
      "Le coco tombe près du tronc.",
      "Rosa boit un soda après le sport.",
      "Le robot range les bols dans le frigo.",
      "Le pont enjambe le cours d’eau.",
      "Olivia lit un roman au bord de l’eau.",
      "Le corbeau vole au-dessus du toît.",
      "Le moto-cross file dans le pré.",
      "Le chocolat fond dans la casserole.",
      "Tom pose son vélo contre le mur.",
      "Le globe tourne dans le bureau du prof.",
    ],
    audioPairs: [
      { word: 'coffre', other: 'avocate' },
      { word: 'boxeur', other: 'corbeau' },
      { word: 'tomate', other: 'boxeur' },
      { word: 'bottes', other: 'bottes' },
      { word: 'avocate', other: 'tomate' },
      { word: 'corbeau', other: 'parasol' },
      { word: 'flocon', other: 'coffre' },
      { word: 'parasol', other: 'flocon' },
    ],
    syllableItems: [
      { word: 'Abricot', parts: ['A', 'bri', 'cot'] },
      { word: 'Boxe', parts: ['Boxe'] },
      { word: 'Brocoli', parts: ['Bro', 'co', 'li'] },
      { word: 'Chorizo', parts: ['Cho', 'ri', 'zo'] },
      { word: 'Forêt', parts: ['Fo', 'rêt'] },
      { word: 'Serveuse', parts: ['Ser', 'veuse'] },
      { word: 'Homard', parts: ['Ho', 'mard'] },
      { word: 'Pantalon', parts: ['Pan', 'ta', 'lon'] },
      { word: 'Colibri', parts: ['Co', 'li', 'bri'] },
      { word: 'Échalote', parts: ['É', 'cha', 'lote'] },
      { word: 'Judo', parts: ['Ju', 'do'] },
      { word: 'Lavabo', parts: ['La', 'va', 'bo'] },
    ],
    orderSentences: [
      [
        'Le/determinant',
        'cochon/nom',
        'dort/verbe',
        'dans/preposition',
        'son/determinant',
        'abri./nom',
      ],
      [
        'Le/determinant',
        'robot/nom',
        'est/verbe',
        'sur/preposition',
        'la/determinant',
        'table./nom',
      ],
      ['Mon/determinant', 'vélo/nom', 'est/verbe', 'orange./adjectif'],
      ['Le/determinant', 'soleil/nom', 'brille/verbe', 'fort./adverbe'],
      ['Elle/pronom', 'pose/verbe', 'son/determinant', 'chapeau./nom'],
      [
        'Le/determinant',
        'koala/nom',
        'mange/verbe',
        'des/determinant',
        'feuilles./nom',
      ],
    ],
    wordSearchWords: [
      'tomate',
      'robot',
      'omelette',
      'vélo',
      'orange',
      'ordinateur',
      'cochon',
      'koala',
      'soleil',
      'chocolat',
      'moto',
      'hôpital',
      'crocodile',
      'piano',
      'océan',
      'bonnet',
    ],
  },
  {
    id: 'i',
    topic: 'soutien-i',
    letterUpper: 'I',
    letterLower: 'i',
    sound: '/i/',
    label: 'Voyelle I',
    graphemes: ["i", "î", "ï"],
    words: ["ami", "piment", "miroir", "bijou", "basilic", "miel", "riz", "nid", "chemise", "limace", "brocoli", "cahier", "hiver", "fourmi", "bille", "guitare"],
    syllables: ["mi", "ni", "ti", "pi", "iv", "ib", "ci", "ir", "li", "si", "qid", "nib", "itit", "pic", "vir", "midi", "fig", "fidi", "siti", "sis", "ki", "pi", "il", "ni", "ti", "ri", "is", "mi", "ip", "li"],
    compounds: [
      { parts: ['pi', 'ment'] as const, word: 'piment' },
      { parts: ['mi', 'roir'] as const, word: 'miroir' },
      { parts: ['bi', 'jou'] as const, word: 'bijou' },
      { parts: ['ba', 'silic'] as const, word: 'basilic' },
      { parts: ['mi', 'el'] as const, word: 'miel' },
      { parts: ['che', 'mise'] as const, word: 'chemise' },
      { parts: ['li', 'mace'] as const, word: 'limace' },
      { parts: ['bro', 'coli'] as const, word: 'brocoli' },
    ],
    completes: [
      { article: 'Un', word: 'tigre', before: '', blank: 'ti', after: 'gre' },
      { article: 'Un', word: 'briquet', before: '', blank: 'bri', after: 'quet' },
      { article: 'Un', word: 'cookie', before: '', blank: 'coo', after: 'kie' },
      { article: 'Un', word: 'canari', before: '', blank: 'ca', after: 'nari' },
      { article: 'Un', word: 'kiwi', before: '', blank: 'ki', after: 'wi' },
      { article: 'Un', word: 'épinard', before: '', blank: 'épi', after: 'nard' },
      { article: 'Un', word: 'citron', before: '', blank: 'ci', after: 'tron' },
      { article: 'Une', word: 'cerise', before: '', blank: 'ce', after: 'rise' },
      { article: 'Une', word: 'viande', before: '', blank: 'vi', after: 'ande' },
      { article: 'Un', word: 'hérisson', before: '', blank: 'hé', after: 'risson' },
    ],
    scrambles: [
      { sentence: 'Le biberon est bien rempli', word: 'biberon', letters: 'IBERONB' },
      { sentence: 'Melina a mis une image sur son ordi', word: 'image', letters: 'MAGEI' },
      { sentence: 'Les cerises sont sous le cerisier', word: 'cerisier', letters: 'ERISIERC' },
      { sentence: 'Cécile a choisi le litchi', word: 'litchi', letters: 'ITCHIL' },
      { sentence: 'Qui descend les escaliers avec mon ami', word: 'escaliers', letters: 'SCALIERSE' },
      { sentence: 'Le navire de Lisa avance vite', word: 'navire', letters: 'AVIREN' },
      { sentence: 'Le hibou crie dans la nuit', word: 'hibou', letters: 'IBOUH' },
      { sentence: 'Le livre est sur le lit', word: 'livre', letters: 'IVREL' },
      { sentence: 'Mina lit une histoire au lit', word: 'lit', letters: 'ITL' },
      { sentence: 'Le kiwi est vert et acidulé', word: 'kiwi', letters: 'IWIK' },
      { sentence: 'Un pirate cherche un trésor', word: 'pirate', letters: 'IRATEP' },
      { sentence: 'La pizza arrive enfin sur la table', word: 'pizza', letters: 'IZZAP' },
      { sentence: 'Le ski est un sport d’hiver', word: 'ski', letters: 'KIS' },
      { sentence: 'Iris range sa valise pour le voyage', word: 'valise', letters: 'ALISEV' },
      { sentence: 'Le citron est très acide', word: 'citron', letters: 'ITRONC' },
      { sentence: 'Un igloo est fait de neige', word: 'igloo', letters: 'GLOOI' },
      { sentence: 'Le miroir reflète mon visage', word: 'miroir', letters: 'IROIRM' },
      { sentence: 'La girafe mange en silence', word: 'girafe', letters: 'IRAFEG' },
      { sentence: 'Le ticket est dans ma poche', word: 'ticket', letters: 'ICKETT' },
      { sentence: 'Nina visite le musée de la ville', word: 'visite', letters: 'ISITEV' },
      { sentence: 'Le billet de train est valide', word: 'billet', letters: 'ILLETB' },
      { sentence: 'Un crocodile vit près du fleuve', word: 'crocodile', letters: 'ROCODILEC' },
      { sentence: 'Le stylo écrit très bien', word: 'stylo', letters: 'TYLOS' },
      { sentence: 'La fille lit une histoire', word: 'fille', letters: 'ILLEF' },
      { sentence: 'Le frigo est plein de fruits', word: 'frigo', letters: 'RIGOF' },
    ],
    determinants: [
      {
        parts: [
          { blank: 'La' },
          { t: ' petite fille', u: true },
          { t: ' mange ' },
          { blank: 'la' },
          { t: ' cerise.' },
        ],
        sentence: 'La petite fille mange la cerise.',
      },
      {
        parts: [
          { blank: 'L’' },
          { t: ' hérisson', u: true },
          { t: ' finit ' },
          { blank: 'le' },
          { t: ' citron.' },
        ],
        sentence: 'L’hérisson finit le citron.',
      },
      {
        parts: [
          { blank: 'Les' },
          { t: ' cuisiniers', u: true },
          { t: ' coupent ' },
          { blank: 'le' },
          { t: ' kiwi.' },
        ],
        sentence: 'Les cuisiniers coupent le kiwi.',
      },
      {
        parts: [
          { blank: 'Le' },
          { t: ' tigre', u: true },
          { t: ' dévore ' },
          { blank: 'la' },
          { t: ' viande.' },
        ],
        sentence: 'Le tigre dévore la viande.',
      },
      {
        parts: [
          { blank: 'Le' },
          { t: ' canari', u: true },
          { t: ' picore ' },
          { blank: 'l’' },
          { t: ' épinard.' },
        ],
        sentence: 'Le canari picore l’épinard.',
      },
      {
        parts: [
          { t: 'Emilie partage ' },
          { blank: 'le' },
          { t: ' cookie', u: true },
          { t: ' avec son ami.' },
        ],
        sentence: 'Emilie partage le cookie avec son ami.',
      },
      {
        parts: [
          { t: 'Lili n’aime pas ' },
          { blank: 'le' },
          { t: ' briquet', u: true },
          { t: ' gris.' },
        ],
        sentence: 'Lili n’aime pas le briquet gris.',
      },
      {
        parts: [
          { blank: 'La' },
          { t: ' jolie girafe', u: true },
          { t: ' visite ' },
          { blank: 'les' },
          { t: ' îles de Sion.' },
        ],
        sentence: 'La jolie girafe visite les îles de Sion.',
      },
    ],
    countPhrases: ["La fille visite la ville avec son ami.", "Le piano joue une jolie mélodie.", "Elise met une chemise grise dans sa valise.", "Qui a mis le crayon ici ?", "La vitrine est remplie de figurines d’animaux.", "Michel n’a pas fini son bol de riz."],
    readPhrases: [
      "Elle fait un exercice difficile.",
      "Lili choisit une jolie tulipe.",
      "Le cuisinier prépare du riz et des épinards.",
      "J’admire les photographies.",
      "Iris lit un livre illustré.",
      "La jolie fille colorie une image.",
      "Dimitri finit son dîner dans huit minutes.",
      "La petite souris grignote du riz.",
      "Il choisit des lilas et des jonquilles.",
      "Nina a mis une liste sur la vitre.",
      "Le pirate visite une île.",
      "La souris file dans la cuisine.",
      "Mimi porte un costume gris.",
      "Emilie dessine une pie et un dinosaure.",
      "La rapide fourmi transporte des sucreries.",
      "Rémi est timide quand il imite le tigre.",
      "Le tigre dort dans la jungle silencieuse.",
      "Iris lit une histoire dans son lit.",
      "Le kiwi vert est trop acide pour Julie.",
      "Philippe range six livres sur l’étagère.",
      "La cerise tombe vite de l’arbre.",
      "Le mini robot vibre près de la pile.",
      "Le briquet est sur la table grise.",
      "Le cookie est trop sucré pour Lili.",
      "Le canari chante près de la fenêtre.",
      "L’épinard est dans le panier.",
      "Le citron est très acide.",
      "La viande est dans le frigo.",
      "Le hérisson se cache sous les feuilles.",
      "Le navire avance sur la mer.",
      "Le hibou crie dans la nuit.",
      "Nina visite la ville avec son ami.",
      "Le piano joue une jolie mélodie.",
      "Qui a mis le crayon ici ?",
      "La vitrine est remplie de figurines.",
      "Michel n’a pas fini son bol de riz.",
      "Emilie partage le cookie avec son ami.",
      "Le pirate cherche une île déserte.",
      "Iris choisit une chemise grise.",
      "La fille visite la piscine le midi.",
      "Dimitri imite le cri du tigre.",
      "Le livre illustré est sur le lit.",
      "Mimi finit son exercice difficile.",
      "La souris file vite dans le nid.",
      "Philippe lit six pages du livre.",
      "Le citron vert est dans l’assiette.",
      "Iris range sa chemise dans la valise.",
      "Le kiwi est posé près du riz.",
      "La pie vole au-dessus de la ville.",
      "Rémi visite le musée avec Iris.",
    ],
    audioPairs: [
      { word: 'zipper', other: 'panier' },
      { word: 'tennis', other: 'surligneur' },
      { word: 'penderie', other: 'zipper' },
      { word: 'panier', other: 'tennis' },
      { word: 'surligneur', other: 'vitrine' },
      { word: 'vitrine', other: 'penderie' },
      { word: 'soulier', other: 'grizzly' },
      { word: 'grizzly', other: 'soulier' },
    ],
    syllableItems: [
      { word: 'Artichaut', parts: ['Ar', 'ti', 'chaut'] },
      { word: 'Mixeur', parts: ['Mi', 'xeur'] },
      { word: 'Balai', parts: ['Ba', 'lai'] },
      { word: 'glacier', parts: ['gla', 'cier'] },
      { word: 'moustique', parts: ['mous', 'tique'] },
      { word: 'clarinette', parts: ['cla', 'ri', 'nette'] },
      { word: 'cassis', parts: ['cas', 'sis'] },
      { word: 'imprimante', parts: ['im', 'pri', 'mante'] },
      { word: 'kangourou', parts: ['kan', 'gou', 'rou'] },
      { word: 'dentifrice', parts: ['den', 'ti', 'frice'] },
      { word: 'frite', parts: ['fri', 'te'] },
      { word: 'chien', parts: ['chien'] },
    ],
    orderSentences: [
      [
        'Nina/nom',
        'a/verbe',
        'mis/verbe',
        'une/determinant',
        'liste/nom',
        'sur/preposition',
        'la/determinant',
        'vitre./nom',
      ],
      [
        'Michel/nom',
        'n’a/verbe',
        'pas/negation',
        'fini/verbe',
        'son/determinant',
        'bol/nom',
        'de/preposition',
        'riz./nom',
      ],
      [
        'La/determinant',
        'fille/nom',
        'visite/verbe',
        'la/determinant',
        'ville/nom',
        'avec/preposition',
        'son/determinant',
        'ami./nom',
      ],
      [
        'Qui/pronom',
        'a/verbe',
        'mis/verbe',
        'le/determinant',
        'crayon/nom',
        'ici/adverbe',
        '?/interjection',
      ],
      [
        'Emilie/nom',
        'partage/verbe',
        'le/determinant',
        'cookie/nom',
        'avec/preposition',
        'son/determinant',
        'ami./nom',
      ],
      [
        'L’/determinant',
        'hérisson/nom',
        'finit/verbe',
        'le/determinant',
        'citron./nom',
      ],
    ],
    wordSearchWords: [
      'visite',
      'ville',
      'cerise',
      'hérisson',
      'citron',
      'tigre',
      'kiwi',
      'pirate',
      'cuisine',
      'souris',
      'image',
      'liste',
      'vitre',
      'ami',
      'fille',
      'dinosaure',
    ],
  },
  {
    id: 'u',
    topic: 'soutien-u',
    letterUpper: 'U',
    letterLower: 'u',
    sound: '/y/',
    label: 'Voyelle U',
    graphemes: ["u", "û"],
    words: ["alumette", "voiture", "jumelles", "laitue", "jus", "buffet", "usine", "flûte", "fruit", "ambulance", "zébu", "jupe", "chaussure", "tulipe", "bus", "légume"],
    syllables: ["mu", "nu", "tu", "pu", "vu", "bu", "cu", "ru", "lu", "su", "qud", "nub", "utut", "pup", "vur", "mudu", "fug", "fudu", "sutu", "muc", "um", "up", "ul", "nu", "tu", "ru", "us", "mu", "uq", "lu"],
    compounds: [
      { parts: ['a', 'lumette'] as const, word: 'alumette' },
      { parts: ['voi', 'ture'] as const, word: 'voiture' },
      { parts: ['ju', 'melles'] as const, word: 'jumelles' },
      { parts: ['lai', 'tue'] as const, word: 'laitue' },
      { parts: ['buf', 'fet'] as const, word: 'buffet' },
      { parts: ['u', 'sine'] as const, word: 'usine' },
      { parts: ['tu', 'lipe'] as const, word: 'tulipe' },
      { parts: ['chaus', 'sure'] as const, word: 'chaussure' },
      { parts: ['lé', 'gume'] as const, word: 'légume' },
      { parts: ['am', 'bulance'] as const, word: 'ambulance' },
    ],
    completes: [
      { article: 'Un', word: 'uniforme', before: '', blank: 'u', after: 'niforme' },
      { article: 'Une', word: 'sucette', before: '', blank: 'su', after: 'cette' },
      { article: 'Un', word: 'biscuit', before: '', blank: 'bis', after: 'cuit' },
      { article: 'Une', word: 'prune', before: '', blank: 'pru', after: 'ne' },
      { article: 'Un', word: 'nuage', before: '', blank: 'nu', after: 'age' },
      { article: 'Une', word: 'huile', before: '', blank: 'hui', after: 'le' },
      { article: 'Une', word: 'plume', before: '', blank: 'plu', after: 'me' },
      { article: 'Un', word: 'muguet', before: '', blank: 'mu', after: 'guet' },
      { article: 'Une', word: 'luciole', before: '', blank: 'lu', after: 'ciole' },
      { article: 'Une', word: 'peinture', before: 'pein', blank: 'tu', after: 're' },
    ],
    scrambles: [
      { sentence: 'La dune surplombe un petit refuge', word: 'dune', letters: 'UNED' },
      { sentence: 'Le minuscule walrus nage sous la brume', word: 'walrus', letters: 'ALRUSW' },
      { sentence: 'Un ruisseau murmure dans la verdure', word: 'ruisseau', letters: 'UISSEAUR' },
      { sentence: 'La méduse est curieuse et rusée', word: 'méduse', letters: 'ÉDUSEM' },
      { sentence: 'Les joueurs musclés de rugby courent sous la pluie', word: 'rugby', letters: 'UGBYR' },
      { sentence: 'Mon pull turquoise est unique', word: 'pull', letters: 'ULLP' },
      { sentence: 'Le musicien joue du tuba dans la rue', word: 'musicien', letters: 'USICIENM' },
      { sentence: 'Le nuage cache le soleil', word: 'nuage', letters: 'UAGEN' },
      { sentence: 'Une prune mûre tombe du prunier', word: 'prune', letters: 'RUNEP' },
      { sentence: 'Le bus s’arrête devant l’école', word: 'bus', letters: 'USB' },
      { sentence: 'Lucas boit un jus d’orange', word: 'jus', letters: 'USJ' },
      { sentence: 'La lune brille dans la nuit', word: 'lune', letters: 'UNEL' },
      { sentence: 'Le pull bleu est trop grand', word: 'bleu', letters: 'LEUB' },
      { sentence: 'Une tortue avance vers le rivage', word: 'tortue', letters: 'ORTUET' },
      { sentence: 'Le cube rouge est sous la table', word: 'cube', letters: 'UBEC' },
      { sentence: 'Ursule ouvre le tube de colle', word: 'tube', letters: 'UBET' },
      { sentence: 'Le dessert sucré plaît aux enfants', word: 'sucré', letters: 'UCRÉS' },
      { sentence: 'Un murmure court dans la salle', word: 'murmure', letters: 'URMUREM' },
      { sentence: 'La bulle d’air monte dans l’eau', word: 'bulle', letters: 'ULLEB' },
      { sentence: 'Le fruit juteux est sur l’assiette', word: 'fruit', letters: 'RUITF' },
      { sentence: 'Hugo porte un costume sombre', word: 'costume', letters: 'OSTUMEC' },
      { sentence: 'La plume flotte dans le vent', word: 'plume', letters: 'LUMEP' },
      { sentence: 'Le bureau est rangé et propre', word: 'bureau', letters: 'UREAUB' },
      { sentence: 'Une fusée part vers la Lune', word: 'fusée', letters: 'USÉEF' },
      { sentence: 'Le tuba joue une courte note', word: 'tuba', letters: 'UBAT' },
    ],
    determinants: [
      {
        parts: [{ blank: 'Le' }, { t: ' nuage', u: true }, { t: ' obscur couvre la lune.' }],
        sentence: 'Le nuage obscur couvre la lune.',
      },
      {
        parts: [{ blank: 'Les' }, { t: ' prunes', u: true }, { t: ' mûres sont dans le fruitier.' }],
        sentence: 'Les prunes mûres sont dans le fruitier.',
      },
      {
        parts: [{ blank: 'Le' }, { t: ' muguet', u: true }, { t: ' parfumé pousse dans la nature.' }],
        sentence: 'Le muguet parfumé pousse dans la nature.',
      },
      {
        parts: [{ blank: 'L’' }, { t: ' uniforme', u: true }, { t: ' écru est devenu trop court.' }],
        sentence: 'L’uniforme écru est devenu trop court.',
      },
      {
        parts: [{ blank: 'La' }, { t: ' plume', u: true }, { t: ' brune tombe sur le mur.' }],
        sentence: 'La plume brune tombe sur le mur.',
      },
      {
        parts: [{ blank: 'Les' }, { t: ' biscuits', u: true }, { t: ' sucrés sont sur le bureau.' }],
        sentence: 'Les biscuits sucrés sont sur le bureau.',
      },
      {
        parts: [
          { blank: 'La' },
          { t: ' peinture', u: true },
          { t: ' de la sucette brille dans la nuit.' },
        ],
        sentence: 'La peinture de la sucette brille dans la nuit.',
      },
      {
        parts: [{ blank: 'L’' }, { t: ' huile', u: true }, { t: ' pure est utile en cuisine.' }],
        sentence: 'L’huile pure est utile en cuisine.',
      },
    ],
    countPhrases: ["La fusée monte au-dessus des nuages.", "Le renard a trouvé une plume brune.", "La musique résonne dans la rue.", "Une tortue avance doucement sous la pluie.", "Le juge écoute le début du procès.", "Le curé discute avec plusieurs habitants du village."],
    readPhrases: [
      "Ursula porte une jupe sur mesure.",
      "Le début du film surprend le public.",
      "Le costume du danseur est de couleur prune.",
      "Luc ajoute du sucre dans son jus.",
      "La bûche brûle dans la cheminée.",
      "Un curieux étudiant observe la plume tomber.",
      "Julie écoute de la musique dans sa voiture.",
      "Il cherche une solution pour aller sur la lune.",
      "Les cuisiniers épluchent des légumes.",
      "La pluie tombe sur les tuiles.",
      "Le futur médecin étudie beaucoup.",
      "Une tortue se réfugie sous un buisson.",
      "Au menu, il y a des fruits et des légumes.",
      "Le bus passe dans un tunnel.",
      "La lumière du soleil illumine la clôture.",
      "Lucie ne met pas sa couverture la nuit.",
      "La prune mûre tombe du prunier.",
      "Luc range son pull turquoise dans l’armoire.",
      "Une plume flotte au-dessus du mur.",
      "Le biscuit sucré fond dans la bouche.",
      "La dune surplombe le rivage.",
      "Une huile parfumée coule dans la casserole.",
      "L’uniforme est propre et rangé.",
      "La sucette est trop sucrée.",
      "Le nuage cache le soleil.",
      "Le muguet parfumé pousse au jardin.",
      "La luciole brille dans la nuit.",
      "La peinture est encore fraîche.",
      "Le pull turquoise est unique.",
      "La fusée monte au-dessus des nuages.",
      "Le juge écoute le début du procès.",
      "Le curé discute avec plusieurs habitants.",
      "Une tortue avance doucement sous la pluie.",
      "La musique résonne dans la rue.",
      "Julie boit son jus dans la cuisine.",
      "Luc pose la plume sur le bureau.",
      "Le bus s’arrête près du parc public.",
      "Ursula lit un livre sous la lune.",
      "La jupe bleue est sur le lit.",
      "Le sucre fond dans le jus chaud.",
      "Lucie range les légumes dans le frigo.",
      "Une dune de sable borde la plage.",
      "Le nuage gris passe au-dessus du mur.",
      "Julie porte une jupe prune.",
      "Le tunnel est long et obscur.",
      "Luc écoute la musique du futur.",
      "La tortue nage sous le buisson d’eau.",
      "Ursula ajoute du sucre dans le pudding.",
      "Le public applaudit le début du spectacle.",
      "Julie observe la plume tomber du nid.",
    ],
    audioPairs: [
      { word: 'huitre', other: 'lunette' },
      { word: 'calculatrice', other: 'huitre' },
      { word: 'bulldozer', other: 'calculatrice' },
      { word: 'bureau', other: 'juge' },
      { word: 'libellule', other: 'cuisinière' },
      { word: 'cuisinière', other: 'libellule' },
      { word: 'lunette', other: 'bureau' },
      { word: 'juge', other: 'bulldozer' },
    ],
    syllableItems: [
      { word: 'agriculteur', parts: ['a', 'gri', 'cul', 'teur'] },
      { word: 'peluche', parts: ['pe', 'luche'] },
      { word: 'balai', parts: ['ba', 'lai'] },
      { word: 'ciseaux', parts: ['ci', 'seaux'] },
      { word: 'surligneur', parts: ['sur', 'li', 'gneur'] },
      { word: 'clarinette', parts: ['cla', 'ri', 'nette'] },
      { word: 'gazoduc', parts: ['ga', 'zo', 'duc'] },
      { word: 'écureuil', parts: ['é', 'cu', 'reuil'] },
      { word: 'tortue', parts: ['tor', 'tue'] },
      { word: 'culotte', parts: ['cu', 'lotte'] },
      { word: 'hirondelle', parts: ['hi', 'ron', 'delle'] },
      { word: 'fusée', parts: ['fu', 'sée'] },
    ],
    orderSentences: [
      [
        'Luc/nom',
        'ajoute/verbe',
        'du/determinant',
        'sucre/nom',
        'dans/preposition',
        'son/determinant',
        'jus./nom',
      ],
      [
        'Le/determinant',
        'renard/nom',
        'a/verbe',
        'trouvé/verbe',
        'une/determinant',
        'plume/nom',
        'brune./adjectif',
      ],
      [
        'Au/preposition',
        'menu,/nom',
        'il/pronom',
        'y/pronom',
        'a/verbe',
        'des/determinant',
        'fruits/nom',
        'et/conjonction',
        'des/determinant',
        'légumes./nom',
      ],
      [
        'La/determinant',
        'jupe/nom',
        'bleue/adjectif',
        'est/verbe',
        'sur/preposition',
        'le/determinant',
        'lit./nom',
      ],
      [
        'Le/determinant',
        'bus/nom',
        'passe/verbe',
        'dans/preposition',
        'la/determinant',
        'rue./nom',
      ],
      [
        'Une/determinant',
        'tulipe/nom',
        'pousse/verbe',
        'dans/preposition',
        'le/determinant',
        'jardin./nom',
      ],
    ],
    wordSearchWords: [
      'sucre',
      'plume',
      'lune',
      'jupe',
      'bus',
      'tunnel',
      'fruit',
      'légume',
      'tortue',
      'musique',
      'uniforme',
      'muguet',
      'nuage',
      'bureau',
      'prune',
      'jus',
    ],
  },
  {
    id: 'e',
    topic: 'soutien-e',
    letterUpper: 'E',
    letterLower: 'e',
    sound: '/ə/',
    label: 'Voyelle E',
    graphemes: ["e", "é", "è", "ê", "ë"],
    words: ["biberon", "renard", "cheval", "semelle", "brebis", "genou", "recyclage", "cheminée", "chenille", "meringue", "enveloppe", "semaine", "secrétaire", "cerise", "fenouil", "cheveux"],
    syllables: ["me", "ne", "te", "pe", "ve", "be", "ce", "re", "le", "se", "kede", "fel", "pefe", "zev", "ned", "mebe", "rep", "tepe", "eve", "jede", "fe", "je", "qe", "eg", "de", "er", "el", "es", "ez", "eq"],
    compounds: [
      { parts: ['bi', 'beron'] as const, word: 'biberon' },
      { parts: ['re', 'nard'] as const, word: 'renard' },
      { parts: ['che', 'val'] as const, word: 'cheval' },
      { parts: ['se', 'melle'] as const, word: 'semelle' },
      { parts: ['bre', 'bis'] as const, word: 'brebis' },
      { parts: ['ge', 'nou'] as const, word: 'genou' },
      { parts: ['re', 'cyclage'] as const, word: 'recyclage' },
      { parts: ['che', 'minée'] as const, word: 'cheminée' },
      { parts: ['se', 'maine'] as const, word: 'semaine' },
      { parts: ['ce', 'rise'] as const, word: 'cerise' },
    ],
    completes: [
      { article: 'Une', word: 'crevette', before: '', blank: 'cre', after: 'vette' },
      { article: 'Une', word: 'fenêtre', before: '', blank: 'fe', after: 'nêtre' },
      { article: 'Une', word: 'pelote', before: '', blank: 'pe', after: 'lote' },
      { article: 'Un', word: 'requin', before: '', blank: 're', after: 'quin' },
      { article: 'Une', word: 'recette', before: '', blank: 're', after: 'cette' },
      { article: 'Une', word: 'chemise', before: '', blank: 'che', after: 'mise' },
      { article: 'Une', word: 'peluche', before: '', blank: 'pe', after: 'luche' },
      { article: 'Une', word: 'grenade', before: '', blank: 'gre', after: 'nade' },
      { article: 'Un', word: 'chemin', before: '', blank: 'che', after: 'min' },
      { article: 'Un', word: 'repas', before: '', blank: 're', after: 'pas' },
    ],
    scrambles: [
      { sentence: 'Le melon n’est pas pour eux', word: 'melon', letters: 'ELONM' },
      { sentence: 'C’est le premier de la classe', word: 'premier', letters: 'REMIERP' },
      { sentence: 'Elle regarde la pelote de laine', word: 'regarde', letters: 'EGARDER' },
      { sentence: 'Le petit grelot a deux rubans', word: 'grelot', letters: 'RELOTG' },
      { sentence: 'Le venin de ce serpent est fort', word: 'venin', letters: 'ENINV' },
      { sentence: 'Le grenier est plein de vieux meubles', word: 'grenier', letters: 'RENIERG' },
      { sentence: 'La chenille trouve une cerise sur la pelouse', word: 'pelouse', letters: 'ELOUSEP' },
      { sentence: 'Le bébé dort dans son berceau', word: 'bébé', letters: 'ÉBÉB' },
      { sentence: 'Éva met la clé sous le paillasson', word: 'clé', letters: 'LÉC' },
      { sentence: 'Le vélo est devant l’école', word: 'vélo', letters: 'ÉLOV' },
      { sentence: 'Une cerise tombe de l’arbre', word: 'cerise', letters: 'ERISEC' },
      { sentence: 'Le bel éléphant marche lentement', word: 'éléphant', letters: 'LÉPHANTÉ' },
      { sentence: 'René boit du thé le matin', word: 'thé', letters: 'HÉT' },
      { sentence: 'La mer est calme ce soir', word: 'mer', letters: 'ERM' },
      { sentence: 'Le serpent se cache sous la pierre', word: 'serpent', letters: 'ERPENTS' },
      { sentence: 'Une étoile brille dans le ciel', word: 'étoile', letters: 'TOILEÉ' },
      { sentence: 'Le bel oiseau chante près de la fenêtre', word: 'oiseau', letters: 'ISEAUO' },
      { sentence: 'Hélène range ses cahiers', word: 'cahiers', letters: 'AHIERSC' },
      { sentence: 'Le dessert est prêt pour le goûter', word: 'dessert', letters: 'ESSERTD' },
      { sentence: 'La fenêtre est ouverte sur le jardin', word: 'fenêtre', letters: 'ENÊTREF' },
      { sentence: 'Le bel été dure longtemps', word: 'été', letters: 'TÉÉ' },
      { sentence: 'Une épée brille dans le musée', word: 'épée', letters: 'PÉEÉ' },
      { sentence: 'Le bel élève lit le texte', word: 'élève', letters: 'LÈVEÉ' },
      { sentence: 'La scène est prête pour le spectacle', word: 'scène', letters: 'CÈNES' },
      { sentence: 'Le bel écran montre un film', word: 'écran', letters: 'CRANÉ' },
    ],
    determinants: [
      {
        parts: [
          { t: 'Je me demande où se trouve ' },
          { blank: 'la' },
          { t: ' chemise', u: true },
          { t: ' bleue.' },
        ],
        sentence: 'Je me demande où se trouve la chemise bleue.',
      },
      {
        parts: [
          { t: 'Deux enfants regardent par ' },
          { blank: 'la' },
          { t: ' fenêtre', u: true },
          { t: '.' },
        ],
        sentence: 'Deux enfants regardent par la fenêtre.',
      },
      {
        parts: [
          { t: 'Je me lève pour manger ' },
          { blank: 'le' },
          { t: ' repas', u: true },
          { t: '.' },
        ],
        sentence: 'Je me lève pour manger le repas.',
      },
      {
        parts: [
          { t: 'Je mets ' },
          { blank: 'les' },
          { t: ' petites crevettes', u: true },
          { t: ' dans ' },
          { blank: 'le' },
          { t: ' feu.' },
        ],
        sentence: 'Je mets les petites crevettes dans le feu.',
      },
      {
        parts: [
          { blank: 'Le' },
          { t: ' chemin', u: true },
          { t: ' devient étroit après ' },
          { blank: 'le' },
          { t: ' cerisier.' },
        ],
        sentence: 'Le chemin devient étroit après le cerisier.',
      },
      {
        parts: [
          { t: 'Je veux ' },
          { blank: 'la' },
          { t: ' recette', u: true },
          { t: ' de gâteau de Déborah.' },
        ],
        sentence: 'Je veux la recette de gâteau de Déborah.',
      },
      {
        parts: [
          { blank: 'L’' },
          { t: ' oiseau', u: true },
          { t: ' se pose sur ' },
          { blank: 'la' },
          { t: ' peluche.' },
        ],
        sentence: 'L’oiseau se pose sur la peluche.',
      },
      {
        parts: [
          { t: 'Nous pesons ' },
          { blank: 'les' },
          { t: ' grenades', u: true },
          { t: ' sur ' },
          { blank: 'la' },
          { t: ' balance.' },
        ],
        sentence: 'Nous pesons les grenades sur la balance.',
      },
    ],
    countPhrases: ["Je veux acheter deux œufs.", "Ma mère mesure le niveau de l’eau.", "Vous semez les graines sur la pelouse ?", "Je peux mettre le jeu sur la table.", "Le cheval peut venir avec nous.", "Alicia n’est pas heureuse quand elle regarde le feu."],
    readPhrases: [
      "Le petit cheval regarde la grenouille.",
      "Je me demande ce que je vais faire ce soir.",
      "Le renard se promène le long de la rivière.",
      "Ce que tu me dis me semble étrange.",
      "Le redoutable chevalier se repose sur le sol.",
      "Le second chat retourne sur la pelouse.",
      "Je le retrouve devant le magasin de fleurs.",
      "Ne me dérange pas, je regarde le ciel se colorer.",
      "Que ferons-nous demain, se demande le fermier ?",
      "Le chemin de terre mène vers le reposant village.",
      "Ce remède laisse un léger regret.",
      "Le refuge du chevreau velu est près de la colline.",
      "Les revenants se retrouvent chaque nuit.",
      "Après le repas, le renard retourne à son refuge.",
      "Elle se remet de son retard.",
      "Je regarde le reflet de ma femme dans l’eau.",
      "Je veux acheter deux œufs.",
      "Ma mère mesure le niveau de l’eau.",
      "Vous semez les graines sur la pelouse ?",
      "Je peux mettre le jeu sur la table.",
      "Le cheval peut venir avec nous.",
      "Alicia n’est pas heureuse quand elle regarde le feu.",
      "Le repas est prêt pour le déjeuner.",
      "La fenêtre reste ouverte sur le jardin.",
      "Une crevette rose est dans l’assiette.",
      "Le chemin mène vers l’école du village.",
      "Elle prépare une recette avec des œufs.",
      "Le bébé regarde le feu dans la cheminée.",
      "La pelote de laine est sur la table.",
      "Le requin nage dans la mer.",
      "La chemise bleue est pliée.",
      "La peluche est sur le lit.",
      "La grenade est un fruit juteux.",
      "Le melon n’est pas pour eux.",
      "Le bébé dort dans son berceau.",
      "Le renard court dans le pré.",
      "Elle prépare le repas du soir.",
      "La fenêtre est ouverte sur le jardin.",
      "Je mets le jeu près de la fenêtre.",
      "Le cheval vient avec le fermier.",
      "Le chemin de terre est encore humide.",
      "Elle se lève tôt pour le repas.",
      "Le refuge est près de la rivière.",
      "Je regarde le ciel se colorer.",
      "Le remède est sur la table.",
      "La grenouille saute près de la pelouse.",
      "Le fermier seme les graines ce matin.",
      "Elle retrouve son ami devant le magasin.",
      "Le chevalier se repose après le repas.",
      "Je me demande ce que fera le renard.",
    ],
    audioPairs: [
      { word: 'médecin', other: 'relax' },
      { word: 'casserole', other: 'pansement' },
      { word: 'rejoindre', other: 'rejoindre' },
      { word: 'relax', other: 'sonnerie' },
      { word: 'pansement', other: 'médecin' },
      { word: 'reflet', other: 'remix' },
      { word: 'remix', other: 'reflet' },
      { word: 'sonnerie', other: 'casserole' },
    ],
    syllableItems: [
      { word: 'betterave', parts: ['bet', 'te', 'rave'] },
      { word: 'baignoire', parts: ['bai', 'gnoire'] },
      { word: 'madelaine', parts: ['ma', 'de', 'laine'] },
      { word: 'cadenas', parts: ['ca', 'de', 'nas'] },
      { word: 'harmonica', parts: ['har', 'mo', 'ni', 'ca'] },
      { word: 'fenouil', parts: ['fe', 'nouil'] },
      { word: 'hanneton', parts: ['han', 'ne', 'ton'] },
      { word: 'grenouille', parts: ['gre', 'nouille'] },
      { word: 'caleçon', parts: ['ca', 'le', 'çon'] },
      { word: 'coquelicot', parts: ['co', 'que', 'li', 'cot'] },
      { word: 'hexagone', parts: ['hex', 'a', 'gone'] },
      { word: 'cerise', parts: ['ce', 'rise'] },
    ],
    orderSentences: [
      [
        'Après/preposition',
        'le/determinant',
        'repas,/nom',
        'le/determinant',
        'renard/nom',
        'retourne/verbe',
        'à/preposition',
        'son/determinant',
        'refuge./nom',
      ],
      [
        'Elle/pronom',
        'se/pronom',
        'remet/verbe',
        'de/preposition',
        'son/determinant',
        'retard./nom',
      ],
      [
        'Le/determinant',
        'cheval/nom',
        'mange/verbe',
        'dans/preposition',
        'le/determinant',
        'pré./nom',
      ],
      [
        'La/determinant',
        'chenille/nom',
        'est/verbe',
        'sur/preposition',
        'la/determinant',
        'feuille./nom',
      ],
      [
        'Cette/determinant',
        'semaine,/nom',
        'je/pronom',
        'vais/verbe',
        'à/preposition',
        'l’école./nom',
      ],
      [
        'Le/determinant',
        'menu/nom',
        'est/verbe',
        'sur/preposition',
        'la/determinant',
        'table./nom',
      ],
    ],
    wordSearchWords: [
      'renard',
      'cheval',
      'chenille',
      'semaine',
      'fenêtre',
      'repas',
      'refuge',
      'pelouse',
      'grenouille',
      'ferme',
      'chemin',
      'crevette',
      'recette',
      'médecin',
      'enveloppe',
      'cerise',
    ],
  },
  {
    id: 'y',
    topic: 'soutien-y',
    letterUpper: 'Y',
    letterLower: 'y',
    sound: '/i/',
    label: 'Voyelle Y',
    graphemes: ["y"],
    words: ["stylo", "pyjama", "bicyclette", "cygne", "gymnaste", "pyramide", "encyclopédie", "myrtille", "cyclone", "gymnase", "mythologie", "dyslexie", "hydrogène", "motocyclette", "hygiène", "cylindre"],
    syllables: ["my", "ny", "ty", "yp", "vy", "yb", "yk", "ys", "ly", "zy", "myk", "tyf", "pyzy", "vyl", "ysyd", "ykyr", "fyby", "ryta", "ysny", "yrpy", "yf", "yl", "ys", "ny", "qy", "dy", "yj", "my", "yg", "ry"],
    compounds: [
      { parts: ['sty', 'lo'] as const, word: 'stylo' },
      { parts: ['py', 'jama'] as const, word: 'pyjama' },
      { parts: ['bicy', 'clette'] as const, word: 'bicyclette' },
      { parts: ['cy', 'gne'] as const, word: 'cygne' },
      { parts: ['gym', 'naste'] as const, word: 'gymnaste' },
      { parts: ['py', 'ramide'] as const, word: 'pyramide' },
      { parts: ['encyclo', 'pédie'] as const, word: 'encyclopédie' },
      { parts: ['myr', 'tille'] as const, word: 'myrtille' },
      { parts: ['cy', 'clone'] as const, word: 'cyclone' },
      { parts: ['gym', 'nase'] as const, word: 'gymnase' },
    ],
    completes: [
      { article: 'Un', word: 'stylo', before: '', blank: 'sty', after: 'lo' },
      { article: 'Un', word: 'pyjama', before: '', blank: 'py', after: 'jama' },
      { article: 'Une', word: 'bicyclette', before: '', blank: 'bi', after: 'cyclette' },
      { article: 'Un', word: 'cygne', before: '', blank: 'cy', after: 'gne' },
      { article: 'Un', word: 'gymnaste', before: '', blank: 'gym', after: 'naste' },
      { article: 'Une', word: 'pyramide', before: '', blank: 'py', after: 'ramide' },
      { article: 'Une', word: 'encyclopédie', before: 'ency', blank: 'clo', after: 'pédie' },
      { article: 'Une', word: 'myrtille', before: '', blank: 'myr', after: 'tille' },
      { article: 'Un', word: 'cyclone', before: '', blank: 'cy', after: 'clone' },
      { article: 'Un', word: 'gymnase', before: '', blank: 'gym', after: 'nase' },
    ],
    scrambles: [
      { sentence: 'Le papyrus est un vieux document', word: 'papyrus', letters: 'APYRUSP' },
      { sentence: 'Le gyrophare brille vite dans la nuit', word: 'gyrophare', letters: 'YROPHAREG' },
      { sentence: 'L’hydravion atterrit à midi', word: 'hydravion', letters: 'YDRAVIONH' },
      { sentence: 'La styliste dessine un bikini', word: 'styliste', letters: 'TYLISTES' },
      { sentence: 'Il est professeur de physique', word: 'physique', letters: 'HYSIQUEP' },
      { sentence: 'Le rugby est mon hobby favori', word: 'rugby', letters: 'UGBYR' },
      { sentence: 'L’Égypte a de grandes pyramides', word: 'Égypte', letters: 'GYPTEÉ' },
      { sentence: 'Le stylo est sur le bureau', word: 'stylo', letters: 'TYLOS' },
      { sentence: 'Yann joue du xylophone', word: 'xylophone', letters: 'YLOPHONEX' },
      { sentence: 'La pyramide est immense', word: 'pyramide', letters: 'YRAMIDEP' },
      { sentence: 'Le yoga calme les enfants', word: 'yoga', letters: 'OGAY' },
      { sentence: 'Un kayak glisse sur le lac', word: 'kayak', letters: 'AYAKK' },
      { sentence: 'La dynamo produit de l’électricité', word: 'dynamo', letters: 'YNAMOD' },
      { sentence: 'Le labyrinthe est difficile', word: 'labyrinthe', letters: 'ABYRINTHEL' },
      { sentence: 'Yves lit un mystère passionnant', word: 'mystère', letters: 'YSTÈREM' },
      { sentence: 'Le cycliste pédale très vite', word: 'cycliste', letters: 'YCLISTEC' },
      { sentence: 'Une lyre antique est au musée', word: 'lyre', letters: 'YREL' },
      { sentence: 'Le pyjama est confortable', word: 'pyjama', letters: 'YJAMAP' },
      { sentence: 'Le gypse est une pierre blanche', word: 'gypse', letters: 'YPSEG' },
      { sentence: 'Le cygne nage sur l’étang', word: 'cygne', letters: 'YGNEC' },
      { sentence: 'Maya boit un yaourt nature', word: 'yaourt', letters: 'AOURTY' },
      { sentence: 'Un hymne retentit dans la salle', word: 'hymne', letters: 'YMNEH' },
      { sentence: 'Le lynx observe la forêt', word: 'lynx', letters: 'YNXL' },
      { sentence: 'La typographie est soignée', word: 'typographie', letters: 'YPOGRAPHIET' },
      { sentence: 'Le synonyme est écrit au tableau', word: 'synonyme', letters: 'YNONYMES' },
    ],
    determinants: [
      {
        parts: [{ blank: 'Le' }, { t: ' labyrinthe', u: true }, { t: ' est si difficile.' }],
        sentence: 'Le labyrinthe est si difficile.',
      },
      {
        parts: [{ blank: 'La' }, { t: ' dynamo', u: true }, { t: ' produit de l’électricité.' }],
        sentence: 'La dynamo produit de l’électricité.',
      },
      {
        parts: [
          { t: 'Je sers ' },
          { blank: 'le' },
          { t: ' curry', u: true },
          { t: ' avec du riz.' },
        ],
        sentence: 'Je sers le curry avec du riz.',
      },
      {
        parts: [
          { t: 'Sur la piste, ' },
          { blank: 'le' },
          { t: ' cycliste', u: true },
          { t: ' roule très vite.' },
        ],
        sentence: 'Sur la piste, le cycliste roule très vite.',
      },
      {
        parts: [
          { blank: 'Le' },
          { t: ' papillon', u: true },
          { t: ' sort de ' },
          { blank: 'la' },
          { t: ' chrysalide.' },
        ],
        sentence: 'Le papillon sort de la chrysalide.',
      },
      {
        parts: [
          { blank: 'Le' },
          { t: ' python', u: true },
          { t: ' vit dans ' },
          { blank: 'la' },
          { t: ' rivière.' },
        ],
        sentence: 'Le python vit dans la rivière.',
      },
      {
        parts: [
          { t: 'Où est ' },
          { blank: 'le' },
          { t: ' whisky', u: true },
          { t: ' que tu as pris ?' },
        ],
        sentence: 'Où est le whisky que tu as pris ?',
      },
      {
        parts: [
          { t: 'Dans l’histoire, ' },
          { blank: 'les' },
          { t: ' cyclopes', u: true },
          { t: ' vivent dans des grottes.' },
        ],
        sentence: 'Dans l’histoire, les cyclopes vivent dans des grottes.',
      },
    ],
    countPhrases: ["Le gymnase est fermé aujourd'hui.", "Ce type d'oiseau vole trop vite.", "La glycémie de l’infirmière est stable.", "Ce polyglotte parle six langues différentes.", "Voici les règles d'hygiène du lycée.", "Je n’aime pas du tout la gymnastique."],
    readPhrases: [
      "Il y a un stylo, un livre et un pyjama ici.",
      "Mon ami a remis sa bicyclette à minuit.",
      "Le jury analyse le mystère de ce crime.",
      "À midi, il y a un joli cygne dans la ville.",
      "Le physicien étudie le système avec un style précis.",
      "Six amis roulent à motocyclette.",
      "Ce polygone a une belle symétrie.",
      "La cycliste et l’infirmière habitent près du lycée.",
      "La pyramide est immense et ancienne.",
      "Qui a pris mon cylindre gris ?",
      "Ils ont pris rapidement un tricycle.",
      "Son hobby favori, c’est la dactylo.",
      "La syllabe finale est difficile à lire.",
      "La fille lit un mythe ancien dans son lit.",
      "Quel type de films aimes-tu ?",
      "Le rythme de sa vie est calme.",
      "Le gymnase est fermé aujourd’hui.",
      "Ce type d’oiseau vole trop vite.",
      "La glycémie de l’infirmière est stable.",
      "Ce polyglotte parle six langues différentes.",
      "Voici les règles d’hygiène du lycée.",
      "Je n’aime pas du tout la gymnastique.",
      "Le stylo jaune est près du pyjama.",
      "La bicyclette rouge reste dans le garage.",
      "Le cygne nage sur l’étang du parc.",
      "La pyramide est dessinée dans le livre.",
      "Le cyclone approche de la côte.",
      "Yves range l’encyclopédie sur l’étagère.",
      "La myrtille est bleue et sucrée.",
      "Le gymnaste saute très haut.",
      "L’hydravion atterrit à midi.",
      "Le kayak glisse sur le lac.",
      "Yves lit un mythe dans son lit.",
      "Le lycée ouvre ses portes à huit heures.",
      "La syllabe « ly » est dans le mot lycée.",
      "Le rythme du tambour est rapide.",
      "Yves porte son pyjama le soir.",
      "La cycliste roule près du lycée.",
      "Le physicien mesure le système.",
      "Un tricycle est garé devant le gymnase.",
      "La dactylo travaille avec précision.",
      "Yves étudie la mythologie au lycée.",
      "Le cylindre gris est sur la table.",
      "La myrtille pousse près du chemin.",
      "Le type de stylo est important.",
      "Yves analyse le mystère du crime.",
      "La bicyclette est trop petite pour Yves.",
      "Le cygne blanc nage près du kayak.",
      "Yves range son stylo dans le pyjama.",
      "Le polygone a une symétrie parfaite.",
    ],
    audioPairs: [
      { word: 'sytème', other: 'typique' },
      { word: 'mystère', other: 'myopie' },
      { word: 'analyse', other: 'paysage' },
      { word: 'physicien', other: 'syllabe' },
    ],
    syllableItems: [
      { word: 'polygone', parts: ['po', 'ly', 'gone'] },
      { word: 'cyclisme', parts: ['cy', 'clisme'] },
      { word: 'polystyrène', parts: ['po', 'ly', 'sty', 'rène'] },
      { word: 'symétrie', parts: ['sy', 'mé', 'trie'] },
      { word: 'rythme', parts: ['ryth', 'me'] },
      { word: 'dynamite', parts: ['dy', 'na', 'mite'] },
      { word: 'recycler', parts: ['re', 'cy', 'cler'] },
      { word: 'oxygène', parts: ['ox', 'y', 'gène'] },
      { word: 'pyramide', parts: ['py', 'ra', 'mide'] },
      { word: 'stylo', parts: ['sty', 'lo'] },
      { word: 'cygne', parts: ['cy', 'gne'] },
      { word: 'gymnase', parts: ['gym', 'nase'] },
    ],
    orderSentences: [
      [
        'Il/pronom',
        'y/pronom',
        'a/verbe',
        'un/determinant',
        'stylo,/nom',
        'un/determinant',
        'livre/nom',
        'et/conjonction',
        'un/determinant',
        'pyjama/nom',
        'ici./adverbe',
      ],
      [
        'Mon/determinant',
        'ami/nom',
        'a/verbe',
        'remis/verbe',
        'sa/determinant',
        'bicyclette/nom',
        'à/preposition',
        'minuit./nom',
      ],
      [
        'À/preposition',
        'midi,/nom',
        'il/pronom',
        'y/pronom',
        'a/verbe',
        'un/determinant',
        'joli/adjectif',
        'cygne/nom',
        'dans/preposition',
        'la/determinant',
        'ville./nom',
      ],
      [
        'Ce/determinant',
        'polygone/nom',
        'a/verbe',
        'une/determinant',
        'belle/adjectif',
        'symétrie./nom',
      ],
      [
        'Qui/pronom',
        'a/verbe',
        'pris/verbe',
        'mon/determinant',
        'cylindre/nom',
        'gris/adjectif',
        '?/interjection',
      ],
      [
        'Son/determinant',
        'hobby/nom',
        'favori,/adjectif',
        'c’est/verbe',
        'la/determinant',
        'dactylo./nom',
      ],
    ],
    wordSearchWords: [
      'stylo',
      'pyjama',
      'bicyclette',
      'mystère',
      'cygne',
      'physique',
      'polygone',
      'symétrie',
      'cylindre',
      'lycée',
      'pyramide',
      'mythe',
      'rythme',
      'dactylo',
      'hobby',
      'système',
    ],
  },
]

export function soutienBankByTopic(topic: string): SoutienVowelBank | undefined {
  return SOUTIEN_VOWEL_BANKS.find((b) => b.topic === topic)
}

