/** Banque lecture soutien-scolaire : mots déjà découpés en phonèmes pédagogiques. */
export type LectureWordItem = {
  label: string
  phonemes: readonly string[]
}

export const LECTURE_WORD_ITEMS: readonly LectureWordItem[] = [
  { label: "abeille", phonemes: ["/a/", "/b/", "/ɛ/", "/j/"] },
  { label: "abricot", phonemes: ["/a/", "/b/", "/r/", "/i/", "/k/", "/o/"] },
  { label: "accordéon", phonemes: ["/a/", "/k/", "/o/", "/r/", "/d/", "/e/", "/ɔ̃/"] },
  { label: "acrylique", phonemes: ["/a/", "/k/", "/r/", "/i/", "/l/"] },
  { label: "activité", phonemes: ["/a/", "/k/", "/t/", "/i/", "/v/", "/e/"] },
  { label: "actrice", phonemes: ["/a/", "/k/", "/t/", "/r/", "/i/", "/s/"] },
  { label: "addition", phonemes: ["/a/", "/d/", "/i/", "/sjɔ̃/"] },
  { label: "agenda", phonemes: ["/a/", "/ʒ/", "/ɑ̃/", "/d/"] },
  { label: "agente-entretien", phonemes: ["/a/", "/ʒ/", "/ɑ̃/", "/t/", "/e/", "/r/", "/jɛ̃/"] },
  { label: "agricultrice", phonemes: ["/a/", "/g/", "/r/", "/i/", "/k/", "/y/", "/l/", "/t/", "/s/"] },
  { label: "aigle", phonemes: ["/ɛ/", "/g/", "/l/"] },
  { label: "ail", phonemes: ["/ɛ/", "/l/"] },
  { label: "album", phonemes: ["/a/", "/l/", "/b/", "/œ̃/"] },
  { label: "alimentation", phonemes: ["/a/", "/l/", "/i/", "/m/", "/ɑ̃/", "/t/", "/sjɔ̃/"] },
  { label: "aliments", phonemes: ["/a/", "/l/", "/i/", "/m/", "/ɑ̃/", "/t/"] },
  { label: "allumette", phonemes: ["/a/", "/l/", "/y/", "/m/", "/e/", "/t/"] },
  { label: "alphabet", phonemes: ["/a/", "/l/", "/f/", "/b/", "/e/"] },
  { label: "amazone", phonemes: ["/a/", "/m/", "/z/", "/o/", "/n/"] },
  { label: "ambulance", phonemes: ["/ɑ̃/", "/b/", "/y/", "/l/", "/s/"] },
  { label: "ami", phonemes: ["/a/", "/m/", "/i/"] },
  { label: "ananas", phonemes: ["/a/", "/n/", "/s/"] },
  { label: "animal", phonemes: ["/a/", "/n/", "/i/", "/m/", "/l/"] },
  { label: "animaux", phonemes: ["/a/", "/n/", "/i/", "/m/", "/o/"] },
  { label: "annexe", phonemes: ["/a/", "/n/", "/e/", "/ks/"] },
  { label: "appareil-photo", phonemes: ["/a/", "/p/", "/r/", "/ɛ/", "/j/", "/f/", "/o/", "/t/"] },
  { label: "araignée", phonemes: ["/a/", "/r/", "/ɛ/", "/ɲ/", "/e/"] },
  { label: "arbre", phonemes: ["/a/", "/r/", "/b/"] },
  { label: "arc", phonemes: ["/a/", "/r/", "/k/"] },
  { label: "architecte", phonemes: ["/a/", "/r/", "/ʃ/", "/i/", "/t/", "/e/", "/k/"] },
  { label: "ardoise", phonemes: ["/a/", "/r/", "/d/", "/wa/", "/z/"] },
  { label: "armoire", phonemes: ["/a/", "/r/", "/m/", "/wa/"] },
  { label: "arrosoir", phonemes: ["/a/", "/r/", "/o/", "/z/", "/wa/"] },
  { label: "artichaut", phonemes: ["/a/", "/r/", "/t/", "/i/", "/ʃ/", "/o/"] },
  { label: "asperge", phonemes: ["/a/", "/s/", "/p/", "/e/", "/r/", "/ʒ/"] },
  { label: "astronaute", phonemes: ["/a/", "/s/", "/t/", "/r/", "/o/", "/n/"] },
  { label: "astéroïde", phonemes: ["/a/", "/s/", "/t/", "/e/", "/r/", "/wa/", "/d/"] },
  { label: "atlas", phonemes: ["/a/", "/t/", "/l/"] },
  { label: "aubergine", phonemes: ["/o/", "/b/", "/e/", "/r/", "/ʒ/", "/i/", "/n/"] },
  { label: "autobus", phonemes: ["/o/", "/t/", "/b/", "/y/", "/s/"] },
  { label: "autruche", phonemes: ["/o/", "/t/", "/r/", "/y/", "/ʃ/"] },
  { label: "avion", phonemes: ["/a/", "/v/", "/i/", "/ɔ̃/"] },
  { label: "avocat", phonemes: ["/a/", "/v/", "/o/", "/k/"] },
  { label: "avocate", phonemes: ["/a/", "/v/", "/o/", "/k/", "/t/"] },
  { label: "azalée", phonemes: ["/a/", "/z/", "/l/", "/e/"] },
  { label: "azur", phonemes: ["/a/", "/z/", "/y/", "/r/"] },
  { label: "bague", phonemes: ["/b/", "/a/", "/g/"] },
  { label: "baignoire", phonemes: ["/b/", "/ɛ/", "/ɲ/", "/wa/", "/r/"] },
  { label: "balai", phonemes: ["/b/", "/a/", "/l/", "/ɛ/"] },
  { label: "balance", phonemes: ["/b/", "/a/", "/l/", "/ɑ̃/", "/s/"] },
  { label: "baleine", phonemes: ["/b/", "/a/", "/l/", "/ɛ/", "/n/"] },
  { label: "balle", phonemes: ["/b/", "/a/", "/l/"] },
  { label: "ballon", phonemes: ["/b/", "/a/", "/l/", "/ɔ̃/"] },
  { label: "bambou", phonemes: ["/b/", "/ɑ̃/", "/u/"] },
  { label: "banane", phonemes: ["/b/", "/a/", "/n/"] },
  { label: "banc", phonemes: ["/b/", "/ɑ̃/", "/k/"] },
  { label: "banjo", phonemes: ["/b/", "/ɑ̃/", "/ʒ/", "/o/"] },
  { label: "basilic", phonemes: ["/b/", "/a/", "/z/", "/i/", "/l/", "/k/"] },
  { label: "basketball", phonemes: ["/b/", "/a/", "/s/", "/k/", "/e/", "/t/", "/o/", "/l/"] },
  { label: "baskets", phonemes: ["/b/", "/a/", "/s/", "/k/", "/e/", "/t/"] },
  { label: "bateau", phonemes: ["/b/", "/a/", "/t/", "/o/"] },
  { label: "batte", phonemes: ["/b/", "/a/", "/t/"] },
  { label: "batterie", phonemes: ["/b/", "/a/", "/t/", "/e/", "/r/", "/i/"] },
  { label: "bazar", phonemes: ["/b/", "/a/", "/z/", "/r/"] },
  { label: "beige", phonemes: ["/b/", "/ɛ/", "/ʒ/"] },
  { label: "beignet", phonemes: ["/b/", "/ɛ/", "/ɲ/", "/e/"] },
  { label: "berceau", phonemes: ["/b/", "/e/", "/r/", "/s/", "/o/"] },
  { label: "betterave", phonemes: ["/b/", "/e/", "/t/", "/r/", "/a/", "/v/"] },
  { label: "beurre", phonemes: ["/b/", "/ø/", "/r/"] },
  { label: "biberon", phonemes: ["/b/", "/i/", "/e/", "/r/", "/ɔ̃/"] },
  { label: "bicyclette", phonemes: ["/b/", "/i/", "/s/", "/k/", "/l/", "/e/", "/t/"] },
  { label: "bijou", phonemes: ["/b/", "/i/", "/ʒ/", "/u/"] },
  { label: "billard", phonemes: ["/b/", "/j/", "/a/", "/r/"] },
  { label: "bille", phonemes: ["/b/", "/j/"] },
  { label: "biscuit", phonemes: ["/b/", "/i/", "/s/", "/k/", "/ɥi/"] },
  { label: "blanc", phonemes: ["/b/", "/l/", "/ɑ̃/", "/k/"] },
  { label: "bleu", phonemes: ["/b/", "/l/", "/ø/"] },
  { label: "bleuet", phonemes: ["/b/", "/l/", "/ø/", "/e/"] },
  { label: "blizzard", phonemes: ["/b/", "/l/", "/i/", "/z/", "/a/", "/r/"] },
  { label: "blouson", phonemes: ["/b/", "/l/", "/u/", "/z/", "/ɔ̃/"] },
  { label: "bocal", phonemes: ["/b/", "/o/", "/k/", "/a/", "/l/"] },
  { label: "boisson", phonemes: ["/b/", "/wa/", "/s/", "/ɔ̃/"] },
  { label: "bonbon", phonemes: ["/b/", "/ɔ̃/"] },
  { label: "bonnet", phonemes: ["/b/", "/o/", "/n/", "/e/"] },
  { label: "bordeaux", phonemes: ["/b/", "/o/", "/r/", "/d/"] },
  { label: "bottes", phonemes: ["/b/", "/o/", "/t/", "/e/"] },
  { label: "bottines", phonemes: ["/b/", "/o/", "/t/", "/i/", "/n/", "/e/"] },
  { label: "bouche", phonemes: ["/b/", "/u/", "/ʃ/"] },
  { label: "bouchère", phonemes: ["/b/", "/u/", "/ʃ/", "/e/", "/r/"] },
  { label: "boucles-d-oreilles", phonemes: ["/b/", "/u/", "/k/", "/l/", "/e/", "/s/", "/d/", "/o/", "/r/", "/ɛ/", "/j/"] },
  { label: "bougie", phonemes: ["/b/", "/u/", "/ʒ/", "/i/"] },
  { label: "boulangère", phonemes: ["/b/", "/u/", "/l/", "/ɑ̃/", "/ʒ/", "/e/", "/r/"] },
  { label: "bouleau", phonemes: ["/b/", "/u/", "/l/", "/o/"] },
  { label: "bouquet", phonemes: ["/b/", "/u/", "/k/", "/e/"] },
  { label: "boussole", phonemes: ["/b/", "/u/", "/s/", "/o/", "/l/"] },
  { label: "bouteille", phonemes: ["/b/", "/u/", "/t/", "/ɛ/", "/j/"] },
  { label: "bouteille-deau", phonemes: ["/b/", "/u/", "/t/", "/ɛ/", "/j/", "/e/", "/d/", "/o/"] },
  { label: "boutique", phonemes: ["/b/", "/u/", "/t/", "/i/", "/k/"] },
  { label: "bowling", phonemes: ["/b/", "/o/", "/w/", "/l/", "/ɛ̃/"] },
  { label: "boxe", phonemes: ["/b/", "/o/", "/ks/"] },
  { label: "boxeur", phonemes: ["/b/", "/o/", "/ks/", "/ø/", "/r/"] },
  { label: "boîte", phonemes: ["/b/", "/wa/", "/t/"] },
  { label: "bracelet", phonemes: ["/b/", "/r/", "/a/", "/s/", "/e/", "/l/"] },
  { label: "bras", phonemes: ["/b/", "/r/", "/a/"] },
  { label: "briquet", phonemes: ["/b/", "/r/", "/i/", "/k/", "/e/"] },
  { label: "brocoli", phonemes: ["/b/", "/r/", "/o/", "/k/", "/l/", "/i/"] },
  { label: "bronze", phonemes: ["/b/", "/r/", "/ɔ̃/", "/z/"] },
  { label: "brosse", phonemes: ["/b/", "/r/", "/o/", "/s/"] },
  { label: "brosse-a-dents", phonemes: ["/b/", "/r/", "/o/", "/s/", "/e/", "/a/", "/d/", "/ɑ̃/", "/t/"] },
  { label: "brouette", phonemes: ["/b/", "/r/", "/w/", "/e/", "/t/"] },
  { label: "brownie", phonemes: ["/b/", "/r/", "/o/", "/w/", "/n/", "/i/"] },
  { label: "brun", phonemes: ["/b/", "/r/", "/œ̃/"] },
  { label: "buffet", phonemes: ["/b/", "/y/", "/f/", "/e/"] },
  { label: "bulldozer", phonemes: ["/b/", "/y/", "/l/", "/d/", "/o/", "/z/", "/e/", "/r/"] },
  { label: "bungalow", phonemes: ["/b/", "/œ̃/", "/g/", "/a/", "/l/", "/o/", "/w/"] },
  { label: "bureau", phonemes: ["/b/", "/y/", "/r/", "/o/"] },
  { label: "bus", phonemes: ["/b/", "/y/", "/s/"] },
  { label: "but", phonemes: ["/b/", "/y/"] },
  { label: "bébé", phonemes: ["/b/", "/e/"] },
  { label: "béret", phonemes: ["/b/", "/e/", "/r/"] },
  { label: "cadeau", phonemes: ["/k/", "/a/", "/d/", "/o/"] },
  { label: "cadenas", phonemes: ["/k/", "/a/", "/d/", "/e/", "/n/"] },
  { label: "café", phonemes: ["/k/", "/a/", "/f/", "/e/"] },
  { label: "cahier", phonemes: ["/k/", "/a/", "/∅/", "/j/", "/e/"] },
  { label: "caissière", phonemes: ["/k/", "/ɛ/", "/s/", "/i/", "/e/", "/r/"] },
  { label: "calculatrice", phonemes: ["/k/", "/a/", "/l/", "/y/", "/t/", "/r/", "/i/", "/s/"] },
  { label: "caleçon", phonemes: ["/k/", "/a/", "/l/", "/e/", "/ɔ̃/"] },
  { label: "camion", phonemes: ["/k/", "/a/", "/m/", "/i/", "/ɔ̃/"] },
  { label: "campagne", phonemes: ["/k/", "/ɑ̃/", "/p/", "/a/", "/ɲ/"] },
  { label: "caméléon", phonemes: ["/k/", "/a/", "/m/", "/e/", "/l/", "/ɔ̃/"] },
  { label: "canard", phonemes: ["/k/", "/a/", "/n/", "/r/"] },
  { label: "canari", phonemes: ["/k/", "/a/", "/n/", "/r/", "/i/"] },
  { label: "canyon", phonemes: ["/k/", "/a/", "/n/", "/i/", "/ɔ̃/"] },
  { label: "caravane", phonemes: ["/k/", "/a/", "/r/", "/v/", "/n/"] },
  { label: "carotte", phonemes: ["/k/", "/a/", "/r/", "/o/", "/t/"] },
  { label: "carré", phonemes: ["/k/", "/a/", "/r/", "/e/"] },
  { label: "cartable", phonemes: ["/k/", "/a/", "/r/", "/t/", "/b/", "/l/"] },
  { label: "carte", phonemes: ["/k/", "/a/", "/r/", "/t/"] },
  { label: "carte-de-credit", phonemes: ["/k/", "/a/", "/r/", "/t/", "/e/", "/d/", "/i/"] },
  { label: "carte-detudiant", phonemes: ["/k/", "/a/", "/r/", "/t/", "/e/", "/d/", "/y/", "/i/", "/ɑ̃/"] },
  { label: "carte-didentite", phonemes: ["/k/", "/a/", "/r/", "/t/", "/e/", "/d/", "/i/", "/ɑ̃/"] },
  { label: "casque", phonemes: ["/k/", "/a/", "/s/"] },
  { label: "casquette", phonemes: ["/k/", "/a/", "/s/", "/e/", "/t/"] },
  { label: "cassis", phonemes: ["/k/", "/a/", "/s/", "/i/"] },
  { label: "ceinture", phonemes: ["/s/", "/ɛ̃/", "/t/", "/y/", "/r/"] },
  { label: "cerceau", phonemes: ["/s/", "/e/", "/r/", "/o/"] },
  { label: "cercle", phonemes: ["/s/", "/e/", "/r/", "/k/", "/l/"] },
  { label: "cerf", phonemes: ["/s/", "/e/", "/r/", "/f/"] },
  { label: "cerf-volant", phonemes: ["/s/", "/e/", "/r/", "/f/", "/v/", "/o/", "/l/", "/ɑ̃/"] },
  { label: "cerise", phonemes: ["/s/", "/e/", "/r/", "/i/", "/z/"] },
  { label: "cerisier", phonemes: ["/s/", "/e/", "/r/", "/i/", "/z/", "/j/"] },
  { label: "cerveau", phonemes: ["/s/", "/e/", "/r/", "/v/", "/o/"] },
  { label: "chaise", phonemes: ["/ʃ/", "/ɛ/", "/z/"] },
  { label: "chalet", phonemes: ["/ʃ/", "/a/", "/l/", "/e/"] },
  { label: "champ", phonemes: ["/ʃ/", "/ɑ̃/"] },
  { label: "champignon", phonemes: ["/ʃ/", "/ɑ̃/", "/p/", "/i/", "/ɲ/", "/ɔ̃/"] },
  { label: "chanteuse", phonemes: ["/ʃ/", "/ɑ̃/", "/t/", "/ø/", "/z/"] },
  { label: "chapeau", phonemes: ["/ʃ/", "/a/", "/p/", "/o/"] },
  { label: "chargeur", phonemes: ["/ʃ/", "/a/", "/r/", "/ʒ/", "/ø/"] },
  { label: "charpentière", phonemes: ["/ʃ/", "/a/", "/r/", "/p/", "/ɑ̃/", "/t/", "/i/", "/e/"] },
  { label: "chat", phonemes: ["/ʃ/", "/a/"] },
  { label: "chataignier", phonemes: ["/ʃ/", "/a/", "/t/", "/ɛ/", "/ɲ/", "/j/", "/e/"] },
  { label: "chaud", phonemes: ["/ʃ/", "/o/"] },
  { label: "chauffeuse", phonemes: ["/ʃ/", "/o/", "/f/", "/ø/", "/z/"] },
  { label: "chaussettes", phonemes: ["/ʃ/", "/o/", "/s/", "/e/", "/t/"] },
  { label: "chaussons", phonemes: ["/ʃ/", "/o/", "/s/", "/ɔ̃/"] },
  { label: "chaussures", phonemes: ["/ʃ/", "/o/", "/s/", "/y/", "/r/", "/e/"] },
  { label: "chaîne", phonemes: ["/ʃ/", "/ɛ/", "/n/"] },
  { label: "cheminée", phonemes: ["/ʃ/", "/e/", "/m/", "/i/", "/n/"] },
  { label: "chemise", phonemes: ["/ʃ/", "/e/", "/m/", "/i/", "/z/"] },
  { label: "chenille", phonemes: ["/ʃ/", "/e/", "/n/", "/j/"] },
  { label: "cheval", phonemes: ["/ʃ/", "/e/", "/v/", "/a/", "/l/"] },
  { label: "cheveux", phonemes: ["/ʃ/", "/e/", "/v/", "/ø/"] },
  { label: "chien", phonemes: ["/ʃ/", "/jɛ̃/"] },
  { label: "chips", phonemes: ["/ʃ/", "/i/", "/p/"] },
  { label: "chocolat", phonemes: ["/ʃ/", "/o/", "/k/", "/l/", "/a/"] },
  { label: "chocolat-chaud", phonemes: ["/ʃ/", "/o/", "/k/", "/l/", "/a/", "/t/"] },
  { label: "choix", phonemes: ["/ʃ/", "/wa/"] },
  { label: "chorizo", phonemes: ["/ʃ/", "/o/", "/r/", "/i/", "/z/"] },
  { label: "chou", phonemes: ["/ʃ/", "/u/"] },
  { label: "chou-fleur", phonemes: ["/ʃ/", "/u/", "/f/", "/l/", "/ø/", "/r/"] },
  { label: "chronomètre", phonemes: ["/ʃ/", "/r/", "/o/", "/n/", "/m/", "/e/", "/t/"] },
  { label: "chrysalide", phonemes: ["/ʃ/", "/r/", "/i/", "/z/", "/a/", "/l/", "/d/"] },
  { label: "chrysanthème", phonemes: ["/ʃ/", "/r/", "/i/", "/z/", "/ɑ̃/", "/t/", "/e/", "/m/"] },
  { label: "château", phonemes: ["/ʃ/", "/a/", "/t/", "/o/"] },
  { label: "chèvre", phonemes: ["/ʃ/", "/e/", "/v/", "/r/"] },
  { label: "chêne", phonemes: ["/ʃ/", "/e/", "/n/"] },
  { label: "cible", phonemes: ["/s/", "/i/", "/b/", "/l/"] },
  { label: "cigogne", phonemes: ["/s/", "/i/", "/g/", "/o/", "/ɲ/"] },
  { label: "cire", phonemes: ["/s/", "/i/", "/r/"] },
  { label: "ciseaux", phonemes: ["/s/", "/i/", "/z/", "/o/"] },
  { label: "citron", phonemes: ["/s/", "/i/", "/t/", "/r/", "/ɔ̃/"] },
  { label: "citronnade", phonemes: ["/s/", "/i/", "/t/", "/r/", "/o/", "/n/", "/a/", "/d/"] },
  { label: "citrouille", phonemes: ["/s/", "/i/", "/t/", "/r/", "/u/", "/j/"] },
  { label: "clarinette", phonemes: ["/k/", "/l/", "/a/", "/r/", "/i/", "/n/", "/e/", "/t/"] },
  { label: "classeur", phonemes: ["/k/", "/l/", "/a/", "/s/", "/ø/", "/r/"] },
  { label: "clavier", phonemes: ["/k/", "/l/", "/a/", "/v/", "/j/", "/e/"] },
  { label: "climatiseur", phonemes: ["/k/", "/l/", "/i/", "/m/", "/a/", "/t/", "/z/", "/ø/", "/r/"] },
  { label: "clou", phonemes: ["/k/", "/l/", "/u/"] },
  { label: "clown", phonemes: ["/k/", "/l/", "/o/", "/w/", "/n/"] },
  { label: "clémentine", phonemes: ["/k/", "/l/", "/e/", "/m/", "/ɑ̃/", "/t/", "/i/", "/n/"] },
  { label: "cobra", phonemes: ["/k/", "/o/", "/b/", "/r/", "/a/"] },
  { label: "coccinelle", phonemes: ["/k/", "/o/", "/s/", "/i/", "/n/", "/e/", "/l/"] },
  { label: "cochon", phonemes: ["/k/", "/o/", "/ʃ/", "/ɔ̃/"] },
  { label: "coeur", phonemes: ["/k/", "/ø/", "/r/"] },
  { label: "coffre", phonemes: ["/k/", "/o/", "/f/", "/r/"] },
  { label: "coiffeuse", phonemes: ["/k/", "/wa/", "/f/", "/ø/", "/z/"] },
  { label: "coin", phonemes: ["/k/", "/wɛ̃/"] },
  { label: "coing", phonemes: ["/k/", "/wɛ̃/"] },
  { label: "colibri", phonemes: ["/k/", "/o/", "/l/", "/i/", "/b/", "/r/"] },
  { label: "colle", phonemes: ["/k/", "/o/", "/l/"] },
  { label: "collier", phonemes: ["/k/", "/o/", "/l/", "/j/", "/e/"] },
  { label: "colline", phonemes: ["/k/", "/o/", "/l/", "/i/", "/n/"] },
  { label: "colombe", phonemes: ["/k/", "/o/", "/l/", "/ɔ̃/", "/b/"] },
  { label: "commode", phonemes: ["/k/", "/o/", "/m/", "/d/"] },
  { label: "compas", phonemes: ["/k/", "/ɔ̃/", "/p/", "/a/"] },
  { label: "comptoire", phonemes: ["/k/", "/ɔ̃/", "/p/", "/t/", "/wa/", "/r/"] },
  { label: "comète", phonemes: ["/k/", "/o/", "/m/", "/e/", "/t/"] },
  { label: "concombre", phonemes: ["/k/", "/ɔ̃/", "/b/", "/r/"] },
  { label: "confiture", phonemes: ["/k/", "/ɔ̃/", "/f/", "/i/", "/t/", "/y/", "/r/"] },
  { label: "cookie", phonemes: ["/k/", "/o/", "/i/"] },
  { label: "coq", phonemes: ["/k/", "/o/"] },
  { label: "coquelicot", phonemes: ["/k/", "/o/", "/e/", "/l/", "/i/"] },
  { label: "corail", phonemes: ["/k/", "/o/", "/r/", "/ɛ/", "/l/"] },
  { label: "corbeau", phonemes: ["/k/", "/o/", "/r/", "/b/"] },
  { label: "corde", phonemes: ["/k/", "/o/", "/r/", "/d/"] },
  { label: "corde-a-sauter", phonemes: ["/k/", "/o/", "/r/", "/d/", "/e/", "/a/", "/s/", "/t/"] },
  { label: "coriandre", phonemes: ["/k/", "/o/", "/r/", "/i/", "/ɑ̃/", "/d/"] },
  { label: "coton-tige", phonemes: ["/k/", "/o/", "/t/", "/ɔ̃/", "/i/", "/ʒ/"] },
  { label: "cou", phonemes: ["/k/", "/u/"] },
  { label: "courgette", phonemes: ["/k/", "/u/", "/r/", "/ʒ/", "/e/", "/t/"] },
  { label: "couronne", phonemes: ["/k/", "/u/", "/r/", "/o/", "/n/"] },
  { label: "course", phonemes: ["/k/", "/u/", "/r/", "/s/"] },
  { label: "couteau", phonemes: ["/k/", "/u/", "/t/", "/o/"] },
  { label: "cow-boy", phonemes: ["/k/", "/o/", "/w/", "/b/", "/i/"] },
  { label: "coyote", phonemes: ["/k/", "/o/", "/i/", "/t/"] },
  { label: "crabe", phonemes: ["/k/", "/r/", "/a/", "/b/"] },
  { label: "craie", phonemes: ["/k/", "/r/", "/ɛ/"] },
  { label: "crapaud", phonemes: ["/k/", "/r/", "/a/", "/p/", "/o/"] },
  { label: "cravate", phonemes: ["/k/", "/r/", "/a/", "/v/", "/t/"] },
  { label: "crayon", phonemes: ["/k/", "/r/", "/ɛ/", "/j/", "/ɔ̃/"] },
  { label: "crevette", phonemes: ["/k/", "/r/", "/e/", "/v/", "/t/"] },
  { label: "criquet", phonemes: ["/k/", "/r/", "/i/", "/e/"] },
  { label: "crocodile", phonemes: ["/k/", "/r/", "/o/", "/d/", "/i/", "/l/"] },
  { label: "croissant", phonemes: ["/k/", "/r/", "/wa/", "/s/", "/ɑ̃/"] },
  { label: "croix", phonemes: ["/k/", "/r/", "/wa/"] },
  { label: "crêpe", phonemes: ["/k/", "/r/", "/e/", "/p/"] },
  { label: "cube", phonemes: ["/k/", "/y/", "/b/"] },
  { label: "cuisinier", phonemes: ["/k/", "/ɥi/", "/z/", "/i/", "/n/", "/j/", "/e/"] },
  { label: "cuisinière", phonemes: ["/k/", "/ɥi/", "/z/", "/i/", "/n/", "/e/", "/r/"] },
  { label: "culotte", phonemes: ["/k/", "/y/", "/l/", "/o/", "/t/"] },
  { label: "cupcake", phonemes: ["/k/", "/y/", "/p/", "/a/"] },
  { label: "cyan", phonemes: ["/s/", "/i/", "/ɑ̃/"] },
  { label: "cyborg", phonemes: ["/s/", "/i/", "/b/", "/o/", "/r/"] },
  { label: "cyclone", phonemes: ["/s/", "/i/", "/k/", "/l/", "/o/", "/n/"] },
  { label: "cygne", phonemes: ["/s/", "/i/", "/ɲ/"] },
  { label: "cylindre", phonemes: ["/s/", "/i/", "/l/", "/ɛ̃/", "/d/", "/r/"] },
  { label: "cypres", phonemes: ["/s/", "/i/", "/p/", "/r/", "/e/"] },
  { label: "céleri", phonemes: ["/s/", "/e/", "/l/", "/r/", "/i/"] },
  { label: "cône", phonemes: ["/k/", "/o/", "/n/"] },
  { label: "danse", phonemes: ["/d/", "/ɑ̃/", "/s/"] },
  { label: "danseuse", phonemes: ["/d/", "/ɑ̃/", "/s/", "/ø/", "/z/"] },
  { label: "datte", phonemes: ["/d/", "/a/", "/t/"] },
  { label: "dauphin", phonemes: ["/d/", "/o/", "/f/", "/ɛ̃/"] },
  { label: "dent", phonemes: ["/d/", "/ɑ̃/"] },
  { label: "dentifrice", phonemes: ["/d/", "/ɑ̃/", "/t/", "/i/", "/f/", "/r/", "/s/"] },
  { label: "dentiste", phonemes: ["/d/", "/ɑ̃/", "/t/", "/i/", "/s/"] },
  { label: "deux", phonemes: ["/d/", "/ø/"] },
  { label: "dictionnaire", phonemes: ["/d/", "/i/", "/k/", "/sjɔ̃/", "/n/", "/ɛ/", "/r/"] },
  { label: "dimanche", phonemes: ["/d/", "/i/", "/m/", "/ɑ̃/", "/ʃ/"] },
  { label: "dinde", phonemes: ["/d/", "/ɛ̃/"] },
  { label: "dix", phonemes: ["/d/", "/i/"] },
  { label: "docteur", phonemes: ["/d/", "/o/", "/k/", "/t/", "/ø/", "/r/"] },
  { label: "dodo", phonemes: ["/d/", "/o/"] },
  { label: "doigt", phonemes: ["/d/", "/wa/"] },
  { label: "domino", phonemes: ["/d/", "/o/", "/m/", "/i/", "/n/"] },
  { label: "donut", phonemes: ["/d/", "/o/", "/n/", "/y/"] },
  { label: "dos", phonemes: ["/d/", "/o/"] },
  { label: "douche", phonemes: ["/d/", "/u/", "/ʃ/"] },
  { label: "doux", phonemes: ["/d/", "/u/"] },
  { label: "douze", phonemes: ["/d/", "/u/", "/z/"] },
  { label: "dragon", phonemes: ["/d/", "/r/", "/a/", "/g/", "/ɔ̃/"] },
  { label: "drapeau", phonemes: ["/d/", "/r/", "/a/", "/p/", "/o/"] },
  { label: "dune", phonemes: ["/d/", "/y/", "/n/"] },
  { label: "dynamite", phonemes: ["/d/", "/i/", "/n/", "/a/", "/m/", "/t/"] },
  { label: "dynamo", phonemes: ["/d/", "/i/", "/n/", "/a/", "/m/", "/o/"] },
  { label: "dé", phonemes: ["/d/", "/e/"] },
  { label: "déodorant", phonemes: ["/d/", "/e/", "/o/", "/r/", "/ɑ̃/"] },
  { label: "désert", phonemes: ["/d/", "/e/", "/z/", "/r/"] },
  { label: "eau", phonemes: ["/o/"] },
  { label: "edelweiss", phonemes: ["/e/", "/d/", "/l/", "/w/", "/ɛ/", "/s/"] },
  { label: "enceinte", phonemes: ["/ɑ̃/", "/s/", "/ɛ̃/", "/t/"] },
  { label: "encre", phonemes: ["/ɑ̃/", "/k/", "/r/"] },
  { label: "encyclopédie", phonemes: ["/ɑ̃/", "/s/", "/i/", "/k/", "/l/", "/o/", "/p/", "/e/", "/d/"] },
  { label: "entonnoir", phonemes: ["/ɑ̃/", "/t/", "/o/", "/n/", "/wa/", "/r/"] },
  { label: "enveloppe", phonemes: ["/ɑ̃/", "/v/", "/e/", "/l/", "/o/", "/p/"] },
  { label: "escalade", phonemes: ["/e/", "/s/", "/k/", "/a/", "/l/", "/d/"] },
  { label: "escalier", phonemes: ["/e/", "/s/", "/k/", "/a/", "/l/", "/j/"] },
  { label: "escargot", phonemes: ["/e/", "/s/", "/k/", "/a/", "/r/", "/g/", "/o/"] },
  { label: "extincteur", phonemes: ["/e/", "/ks/", "/t/", "/ɛ̃/", "/k/", "/ø/", "/r/"] },
  { label: "factrice", phonemes: ["/f/", "/a/", "/k/", "/t/", "/r/", "/i/", "/s/"] },
  { label: "falaise", phonemes: ["/f/", "/a/", "/l/", "/ɛ/", "/z/"] },
  { label: "farine", phonemes: ["/f/", "/a/", "/r/", "/i/", "/n/"] },
  { label: "faucon", phonemes: ["/f/", "/o/", "/k/", "/ɔ̃/"] },
  { label: "fauteuil", phonemes: ["/f/", "/o/", "/t/", "/ø/", "/j/"] },
  { label: "fax", phonemes: ["/f/", "/a/"] },
  { label: "femme", phonemes: ["/f/", "/e/", "/m/"] },
  { label: "fenouil", phonemes: ["/f/", "/e/", "/n/", "/u/", "/j/"] },
  { label: "fenêtre", phonemes: ["/f/", "/e/", "/n/", "/t/", "/r/"] },
  { label: "fermière", phonemes: ["/f/", "/e/", "/r/", "/m/", "/i/"] },
  { label: "ferry", phonemes: ["/f/", "/e/", "/r/", "/i/"] },
  { label: "feu", phonemes: ["/f/", "/ø/"] },
  { label: "feuille", phonemes: ["/f/", "/ø/", "/j/"] },
  { label: "feutre", phonemes: ["/f/", "/ø/", "/t/", "/r/"] },
  { label: "fez", phonemes: ["/f/", "/e/"] },
  { label: "figue", phonemes: ["/f/", "/i/", "/g/"] },
  { label: "filet", phonemes: ["/f/", "/i/", "/l/", "/e/"] },
  { label: "fille", phonemes: ["/f/", "/j/"] },
  { label: "flamant-rose", phonemes: ["/f/", "/l/", "/a/", "/m/", "/ɑ̃/", "/t/", "/r/", "/o/", "/z/"] },
  { label: "flamme", phonemes: ["/f/", "/l/", "/a/", "/m/"] },
  { label: "flan", phonemes: ["/f/", "/l/", "/ɑ̃/"] },
  { label: "fleur", phonemes: ["/f/", "/l/", "/ø/", "/r/"] },
  { label: "fleuriste", phonemes: ["/f/", "/l/", "/ø/", "/r/", "/i/", "/s/", "/t/"] },
  { label: "flocon", phonemes: ["/f/", "/l/", "/o/", "/k/", "/ɔ̃/"] },
  { label: "flux", phonemes: ["/f/", "/l/", "/y/"] },
  { label: "flèche", phonemes: ["/f/", "/l/", "/e/", "/ʃ/"] },
  { label: "flûte", phonemes: ["/f/", "/l/", "/y/", "/t/"] },
  { label: "foin", phonemes: ["/f/", "/wɛ̃/"] },
  { label: "football", phonemes: ["/f/", "/o/", "/t/", "/b/", "/a/", "/l/"] },
  { label: "forêt", phonemes: ["/f/", "/o/", "/r/", "/e/"] },
  { label: "foulard", phonemes: ["/f/", "/u/", "/l/", "/a/", "/r/"] },
  { label: "four", phonemes: ["/f/", "/u/", "/r/"] },
  { label: "fourmi", phonemes: ["/f/", "/u/", "/r/", "/m/", "/i/"] },
  { label: "foyer", phonemes: ["/f/", "/o/", "/i/", "/e/", "/r/"] },
  { label: "frais", phonemes: ["/f/", "/r/", "/ɛ/"] },
  { label: "fraise", phonemes: ["/f/", "/r/", "/ɛ/", "/z/"] },
  { label: "framboise", phonemes: ["/f/", "/r/", "/ɑ̃/", "/b/", "/wa/", "/z/"] },
  { label: "frites", phonemes: ["/f/", "/r/", "/i/", "/t/", "/e/"] },
  { label: "froid", phonemes: ["/f/", "/r/", "/wa/"] },
  { label: "fromage", phonemes: ["/f/", "/r/", "/o/", "/m/", "/a/", "/ʒ/"] },
  { label: "fruit", phonemes: ["/f/", "/r/", "/ɥi/"] },
  { label: "fusée", phonemes: ["/f/", "/y/", "/z/", "/e/"] },
  { label: "galaxie", phonemes: ["/g/", "/a/", "/l/", "/ks/", "/i/"] },
  { label: "gants", phonemes: ["/g/", "/ɑ̃/", "/t/"] },
  { label: "gare", phonemes: ["/g/", "/a/", "/r/"] },
  { label: "garçon", phonemes: ["/g/", "/a/", "/r/", "/k/", "/ɔ̃/"] },
  { label: "gauffre", phonemes: ["/g/", "/o/", "/f/", "/r/"] },
  { label: "gaufre", phonemes: ["/g/", "/o/", "/f/", "/r/"] },
  { label: "gaz", phonemes: ["/g/", "/a/", "/z/"] },
  { label: "gazelle", phonemes: ["/g/", "/a/", "/z/", "/e/", "/l/"] },
  { label: "gazoduc", phonemes: ["/g/", "/a/", "/z/", "/o/", "/d/", "/y/", "/k/"] },
  { label: "gazon", phonemes: ["/g/", "/a/", "/z/", "/ɔ̃/"] },
  { label: "gecko", phonemes: ["/ʒ/", "/e/", "/k/", "/o/"] },
  { label: "genou", phonemes: ["/ʒ/", "/e/", "/n/", "/u/"] },
  { label: "girafe", phonemes: ["/ʒ/", "/i/", "/r/", "/a/", "/f/"] },
  { label: "glace", phonemes: ["/g/", "/l/", "/a/", "/s/"] },
  { label: "glacier", phonemes: ["/g/", "/l/", "/a/", "/s/", "/j/", "/e/"] },
  { label: "globe", phonemes: ["/g/", "/l/", "/o/", "/b/"] },
  { label: "glycine", phonemes: ["/g/", "/l/", "/i/", "/s/", "/n/"] },
  { label: "gomme", phonemes: ["/g/", "/o/", "/m/"] },
  { label: "gorille", phonemes: ["/g/", "/o/", "/r/", "/j/"] },
  { label: "gouffre", phonemes: ["/g/", "/u/", "/f/", "/r/"] },
  { label: "goutte", phonemes: ["/g/", "/u/", "/t/"] },
  { label: "goyave", phonemes: ["/g/", "/o/", "/i/", "/a/", "/v/"] },
  { label: "grange", phonemes: ["/g/", "/r/", "/ɑ̃/", "/ʒ/"] },
  { label: "gratin", phonemes: ["/g/", "/r/", "/a/", "/t/", "/ɛ̃/"] },
  { label: "gratte-ciel", phonemes: ["/g/", "/r/", "/a/", "/t/", "/e/", "/s/", "/i/", "/l/"] },
  { label: "grenade", phonemes: ["/g/", "/r/", "/e/", "/n/", "/a/", "/d/"] },
  { label: "grenouille", phonemes: ["/g/", "/r/", "/e/", "/n/", "/u/", "/j/"] },
  { label: "gris", phonemes: ["/g/", "/r/", "/i/"] },
  { label: "grizzly", phonemes: ["/g/", "/r/", "/i/", "/z/", "/l/"] },
  { label: "groin", phonemes: ["/g/", "/r/", "/wɛ̃/"] },
  { label: "groseille", phonemes: ["/g/", "/r/", "/o/", "/z/", "/ɛ/", "/j/"] },
  { label: "guitare", phonemes: ["/g/", "/i/", "/t/", "/a/", "/r/"] },
  { label: "guêpe", phonemes: ["/g/", "/e/", "/p/"] },
  { label: "gymnase", phonemes: ["/ʒ/", "/i/", "/m/", "/n/", "/a/", "/z/"] },
  { label: "gymnastique", phonemes: ["/ʒ/", "/i/", "/m/", "/n/", "/a/", "/s/", "/t/", "/k/"] },
  { label: "gâteau", phonemes: ["/g/", "/a/", "/t/", "/o/"] },
  { label: "hache", phonemes: ["/∅/", "/a/", "/ʃ/"] },
  { label: "haltère", phonemes: ["/∅/", "/a/", "/l/", "/t/", "/e/", "/r/"] },
  { label: "hamac", phonemes: ["/∅/", "/a/", "/m/", "/k/"] },
  { label: "hamburger", phonemes: ["/∅/", "/ɑ̃/", "/b/", "/y/", "/r/", "/ʒ/", "/e/"] },
  { label: "handball", phonemes: ["/∅/", "/ɑ̃/", "/d/", "/b/", "/a/", "/l/"] },
  { label: "hanneton", phonemes: ["/∅/", "/a/", "/n/", "/e/", "/t/", "/ɔ̃/"] },
  { label: "haricot", phonemes: ["/∅/", "/a/", "/r/", "/i/", "/k/", "/o/"] },
  { label: "harmonica", phonemes: ["/∅/", "/a/", "/r/", "/m/", "/o/", "/n/", "/i/", "/k/"] },
  { label: "harpe", phonemes: ["/∅/", "/a/", "/r/", "/p/"] },
  { label: "herbe", phonemes: ["/∅/", "/e/", "/r/", "/b/"] },
  { label: "hexagone", phonemes: ["/∅/", "/e/", "/ks/", "/a/", "/g/", "/o/", "/n/"] },
  { label: "hibou", phonemes: ["/∅/", "/i/", "/b/", "/u/"] },
  { label: "hippocampe", phonemes: ["/∅/", "/i/", "/p/", "/o/", "/k/", "/ɑ̃/"] },
  { label: "hirondelle", phonemes: ["/∅/", "/i/", "/r/", "/ɔ̃/", "/d/", "/e/", "/l/"] },
  { label: "hiver", phonemes: ["/∅/", "/i/", "/v/", "/e/", "/r/"] },
  { label: "hobby", phonemes: ["/∅/", "/o/", "/b/", "/i/"] },
  { label: "hockey", phonemes: ["/∅/", "/o/", "/k/", "/e/"] },
  { label: "homard", phonemes: ["/∅/", "/o/", "/m/", "/a/", "/r/"] },
  { label: "homme", phonemes: ["/∅/", "/o/", "/m/"] },
  { label: "hopital", phonemes: ["/∅/", "/o/", "/p/", "/i/", "/t/", "/a/", "/l/"] },
  { label: "horizon", phonemes: ["/∅/", "/o/", "/r/", "/i/", "/z/", "/ɔ̃/"] },
  { label: "houx", phonemes: ["/∅/", "/u/"] },
  { label: "huile", phonemes: ["/∅/", "/ɥi/", "/l/"] },
  { label: "huit", phonemes: ["/∅/", "/ɥi/"] },
  { label: "huitre", phonemes: ["/∅/", "/ɥi/", "/t/", "/r/"] },
  { label: "hydravion", phonemes: ["/∅/", "/i/", "/d/", "/r/", "/a/", "/v/", "/ɔ̃/"] },
  { label: "hygiène", phonemes: ["/∅/", "/i/", "/ʒ/", "/jɛ̃/"] },
  { label: "hypnose", phonemes: ["/∅/", "/i/", "/p/", "/n/", "/o/", "/z/"] },
  { label: "hyène", phonemes: ["/∅/", "/i/", "/e/", "/n/"] },
  { label: "hélicoptère", phonemes: ["/∅/", "/e/", "/l/", "/i/", "/k/", "/o/", "/p/", "/t/", "/r/"] },
  { label: "hérisson", phonemes: ["/∅/", "/e/", "/r/", "/i/", "/s/", "/ɔ̃/"] },
  { label: "hêtre", phonemes: ["/∅/", "/e/", "/t/", "/r/"] },
  { label: "hôpital", phonemes: ["/∅/", "/o/", "/p/", "/i/", "/t/", "/a/", "/l/"] },
  { label: "ibis", phonemes: ["/i/", "/b/", "/s/"] },
  { label: "igloo", phonemes: ["/i/", "/g/", "/l/", "/o/"] },
  { label: "iguane", phonemes: ["/i/", "/g/", "/y/", "/a/", "/n/"] },
  { label: "image", phonemes: ["/i/", "/m/", "/a/", "/ʒ/"] },
  { label: "imprimante", phonemes: ["/ɛ̃/", "/p/", "/r/", "/i/", "/m/", "/ɑ̃/", "/t/"] },
  { label: "index", phonemes: ["/ɛ̃/", "/d/", "/e/"] },
  { label: "infirmière", phonemes: ["/ɛ̃/", "/f/", "/i/", "/r/", "/m/", "/e/"] },
  { label: "infusion", phonemes: ["/ɛ̃/", "/f/", "/y/", "/z/", "/i/", "/ɔ̃/"] },
  { label: "ingénieure", phonemes: ["/ɛ̃/", "/ʒ/", "/e/", "/n/", "/i/", "/ø/", "/r/"] },
  { label: "intercalaire", phonemes: ["/ɛ̃/", "/t/", "/e/", "/r/", "/k/", "/a/", "/l/", "/ɛ/"] },
  { label: "interview", phonemes: ["/ɛ̃/", "/t/", "/e/", "/r/", "/v/", "/i/", "/w/"] },
  { label: "iris", phonemes: ["/i/", "/r/"] },
  { label: "jacinthe", phonemes: ["/ʒ/", "/a/", "/s/", "/ɛ̃/", "/t/"] },
  { label: "jambe", phonemes: ["/ʒ/", "/ɑ̃/", "/b/"] },
  { label: "jardin", phonemes: ["/ʒ/", "/a/", "/r/", "/d/", "/ɛ̃/"] },
  { label: "jardinier", phonemes: ["/ʒ/", "/a/", "/r/", "/d/", "/i/", "/n/", "/j/", "/e/"] },
  { label: "jardinière", phonemes: ["/ʒ/", "/a/", "/r/", "/d/", "/i/", "/n/", "/e/"] },
  { label: "jaune", phonemes: ["/ʒ/", "/o/", "/n/"] },
  { label: "javelot", phonemes: ["/ʒ/", "/a/", "/v/", "/e/", "/l/", "/o/"] },
  { label: "jazz", phonemes: ["/ʒ/", "/a/", "/z/"] },
  { label: "jeu", phonemes: ["/ʒ/", "/ø/"] },
  { label: "jeudi", phonemes: ["/ʒ/", "/ø/", "/d/", "/i/"] },
  { label: "jockey", phonemes: ["/ʒ/", "/o/", "/k/", "/e/"] },
  { label: "joint", phonemes: ["/ʒ/", "/wɛ̃/"] },
  { label: "jonquille", phonemes: ["/ʒ/", "/ɔ̃/", "/k/", "/j/"] },
  { label: "jouet", phonemes: ["/ʒ/", "/w/", "/e/"] },
  { label: "jour", phonemes: ["/ʒ/", "/u/", "/r/"] },
  { label: "journaliste", phonemes: ["/ʒ/", "/u/", "/r/", "/n/", "/a/", "/l/", "/i/", "/s/", "/t/"] },
  { label: "joyau", phonemes: ["/ʒ/", "/o/", "/i/"] },
  { label: "judo", phonemes: ["/ʒ/", "/y/", "/d/", "/o/"] },
  { label: "juge", phonemes: ["/ʒ/", "/y/"] },
  { label: "jumelles", phonemes: ["/ʒ/", "/y/", "/m/", "/e/", "/l/"] },
  { label: "jupe", phonemes: ["/ʒ/", "/y/", "/p/"] },
  { label: "jus", phonemes: ["/ʒ/", "/y/"] },
  { label: "kaki", phonemes: ["/k/", "/a/", "/i/"] },
  { label: "kaléidoscope", phonemes: ["/k/", "/a/", "/l/", "/ɛ/", "/d/", "/o/", "/s/", "/p/"] },
  { label: "kangourou", phonemes: ["/k/", "/ɑ̃/", "/g/", "/u/", "/r/"] },
  { label: "kayak", phonemes: ["/k/", "/a/", "/i/"] },
  { label: "kazoo", phonemes: ["/k/", "/a/", "/z/", "/o/"] },
  { label: "kiwi", phonemes: ["/k/", "/i/", "/w/"] },
  { label: "klaxon", phonemes: ["/k/", "/l/", "/a/", "/ks/", "/ɔ̃/"] },
  { label: "koala", phonemes: ["/k/", "/o/", "/a/", "/l/"] },
  { label: "labyrinthe", phonemes: ["/l/", "/a/", "/b/", "/i/", "/r/", "/ɛ̃/", "/t/"] },
  { label: "lac", phonemes: ["/l/", "/a/", "/k/"] },
  { label: "lait", phonemes: ["/l/", "/ɛ/"] },
  { label: "laitue", phonemes: ["/l/", "/ɛ/", "/t/", "/y/"] },
  { label: "lampe", phonemes: ["/l/", "/ɑ̃/", "/p/"] },
  { label: "lampe-de-poche", phonemes: ["/l/", "/ɑ̃/", "/p/", "/e/", "/d/", "/o/", "/ʃ/"] },
  { label: "langue", phonemes: ["/l/", "/ɑ̃/", "/g/"] },
  { label: "lapin", phonemes: ["/l/", "/a/", "/p/", "/ɛ̃/"] },
  { label: "lavabo", phonemes: ["/l/", "/a/", "/v/", "/b/", "/o/"] },
  { label: "lavande", phonemes: ["/l/", "/a/", "/v/", "/ɑ̃/", "/d/"] },
  { label: "lave-vaisselle", phonemes: ["/l/", "/a/", "/v/", "/e/", "/ɛ/", "/s/"] },
  { label: "legging", phonemes: ["/l/", "/e/", "/g/", "/ʒ/", "/ɛ̃/"] },
  { label: "lentille", phonemes: ["/l/", "/ɑ̃/", "/t/", "/j/"] },
  { label: "libellule", phonemes: ["/l/", "/i/", "/b/", "/e/", "/y/"] },
  { label: "limace", phonemes: ["/l/", "/i/", "/m/", "/a/", "/s/"] },
  { label: "lime", phonemes: ["/l/", "/i/", "/m/"] },
  { label: "limonade", phonemes: ["/l/", "/i/", "/m/", "/o/", "/n/", "/a/", "/d/"] },
  { label: "lion", phonemes: ["/l/", "/i/", "/ɔ̃/"] },
  { label: "litchi", phonemes: ["/l/", "/i/", "/t/", "/ʃ/"] },
  { label: "livre", phonemes: ["/l/", "/i/", "/v/", "/r/"] },
  { label: "livreuse", phonemes: ["/l/", "/i/", "/v/", "/r/", "/ø/", "/z/"] },
  { label: "losange", phonemes: ["/l/", "/o/", "/z/", "/ɑ̃/", "/ʒ/"] },
  { label: "lotion", phonemes: ["/l/", "/o/", "/sjɔ̃/"] },
  { label: "loto", phonemes: ["/l/", "/o/", "/t/"] },
  { label: "loup", phonemes: ["/l/", "/u/"] },
  { label: "loupe", phonemes: ["/l/", "/u/", "/p/"] },
  { label: "luciole", phonemes: ["/l/", "/y/", "/s/", "/i/", "/o/"] },
  { label: "lundi", phonemes: ["/l/", "/œ̃/", "/d/", "/i/"] },
  { label: "lune", phonemes: ["/l/", "/y/", "/n/"] },
  { label: "lunettes", phonemes: ["/l/", "/y/", "/n/", "/e/", "/t/"] },
  { label: "lynx", phonemes: ["/l/", "/i/", "/n/"] },
  { label: "lyre", phonemes: ["/l/", "/i/", "/r/"] },
  { label: "lys", phonemes: ["/l/", "/i/", "/s/"] },
  { label: "légume", phonemes: ["/l/", "/e/", "/g/", "/y/", "/m/"] },
  { label: "lézard", phonemes: ["/l/", "/e/", "/z/", "/a/", "/r/"] },
  { label: "macaron", phonemes: ["/m/", "/a/", "/k/", "/r/", "/ɔ̃/"] },
  { label: "machine-a-laver", phonemes: ["/m/", "/a/", "/ʃ/", "/i/", "/n/", "/e/", "/l/", "/v/", "/r/"] },
  { label: "madeleine", phonemes: ["/m/", "/a/", "/d/", "/e/", "/l/", "/ɛ/", "/n/"] },
  { label: "maillot", phonemes: ["/m/", "/a/", "/j/", "/o/"] },
  { label: "main", phonemes: ["/m/", "/ɛ̃/"] },
  { label: "maison", phonemes: ["/m/", "/ɛ/", "/z/", "/ɔ̃/"] },
  { label: "maman", phonemes: ["/m/", "/a/", "/ɑ̃/"] },
  { label: "mandarine", phonemes: ["/m/", "/ɑ̃/", "/d/", "/a/", "/r/", "/i/", "/n/"] },
  { label: "manette", phonemes: ["/m/", "/a/", "/n/", "/e/", "/t/"] },
  { label: "mangue", phonemes: ["/m/", "/ɑ̃/", "/g/"] },
  { label: "mante-religieuse", phonemes: ["/m/", "/ɑ̃/", "/t/", "/e/", "/r/", "/l/", "/i/", "/ʒ/", "/ø/", "/z/"] },
  { label: "manteau", phonemes: ["/m/", "/ɑ̃/", "/t/", "/o/"] },
  { label: "maracas", phonemes: ["/m/", "/a/", "/r/", "/k/"] },
  { label: "marais", phonemes: ["/m/", "/a/", "/r/", "/ɛ/"] },
  { label: "marguerite", phonemes: ["/m/", "/a/", "/r/", "/g/", "/e/", "/i/", "/t/"] },
  { label: "marionnette", phonemes: ["/m/", "/a/", "/r/", "/i/", "/o/", "/n/", "/e/", "/t/"] },
  { label: "marmite", phonemes: ["/m/", "/a/", "/r/", "/i/", "/t/"] },
  { label: "marqueur", phonemes: ["/m/", "/a/", "/r/", "/k/", "/ø/"] },
  { label: "marron", phonemes: ["/m/", "/a/", "/r/", "/ɔ̃/"] },
  { label: "marronnier", phonemes: ["/m/", "/a/", "/r/", "/o/", "/n/", "/j/", "/e/"] },
  { label: "marteau", phonemes: ["/m/", "/a/", "/r/", "/t/", "/o/"] },
  { label: "mayonnaise", phonemes: ["/m/", "/a/", "/i/", "/o/", "/n/", "/ɛ/", "/z/"] },
  { label: "maçonne", phonemes: ["/m/", "/a/", "/k/", "/o/", "/n/"] },
  { label: "maïs", phonemes: ["/m/", "/ɛ/"] },
  { label: "melon", phonemes: ["/m/", "/e/", "/l/", "/ɔ̃/"] },
  { label: "menthe", phonemes: ["/m/", "/ɑ̃/", "/t/"] },
  { label: "mer", phonemes: ["/m/", "/e/", "/r/"] },
  { label: "meringue", phonemes: ["/m/", "/e/", "/r/", "/ɛ̃/", "/g/"] },
  { label: "micro-ondes", phonemes: ["/m/", "/i/", "/k/", "/r/", "/o/", "/ɔ̃/", "/d/", "/e/"] },
  { label: "miel", phonemes: ["/m/", "/i/", "/e/", "/l/"] },
  { label: "milkshake", phonemes: ["/m/", "/i/", "/l/", "/k/", "/ʃ/", "/a/"] },
  { label: "mille-feuille", phonemes: ["/m/", "/j/", "/e/", "/f/", "/ø/"] },
  { label: "miroir", phonemes: ["/m/", "/i/", "/r/", "/wa/"] },
  { label: "mixeur", phonemes: ["/m/", "/i/", "/ks/", "/ø/", "/r/"] },
  { label: "moineau", phonemes: ["/m/", "/wa/", "/n/", "/o/"] },
  { label: "montagne", phonemes: ["/m/", "/ɔ̃/", "/t/", "/a/", "/ɲ/"] },
  { label: "montgolfière", phonemes: ["/m/", "/ɔ̃/", "/t/", "/g/", "/o/", "/l/", "/f/", "/i/", "/e/", "/r/"] },
  { label: "montre", phonemes: ["/m/", "/ɔ̃/", "/t/", "/r/"] },
  { label: "morceau", phonemes: ["/m/", "/o/", "/r/", "/s/"] },
  { label: "morse", phonemes: ["/m/", "/o/", "/r/", "/s/"] },
  { label: "moto", phonemes: ["/m/", "/o/", "/t/"] },
  { label: "mouche", phonemes: ["/m/", "/u/", "/ʃ/"] },
  { label: "mouette", phonemes: ["/m/", "/w/", "/e/", "/t/"] },
  { label: "moulin", phonemes: ["/m/", "/u/", "/l/", "/ɛ̃/"] },
  { label: "moustique", phonemes: ["/m/", "/u/", "/s/", "/t/", "/i/", "/k/"] },
  { label: "mouton", phonemes: ["/m/", "/u/", "/t/", "/ɔ̃/"] },
  { label: "muffin", phonemes: ["/m/", "/y/", "/f/", "/ɛ̃/"] },
  { label: "muguet", phonemes: ["/m/", "/y/", "/g/", "/e/"] },
  { label: "mur", phonemes: ["/m/", "/y/", "/r/"] },
  { label: "musicienne", phonemes: ["/m/", "/y/", "/z/", "/i/", "/s/", "/jɛ̃/", "/n/"] },
  { label: "mygale", phonemes: ["/m/", "/i/", "/g/", "/a/", "/l/"] },
  { label: "myosotis", phonemes: ["/m/", "/i/", "/o/", "/z/", "/t/"] },
  { label: "myrtille", phonemes: ["/m/", "/i/", "/r/", "/t/", "/j/"] },
  { label: "mythe", phonemes: ["/m/", "/i/", "/t/"] },
  { label: "mécanicienne", phonemes: ["/m/", "/e/", "/k/", "/a/", "/n/", "/i/", "/s/", "/jɛ̃/"] },
  { label: "médaille", phonemes: ["/m/", "/e/", "/d/", "/a/", "/j/"] },
  { label: "médecin", phonemes: ["/m/", "/e/", "/d/", "/s/", "/ɛ̃/"] },
  { label: "méduse", phonemes: ["/m/", "/e/", "/d/", "/y/", "/z/"] },
  { label: "mésange", phonemes: ["/m/", "/e/", "/z/", "/ɑ̃/", "/ʒ/"] },
  { label: "métro", phonemes: ["/m/", "/e/", "/t/", "/r/", "/o/"] },
  { label: "mûre", phonemes: ["/m/", "/y/", "/r/"] },
  { label: "natation", phonemes: ["/n/", "/a/", "/t/", "/sjɔ̃/"] },
  { label: "navet", phonemes: ["/n/", "/a/", "/v/", "/e/"] },
  { label: "navire", phonemes: ["/n/", "/a/", "/v/", "/i/", "/r/"] },
  { label: "nectarine", phonemes: ["/n/", "/e/", "/k/", "/t/", "/a/", "/r/", "/i/"] },
  { label: "nenuphar", phonemes: ["/n/", "/e/", "/y/", "/f/", "/a/", "/r/"] },
  { label: "nez", phonemes: ["/n/", "/e/", "/z/"] },
  { label: "nid", phonemes: ["/n/", "/i/"] },
  { label: "noir", phonemes: ["/n/", "/wa/", "/r/"] },
  { label: "noisetier", phonemes: ["/n/", "/wa/", "/z/", "/e/", "/t/", "/j/"] },
  { label: "noisette", phonemes: ["/n/", "/wa/", "/z/", "/e/", "/t/"] },
  { label: "noix", phonemes: ["/n/", "/wa/"] },
  { label: "noix-de-coco", phonemes: ["/n/", "/wa/", "/ks/", "/d/", "/e/", "/k/", "/o/"] },
  { label: "noyau", phonemes: ["/n/", "/o/", "/i/"] },
  { label: "nuage", phonemes: ["/n/", "/y/", "/a/", "/ʒ/"] },
  { label: "nuit", phonemes: ["/n/", "/ɥi/"] },
  { label: "nylon", phonemes: ["/n/", "/i/", "/l/", "/ɔ̃/"] },
  { label: "oeillet", phonemes: ["/ø/", "/j/", "/e/"] },
  { label: "oeuf", phonemes: ["/ø/", "/f/"] },
  { label: "oie", phonemes: ["/wa/"] },
  { label: "oignon", phonemes: ["/wa/", "/ɲ/", "/ɔ̃/"] },
  { label: "oiseau", phonemes: ["/wa/", "/z/", "/o/"] },
  { label: "olive", phonemes: ["/o/", "/l/", "/i/", "/v/"] },
  { label: "olivier", phonemes: ["/o/", "/l/", "/i/", "/v/", "/j/", "/e/"] },
  { label: "olympiade", phonemes: ["/o/", "/l/", "/i/", "/m/", "/p/", "/a/", "/d/"] },
  { label: "olympique", phonemes: ["/o/", "/l/", "/i/", "/m/", "/p/", "/k/"] },
  { label: "onze", phonemes: ["/ɔ̃/", "/z/"] },
  { label: "orange", phonemes: ["/o/", "/r/", "/ɑ̃/", "/ʒ/"] },
  { label: "orchidée", phonemes: ["/o/", "/r/", "/ʃ/", "/i/", "/d/", "/e/"] },
  { label: "ordinateur", phonemes: ["/o/", "/r/", "/d/", "/i/", "/n/", "/a/", "/t/", "/ø/"] },
  { label: "oreille", phonemes: ["/o/", "/r/", "/ɛ/", "/j/"] },
  { label: "oryx", phonemes: ["/o/", "/r/", "/i/"] },
  { label: "otarie", phonemes: ["/o/", "/t/", "/a/", "/r/", "/i/"] },
  { label: "oursin", phonemes: ["/u/", "/r/", "/s/", "/ɛ̃/"] },
  { label: "ovale", phonemes: ["/o/", "/v/", "/a/", "/l/"] },
  { label: "oxygène", phonemes: ["/o/", "/ks/", "/i/", "/ʒ/", "/e/", "/n/"] },
  { label: "ozone", phonemes: ["/o/", "/z/", "/n/"] },
  { label: "page", phonemes: ["/p/", "/a/", "/ʒ/"] },
  { label: "pain", phonemes: ["/p/", "/ɛ̃/"] },
  { label: "paix", phonemes: ["/p/", "/ɛ/"] },
  { label: "palmier", phonemes: ["/p/", "/a/", "/l/", "/m/", "/j/", "/e/"] },
  { label: "pamplemousse", phonemes: ["/p/", "/ɑ̃/", "/l/", "/e/", "/m/", "/u/", "/s/"] },
  { label: "panda", phonemes: ["/p/", "/ɑ̃/", "/d/", "/a/"] },
  { label: "panier", phonemes: ["/p/", "/a/", "/n/", "/j/", "/e/"] },
  { label: "pantalon", phonemes: ["/p/", "/ɑ̃/", "/t/", "/a/", "/l/", "/ɔ̃/"] },
  { label: "paon", phonemes: ["/p/", "/a/", "/ɔ̃/"] },
  { label: "papa", phonemes: ["/p/", "/a/"] },
  { label: "papaye", phonemes: ["/p/", "/a/", "/i/"] },
  { label: "papier", phonemes: ["/p/", "/a/", "/j/", "/e/"] },
  { label: "papier-toilette", phonemes: ["/p/", "/a/", "/i/", "/e/", "/r/", "/t/", "/wa/", "/l/"] },
  { label: "papillon", phonemes: ["/p/", "/a/", "/j/", "/ɔ̃/"] },
  { label: "paquebot", phonemes: ["/p/", "/a/", "/k/", "/e/", "/b/", "/o/"] },
  { label: "paquerette", phonemes: ["/p/", "/a/", "/k/", "/e/", "/r/", "/t/"] },
  { label: "parapluie", phonemes: ["/p/", "/a/", "/r/", "/l/", "/ɥi/"] },
  { label: "parasol", phonemes: ["/p/", "/a/", "/r/", "/z/", "/o/", "/l/"] },
  { label: "parfum", phonemes: ["/p/", "/a/", "/r/", "/f/", "/œ̃/"] },
  { label: "passoire", phonemes: ["/p/", "/a/", "/s/", "/wa/", "/r/"] },
  { label: "pastèque", phonemes: ["/p/", "/a/", "/s/", "/t/", "/e/", "/k/"] },
  { label: "patate-douce", phonemes: ["/p/", "/a/", "/t/", "/e/", "/d/", "/u/", "/s/"] },
  { label: "patins", phonemes: ["/p/", "/a/", "/t/", "/ɛ̃/"] },
  { label: "paysage", phonemes: ["/p/", "/a/", "/i/", "/z/", "/ʒ/"] },
  { label: "paysan", phonemes: ["/p/", "/a/", "/i/", "/z/", "/ɑ̃/"] },
  { label: "peigne", phonemes: ["/p/", "/ɛ/", "/ɲ/"] },
  { label: "peintre", phonemes: ["/p/", "/ɛ̃/", "/t/", "/r/"] },
  { label: "peinture", phonemes: ["/p/", "/ɛ̃/", "/t/", "/y/", "/r/"] },
  { label: "pelle", phonemes: ["/p/", "/e/", "/l/"] },
  { label: "peluche", phonemes: ["/p/", "/e/", "/l/", "/y/", "/ʃ/"] },
  { label: "penderie", phonemes: ["/p/", "/ɑ̃/", "/d/", "/e/", "/r/", "/i/"] },
  { label: "pentagone", phonemes: ["/p/", "/ɑ̃/", "/t/", "/a/", "/g/", "/o/", "/n/"] },
  { label: "perdrix", phonemes: ["/p/", "/e/", "/r/", "/d/", "/i/"] },
  { label: "perroquet", phonemes: ["/p/", "/e/", "/r/", "/o/", "/k/"] },
  { label: "persil", phonemes: ["/p/", "/e/", "/r/", "/s/", "/i/", "/l/"] },
  { label: "petit-pois", phonemes: ["/p/", "/e/", "/t/", "/i/", "/wa/"] },
  { label: "peuplier", phonemes: ["/p/", "/ø/", "/l/", "/j/", "/e/"] },
  { label: "phare", phonemes: ["/f/", "/a/", "/r/"] },
  { label: "pharmacie", phonemes: ["/f/", "/a/", "/r/", "/m/", "/s/", "/i/"] },
  { label: "pharmacienne", phonemes: ["/f/", "/a/", "/r/", "/m/", "/s/", "/jɛ̃/", "/n/"] },
  { label: "phoque", phonemes: ["/f/", "/o/", "/k/"] },
  { label: "photo", phonemes: ["/f/", "/o/", "/t/"] },
  { label: "photographe", phonemes: ["/f/", "/o/", "/t/", "/g/", "/r/", "/a/"] },
  { label: "photographie", phonemes: ["/f/", "/o/", "/t/", "/g/", "/r/", "/a/", "/i/"] },
  { label: "phénix", phonemes: ["/f/", "/e/", "/n/", "/i/"] },
  { label: "piano", phonemes: ["/p/", "/i/", "/a/", "/n/", "/o/"] },
  { label: "pie", phonemes: ["/p/", "/i/"] },
  { label: "pied", phonemes: ["/p/", "/i/", "/e/"] },
  { label: "pieuvre", phonemes: ["/p/", "/i/", "/ø/", "/v/", "/r/"] },
  { label: "pigeon", phonemes: ["/p/", "/i/", "/ʒ/", "/e/", "/ɔ̃/"] },
  { label: "pile", phonemes: ["/p/", "/i/", "/l/"] },
  { label: "pilote", phonemes: ["/p/", "/i/", "/l/", "/o/", "/t/"] },
  { label: "piment", phonemes: ["/p/", "/i/", "/m/", "/ɑ̃/"] },
  { label: "pin", phonemes: ["/p/", "/ɛ̃/"] },
  { label: "pinceau", phonemes: ["/p/", "/ɛ̃/", "/s/", "/o/"] },
  { label: "pingouin", phonemes: ["/p/", "/ɛ̃/", "/g/", "/wɛ̃/"] },
  { label: "pissenlit", phonemes: ["/p/", "/i/", "/s/", "/ɑ̃/", "/l/"] },
  { label: "piste", phonemes: ["/p/", "/i/", "/s/", "/t/"] },
  { label: "pivoine", phonemes: ["/p/", "/i/", "/v/", "/wa/", "/n/"] },
  { label: "pixel", phonemes: ["/p/", "/i/", "/ks/", "/e/", "/l/"] },
  { label: "pizza", phonemes: ["/p/", "/i/", "/z/", "/a/"] },
  { label: "pizzéria", phonemes: ["/p/", "/i/", "/z/", "/e/", "/r/", "/a/"] },
  { label: "plage", phonemes: ["/p/", "/l/", "/a/", "/ʒ/"] },
  { label: "planche", phonemes: ["/p/", "/l/", "/ɑ̃/", "/ʃ/"] },
  { label: "planète", phonemes: ["/p/", "/l/", "/a/", "/n/", "/e/", "/t/"] },
  { label: "plombière", phonemes: ["/p/", "/l/", "/ɔ̃/", "/b/", "/i/", "/e/", "/r/"] },
  { label: "plume", phonemes: ["/p/", "/l/", "/y/", "/m/"] },
  { label: "poing", phonemes: ["/p/", "/wɛ̃/"] },
  { label: "point", phonemes: ["/p/", "/wɛ̃/"] },
  { label: "pointe", phonemes: ["/p/", "/wɛ̃/", "/t/"] },
  { label: "poire", phonemes: ["/p/", "/wa/", "/r/"] },
  { label: "poireau", phonemes: ["/p/", "/wa/", "/r/", "/o/"] },
  { label: "poirier", phonemes: ["/p/", "/wa/", "/r/", "/j/", "/e/"] },
  { label: "pois-chiche", phonemes: ["/p/", "/wa/", "/s/", "/ʃ/", "/i/"] },
  { label: "poisson", phonemes: ["/p/", "/wa/", "/s/", "/ɔ̃/"] },
  { label: "poivron", phonemes: ["/p/", "/wa/", "/v/", "/r/", "/ɔ̃/"] },
  { label: "policière", phonemes: ["/p/", "/o/", "/l/", "/i/", "/s/", "/e/", "/r/"] },
  { label: "polygone", phonemes: ["/p/", "/o/", "/l/", "/i/", "/g/", "/n/"] },
  { label: "pomme", phonemes: ["/p/", "/o/", "/m/"] },
  { label: "pomme-de-terre", phonemes: ["/p/", "/o/", "/m/", "/e/", "/d/", "/t/", "/r/"] },
  { label: "pommier", phonemes: ["/p/", "/o/", "/m/", "/j/", "/e/"] },
  { label: "pompier", phonemes: ["/p/", "/ɔ̃/", "/j/", "/e/"] },
  { label: "pompière", phonemes: ["/p/", "/ɔ̃/", "/i/", "/e/", "/r/"] },
  { label: "poney", phonemes: ["/p/", "/o/", "/n/", "/e/"] },
  { label: "pont", phonemes: ["/p/", "/ɔ̃/"] },
  { label: "porte-cles", phonemes: ["/p/", "/o/", "/r/", "/t/", "/e/", "/k/", "/l/"] },
  { label: "porte-documents", phonemes: ["/p/", "/o/", "/r/", "/t/", "/e/", "/d/", "/k/", "/y/", "/m/", "/ɑ̃/"] },
  { label: "porte-manteau", phonemes: ["/p/", "/o/", "/r/", "/t/", "/e/", "/m/", "/ɑ̃/"] },
  { label: "porte-mine", phonemes: ["/p/", "/o/", "/r/", "/t/", "/e/", "/m/", "/i/", "/n/"] },
  { label: "portefeuille", phonemes: ["/p/", "/o/", "/r/", "/t/", "/e/", "/f/", "/ø/", "/j/"] },
  { label: "post-it", phonemes: ["/p/", "/o/", "/s/", "/t/", "/i/"] },
  { label: "potion", phonemes: ["/p/", "/o/", "/sjɔ̃/"] },
  { label: "potiron", phonemes: ["/p/", "/o/", "/t/", "/i/", "/r/", "/ɔ̃/"] },
  { label: "poubelle", phonemes: ["/p/", "/u/", "/b/", "/e/", "/l/"] },
  { label: "poule", phonemes: ["/p/", "/u/", "/l/"] },
  { label: "poulet", phonemes: ["/p/", "/u/", "/l/", "/e/"] },
  { label: "poupée", phonemes: ["/p/", "/u/", "/e/"] },
  { label: "prairie", phonemes: ["/p/", "/r/", "/ɛ/", "/i/"] },
  { label: "prix", phonemes: ["/p/", "/r/", "/i/"] },
  { label: "professeure", phonemes: ["/p/", "/r/", "/o/", "/f/", "/e/", "/s/", "/ø/"] },
  { label: "prune", phonemes: ["/p/", "/r/", "/y/", "/n/"] },
  { label: "pull", phonemes: ["/p/", "/y/", "/l/"] },
  { label: "punaise", phonemes: ["/p/", "/y/", "/n/", "/ɛ/", "/z/"] },
  { label: "pupitre", phonemes: ["/p/", "/y/", "/i/", "/t/", "/r/"] },
  { label: "puzzle", phonemes: ["/p/", "/y/", "/z/", "/l/"] },
  { label: "pyjama", phonemes: ["/p/", "/i/", "/ʒ/", "/a/", "/m/"] },
  { label: "pyramide", phonemes: ["/p/", "/i/", "/r/", "/a/", "/m/", "/d/"] },
  { label: "python", phonemes: ["/p/", "/i/", "/t/", "/ɔ̃/"] },
  { label: "pâtes", phonemes: ["/p/", "/a/", "/t/", "/e/"] },
  { label: "pélican", phonemes: ["/p/", "/e/", "/l/", "/i/", "/k/", "/ɑ̃/"] },
  { label: "pêche", phonemes: ["/p/", "/e/", "/ʃ/"] },
  { label: "pêcheuse", phonemes: ["/p/", "/e/", "/ʃ/", "/ø/", "/z/"] },
  { label: "quatorze", phonemes: ["/k/", "/a/", "/t/", "/o/", "/r/", "/z/"] },
  { label: "quetzal", phonemes: ["/k/", "/e/", "/t/", "/z/", "/a/", "/l/"] },
  { label: "quinze", phonemes: ["/k/", "/ɛ̃/", "/z/"] },
  { label: "radio", phonemes: ["/r/", "/a/", "/d/", "/i/", "/o/"] },
  { label: "radis", phonemes: ["/r/", "/a/", "/d/", "/i/"] },
  { label: "raie", phonemes: ["/r/", "/ɛ/"] },
  { label: "raisin", phonemes: ["/r/", "/ɛ/", "/z/", "/ɛ̃/"] },
  { label: "randonnée", phonemes: ["/r/", "/ɑ̃/", "/d/", "/o/", "/n/", "/e/"] },
  { label: "rapporteur", phonemes: ["/r/", "/a/", "/p/", "/o/", "/t/", "/ø/"] },
  { label: "raquette", phonemes: ["/r/", "/a/", "/k/", "/e/", "/t/"] },
  { label: "rasoir", phonemes: ["/r/", "/a/", "/z/", "/wa/"] },
  { label: "rat", phonemes: ["/r/", "/a/"] },
  { label: "rateau", phonemes: ["/r/", "/a/", "/t/", "/o/"] },
  { label: "rectangle", phonemes: ["/r/", "/e/", "/k/", "/t/", "/ɑ̃/", "/g/", "/l/"] },
  { label: "recyclage", phonemes: ["/r/", "/e/", "/s/", "/i/", "/k/", "/l/", "/a/", "/ʒ/"] },
  { label: "renard", phonemes: ["/r/", "/e/", "/n/", "/a/"] },
  { label: "requin", phonemes: ["/r/", "/e/", "/k/", "/ɛ̃/"] },
  { label: "restaurant", phonemes: ["/r/", "/e/", "/s/", "/t/", "/o/", "/ɑ̃/"] },
  { label: "rideau", phonemes: ["/r/", "/i/", "/d/", "/o/"] },
  { label: "rivière", phonemes: ["/r/", "/i/", "/v/", "/e/"] },
  { label: "riz", phonemes: ["/r/", "/i/", "/z/"] },
  { label: "rizière", phonemes: ["/r/", "/i/", "/z/", "/e/"] },
  { label: "robe", phonemes: ["/r/", "/o/", "/b/"] },
  { label: "robot", phonemes: ["/r/", "/o/", "/b/"] },
  { label: "rocher", phonemes: ["/r/", "/o/", "/ʃ/", "/e/"] },
  { label: "romarin", phonemes: ["/r/", "/o/", "/m/", "/a/", "/ɛ̃/"] },
  { label: "rose", phonemes: ["/r/", "/o/", "/z/"] },
  { label: "rouge", phonemes: ["/r/", "/u/", "/ʒ/"] },
  { label: "rue", phonemes: ["/r/", "/y/"] },
  { label: "rugby", phonemes: ["/r/", "/y/", "/g/", "/b/", "/i/"] },
  { label: "ruisseau", phonemes: ["/r/", "/ɥi/", "/s/", "/o/"] },
  { label: "rythme", phonemes: ["/r/", "/i/", "/t/", "/m/"] },
  { label: "règle", phonemes: ["/r/", "/e/", "/g/", "/l/"] },
  { label: "réflexe", phonemes: ["/r/", "/e/", "/f/", "/l/", "/ks/"] },
  { label: "réfrigerateur", phonemes: ["/r/", "/e/", "/f/", "/i/", "/ʒ/", "/a/", "/t/", "/ø/"] },
  { label: "réveil", phonemes: ["/r/", "/e/", "/v/", "/ɛ/", "/j/"] },
  { label: "sac-a-main", phonemes: ["/s/", "/a/", "/k/", "/m/", "/ɛ̃/"] },
  { label: "salade", phonemes: ["/s/", "/a/", "/l/", "/d/"] },
  { label: "salade-de-fruits", phonemes: ["/s/", "/a/", "/l/", "/d/", "/e/", "/f/", "/r/", "/ɥi/", "/t/"] },
  { label: "salamandre", phonemes: ["/s/", "/a/", "/l/", "/m/", "/ɑ̃/", "/d/", "/r/"] },
  { label: "sandales", phonemes: ["/s/", "/ɑ̃/", "/d/", "/a/", "/l/", "/e/"] },
  { label: "sandwich", phonemes: ["/s/", "/ɑ̃/", "/d/", "/w/", "/i/", "/ʃ/"] },
  { label: "sapin", phonemes: ["/s/", "/a/", "/p/", "/ɛ̃/"] },
  { label: "satellite", phonemes: ["/s/", "/a/", "/t/", "/e/", "/l/", "/i/"] },
  { label: "saturne", phonemes: ["/s/", "/a/", "/t/", "/y/", "/r/", "/n/"] },
  { label: "saule-pleureur", phonemes: ["/s/", "/o/", "/l/", "/e/", "/p/", "/ø/", "/r/"] },
  { label: "sauterelle", phonemes: ["/s/", "/o/", "/t/", "/e/", "/r/", "/l/"] },
  { label: "savon", phonemes: ["/s/", "/a/", "/v/", "/ɔ̃/"] },
  { label: "saxophone", phonemes: ["/s/", "/a/", "/ks/", "/o/", "/f/", "/n/"] },
  { label: "scarabée", phonemes: ["/s/", "/k/", "/a/", "/r/", "/b/", "/e/"] },
  { label: "scientifique", phonemes: ["/s/", "/jɛ̃/", "/t/", "/i/", "/f/", "/k/"] },
  { label: "scooter", phonemes: ["/s/", "/k/", "/o/", "/t/", "/e/", "/r/"] },
  { label: "scorpion", phonemes: ["/s/", "/k/", "/o/", "/r/", "/p/", "/i/", "/ɔ̃/"] },
  { label: "scotch", phonemes: ["/s/", "/k/", "/o/", "/t/", "/ʃ/"] },
  { label: "seau", phonemes: ["/s/", "/o/"] },
  { label: "secrétaire", phonemes: ["/s/", "/e/", "/k/", "/r/", "/t/", "/ɛ/"] },
  { label: "seize", phonemes: ["/s/", "/ɛ/", "/z/"] },
  { label: "semaine", phonemes: ["/s/", "/e/", "/m/", "/ɛ/", "/n/"] },
  { label: "sentier", phonemes: ["/s/", "/ɑ̃/", "/t/", "/j/", "/e/"] },
  { label: "sequoia", phonemes: ["/s/", "/e/", "/k/", "/wa/", "/a/"] },
  { label: "serpent", phonemes: ["/s/", "/e/", "/r/", "/p/", "/ɑ̃/"] },
  { label: "serveuse", phonemes: ["/s/", "/e/", "/r/", "/v/", "/ø/", "/z/"] },
  { label: "shampoing", phonemes: ["/ʃ/", "/ɑ̃/", "/p/", "/wɛ̃/"] },
  { label: "short", phonemes: ["/ʃ/", "/o/", "/r/"] },
  { label: "sifflet", phonemes: ["/s/", "/i/", "/f/", "/l/", "/e/"] },
  { label: "silex", phonemes: ["/s/", "/i/", "/l/", "/e/"] },
  { label: "singe", phonemes: ["/s/", "/ɛ̃/", "/ʒ/"] },
  { label: "six", phonemes: ["/s/", "/i/"] },
  { label: "skateboard", phonemes: ["/s/", "/k/", "/a/", "/t/", "/e/", "/b/", "/o/", "/r/"] },
  { label: "ski", phonemes: ["/s/", "/k/", "/i/"] },
  { label: "smartphone", phonemes: ["/s/", "/m/", "/a/", "/r/", "/t/", "/f/", "/o/", "/n/"] },
  { label: "smoothie", phonemes: ["/s/", "/m/", "/o/", "/t/", "/i/"] },
  { label: "snowboard", phonemes: ["/s/", "/n/", "/o/", "/w/", "/b/", "/a/", "/r/"] },
  { label: "soda", phonemes: ["/s/", "/o/", "/d/", "/a/"] },
  { label: "soja", phonemes: ["/s/", "/o/", "/ʒ/", "/a/"] },
  { label: "soleil", phonemes: ["/s/", "/o/", "/l/", "/ɛ/", "/j/"] },
  { label: "soulier", phonemes: ["/s/", "/u/", "/l/", "/j/", "/e/"] },
  { label: "soupe", phonemes: ["/s/", "/u/", "/p/"] },
  { label: "souris", phonemes: ["/s/", "/u/", "/r/", "/i/"] },
  { label: "sous-marin", phonemes: ["/s/", "/u/", "/m/", "/a/", "/r/", "/ɛ̃/"] },
  { label: "soutien-gorge", phonemes: ["/s/", "/u/", "/t/", "/jɛ̃/", "/g/", "/o/", "/r/", "/ʒ/"] },
  { label: "sphinx", phonemes: ["/s/", "/f/", "/ɛ̃/"] },
  { label: "sphère", phonemes: ["/s/", "/f/", "/e/", "/r/"] },
  { label: "stade", phonemes: ["/s/", "/t/", "/a/", "/d/"] },
  { label: "station", phonemes: ["/s/", "/t/", "/a/", "/sjɔ̃/"] },
  { label: "steward", phonemes: ["/s/", "/t/", "/e/", "/w/", "/a/", "/r/"] },
  { label: "stylet", phonemes: ["/s/", "/t/", "/i/", "/l/", "/e/"] },
  { label: "stylo", phonemes: ["/s/", "/t/", "/i/", "/l/", "/o/"] },
  { label: "sucette", phonemes: ["/s/", "/y/", "/e/", "/t/"] },
  { label: "surligneur", phonemes: ["/s/", "/y/", "/r/", "/l/", "/i/", "/ɲ/", "/ø/"] },
  { label: "symbole", phonemes: ["/s/", "/i/", "/m/", "/b/", "/o/", "/l/"] },
  { label: "sèche-cheveux", phonemes: ["/s/", "/e/", "/ʃ/", "/v/", "/ø/"] },
  { label: "t-shirt", phonemes: ["/t/", "/ʃ/", "/i/", "/r/"] },
  { label: "table-de-nuit", phonemes: ["/t/", "/a/", "/b/", "/l/", "/e/", "/d/", "/n/", "/ɥi/"] },
  { label: "tableau", phonemes: ["/t/", "/a/", "/b/", "/l/", "/o/"] },
  { label: "tablette", phonemes: ["/t/", "/a/", "/b/", "/l/", "/e/"] },
  { label: "talon", phonemes: ["/t/", "/a/", "/l/", "/ɔ̃/"] },
  { label: "tambour", phonemes: ["/t/", "/ɑ̃/", "/b/", "/u/", "/r/"] },
  { label: "tambourin", phonemes: ["/t/", "/ɑ̃/", "/b/", "/u/", "/r/", "/ɛ̃/"] },
  { label: "tampon", phonemes: ["/t/", "/ɑ̃/", "/p/", "/ɔ̃/"] },
  { label: "tapis", phonemes: ["/t/", "/a/", "/p/", "/i/"] },
  { label: "taxi", phonemes: ["/t/", "/a/", "/ks/", "/i/"] },
  { label: "tempête", phonemes: ["/t/", "/ɑ̃/", "/p/", "/e/"] },
  { label: "tennis", phonemes: ["/t/", "/e/", "/n/", "/i/", "/s/"] },
  { label: "tente", phonemes: ["/t/", "/ɑ̃/"] },
  { label: "thym", phonemes: ["/t/", "/i/", "/m/"] },
  { label: "thé", phonemes: ["/t/", "/e/"] },
  { label: "tigre", phonemes: ["/t/", "/i/", "/g/", "/r/"] },
  { label: "timbre", phonemes: ["/t/", "/ɛ̃/", "/b/", "/r/"] },
  { label: "tiramisu", phonemes: ["/t/", "/i/", "/r/", "/a/", "/m/", "/z/", "/y/"] },
  { label: "tisane", phonemes: ["/t/", "/i/", "/z/", "/a/", "/n/"] },
  { label: "toit", phonemes: ["/t/", "/wa/"] },
  { label: "tomate", phonemes: ["/t/", "/o/", "/m/", "/a/"] },
  { label: "topaze", phonemes: ["/t/", "/o/", "/p/", "/a/", "/z/"] },
  { label: "tornade", phonemes: ["/t/", "/o/", "/r/", "/n/", "/a/", "/d/"] },
  { label: "tortue", phonemes: ["/t/", "/o/", "/r/", "/y/"] },
  { label: "toucan", phonemes: ["/t/", "/u/", "/k/", "/ɑ̃/"] },
  { label: "toupie", phonemes: ["/t/", "/u/", "/p/", "/i/"] },
  { label: "tournesol", phonemes: ["/t/", "/u/", "/r/", "/n/", "/e/", "/z/", "/o/", "/l/"] },
  { label: "tournevis", phonemes: ["/t/", "/u/", "/r/", "/n/", "/e/", "/v/", "/i/"] },
  { label: "tracteur", phonemes: ["/t/", "/r/", "/a/", "/k/", "/ø/"] },
  { label: "train", phonemes: ["/t/", "/r/", "/ɛ̃/"] },
  { label: "tram", phonemes: ["/t/", "/r/", "/ɑ̃/"] },
  { label: "tramway", phonemes: ["/t/", "/r/", "/ɑ̃/", "/w/", "/a/", "/i/"] },
  { label: "trapèze", phonemes: ["/t/", "/r/", "/a/", "/p/", "/e/", "/z/"] },
  { label: "trapéziste", phonemes: ["/t/", "/r/", "/a/", "/p/", "/e/", "/z/", "/i/", "/s/"] },
  { label: "treize", phonemes: ["/t/", "/r/", "/ɛ/", "/z/"] },
  { label: "triangle", phonemes: ["/t/", "/r/", "/i/", "/ɑ̃/", "/g/", "/l/"] },
  { label: "trombone", phonemes: ["/t/", "/r/", "/ɔ̃/", "/b/", "/o/", "/n/"] },
  { label: "trompette", phonemes: ["/t/", "/r/", "/ɔ̃/", "/p/", "/e/"] },
  { label: "trophée", phonemes: ["/t/", "/r/", "/o/", "/f/", "/e/"] },
  { label: "trottinette", phonemes: ["/t/", "/r/", "/o/", "/i/", "/n/", "/e/"] },
  { label: "trousse", phonemes: ["/t/", "/r/", "/u/", "/s/"] },
  { label: "tsar", phonemes: ["/t/", "/s/", "/a/", "/r/"] },
  { label: "tulipe", phonemes: ["/t/", "/y/", "/l/", "/i/", "/p/"] },
  { label: "turquoise", phonemes: ["/t/", "/y/", "/r/", "/k/", "/wa/", "/z/"] },
  { label: "tuyau", phonemes: ["/t/", "/y/", "/i/", "/o/"] },
  { label: "typhon", phonemes: ["/t/", "/i/", "/f/", "/ɔ̃/"] },
  { label: "tyrannosaure", phonemes: ["/t/", "/i/", "/r/", "/a/", "/n/", "/o/", "/z/"] },
  { label: "télécommande", phonemes: ["/t/", "/e/", "/l/", "/k/", "/o/", "/m/", "/ɑ̃/", "/d/"] },
  { label: "téléphone", phonemes: ["/t/", "/e/", "/l/", "/f/", "/o/", "/n/"] },
  { label: "téléphérique", phonemes: ["/t/", "/e/", "/l/", "/f/", "/r/", "/i/", "/k/"] },
  { label: "téléscope", phonemes: ["/t/", "/e/", "/l/", "/s/", "/k/", "/o/", "/p/"] },
  { label: "télévision", phonemes: ["/t/", "/e/", "/l/", "/v/", "/i/", "/z/", "/ɔ̃/"] },
  { label: "tête", phonemes: ["/t/", "/e/"] },
  { label: "uniforme", phonemes: ["/y/", "/n/", "/i/", "/f/", "/o/", "/r/", "/m/"] },
  { label: "usine", phonemes: ["/y/", "/z/", "/i/", "/n/"] },
  { label: "vache", phonemes: ["/v/", "/a/", "/ʃ/"] },
  { label: "valise", phonemes: ["/v/", "/a/", "/l/", "/i/", "/z/"] },
  { label: "vallee", phonemes: ["/v/", "/a/", "/l/", "/e/"] },
  { label: "vampire", phonemes: ["/v/", "/ɑ̃/", "/p/", "/i/", "/r/"] },
  { label: "vanille", phonemes: ["/v/", "/a/", "/n/", "/j/"] },
  { label: "vendeuse", phonemes: ["/v/", "/ɑ̃/", "/d/", "/ø/", "/z/"] },
  { label: "ventre", phonemes: ["/v/", "/ɑ̃/", "/t/", "/r/"] },
  { label: "ver-de-terre", phonemes: ["/v/", "/e/", "/r/", "/d/", "/t/"] },
  { label: "verre", phonemes: ["/v/", "/e/", "/r/"] },
  { label: "vert", phonemes: ["/v/", "/e/", "/r/"] },
  { label: "veste", phonemes: ["/v/", "/e/", "/s/", "/t/"] },
  { label: "viande", phonemes: ["/v/", "/i/", "/ɑ̃/", "/d/"] },
  { label: "violet", phonemes: ["/v/", "/i/", "/o/", "/l/", "/e/"] },
  { label: "violette", phonemes: ["/v/", "/i/", "/o/", "/l/", "/e/", "/t/"] },
  { label: "violon", phonemes: ["/v/", "/i/", "/o/", "/l/", "/ɔ̃/"] },
  { label: "violoncelle", phonemes: ["/v/", "/i/", "/o/", "/l/", "/ɔ̃/", "/s/", "/e/"] },
  { label: "vitrine", phonemes: ["/v/", "/i/", "/t/", "/r/", "/n/"] },
  { label: "vizir", phonemes: ["/v/", "/i/", "/z/", "/r/"] },
  { label: "voiture", phonemes: ["/v/", "/wa/", "/t/", "/y/", "/r/"] },
  { label: "voix", phonemes: ["/v/", "/wa/"] },
  { label: "volant", phonemes: ["/v/", "/o/", "/l/", "/ɑ̃/"] },
  { label: "volcan", phonemes: ["/v/", "/o/", "/l/", "/k/", "/ɑ̃/"] },
  { label: "volleyball", phonemes: ["/v/", "/o/", "/l/", "/e/", "/b/", "/a/"] },
  { label: "vortex", phonemes: ["/v/", "/o/", "/r/", "/t/", "/e/"] },
  { label: "voyage", phonemes: ["/v/", "/o/", "/i/", "/a/", "/ʒ/"] },
  { label: "vélo", phonemes: ["/v/", "/e/", "/l/", "/o/"] },
  { label: "vétérinaire", phonemes: ["/v/", "/e/", "/t/", "/r/", "/i/", "/n/", "/ɛ/"] },
  { label: "wagon", phonemes: ["/w/", "/a/", "/g/", "/ɔ̃/"] },
  { label: "wagonnet", phonemes: ["/w/", "/a/", "/g/", "/o/", "/n/", "/e/"] },
  { label: "wakeboard", phonemes: ["/w/", "/a/", "/k/", "/e/", "/b/", "/o/", "/r/"] },
  { label: "walkie-talkie", phonemes: ["/w/", "/a/", "/l/", "/k/", "/i/", "/e/", "/t/"] },
  { label: "walkman", phonemes: ["/w/", "/a/", "/l/", "/k/", "/m/", "/ɑ̃/"] },
  { label: "wallaby", phonemes: ["/w/", "/a/", "/l/", "/b/", "/i/"] },
  { label: "walrus", phonemes: ["/w/", "/a/", "/l/", "/r/", "/y/"] },
  { label: "wapiti", phonemes: ["/w/", "/a/", "/p/", "/i/", "/t/"] },
  { label: "wasabi", phonemes: ["/w/", "/a/", "/z/", "/b/", "/i/"] },
  { label: "water-polo", phonemes: ["/w/", "/a/", "/t/", "/e/", "/r/", "/p/", "/o/", "/l/"] },
  { label: "webcam", phonemes: ["/w/", "/e/", "/b/", "/k/", "/ɑ̃/"] },
  { label: "western", phonemes: ["/w/", "/e/", "/s/", "/t/", "/r/", "/n/"] },
  { label: "whippet", phonemes: ["/w/", "/∅/", "/i/", "/p/", "/e/"] },
  { label: "whisky", phonemes: ["/w/", "/∅/", "/i/", "/s/", "/k/"] },
  { label: "wifi", phonemes: ["/w/", "/i/", "/f/"] },
  { label: "wigwam", phonemes: ["/w/", "/i/", "/g/", "/ɑ̃/"] },
  { label: "windsurf", phonemes: ["/w/", "/ɛ̃/", "/d/", "/s/", "/y/", "/r/", "/f/"] },
  { label: "wok", phonemes: ["/w/", "/o/", "/k/"] },
  { label: "wombat", phonemes: ["/w/", "/ɔ̃/", "/b/", "/a/"] },
  { label: "wrap", phonemes: ["/w/", "/r/", "/a/"] },
  { label: "xylophone", phonemes: ["/ks/", "/i/", "/l/", "/o/", "/f/", "/n/"] },
  { label: "yacht", phonemes: ["/i/", "/a/", "/ʃ/"] },
  { label: "yak", phonemes: ["/i/", "/a/", "/k/"] },
  { label: "yaourt", phonemes: ["/i/", "/a/", "/u/", "/r/"] },
  { label: "yoga", phonemes: ["/i/", "/o/", "/g/", "/a/"] },
  { label: "yorkshire", phonemes: ["/i/", "/o/", "/r/", "/k/", "/ʃ/"] },
  { label: "yoyo", phonemes: ["/i/", "/o/"] },
  { label: "yucca", phonemes: ["/i/", "/y/", "/k/", "/a/"] },
  { label: "yéti", phonemes: ["/i/", "/e/", "/t/"] },
  { label: "zigzag", phonemes: ["/z/", "/i/", "/g/", "/a/"] },
  { label: "zinc", phonemes: ["/z/", "/ɛ̃/", "/k/"] },
  { label: "zinnia", phonemes: ["/z/", "/i/", "/n/", "/a/"] },
  { label: "zipper", phonemes: ["/z/", "/i/", "/p/", "/e/", "/r/"] },
  { label: "zircon", phonemes: ["/z/", "/i/", "/r/", "/k/", "/ɔ̃/"] },
  { label: "zodiaque", phonemes: ["/z/", "/o/", "/d/", "/i/", "/a/", "/k/"] },
  { label: "zombie", phonemes: ["/z/", "/ɔ̃/", "/b/", "/i/"] },
  { label: "zoo", phonemes: ["/z/", "/o/"] },
  { label: "zoom", phonemes: ["/z/", "/o/", "/ɔ̃/"] },
  { label: "zorro", phonemes: ["/z/", "/o/", "/r/"] },
  { label: "zouave", phonemes: ["/z/", "/w/", "/a/", "/v/"] },
  { label: "zouk", phonemes: ["/z/", "/u/", "/k/"] },
  { label: "zèbre", phonemes: ["/z/", "/e/", "/b/", "/r/"] },
  { label: "zébu", phonemes: ["/z/", "/e/", "/b/", "/y/"] },
  { label: "zéphyr", phonemes: ["/z/", "/e/", "/f/", "/i/", "/r/"] },
  { label: "zéro", phonemes: ["/z/", "/e/", "/r/", "/o/"] },
  { label: "échalote", phonemes: ["/e/", "/ʃ/", "/a/", "/l/", "/o/", "/t/"] },
  { label: "écharpe", phonemes: ["/e/", "/ʃ/", "/a/", "/r/", "/p/"] },
  { label: "échecs", phonemes: ["/e/", "/ʃ/", "/k/"] },
  { label: "échelle", phonemes: ["/e/", "/ʃ/", "/l/"] },
  { label: "école", phonemes: ["/e/", "/k/", "/o/", "/l/"] },
  { label: "écouteurs", phonemes: ["/e/", "/k/", "/u/", "/t/", "/ø/", "/r/"] },
  { label: "écureuil", phonemes: ["/e/", "/k/", "/y/", "/r/", "/ø/", "/j/"] },
  { label: "élastique", phonemes: ["/e/", "/l/", "/a/", "/s/", "/t/", "/i/", "/k/"] },
  { label: "électricienne", phonemes: ["/e/", "/l/", "/k/", "/t/", "/r/", "/i/", "/s/", "/jɛ̃/", "/n/"] },
  { label: "éléphant", phonemes: ["/e/", "/l/", "/f/", "/ɑ̃/"] },
  { label: "épaule", phonemes: ["/e/", "/p/", "/o/", "/l/"] },
  { label: "épicière", phonemes: ["/e/", "/p/", "/i/", "/s/", "/r/"] },
  { label: "épinard", phonemes: ["/e/", "/p/", "/i/", "/n/", "/a/", "/r/"] },
  { label: "éponge", phonemes: ["/e/", "/p/", "/ɔ̃/", "/ʒ/"] },
  { label: "équerre", phonemes: ["/e/", "/k/", "/r/"] },
  { label: "érable", phonemes: ["/e/", "/r/", "/a/", "/b/", "/l/"] },
  { label: "étang", phonemes: ["/e/", "/t/", "/ɑ̃/"] },
  { label: "étoile-de-mer", phonemes: ["/e/", "/t/", "/wa/", "/l/", "/d/", "/m/", "/r/"] },
  { label: "île", phonemes: ["/i/", "/l/"] },
  { label: "œil", phonemes: ["/ø/", "/j/"] },
  { label: "œillet", phonemes: ["/ø/", "/j/", "/e/"] },
  { label: "œuf", phonemes: ["/ø/", "/f/"] },
]

